Refactor the way cards are laid out -- separated by expansion.
bafolts/terraforming-mars pull request #1324
Opened 2020-09-19 03:39 UTC by kberg

Whoo that took a ton of work but I cleaned up my repo a bit.

2020-09-26 16:08 UTC, kberg commented
Sorry, didn't realize this had conflicts. Pushed an update that should make this mergeable.

2020-10-01 06:23 UTC, vincentneko commented on src/Game.ts
> +import { SelectResourceCard } from "./inputs/SelectResourceCard";
`SelectResourceCard `is not a playerInput, it's a `PlayerInterrupt` and should remain in interrupts folder.

2020-10-01 06:24 UTC, vincentneko commented on src/Game.ts
> -
Theses changes should not be mixed with the primary goal of this PR, can you please revert to initial state ?

2020-10-01 06:24 UTC, vincentneko commented on src/Game.ts
> +      this.addInterrupt({player: player, playerInput: SelectResourceCard.newInstance(this, player, resourceType, resourceCards, count, title)});
Theses changes should not be mixed with the primary goal of this PR, can you please revert to initial state ?

2020-10-01 06:27 UTC, vincentneko requested changes
This PR looks great, the changes are huge and would need testing.
There are some modifications for `selectResourceInterrupt` that I would like to address separately, can you please revert everything related to it so we can focus on the card refactor ?

2020-10-01 06:27 UTC, vincentneko commented on src/inputs/SelectResourceCard.ts
> +export class SelectResourceCard {
Theses changes should not be mixed with the primary goal of this PR, can you please revert to initial state ?

2020-10-01 21:05 UTC, kberg commented on src/inputs/SelectResourceCard.ts
> +export class SelectResourceCard {
Man. What a rookie. I am. :D

2020-10-01 21:24 UTC, kberg commented on src/Game.ts
> +import { SelectResourceCard } from "./inputs/SelectResourceCard";
Of course. Mea culpa. I'm sorry.

2020-10-01 21:29 UTC, kberg reviewed
I'm going to dump this and start again. Something's gone a bit pear-shaped with this branch.

2020-10-02 02:04 UTC, closed without merging