Hide player id's
bafolts/terraforming-mars pull request #1434
Opened 2020-10-01 10:33 UTC by vincentneko

Warning : This one will break any pending game

Use color instead of playerId in otherPlayers data.
PlayerId will not be visible anymore in Vue data and therefore someone will not be able to access other players pages.

2020-10-01 11:54 UTC, chosta commented
This is very nice! The only general remark is that maybe a separate PlayerIndex set from 0 to 5 would be better. Also, we are kind of stuck to "red", "black", etc. as identifiers for the different players. This might be an issue if we want black to be another color (in terms our brains mapping colors to identifiers, otherwise it shouldn't) . But I know that this would take a lot of refactoring so just mentioning it here as food for thought.

2020-10-02 00:58 UTC, bafolts commented on src/Game.ts
> +      let passedPlayersColors: Array<Color> = [];
This map as well use `this.passedPlayers.map((player) => this.getPlayerById(player).color)` as this is mapping the data.

2020-10-02 01:02 UTC, kberg commented
I agree, this is a nice idea. And can solve enough of the spectator problem to make it live.

2020-10-02 01:09 UTC, bafolts commented on src/Player.ts
> +            (player) => player.color === input[0][0]
The only games I think which would break are games where users have the browser open and they can take an input still using id. To not break these users if this check were to use `(player) => player.color === input[0][0] || player.id === [0][0]` I think there would be no introduced errors.

2020-10-02 01:22 UTC, bafolts commented on server.ts
> +                (player) => player.color
The `SELECT_DELEGATE` option will also need to use `player.color` instead of `player.id`.

2020-10-02 01:23 UTC, bafolts requested changes
Also need to include `SELECT_DELEGATE` as that is using the player id instead of color. If we check for both the `id` and `color` when matching on the input as this first rolls out we should avoid any intermediate issues during the swap.

2020-10-02 05:56 UTC, vincentneko commented on src/Game.ts
> +      let passedPlayersColors: Array<Color> = [];
I get a "Property 'map' does not exist on type 'Set<string>'" when I try to switch to map

2020-10-02 06:10 UTC, vincentneko commented on server.ts
> +                (player) => player.color
Good catch !

2020-10-02 15:19 UTC, closed without merging