Hide player Id (new PR without conflicts)
bafolts/terraforming-mars pull request #1454
Opened 2020-10-02 15:17 UTC by vincentneko

2020-10-02 16:17 UTC, nwai90 approved these changes

2020-10-03 01:34 UTC, bafolts commented on src/Player.ts
> +            (player) => player.color === input[0][0] || player.id === [0][0].toString()
This must be a typo, this should be `input[0][0]` and not `[0][0].toString()`

2020-10-03 01:37 UTC, bafolts commented on src/Player.ts
> +            (player) => player.color === input[0][0] || player.id === [0][0].toString()
This check also needs to be added for `SelectDelegate`

https://github.com/bafolts/terraforming-mars/blob/master/src/Player.ts#L797

2020-10-03 01:40 UTC, bafolts commented on src/components/overview/PlayersOverview.ts
> +                (p: Player) => p.id === this.player.color
This will need to check that `p.color === this.player.color`

2020-10-03 01:40 UTC, bafolts commented on src/components/overview/PlayersOverview.ts
> +        if (p.id === player.color) {
This will need to check that `p.color === player.color`

2020-10-03 01:42 UTC, bafolts commented on src/components/overview/PlayersOverview.ts
>      players.forEach((p: Player, index: number) => {
fwiw a client side component will only ever have `PlayerModel` as a type and not `Player`.

2020-10-03 01:43 UTC, bafolts commented on src/components/LogPanel.ts
> +                        if (data.value === player.color) {
This will need the same intermediate workaround for the transition of `data.value === player.color || data.value === player.id`. Games running during the transition could have both `id` or `color` stored for this value.

2020-10-03 01:45 UTC, bafolts commented on src/Player.ts
> +              .playerId(color));
I would use `.player(getPlayerById(game.monsInsuranceOwner))` here.

2020-10-03 01:47 UTC, bafolts commented on server.ts
> +            id: player.color,
If possible we should remove `id` from `PlayerModel`. Anything in `src/components/` at that point should only make reference to `PlayerModel` and not `Player`.

2020-10-03 01:50 UTC, bafolts requested changes
Two minor suggestions and one typo spotted.

As a note and change that could be done separately. Anything in `src/components/` should only make reference to `PlayerModel`. I see there are some references to `Player` which could lead to bugs during runtime when the type is actually `PlayerModel`.

2020-10-03 06:41 UTC, vincentneko commented on src/Player.ts
> +            (player) => player.color === input[0][0] || player.id === [0][0].toString()
If I remove the` .toString()` I get a "This condition will always return 'false' since the types 'string' and 'number' have no overlap." error

2020-10-03 06:42 UTC, vincentneko commented on src/components/overview/PlayersOverview.ts
>      players.forEach((p: Player, index: number) => {
Thanks for the clarification. Maybe we can work on this in another PR ?

2020-10-03 15:43 UTC, bafolts commented on src/components/overview/PlayersOverview.ts
>      players.forEach((p: Player, index: number) => {
Since I have awoken from my slumber I may tackle this in separate PR as well

2020-10-03 15:49 UTC, bafolts approved these changes
This is a great change since it no longer exposes player ids. I can't think of what this could break but this PR could very well have something we aren't considering. Once merged we may end up needing to react to a change. New games will most likely be fine but games that are in progress and have both color and id stored could have issues.

2020-10-04 10:30 UTC, merged