Add filter to debug UI card list.
bafolts/terraforming-mars pull request #1479
Opened 2020-10-04 23:49 UTC by kberg

![filter](https://user-images.githubusercontent.com/413481/95030052-bf49e580-067a-11eb-908c-39d4e4fbc781.png)

2020-10-05 07:25 UTC, alrusdi requested changes

2020-10-05 07:25 UTC, alrusdi commented on src/components/DebugUI.ts
> +                <h2>Cards list <input placeholder="filter" v-model="filterText"></h2>
Add classes "form-input form-inline" to the input

2020-10-05 07:25 UTC, alrusdi commented on src/components/DebugUI.ts
> +          filterText: ""
Can you take initial value of filterText from URL like "/debug-ui/?search-card=venusian" ahen component is "mounted"?

2020-10-07 04:15 UTC, kberg commented on src/components/DebugUI.ts
> +          filterText: ""
I didn't realize this was holding up the review, sorry. Can that be done in a follow-up? I'm not sure I want to start diving into URL parameters yet.

2020-10-07 07:40 UTC, alrusdi commented on src/components/DebugUI.ts
> +                <h2>Cards list <input placeholder="filter" v-model="filterText"></h2>
@kberg and what about this change?

2020-10-07 14:49 UTC, kberg commented on src/components/DebugUI.ts
> +                <h2>Cards list <input placeholder="filter" v-model="filterText"></h2>
> Add classes "form-input form-inline" to the input
Done, good, thanks!

> @kberg and what about this change?

My head doesn't have that anymore. Still an issue?

2020-10-08 04:39 UTC, alrusdi approved these changes

2020-10-08 04:39 UTC, merged