Moved buttons to vue
bafolts/terraforming-mars pull request #1490
Opened 2020-10-05 15:36 UTC by chosta

done: 
+ moved all <button> elements to a <Button> vue component
+ by default all buttons are disabled + loading when waiting for server response
+ multiple props to control the layout, functionality and behavior of the buttons

comments:
+ we might use a better loading indicator @ssimeonoff 
+ the .btn css is overriding btn-error and btn-success properties, I decided to not change functionality and do another pull request to resolve this issue
+ I think titanium max does not work properly (in comparison to steel) @nwai90 

I've tested all the changes manually but any other manual test is welcome.
@alrusdi @kberg @bafolts

2020-10-05 15:37 UTC, chosta commented
99% of the work is in 1760c532a19c123c1929911d41efe8b903f25492

2020-10-06 00:06 UTC, bafolts commented on src/components/AndOptions.ts
> +                    onClick: this.saveData,
I would prefer to still use `() => { this.saveData(); }`. The fat arrow function maps the `this` argument automatically. Leaving this function exposed as `this.saveData` I am not sure what the `this` argument will end up being. Using the fat arrow function keeps the context within this class.

2020-10-06 00:11 UTC, bafolts commented on src/components/CardsFilter.ts
> +                <Button size="small" type="error" :onClick="removeCard.bind(null, cardName)" v-html="getCrossHtml()" />
I am not sure how this works. Providing `null` as the `thisArg` to the `removeCard` function should end up causing a runtime exception.We can't lose scope.

2020-10-06 00:16 UTC, bafolts commented on src/components/LogPanel.ts
> +            <Button size="big" type="close" :onClick="hideMe" align="right" />
In other places this `getCrossHtml` was provided to `Button`. I assume that also need to be passed here.

2020-10-06 00:19 UTC, bafolts commented on src/components/OrOptions.ts
> +                                    onClick: this.saveData,
I would also use fat-arrow function as it encapsulates the `this` argument.

2020-10-06 00:19 UTC, bafolts commented on src/components/OtherPlayer.ts
> +                <Button size="big" type="close" :onClick="hideMe" align="right" />
I assume this also needs the cross HTML provided.

2020-10-06 00:23 UTC, bafolts commented on src/components/SelectColony.ts
>              <colony :colony="colony"></colony>
Does this need the `Button` component listed as a dependency?

2020-10-06 00:33 UTC, bafolts commented on src/components/WaitingFor.ts
> +            if (root.isServerSideRequestInProgress) return;
I would add a `console.warn` here when this request is ignored. If there were ever a bug regarding how `isServerSideRequestInProgress` is being set we would end up failing silently which could be very difficult to track down. With a warning logged we could spot this warning.

2020-10-06 00:35 UTC, bafolts commented on src/components/WaitingFor.ts
>              xhr.onload = () => {
`xhr.onerror` needs to also set `isServerSideRequestInProgress` to `false`.

2020-10-06 00:37 UTC, bafolts commented on src/components/common/Button.ts
> +            const classes: Array<String> = ["btn"];
This should be `Array<string>` as this pushes `string` to the array and not `String`.

2020-10-06 00:38 UTC, bafolts commented on src/components/common/Button.ts
> +            if (this.size === "small") {
This can also be `else if (this.size === "small")`

2020-10-06 00:42 UTC, bafolts commented on src/components/common/Button.ts
> +                    (this.$root as any).isServerSideRequestInProgress
As i am only vaguely familiar with vue.js I am curious. How does this template know it needs to be redrawn when `isServerSideRequestInProgress` changes. Anytime the data changes on the app does every child component redraw?

2020-10-06 00:50 UTC, bafolts requested changes
Spotted a few places of concern. 

* We should provide fat arrow function whenever possible as it retains the `this` argument. Some of the onClick handlers were binding to `null` for the `this` argument which leaves me perplexed as to how that works. We may be getting lucky that there only happens to be one instance of that class.

* There seems to be some leftover cross HTML that may have existed before a type of "close" was a thing.

* When isServerSideRequestInProgress changes on app does vue then redraw the entire application? This seems heavy handed for a button that may need to show "loading". Is there a better way to isolate this property perhaps to a `Button` singleton? If vue has a way to find all buttons it may be simpler to iterate over each button and set this property. We should try to keep this property specific to Button.

2020-10-06 06:08 UTC, chosta commented on src/components/LogPanel.ts
> +            <Button size="big" type="close" :onClick="hideMe" align="right" />
I ditched the getHtml and added types that provide the html conditionally. I should learn to group commit changes better so reviews are easier.

2020-10-06 06:13 UTC, chosta commented on src/components/SelectColony.ts
>              <colony :colony="colony"></colony>
Well spotted. I though I tested this manually...I realised it's called on rare occasions like Aridor's first action.

2020-10-06 06:18 UTC, chosta commented on src/components/common/Button.ts
> +            if (this.size === "small") {
it should,yes

2020-10-06 06:24 UTC, chosta commented on src/components/AndOptions.ts
> +                    onClick: this.saveData,
That is good point.

2020-10-06 06:25 UTC, chosta commented on src/styles/payments.less
> +/* .max_button {
done

2020-10-06 06:29 UTC, chosta commented on src/components/CardsFilter.ts
> +                <Button size="small" type="error" :onClick="removeCard.bind(null, cardName)" v-html="getCrossHtml()" />
There are two ways to pass functions with parameters as props in vue. The first is what you see and null is replacing the event which is the default parameter if we do it like that. This does work. The recommended Vue way is to use $emit but I couldn't make it work. I'll give it one more try and ask for help if I don't succeed.
https://stackoverflow.com/a/39479405/83336

2020-10-06 06:32 UTC, chosta commented on src/components/LogPanel.ts
> +            <Button size="big" type="close" :onClick="hideMe" align="right" />
Nevermind, I actually left it in one place. Well spotted

2020-10-06 06:44 UTC, chosta commented on src/components/WaitingFor.ts
> +            if (root.isServerSideRequestInProgress) return;
Makes sense. Not sure I did it correct as I don't see any warning. Please, check 
0107b3d

2020-10-06 06:45 UTC, chosta commented on src/components/common/Button.ts
> +                    (this.$root as any).isServerSideRequestInProgress
I'll comment below

2020-10-06 06:50 UTC, alrusdi commented on src/components/CardsFilter.ts
> +                <Button size="small" type="error" :onClick="removeCard.bind(null, cardName)" v-html="getCrossHtml()" />
Have you tried something like :onClick="_=>removeCard(cardName)" ?

2020-10-06 06:55 UTC, chosta commented
> * We should provide fat arrow function whenever possible as it retains the `this` argument. Some of the onClick handlers were binding to `null` for the `this` argument which leaves me perplexed as to how that works. We may be getting lucky that there only happens to be one instance of that class.

Need to try using $emit for parent to child function with params as a prop, as it is the recommended vue way. This one works too, though. I've done it in react many times and I figured that it shold be safe but I recognize your concerns.



> * There seems to be some leftover cross HTML that may have existed before a type of "close" was a thing.

Done



> * When isServerSideRequestInProgress changes on app does vue then redraw the entire application? This seems heavy handed for a button that may need to show "loading". Is there a better way to isolate this property perhaps to a `Button` singleton? If vue has a way to find all buttons it may be simpler to iterate over each button and set this property. We should try to keep this property specific to Button.

I am using my intuition here again coming from my experience from React. I presume that global state in vue works in a similar way as context (also redux) in React. The approach `it may be simpler to iterate over each button` was initially introduced by @alrusdi who iterated (hardcore) trough all .btn elements and added the "loading" class. This whole PR was done to avoid the approach :) .Now that we have a Button as Vue we might have a solution that iterates the elements just not sure how atm. I'll research a bit but any help here is needed from more experienced Vue users.

2020-10-06 08:26 UTC, chosta commented on src/components/CardsFilter.ts
> +                <Button size="small" type="error" :onClick="removeCard.bind(null, cardName)" v-html="getCrossHtml()" />
what kind of sorcery is this :D

2020-10-06 23:40 UTC, bafolts approved these changes
Code wise nothing stands out anymore. Once rolled out if there is some bug I assume it will show up as some click event not working as expected.

2020-10-07 07:39 UTC, merged