Fix global requirement adjustment box
bafolts/terraforming-mars pull request #1494
Opened 2020-10-05 18:51 UTC by vsrisuknimit

- Changed global requirement from "temp/O2/ocean" to "global requirements" so that it implies Venus ad well.
- Fixed the link of community-corp wiki page.

![image](https://user-images.githubusercontent.com/14239220/95119559-236fb680-071a-11eb-832a-7997b3291ebd.png)

![image](https://user-images.githubusercontent.com/14239220/95119588-2ec2e200-071a-11eb-964a-63904567a43f.png)

2020-10-05 18:52 UTC, vsrisuknimit commented
This PR addresses #1489.

2020-10-05 21:55 UTC, kberg commented
Speaking as someone who doesn't use Venus, I'd much prefer the original. If you wanted to add "Venus" to the global requirements box, that wouldn't bother me as much. Plus, if cards eventually become data driven like Dani is planning, Venus can be optionally added and removed.

2020-10-06 05:15 UTC, alrusdi requested changes

2020-10-06 05:15 UTC, alrusdi commented on src/HTML_data.ts
> +                  (Effect: Your temperature, oxygen, ocean, and venus requirements are +2 or -2 steps, your choice in each case.)
Please change this text in all translations too

2020-10-06 05:21 UTC, kberg commented on src/HTML_data.ts
> +                  (Effect: Your temperature, oxygen, ocean, and venus requirements are +2 or -2 steps, your choice in each case.)
"venus requirements" should be "Venus requirements."

2020-10-06 09:16 UTC, vsrisuknimit commented on src/HTML_data.ts
> +                  (Effect: Your temperature, oxygen, ocean, and venus requirements are +2 or -2 steps, your choice in each case.)
Fixed

2020-10-06 09:21 UTC, alrusdi commented
@vsrisuknimit What about Special Design card? Is it included?

2020-10-06 09:28 UTC, alrusdi approved these changes

2020-10-06 09:29 UTC, merged