Fix new graphics on corporations
bafolts/terraforming-mars pull request #1519
Opened 2020-10-06 18:03 UTC by vsrisuknimit

- Update the corporations with new graphics.

Some examples:

Old
![image](https://user-images.githubusercontent.com/14239220/95241982-9477a280-07dc-11eb-9ca2-c0758e903cbf.png)

Updated
![image](https://user-images.githubusercontent.com/14239220/95242024-a0fbfb00-07dc-11eb-8507-acef07840ccf.png)
![image](https://user-images.githubusercontent.com/14239220/95242070-ae18ea00-07dc-11eb-9a9a-ccf08a319d5b.png)
![image](https://user-images.githubusercontent.com/14239220/95242110-bbce6f80-07dc-11eb-95c7-33c935222b9a.png)

2020-10-06 19:06 UTC, alrusdi requested changes

2020-10-06 19:06 UTC, alrusdi commented on src/HTML_data.ts
> +      <div class="production-box production-box-size3" style="margin-left:20px;margin-top:-10px;">
Please move inline styles to cards.less

2020-10-06 19:15 UTC, vsrisuknimit commented on src/HTML_data.ts
> +      <div class="production-box production-box-size3" style="margin-left:20px;margin-top:-10px;">
@alrusdi There are inline styles everywhere in corporation cards. Do you want me to move just this one box specifically or everywhere?

Full Helion code for example:
https://github.com/bafolts/terraforming-mars/blob/6ec98ef60abb6d5988e1d20cf80b00cf4a8a2901/src/HTML_data.ts#L5119-L5150

2020-10-06 19:23 UTC, alrusdi commented on src/HTML_data.ts
> +      <div class="production-box production-box-size3" style="margin-left:20px;margin-top:-10px;">
Not all, but if you take some card to fix please do full cleanup of that card. 
In this case move all inline styles of Helion corp to cards.less
If each of us will do it - someday we will finish that cleanup

2020-10-07 00:23 UTC, vsrisuknimit commented on src/HTML_data.ts
> +      <div class="production-box production-box-size3" style="margin-left:20px;margin-top:-10px;">
@alrusdi I moved all inline style for Helion to card.less. I fixed many other corps too in terms of graphics but I will deal with their styles later if that is okay.

2020-10-07 07:35 UTC, alrusdi approved these changes

2020-10-07 07:35 UTC, merged