Add community preludes
bafolts/terraforming-mars pull request #1528
Opened 2020-10-07 11:10 UTC by nwai90

<img width="739" alt="Screenshot 2020-10-07 at 7 07 53 PM" src="https://user-images.githubusercontent.com/2408094/95323438-bbaf9c00-08d0-11eb-9ccd-8e56e2ded1f3.png">

2020-10-07 11:21 UTC, alrusdi reviewed
Do we really need assets/miranda.jpg?

2020-10-07 12:22 UTC, vsrisuknimit commented on src/HTML_data.ts
> +          <div class="triangle triangle-black"></div>
Use these instead of colony.
<div class="tile colony"></div>
<div class="tile colony"></div>

2020-10-07 12:26 UTC, vsrisuknimit requested changes

2020-10-07 12:26 UTC, vsrisuknimit commented on src/HTML_data.ts
> +          <div class="triangle triangle-white"></div> : <span style="font-family:Prototype;font-size:24px;">+1</span>
Use this from Trade Envoy:
`<div class="tile trade"></div> : <span class="card-sign">+1</span>`

2020-10-07 12:29 UTC, kberg requested changes
Also, are you planning tests for these new cards?

2020-10-07 12:29 UTC, kberg commented on src/cards/colonies/SpacePortColony.ts
> +      if (player.fleetSize < MAX_FLEET_SIZE) player.fleetSize++;
Instead of doing this every time, can you add player.adjustFleetSize()?

2020-10-07 13:05 UTC, nwai90 commented
> Do we really need assets/miranda.jpg?

Oops. Rebase issue :)

2020-10-07 13:13 UTC, nwai90 commented on src/cards/colonies/SpacePortColony.ts
> +      if (player.fleetSize < MAX_FLEET_SIZE) player.fleetSize++;
Good idea! I will add it as `player.increaseFleetSize()` as there's no situation (yet) where a player can lose a trade fleet

2020-10-08 04:59 UTC, alrusdi approved these changes

2020-10-08 06:04 UTC, kberg commented on src/cards/colonies/SpacePortColony.ts
> +      if (player.fleetSize < MAX_FLEET_SIZE) player.fleetSize++;
Thanks!

2020-10-08 06:04 UTC, kberg commented
> Also, are you planning tests for these new cards?

I'd like an answer to this one if you don't mind.

2020-10-08 07:38 UTC, nwai90 commented
> > Also, are you planning tests for these new cards?
> 
> I'd like an answer to this one if you don't mind.

Ah, missed that. Done~

2020-10-09 00:50 UTC, kberg commented
Hi!

If I submit #1444 it would break this PR, and it's probably easier for me to resolve those than for you to (as I know the layout) I'll wait until this is submitted and resolve it.

2020-10-09 04:27 UTC, nwai90 commented on src/cards/community/PoliticalUprising.ts
> +            const turmoilCards = ALL_TURMOIL_PROJECTS_CARDS.map((c) => c.cardName);
Good catch - updated to remove the card from deck.

I would not alter the description though. The previous print version descriptions are way too lengthy and newer cards like Factorum have officially adopted the shorthand description (https://boardgamegeek.com/thread/2351530/article/33827350#33827350)

2020-10-09 04:37 UTC, kberg commented on src/cards/community/PoliticalUprising.ts
> +            const turmoilCards = ALL_TURMOIL_PROJECTS_CARDS.map((c) => c.cardName);
> I would not alter the description though. The previous print version descriptions are way too lengthy and newer cards like Factorum have officially adopted the shorthand description (https://boardgamegeek.com/thread/2351530/article/33827350#33827350)

OK.

2020-10-09 04:37 UTC, kberg commented on src/HTML_data.ts
> +          Raise Venus 2 steps. Draw 2 Venus cards from the deck.
> This is probably going to be the same issue. I recommend changing the text to "Draw cards from the deck until you reveal 2 venus cards. Put those cards in your hand and discard the rest." Or whatever Acquired Space Agency says.

And you can ignore this, too.

2020-10-09 05:19 UTC, nwai90 commented on src/Player.ts
> +        if (selectedCard.name === CardName.VALUABLE_GASES) {
Moved. Same for Eccentric Sponsor and Ecology Experts above

2020-10-09 06:08 UTC, kberg commented on src/cards/community/AerospaceMission.ts
> +              let description = "Build colonies on " + c1.name + " (" + c1.description + ") and " + c2.name + " (" + c2.description + ")"
let description = `Build colonies on ${c1.name} (${c1.description}) and ${c2.name} (${c2.description})"

Your call of course.

2020-10-09 06:09 UTC, kberg commented on src/cards/community/ByElection.ts
> +        if (game.gameOptions.turmoilExtension) {
Probably not necessary since the card will only be in play with the Turmoil extension.

2020-10-09 06:11 UTC, kberg commented on src/cards/community/PoliticalUprising.ts
> +            const turmoilCards = ALL_TURMOIL_PROJECTS_CARDS.map((c) => c.cardName);
Sorry, are you sure it's not supposed to be something like `game.drawProjectCardsByCondition(1, c => turmoilCards.includes(card.name))`

2020-10-09 06:13 UTC, kberg commented on tests/cards/community/AerospaceMission.spec.ts
> +        expect(openColonies[0].colonies.find((c) => c === player.id)).not.to.eq(undefined);
You can do is.not.undefined or .is.undefined Your call.

2020-10-09 06:14 UTC, kberg commented on tests/cards/community/PoliticalUprising.spec.ts
> +    it("Should play", function () {
I just like this test.

2020-10-09 06:15 UTC, kberg approved these changes
Minor stuff obviously. This is good! I look forward to playing these.

2020-10-09 06:33 UTC, nwai90 commented on src/cards/community/PoliticalUprising.ts
> +            const turmoilCards = ALL_TURMOIL_PROJECTS_CARDS.map((c) => c.cardName);
@kberg I thought about that. Turmoil cards are relatively rare (only 16 of them) and it's preferable to avoid discarding a large chunk of the deck here imo. This is only possible here as we can easily grab one from the deck this way without affecting all other cards in the deck

2020-10-09 06:36 UTC, nwai90 commented on tests/cards/community/AerospaceMission.spec.ts
> +        expect(openColonies[0].colonies.find((c) => c === player.id)).not.to.eq(undefined);
👍 Saw it! That's easier yes

2020-10-09 07:02 UTC, nwai90 commented on src/cards/community/ByElection.ts
> +        if (game.gameOptions.turmoilExtension) {
I will remove this check and add a test for it. More defensive

2020-10-10 10:35 UTC, merged

2020-10-10 14:09 UTC, bafolts commented on src/Player.ts
> +        const preludesWithPlayCardEffects = [CardName.ECOLOGY_EXPERTS, CardName.ECCENTRIC_SPONSOR, CardName.VALUABLE_GASES];
I am looking through recent commits to spot issues which could have crashed the heroku instance as the cheap plan logs only go back 1500 entries. This usage of `selectedCard.addPlayCardInterrupt!` is dangerous. If that function doesn't exist at some point it will lead to a runtime exception. I would instead remove this look-up and use:

```
if (selectedCard.addPlayCardInterrupt !== undefined) {
    selectedCard.addPlayCardInterrupt(this, game);
}
```

Also avoids the need of the lookup. This most likely didn't cause the crash as the property should exist.

2020-10-10 14:12 UTC, bafolts commented on src/cards/IProjectCard.ts
> +    addPlayCardInterrupt?: Function;
The usage of `Function` is too abstract. This should be the type with arguments such as `(player: Player, game: Game) => void`.

2020-10-10 14:16 UTC, bafolts commented on src/cards/community/ByElection.ts
> +        game.turmoil!.addInfluenceBonus(player);
If `game.turmoil` is `undefined` this will crash the server.

2020-10-10 14:17 UTC, bafolts commented on src/cards/community/ByElection.ts
> +            game.turmoil!.rulingParty = game.turmoil!.getPartyByName(p.partyName);
This usage of `game.turmoil!` can crash the server if `turmoil` is `undefined`. This class doesn't create the `turmoil` property on `game` so can't assume it will exist.

2020-10-10 14:21 UTC, bafolts commented on src/cards/community/VenusFirst.ts
> +            game.log("${0} drew ${1} and ${2}", b => b.player(player).card(drawnCards[0]).card(drawnCards[1]));
If `drawnCards[0]` or `drawnCards[1]` is `undefined` this will crash the game server.