Improve game creation page
bafolts/terraforming-mars pull request #1551
Opened 2020-10-09 13:09 UTC by vsrisuknimit

- Remove radio box and toggle. Create clickable label instead.
- Add icons for expansions.
- Add color for boards, move board column next to expansion.

![image](https://user-images.githubusercontent.com/14239220/95586652-fae40700-0a0e-11eb-9e65-008ba7898d3c.png)

2020-10-09 13:22 UTC, kberg commented
That looks great.

2020-10-09 14:14 UTC, vsrisuknimit commented
still working on turning WGT by default upon clicking venus expansion. Not working yet. Need help @kberg .

2020-10-09 15:19 UTC, chosta commented on src/components/CreateGameForm.ts
> +        getBoardColor: function(boardName: String): String {
1) Better to be explicit here `getBoardColorClass` - we get a string but we don't know what it is
2) We use lowercase for `string` `boolean` etc. types. Capital letters for classes like `Player`

2020-10-09 15:24 UTC, chosta requested changes
Great work! Visually appealing and very intuitive.

2020-10-09 15:24 UTC, chosta commented on src/components/CreateGameForm.ts
> +                    <!--CREATE PLAYERNAME AND COLOR HERE-->
Comments only for non-trivial code if possible. Also html comments are using bytes.

2020-10-09 15:24 UTC, chosta commented on src/components/CreateGameForm.ts
> +                                <span v-i18n>63 TR solo mode</span>&nbsp;<a href="https://github.com/bafolts/terraforming-mars/wiki/Variants#tr-solo-mode" class="tooltip" target="_blank">&#9432;</a>
avoid using `&nbsp;` it's almost always better to have a markup on an element that offsets a couple of pixels

2020-10-09 15:24 UTC, chosta commented on src/styles/common.less
> +/*
We can get rid of comments in css.

2020-10-09 15:24 UTC, chosta commented on src/styles/create_game_form.less
> +    background-color: rgba(238, 121, 43, 0.5);
Please, check `variables.less` and `mixins.less` and try to add colors for the different expansions as constants. We should aim for reusable code in every possible way :)

2020-10-09 16:25 UTC, vsrisuknimit commented on src/components/CreateGameForm.ts
> +                    <!--CREATE PLAYERNAME AND COLOR HERE-->
It was non-trivial to me at first why it was on top not at the bottom.

2020-10-09 16:26 UTC, vsrisuknimit commented on src/components/CreateGameForm.ts
> +                                <span v-i18n>63 TR solo mode</span>&nbsp;<a href="https://github.com/bafolts/terraforming-mars/wiki/Variants#tr-solo-mode" class="tooltip" target="_blank">&#9432;</a>
It was already there for ? question mark help icon. Should I replace it or add a class on top of it?

2020-10-09 16:32 UTC, chosta commented
No need, just a recommendation for the future

On Fri, Oct 9, 2020, 19:27 Jeep <notifications@github.com> wrote:

> *@vsrisuknimit* commented on this pull request.
> ------------------------------
>
> In src/components/CreateGameForm.ts
> <https://github.com/bafolts/terraforming-mars/pull/1551#discussion_r502542987>
> :
>
> >
> -                            <label class="form-switch" v-if="playersCount > 1">
> -                                <input type="checkbox" v-model="randomFirstPlayer">
> -                                <i class="form-icon"></i> <span v-i18n>Random first player</span>
> +                            <template v-if="playersCount === 1">
> +                            <input type="checkbox" v-model="soloTR" id="soloTR-checkbox">
> +                            <label for="soloTR-checkbox">
> +                                <span v-i18n>63 TR solo mode</span>&nbsp;<a href="https://github.com/bafolts/terraforming-mars/wiki/Variants#tr-solo-mode" class="tooltip" target="_blank">&#9432;</a>
>
> It was already there for ? question mark help icon. Should I replace it or
> add a class on top of it?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/bafolts/terraforming-mars/pull/1551#discussion_r502542987>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGMEU4DNGURDTYIWMHARF3SJ42V7ANCNFSM4SKB4TRA>
> .
>

2020-10-09 22:02 UTC, vsrisuknimit commented on src/styles/create_game_form.less
> +    background-color: rgba(238, 121, 43, 0.5);
added

2020-10-09 22:04 UTC, vsrisuknimit commented
Solo selected:

![image](https://user-images.githubusercontent.com/14239220/95635163-ab76f880-0a59-11eb-947d-55e3b8f0b1fa.png)

More than one player selected:

![image](https://user-images.githubusercontent.com/14239220/95635196-bf225f00-0a59-11eb-810e-95592e18de51.png)

2020-10-09 22:09 UTC, vsrisuknimit commented
One more thing to add then I am done. Working on the color selection.

2020-10-10 13:10 UTC, vsrisuknimit commented
@alrusdi Could you have a look at this?

2020-10-12 09:00 UTC, chosta commented
Looks good to me. Let's see what @alrusdi has to say about it.

2020-10-12 11:12 UTC, alrusdi commented
I like it!

2020-10-12 12:20 UTC, vsrisuknimit commented
@alrusdi Thanks!

It is good to go if someone approves of the code change.

2020-10-12 12:22 UTC, alrusdi approved these changes

2020-10-12 12:23 UTC, merged