Cards metadata to vue
bafolts/terraforming-mars pull request #1605
Opened 2020-10-13 15:46 UTC by chosta

Continuing the battle with HTML_data.ts:
+ added `CardMetadata` interface (still more attributes to come)
+ added CardRequirements to metadata
+ abstracting the `<div class="content">` by checking if metadata exists. If yes => use Vue components , no => use the HTML_data.ts content
+ first card to be set free is also the best one in the game ->>> `Dust Seals` !

This is WIP so, please just comment on what you think needs to change in the existing code and not what is still missing :)

2020-10-14 04:51 UTC, kberg commented
I hate to correct you, but the best card in the game is the one that I play to take six plants away from **you**! BAHAHAHAHAHAHA,

Lemme look at your PR.

2020-10-14 04:59 UTC, kberg requested changes

2020-10-14 04:59 UTC, kberg commented on src/cards/CardRequirement.ts
> +    private getParsedAmount(): string {
Include degree for temperature?

Also toString() is a more than adequate name.

2020-10-14 04:59 UTC, kberg commented on src/cards/CardRequirement.ts
> +    public getReqText(): string {
Sorry, what does getReqText mean?

2020-10-14 04:59 UTC, kberg commented on src/cards/DustSeals.ts
> +        requirements: new CardRequirements([
Have CardRequirements accept `...CardRequirement`

Also this can be made much simpler vis. LogBuilder.

Imagine this Api:

```
requirements: CardRequirements.create(b => {
  b.oceans(3).max();
  b.science(12);
});
```

2020-10-14 04:59 UTC, kberg commented on src/cards/DustSeals.ts
> +        requirements: new CardRequirements([
It's about a hundred of these, that'll be much easier to read.

2020-10-14 04:59 UTC, kberg commented on src/cards/DustSeals.ts
> +        return (
Can you disable the auto formatter so reviews are more focused?

2020-10-14 04:59 UTC, kberg commented on src/cards/IProjectCard.ts
>      hasRequirements?: boolean;
I think this makes hasRequirements obsolete, right?

2020-10-14 04:59 UTC, kberg commented
Terrific, I love this. Keep it up and to show my thanks I'll pass you `Sabotage` in the draft.

2020-10-14 13:55 UTC, chosta commented on src/cards/CardRequirement.ts
> +    public getReqText(): string {
:) means a lazy dev does things twice

2020-10-14 13:56 UTC, chosta commented on src/cards/DustSeals.ts
> +        return (
I'd like to give another approach a try instead. First format all the files I want to work on and send as a separate commit. I won't give up on formatting that easy :)
+ I increased default width to 160 columns so let's see how it goes
I appreciate your patience

2020-10-14 13:57 UTC, chosta commented on src/cards/IProjectCard.ts
>      hasRequirements?: boolean;
It does but I dare not make breaking changes at the moment. I'll add it as a to-do and resolve 
after all cards are gone from the HTML_data

2020-10-14 15:16 UTC, kberg commented on src/cards/CardRequirement.ts
> +    public getReqText(): string {
Sorry, I mean requirement or request? Would you mind spelling it out? (Then I won't ask for a comment! ;))

2020-10-14 15:18 UTC, kberg commented on src/cards/DustSeals.ts
> +        return (
> I appreciate your patience
I felt the same way, I did feel a little bad making the request.

2020-10-14 15:22 UTC, chosta commented on src/cards/CardRequirement.ts
> +    public getReqText(): string {
The curse of knowledge strikes again :)
I'm doing some refactoring, will tag you as soon as I have something complete.

2020-10-14 15:24 UTC, chosta commented on src/cards/DustSeals.ts
> +        return (
But this is a legitimate concern. We have to appreciate the time and effort of reviewers, so lets find a common ground.

2020-10-14 15:27 UTC, kberg commented on src/cards/DustSeals.ts
> +        return (
This is not the thread for it, but so you know, I think the right approach is that we move quickly to adopt a common standard -- if we can reach consensus.

2020-10-14 15:32 UTC, bafolts commented on src/cards/CardMetadata.ts
> +    points?: number; //#TODO -> class to handle points per tag and other special cases
I would use `victoryPoints` for this name as it is more specific than `points`.

2020-10-14 15:35 UTC, bafolts commented on src/cards/CardRequirement.ts
> +    isMax?: boolean = false;
What does it represent if `isMax` is `undefined` versus `false`?

2020-10-14 15:37 UTC, bafolts commented on src/cards/CardRequirements.ts
> +        return this.requirements.filter((req) => req.isMax).length > 0;
This is a good use case for `Array.prototype.some`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2020-10-14 15:42 UTC, bafolts commented on src/cards/DustSeals.ts
> +    public metadata: CardMetadata = {
Could `tags` and `cardType` also go on `CardMetadata`? We don't have a `SerializedCard` but eventually `SerializedCard` would only need to store the `CardName` and any resources on the card or other dynamic properties.

2020-10-14 15:56 UTC, chosta commented on src/cards/CardRequirements.ts
> +    public static create(f: (r: CardRequirement) => void): CardRequirements {
@kberg I need some help here :/
Managed to make the first part of the API that you suggested but not sure how to accept multiple CardRequirements in the create method like you suggested. This concept is new to me, feel free to explain what happens in details :)
I'm trying to do that:
`CardRequirements.create((b) => {
            b.oceans(3).max();
            b.science(1)
        }),`

2020-10-14 15:58 UTC, chosta commented on src/cards/CardRequirement.ts
> +    isMax?: boolean = false;
You already know that I'm scared of `undefined` and try to avoid it. If I understand correctly you are suggesting that isMax could simply have the ? and lose the default `false` value?

2020-10-14 15:59 UTC, chosta commented on src/cards/CardMetadata.ts
> +    points?: number; //#TODO -> class to handle points per tag and other special cases
good point (pun intended)

2020-10-14 16:21 UTC, chosta commented on src/cards/CardRequirements.ts
> +        return this.requirements.filter((req) => req.isMax).length > 0;
yes!

2020-10-15 12:03 UTC, chosta commented
@kberg followed your guidance for the CardRequirement refactor. I am also ditching the formatter, just fixing files that are having 2 spaces and having it turned off most of the time.
@bafolts I see that there is some code / logic repetition in the cards like victory points, tags, etc. I'd rather focus on having the complete card description using the metadata and then start refactoring and removing the repetitive logic.
Let me know what you think.

2020-10-17 21:12 UTC, kberg commented
Is this ready for re-review? Sorry for losing track. Also note merge conflict.

2020-10-18 07:55 UTC, chosta commented
@kberg I got this after merging and not sure how to approach it:
```/home/dev/terraforming-mars/dist/src/Dealer.js:27
        found = deck.projectCards.findByCardName(cardName);
                     ^

TypeError: Cannot read property 'projectCards' of undefined
    at /home/dev/terraforming-mars/dist/src/Dealer.js:27:22
    at Array.forEach (<anonymous>)
    at getProjectCardByName (/home/dev/terraforming-mars/dist/src/Dealer.js:23:19)
    at /home/dev/terraforming-mars/dist/src/Dealer.js:157:20
    at Array.map (<anonymous>)
    at Dealer.loadFromJSON (/home/dev/terraforming-mars/dist/src/Dealer.js:156:28)
    at Game.loadFromJSON (/home/dev/terraforming-mars/dist/src/Game.js:1345:30)
    at Statement.<anonymous> (/home/dev/terraforming-mars/dist/src/database/SQLite.js:65:18)
```

2020-10-18 16:39 UTC, kberg commented on src/cards/CardRequirement.ts
> +    isMax?: boolean = false;
Or not have ? at all.

2020-10-18 16:45 UTC, kberg commented
> @kberg I got this after merging and not sure how to approach it:
> 
> ```
>         found = deck.projectCards.findByCardName(cardName);
>                      ^
> 
> TypeError: Cannot read property 'projectCards' of undefined
>     at /home/dev/terraforming-mars/dist/src/Dealer.js:27:22
>     at Array.forEach (<anonymous>)
>     at getProjectCardByName (/home/dev/terraforming-mars/dist/src/Dealer.js:23:19)
>     at /home/dev/terraforming-mars/dist/src/Dealer.js:157:20
>     at Array.map (<anonymous>)
>     at Dealer.loadFromJSON (/home/dev/terraforming-mars/dist/src/Dealer.js:156:28)
>     at Game.loadFromJSON (/home/dev/terraforming-mars/dist/src/Game.js:1345:30)
>     at Statement.<anonymous> (/home/dev/terraforming-mars/dist/src/database/SQLite.js:65:18)
> ```
> 
> It's obviously an old game that doesn't load properly on my local machine. I could purge the DB but this needs attention because it might break other instances (maybe not the demo).

Confirmed that a fresh DB doesn't exhibit this behavior. As I mentioned in chat, send me the DB and I'll see exactly why.

2020-10-22 03:58 UTC, kberg requested changes
Not bad!

2020-10-22 03:58 UTC, kberg commented on src/cards/AdvancedEcosystems.ts
> +            CardRequirement.tag(Tags.PLANT, -1),
Why is this -1? Shouldn't it be 1?

2020-10-22 03:58 UTC, kberg commented on src/cards/IProjectCard.ts
>      hasRequirements?: boolean;
How do you track your TODOs? Are you creating a tracking bug or a comment here, or just do it later?

2020-10-22 03:58 UTC, kberg commented on src/cards/IProjectCard.ts
> +    metadata?: CardMetadata;
IProjectCard extends ICard, for which metadata is a field. Can this be removed?

2020-10-22 06:17 UTC, chosta commented on src/cards/IProjectCard.ts
> +    metadata?: CardMetadata;
Strange, I remember TS complained about not having it. Now that I removed it its all good.

2020-10-22 06:20 UTC, chosta commented on src/cards/AdvancedEcosystems.ts
> +            CardRequirement.tag(Tags.PLANT, -1),
So the thing here is that we sometimes want the actual "1" in front of the requirement:
`max 1 colony`
And in the case we just want the tag name:
`plant microbe animal`
So I figured we could use the `-1` to skip numbers. Maybe an inline comment would help here. I don't wan to overcomplicate things anyway.

2020-10-22 06:35 UTC, chosta commented on src/cards/CardRequirement.ts
> +    public getLabel(): string {
I prefer dealing with whitespaces by using arr.join(" ") but I'll indulge you here:
The `+=` should help improve it a bit more but this `"max "` is a thorn in my eyes just FYI :)
```
let result: string = this.isMax ? "max " : "";
        const amount = this.amountToString();
        if(amount !== ""){
            result += amount;
            result += " ";
        }
        result += this.parseType();

        return result;
```

2020-10-22 06:36 UTC, chosta commented on src/cards/CardRequirement.ts
> +        if(this.type === RequirementType.CITIES) {
I'll add it to a commit in the future.

2020-10-22 06:53 UTC, chosta commented on src/cards/BreathingFilters.ts
>      public cost: number = 11;
I'd like to do that too. No complaints from TS so we should be good to go.

2020-10-22 15:15 UTC, chosta commented
Alright. Progress made.
+ Did changes from your latest reviews but some items will remain with a TODO status
+ I did a thing where `onPlay` in metadata should be able to describe every remaining element from any card design
+ I figured all elements could be described with `CardRow` and items inside of them so I tried to do something that accepts arrays of different types of elements. It does the job of ordering the elements too. I know it might be a bit controversial but the resulting api allows for a fast and seamless card content implementation.
+ A `CardProductionBox` can already reuse some of the components and classes and can be a part of a `CardRow` so this went well, although I have a feeling we can clean up the code (vue especially) and make it even more reusable.
+ I am slowly moving to a new cards_v2.less file that improves css significantly, especially when it comes to centering items and reducing hardcoded styles (thanks flexbox! <3)
+ Started replacing some of the cards and boy is this satisfying. Everything centered and pixel perfect :). Thanks you @kberg for helping me with these APIs, I like how easy is to describe things in human readable manner. With the current functionality should you approve it, I can cover 80% of the cards.

--- still to come ---
+ unit tests once we are decided on the class and interfaces structure
+ `CardEffect`
+ `CardAction`
+ corporations will be left for last but nothing can stop me now

2020-10-23 05:01 UTC, kberg commented on src/cards/AdvancedEcosystems.ts
> +            CardRequirement.tag(Tags.PLANT, -1),
Could have default be 0 or -1?

2020-10-23 05:03 UTC, kberg commented on src/cards/Asteroid.ts
> +        if (PartyHooks.shouldApplyPolicy(game, PartyName.REDS) && !temperatureMaxed) {
As I mentioned to @Lynesth, this kind of reformatting makes reviews harder. This is only 55 files, Lynesth's is over 200! :D

2020-10-23 05:10 UTC, kberg commented on src/cards/IProjectCard.ts
> +// import { CardMetadata } from "../cards/CardMetadata";
Remove?

2020-10-23 05:10 UTC, kberg commented on src/cards/RequirementType.ts
> +    RESOURCE_TYPES = "Resource type",
"Resource types"? (The s at the end.)

2020-10-23 05:10 UTC, kberg commented on src/components/card/CardDescription.ts
> +//#TODO implement points per tag
Recommend TODO(chosta): so it's obvious who's responsible.

2020-10-23 05:10 UTC, kberg commented on src/components/card/CardProductionBoxComponent.ts
> +        console.log(this.data);
eh?

2020-10-23 05:10 UTC, kberg commented on src/styles/cards_v2.less
> +@import "./variables.less";
Tell me more about v2 - is this a temporary name?

2020-10-23 05:10 UTC, kberg commented on src/utils/utils.ts
> +export const firstLetterUpperCase = (s: string): string => s.charAt(0).toUpperCase() + s.slice(1);
You're only using this in one place? Just inline it.

2020-10-26 09:21 UTC, chosta commented on src/cards/Asteroid.ts
> +        if (PartyHooks.shouldApplyPolicy(game, PartyName.REDS) && !temperatureMaxed) {
It's going well, just a couple of merge conflicts :)

2020-10-26 09:22 UTC, chosta commented on src/cards/IProjectCard.ts
> +// import { CardMetadata } from "../cards/CardMetadata";
yes

2020-10-26 09:25 UTC, chosta commented on src/components/card/CardProductionBoxComponent.ts
> +        console.log(this.data);
Just for debugging purposes. Won't be seen in the merge (promise!)

2020-10-26 09:26 UTC, chosta commented on src/styles/cards_v2.less
> +@import "./variables.less";
Its temporary. And its v2 beacuse the css will be refactored and improved significantly.

2020-10-26 09:28 UTC, chosta commented on src/utils/utils.ts
> +export const firstLetterUpperCase = (s: string): string => s.charAt(0).toUpperCase() + s.slice(1);
You are correct about this. My reasoning is that this is a function I have in all my js projects and it's usually used multiple times. I'll move it as this is the correct thing to do.

2020-10-26 09:51 UTC, chosta commented on src/cards/RequirementType.ts
> +    RESOURCE_TYPES = "Resource type",
I'm not sure how to approach this. I follow the logic of OCEANS where we can have 1 Ocean or many Oceans and use it when creating the label text /toPlural/. Changing this to `Resource types` will result in failing unit tests. We can have a card with 1 Resource type as a requirement so I'd leave it as it.

2020-10-27 03:22 UTC, kberg commented on src/styles/cards_v2.less
> +@import "./variables.less";
:+1:

2020-10-27 03:23 UTC, kberg commented
I didn't realize this was five days neglected - sorry!

2020-10-27 03:26 UTC, kberg approved these changes

2020-10-27 03:26 UTC, kberg commented on src/cards/CardMetadata.ts
> +    victoryPoints?: number; //TODO(chosta): class to handle points per tag and other special cases
number | (c: Card) => number ?

2020-10-27 03:27 UTC, kberg commented
This looks great. Is it ready to pull in?

2020-10-27 03:31 UTC, kberg requested changes

2020-10-27 03:31 UTC, kberg commented on src/cards/CardRow.ts
> +export class CardRow {
So, what_is_ a `CardRow` exactly? (You know what I'm going to ask for next. Mwa ha ha ha ha.)

2020-10-27 12:13 UTC, chosta commented on src/cards/CardMetadata.ts
> +    victoryPoints?: number; //TODO(chosta): class to handle points per tag and other special cases
The TODO is for the general functionality but yes, something like that

2020-10-27 12:19 UTC, chosta commented on src/cards/CardRow.ts
> +export class CardRow {
I know but I just really wanted to go for a human understandable API and had to cut some corners. Feel free to suggest any improvements but this to me feels extremely comfortable:
```
public metadata: CardMetadata = {
        description:
            "Raise temperature 2 steps and gain 4 titanium. Remove up to 4 Plants from any player.",
        cardNumber: "011",
        onPlay: [
            CardRow.add([CardBonus.temperature(2)]),
            CardRow.add([CardBonus.titanium(4)]),
            CardRow.add([CardBonus.plants(-4).any()]),
        ],
    };
```
OR
```
public metadata: CardMetadata = {
        description:
            "Add 2 Microbes to ANOTHER card. Increase your heat production 3 steps and your Plant productions 1 step.",
        cardNumber: "170",
        onPlay: [
            CardRow.add([
                  CardProductionBox.add([
                        [CardBonus.heat(3)]
                   ])
            ]),
            CardRow.add([CardBonus.microbes(2), CardSpecial.asterix()]),
        ],
    };
```

2020-10-27 12:23 UTC, chosta commented
> This looks great. Is it ready to pull in?
I'm in the process of functionally describing almost every element that is expected to be on a card. That includes Actions and Effects (should come in the next commits).
I'd like to try doing some tests on the Vue components with the new vue-type-checking approach that @bafolts suggested.
Once we have that, we can merge so others can join and help with the rest of the cards. It takes around 5 mins to describe a card with the metadata AND it's fun :)

2020-10-27 23:44 UTC, kberg commented on src/cards/AerobrakedAmmoniaAsteroid.ts
> +            "Select card to add 2 microbes",
@chosta I'm sorry -- the reformatting makes it difficult to identify the meaningful changes. Can you please remove them?

2020-10-28 06:26 UTC, chosta commented on src/cards/AerobrakedAmmoniaAsteroid.ts
> +            "Select card to add 2 microbes",
@kberg Sorry about that but I actually have autoformatting turned off by default and do most of the formatting manually now...I do agree that it is really hard to identifiy meaningful changes so I'll make sure formatting goes to a separate commit. The only meaningful change for the existing ICard components in the previous commits would be adding the `metadata` property. I don't touch anything else.
Still, if you think I have to do git surgery so it would be easier to review I can go back and do some patching

2020-10-28 16:25 UTC, kberg commented on src/cards/AerobrakedAmmoniaAsteroid.ts
> +            "Select card to add 2 microbes",
Please. This is an 80-file PR.

2020-10-28 17:14 UTC, chosta commented on src/cards/AerobrakedAmmoniaAsteroid.ts
> +            "Select card to add 2 microbes",
I'll do my best. Will also stop adding new cards after today. Will refactor the existing functionality + builder patterns and tests. We can have a merge and then another PR. I'm also trying to carefully select commits and changes so you have a better time reviewing.

2020-10-28 17:47 UTC, chosta commented
@kberg Ares cards getting some love :)
BEFORE
![bio-before](https://user-images.githubusercontent.com/836179/97475674-36ab2600-1956-11eb-85ba-433130ab6d8e.png)

AFTER
![bio-after](https://user-images.githubusercontent.com/836179/97475683-390d8000-1956-11eb-9541-414820b248d9.png)

2020-10-29 10:19 UTC, chosta commented
@kberg I managed to separate formatting in 9d7bdb4 , 1ae8ae7 and 36e2790. Sadly, the rebase actions I did may have resulted in a bigger mess. Code is up to date and everything runs but not sure what to do with these commits. Is this ok, or should I figure out a cleaner approach? Please, advise..

2020-10-29 22:41 UTC, kberg commented on src/cards/Algae.ts
> +        onPlay: [
what is the relationship between `onPlay` which reads to me like something that defines behavior, and `CardRow` and `CardProducitonBox`, which read to me like objects that describe visualization?

2020-10-29 23:25 UTC, kberg requested changes
This will be easier to work with if there weren't so many cards to begin with. I realize this is getting big and difficult, but this PR is definitely big and difficult.

2020-10-29 23:25 UTC, kberg commented on src/cards/AsteroidMiningConsortium.ts
> +            CardRequirement.production(Resources.TITANIUM, -1)
This should be 1, not -1.

2020-10-29 23:25 UTC, kberg commented on src/cards/BiomassCombustors.ts
> +        requirements: new CardRequirements([CardRequirement.oxygen(6)]),
How will plant production be documented?

2020-10-29 23:25 UTC, kberg commented on src/cards/CardBonus.ts
> +        this.resourceType = resourceType;
Is this line necessary if it's declared with a scope in the constructor?

2020-10-29 23:25 UTC, kberg commented on src/cards/CardBonusType.ts
> +export enum CardBonusType {
What is a card bonus type? There is no such thing in the rulebook. So I suggest some documentation for someone coming around.

2020-10-29 23:25 UTC, kberg commented on src/cards/CardRow.ts
> +export class CardRow {
I hear you. But tell me in plain words what a CardRow is, please.

2020-10-29 23:25 UTC, kberg commented on src/cards/CardSpecial.ts
> +export class CardSpecial {
What is a CardSpecial? This isn't clear.

2020-10-29 23:25 UTC, kberg commented on src/cards/CardSpecial.ts
> +import { ComponentSize } from "../components/card/ComponentSize";
I do not recommend importing `components` into non-components packages.

2020-10-29 23:25 UTC, kberg commented on src/cards/CauseAndEffect.ts
> +import { CardSpecial } from "./CardSpecial";
So, as I'm reading this, I think perhaps you ought to move all of these visualization-focused classes into, say, `src/cards/viz`. (Not for nothing, I think all the _actual_ cards in `src/cards/*` ought to move to `src/cards/base`.

2020-10-30 00:54 UTC, Lynesth commented on src/cards/AsteroidMiningConsortium.ts
> +            CardRequirement.production(Resources.TITANIUM, -1)
The -1 is to not print a number in front of the requirement.
I agree it doesn't look intuitive at all and that decision (printing number or not) should probably be a third boolean argument with a default value.

2020-10-30 01:00 UTC, Lynesth commented on src/cards/CardRequirements.ts
> +export class CardRequirements {
Just a suggestion but you could put that class in the same file as CardRequirement and PartyCardRequirement since it's really related.

2020-10-30 01:01 UTC, Lynesth commented on src/cards/Algae.ts
> +        return game.board.getOceansOnBoard() >= 5 - player.getRequirementsBonus(game);
I think what @chosta is working on is only taking care of cards visually, not of their behavior.

2020-10-30 01:01 UTC, Lynesth commented on src/cards/BiomassCombustors.ts
> +        requirements: new CardRequirements([CardRequirement.oxygen(6)]),
I think what @chosta is working on is only taking care of cards visually, not of their behavior.

2020-10-30 08:37 UTC, chosta commented
First of all, thanks for taking the time to review the changes. I agree that this PR is becoming too big and maybe we should have merged earlier. Let me try and address most of your concerns in this comment:

#### Enums
I've tried to reuse existing enum types such as Tags, Resources to describe every possible visual output on a card without having to create a new enum. I can easily have a CardBonusType and put all the enum values inside, this would improve some of the clutter but we would have enum types with repeating values.

#### Metadata - visual vs. behavior
My intention all along was to be able to describe the cards visually using metadata. I understand `metadata` as something that describes an item and not its behavior. Hence the `CardRow`, `CardProductionBox`, `CardSpecial`, etc. I didn't want to rewrite every ICard component so this:
```
game.board.getOceansOnBoard() >= 5 - player.getRequirementsBonus(game);
```
doesn't get implemented by the `CardRequirement` class as its job is to create a `requirements label` on top of the card.

The purpose of this approach is to have an API that describes what is drawn on the card that in a human readable way
```
public metadata: CardMetadata = {
        description:
            "Raise temperature 1 step and gain 2 titanium. Remove up to 3 Plants from any player.",
        cardNumber: "009",
        onPlay: [
            CardRow.add([CardBonus.temperature(1)]),
            CardRow.add([CardBonus.titanium(2)]),
            CardRow.add([CardBonus.plants(-3).any()]),
        ],
    };
```
Lets imagine we don't have this approach and try to describe a card like Lichen. We would have something like:
```
onPlay: { type: "plants", amount: 1, production: true } 
```
this can be drawn on the card without any issues but consider a card like CulturalMetropolis (and many other) where we have a production box that has two rows [-1 production, + 3 MC], a city tile and two delegates. We can describe the behavior but how do we know that we need to have the production box the city tile and the delegates on the same row? We can do that of course but not without any conditional logic.
![cultural](https://user-images.githubusercontent.com/836179/97676933-171d1600-1a9a-11eb-8256-0f8f95e52db5.png)

So the question here is, do we care if metadata `onPlay` (could be renamed) property only takes care of the visual representations of elements on the card canvas or we want to also describe behaviour with it?
+ If we choose to describe behaviour, I'll get rid of Boxes and Rows and start dealing with the logic inside of cards. This though would make the task much more complicated than I imagined it and would require more time and effort.
+ If we stick to using metadata for visual representation, I'll refactor the code by addressing the concerns in your comments (like CardSpecial, Enums, Builder patterns, etc.) Should we choose this approach, we can have 95% of the cards described programmatically with the current functionality. The rest would be exceptions and corporation cards, which require some additional work.

So it's time to decide. Please @bafolts @Lynesth @nwai90 @alrusdi @kberg @vincentneko @ssimeonoff check this comment and let me know what you think. Thanks for taking the time to help with this once again!

2020-10-30 09:13 UTC, Lynesth commented
I think it needs to start somewhere anyway. Even if metadata is only used to build cards visually for now, it could be extended later on to take care of some aspect of the behavior of the card.
It would of course be very nice to have everything thought of beforehand and layered for futur changes but I don't hink that's happening without too much work.

Regarding the PR itself:
- You could probably just make a "functional" one, that brings in the new classes and all (`CardRow`, `CardRequirement`, etc) and then make smaller PRs that adds metadata to cards (I get why kberg was baffled seeing mine before).
- Files that are related to metadata could probably be put inside a `metadata` folder to keep things neat.
- `onPlay` needs to be renamed to something else, it is pretty misleading. Since it's a property that holds the icons on the card, maybe something like `iconography`, `representation` or even `content` would make more sense.

Those are just my opinions on this of course :)

2020-10-30 09:42 UTC, chosta commented
> Even if metadata is only used to build cards visually for now, it could be extended later on to take care of some aspect of the behavior of the card.

Yes, this is how I imagine it too.

> * You could probably just make a "functional" one, that brings in the new classes and all (`CardRow`, `CardRequirement`, etc) and then make smaller PRs that adds metadata to cards (I get why kberg was baffled seeing mine before).

I'll break up this PR in chunks for sure, starting with CardRequirement. It needs some more work. I wanted to have the big picture and took the hands on approach by selecting both "easy" and "complex" cards and trying to draw them. It got me all the answers I need but now I have to take a step back and do proper planning.

2020-11-08 19:34 UTC, kberg commented
What's next?

2020-11-09 13:23 UTC, chosta commented
#1867

2020-11-09 13:23 UTC, closed without merging