Remove CorporationGroup and CorporationNames.
bafolts/terraforming-mars pull request #1617
Opened 2020-10-15 04:36 UTC by kberg

I don't like how this mixes in CorporationFilter yet, and it's lost the module name in the process, but that's recoverable. @chosta, please take a look.

2020-10-15 05:30 UTC, kberg commented
Mea culpa, I forgot a few things. Should be good now.

2020-10-15 05:42 UTC, chosta approved these changes
Looks good. As long as the debug-ui opens up and you see the expansion icons it should be fine. I like the approach, reduces boilerplate a lot.

2020-10-17 00:01 UTC, bafolts commented on src/components/CorporationsFilter.ts
> +    return MANIFEST_BY_MODULE.get(module)!.corporationCards.cards.map(cf => cf.cardName);
Using the `!` operator is dangerous. If `module` is not found in the map this will throw a runtime exception. If `MANIFEST_BY_MODULE.get(module) === undefined` this can return `[]`.

2020-10-17 00:06 UTC, bafolts commented on src/components/CorporationsFilter.ts
> +                ...this.corporateEra ? cardsByModuleMap.get(GameModule.CorpEra)! : [],
The `!` operator is dangerous. I would replace these with:

```
...this.corporateEra ? (cardsByModuleMap.get(GameModule.CorpEra) || []) : []
```

2020-10-17 00:08 UTC, bafolts commented on src/components/CorporationsFilter.ts
> +            return corps!.slice();
If `corps` is `undefined` this can return `[]`.

2020-10-17 00:15 UTC, bafolts commented on src/components/card/CardExpansion.ts
> +const MODULE_TO_CSS: Map<string, string> = new Map([
This generic type should be able to use `Map<GameModule, string>`

2020-10-17 00:26 UTC, bafolts requested changes
I would not use `!` operator. Especially on the server this can end up killing the node process as it introduces `undefined` where it wasn't expected. The enum consolidation is good.

2020-10-17 00:50 UTC, kberg commented on src/components/card/CardExpansion.ts
> +const MODULE_TO_CSS: Map<string, string> = new Map([
There were some issues when I tried that - can't remember what. Mind if I add a TODO?

2020-10-17 00:55 UTC, kberg commented on src/components/CorporationsFilter.ts
> +    return MANIFEST_BY_MODULE.get(module)!.corporationCards.cards.map(cf => cf.cardName);
Yeah, I saw you having issues with ! before, but here me out. MANIFEST_BY_MODULE is a map keyed by GameModule, so under what conditions could this actually occur? That's why I think it's safe here. My personal experience is that returning [] under what is a guaranteed impossible occurrence means that when it happens it hides the error.

If you disagree and you have a reasonable rebuttal, let me know. I'm also not going to fight for it, but it's important you know my reasons -- a few more of these! are going to come up with Ares (particularly inside AresHandler -- but more on that another time.)

2020-10-17 00:56 UTC, kberg commented on src/components/CorporationsFilter.ts
> +                ...this.corporateEra ? cardsByModuleMap.get(GameModule.CorpEra)! : [],
Same -- if this happens there's a real error. LMK your thoughts.

You also don't have to warn me about the ! ongoing you can at least save those characters in your feedback, and Ill be happy to discuss / address them appropriately.

2020-10-17 00:58 UTC, kberg commented on src/components/CorporationsFilter.ts
> +            return corps!.slice();
In this particular case -- is it possible `group as GameModule` could create an item that [i]isn't[/i] a GameModule? Given that CorporationsFilter is a purely internalized class, that just shouldn't happen. I know I'm repeating myself, but again if that happens, it's an error -- why not raise it as one?

2020-10-17 00:59 UTC, kberg commented on src/components/CorporationsFilter.ts
> +    return MANIFEST_BY_MODULE.get(module)!.corporationCards.cards.map(cf => cf.cardName);
I see that you marked it for all of them -- feel free to not have to deeply respond to each one as if I asked them independently -- feel free to respond to all of them right here, or something.

2020-10-17 01:08 UTC, kberg commented
OK. Is there a way to report this as a warning? So we can check logs for invalid behavior instead of silently accepting it?

2020-10-17 01:15 UTC, kberg commented
> I would not use `!` operator. Especially on the server this can end up killing the node process as it introduces `undefined` where it wasn't expected. The enum consolidation is good.

Ah wait a second -- this isn't the server. It's the client. Same concerns?

2020-10-17 01:20 UTC, bafolts commented on src/components/CorporationsFilter.ts
> +            return corps!.slice();
This is a front end component so it wouldn't take down the game server. It is most likely not possible as written today but in the future during some re-factor it broke in some way this could end up throwing that `slice` is not a function of `undefined`. I don't think the user would see this thrown error. If this were to return `[]` the user most likely also wouldn't see any error to know that something went wrong either. Since typescript tries to warn us that the item can be `undefined` I always find it strange when `!` is used as typescript is most likely going to be right at some point in the future and there will be a runtime exception here. If this instead returned an array I guess we wouldn't spot it either unless we logged a warning. As this is client side I am not as concerned as this at least wont crash the game server which would take down all other games running on the process. Could consider using `console.assert` as this is asserting that `corps` will be defined. At that point if it were ever an issue there would be an error message logged to the console.

2020-10-17 01:33 UTC, bafolts approved these changes
I am less concerned with the `!` usage on client as that will potentially error on that component and not kill the node process if it goes uncaught. I don't think we will show these errors to the user so if `!` were used or `[]` returned either way the user is most likely going to experience a bug.

2020-10-17 23:15 UTC, kberg commented
I fixed as many as I could -- hope I caught them all.

2020-10-17 23:19 UTC, kberg commented
Incidentally, had a little bit more of a chat with Brian off-list, I'll stop using ! everywhere.

2020-10-17 23:22 UTC, merged