Ares merge #7: Add Ares-related game data and serialization behavior.
bafolts/terraforming-mars pull request #1679
Opened 2020-10-19 05:42 UTC by kberg

This includes a change to how board spaces bonuses behave under Ares, though of course unused at the moment.

Depends on Ares merge 6 aka #1659

2020-10-20 14:45 UTC, chosta approved these changes
Looking good. Minor issues with design (i'm looking at cards at $beta url, might be outdated).

2020-10-20 14:45 UTC, chosta commented on src/ares/AresHandler.ts
> +// Game.ts-specific behavior for Ares
I don't want to be a prick but do we really want this comment :)

2020-10-20 14:45 UTC, chosta commented on src/ares/AresHandler.ts
> +        case TileType.DUST_STORM_MILD:
I'm the prick. Maybe use indentation here? The old argument "I've seen many projects and most of them use indentation on switch statements" :)

2020-10-20 14:45 UTC, chosta commented on src/cards/ares/BioengineeringEnclosure.ts
> +    // TODO(kberg): this code is a little brittle: if the player chooses not to select a
Can't we force the player to select a card? 
I mean predators don't have an option for not munching another animal..

2020-10-20 14:45 UTC, chosta commented on src/cards/ares/BioengineeringEnclosure.ts
> +}
Unrelated. Card design looks a bit off. Centerd content would be a nice improvement.

2020-10-20 14:45 UTC, chosta commented on src/cards/ares/BiofertilizerFacility.ts
> +        return new SelectSpace(
No remarks. Just acknowledging how beautiful this part of the code is.

2020-10-20 14:45 UTC, chosta commented on src/cards/ares/MetallicAsteroid.ts
> +}
Unrelated. Card has double event tag (i had a bug in Card.ts and fixed it, maybe you've already seen it but just in case..) and tile placement looks a bit off.

2020-10-20 14:45 UTC, chosta commented on src/cards/ares/SolarFarm.ts
> +            const plantsOnSpace = space.bonus.filter((b) => b === SpaceBonus.PLANT).length;
I'm not sure how you get "1 step for each plant tag on the area where you place the tile.". Meaning I don't understand the card :)

2020-10-20 14:45 UTC, chosta commented on tests/cards/ares/BioengineeringEnclosure.spec.ts
> +    name: CardName.ACQUIRED_SPACE_AGENCY,
We are hosting animals on ACQUIRED_SPACE_AGENCY :)

2020-10-20 14:45 UTC, chosta commented on tests/cards/ares/SolarFarm.spec.ts
> +        space.bonus = [
I should learn how this space.bonus works I guess..

2020-10-20 14:54 UTC, kberg commented on src/ares/AresHandler.ts
> +        case TileType.DUST_STORM_MILD:
Huh! For some reason I thought we weren't. Yes. And you're fine.

2020-10-20 14:56 UTC, kberg commented on src/ares/AresHandler.ts
> +// Game.ts-specific behavior for Ares
Removed.

2020-10-20 14:57 UTC, kberg commented on src/cards/ares/BioengineeringEnclosure.ts
> +    // TODO(kberg): this code is a little brittle: if the player chooses not to select a
/shrug That was something I came up with when I got started. It could be a non-issue, particularly after @Lynesth's most recent change.

2020-10-20 14:57 UTC, kberg commented on src/cards/ares/BioengineeringEnclosure.ts
> +}
Oh it most certainly would be. All the imagery needs a refresh. Most.

2020-10-20 14:57 UTC, kberg commented on src/cards/ares/BiofertilizerFacility.ts
> +        return new SelectSpace(
Thanks!

2020-10-20 21:35 UTC, kberg commented on src/cards/ares/MetallicAsteroid.ts
> +}
Most certainly the placement is off -- the visual elements are going to need a good scrubbing.

2020-10-20 21:36 UTC, kberg commented on src/cards/ares/SolarFarm.ts
> +            const plantsOnSpace = space.bonus.filter((b) => b === SpaceBonus.PLANT).length;
Count the number of plants on the space. Then gain that much energy production. (Or energy units, I don't remember.)

Resolving because I think that's sufficient.

2020-10-20 21:36 UTC, kberg commented on src/cards/ares/SolarFarm.ts
> +            const plantsOnSpace = space.bonus.filter((b) => b === SpaceBonus.PLANT).length;
(lmk if I'm wrong.)

2020-10-20 21:37 UTC, kberg commented on tests/cards/ares/BioengineeringEnclosure.spec.ts
> +    name: CardName.ACQUIRED_SPACE_AGENCY,
I kind of like tests that don't rely on expected innards of other cards, so I intentionally pick arbitrarily.

Besides, I'm sure the agency could use a cat.

2020-10-20 23:34 UTC, bafolts commented on src/Game.ts
> +          aresHazards: true,
What does it represent when `aresExtension` is `false` but `aresHazards` is `true`?

2020-10-20 23:37 UTC, kberg commented on src/Game.ts
> +          aresHazards: true,
I knew this was going to come up and I don't know why I didn't do anything about it.

`aresHazards` is meaningless without `aresExtension`, and `aresHazards` is not toggled on the main page, but only used to make certain tests easier to write by setting it `false`. Any thoughts

2020-10-21 00:02 UTC, bafolts commented on src/Game.ts
> +          aresHazards: true,
Which tests did this make easier to write? As far as I can tell nothing in `/src/**/*.ts` is using the `aresHazard` property, we only set it and never read it. The `SolarFarm` unit tests seem to pass whether I use `ARES_OPTIONS_WITH_HAZARDS` or `ARES_OPTIONS_NO_HAZARDS`.

2020-10-21 00:11 UTC, bafolts commented on tests/ares/AresStorageTest.spec.ts
> +        const json = JSON.stringify(game, game.replacer);
We should put this `JSON.stringify(game, game.replacer)` to a `toJSON()` function so we don't have to copy this logic and have `replacer` be public.

2020-10-21 00:14 UTC, bafolts requested changes
I believe this is the first time we have serialized a `Game` outside of the class. I think we should make a `toJSON` as the opposite of `loadFromJSON` to hide the implementation details of `replacer`.

2020-10-21 00:30 UTC, kberg commented on src/Game.ts
> +          aresHazards: true,
It's used in a lot of places: https://github.com/bafolts/terraforming-mars/search?q=ARES_OPTIONS_NO_HAZARDS&type=Code

This isn't all the hazards code, and the code currently under test was older code that didn't have to worry about hazards. Solar Farm is a good example of this.

2020-10-21 00:31 UTC, kberg commented on tests/ares/AresStorageTest.spec.ts
> +        const json = JSON.stringify(game, game.replacer);
ack. I'm happy to do that -- you mind if it's a follow-up PR later?

2020-10-21 05:59 UTC, Lynesth commented on src/Game.ts
> +        space.bonus = [];
Won't this create an issue with Dry Deserts removing an Ocean tile ?
I should be able to get that bonus again when putting an Ocean at the same spot.

2020-10-21 05:59 UTC, Lynesth commented on src/Game.ts
> +            space.bonus = [];
Same issue as above.

2020-10-21 06:02 UTC, Lynesth commented on tests/ares/AresStorageTest.spec.ts
> +    it("When reloading the board, covered spaces don't have bonuses", function() {
Same questioning as above regarding space bonuses.

2020-10-21 06:04 UTC, kberg commented on src/Game.ts
> +        space.bonus = [];
Coming soon: https://github.com/kberg/terraforming-mars/blob/ares/tests/ares/OtherAresTests.spec.ts

Or eventually.

2020-10-21 06:04 UTC, kberg commented on src/Game.ts
> +            space.bonus = [];
OK to resolve?

2020-10-21 06:04 UTC, kberg commented on tests/ares/AresStorageTest.spec.ts
> +    it("When reloading the board, covered spaces don't have bonuses", function() {
OK to resolve?

2020-10-21 06:05 UTC, kberg commented on tests/ares/AresStorageTest.spec.ts
> +    it("When reloading the board, covered spaces don't have bonuses", function() {
Did I say I was going to sleep? I lied. :D

OK I'm going to sleep. Thanks for the review?

2020-10-21 06:06 UTC, kberg commented on src/Game.ts
> +        space.bonus = [];
Oh no, that's not Dry Deserts. Good catch. Grr, hrm...

2020-10-21 06:08 UTC, kberg commented on src/Game.ts
> +        space.bonus = [];
I only considered Dry Deserts as it applies to _upgraded oceans._

I'll have to fix this,  yes. Since aresExpansion can't be enabled on a running server, I hope this can still be approved and merged, with a commitment for an upcoming PR to fix it (in the next day or tw.)

I'm particularly focused on trying to get momentum on the changes.

2020-10-21 06:16 UTC, Lynesth commented on src/Game.ts
> +        space.bonus = [];
Yeah I wouldn't mind. And even if that's not fixed before Ares makes it in, it really is an edge case non game breaking bug.

2020-10-21 06:17 UTC, Lynesth commented on src/Game.ts
> +            space.bonus = [];
Yep

2020-10-21 06:17 UTC, Lynesth commented on tests/ares/AresStorageTest.spec.ts
> +    it("When reloading the board, covered spaces don't have bonuses", function() {
You're welcome, resolve it :)

2020-10-21 14:34 UTC, bafolts commented on src/Game.ts
> +          aresHazards: true,
As far as I can tell the `aresHazards` option is not used.

https://github.com/bafolts/terraforming-mars/search?q=aresHazards&type=Code

The `ARES_OPTIONS_NO_HAZARDS` is being set but I can't see how we ever leverage `aresHazards` to take different code paths.

2020-10-21 14:35 UTC, bafolts commented on tests/ares/AresStorageTest.spec.ts
> +        const json = JSON.stringify(game, game.replacer);
OK

2020-10-21 14:35 UTC, bafolts approved these changes

2020-10-21 14:36 UTC, merged

2020-10-21 14:50 UTC, kberg commented on tests/ares/AresStorageTest.spec.ts
> +        const json = JSON.stringify(game, game.replacer);
Added a tracking issue.

2020-10-21 14:52 UTC, kberg commented on src/Game.ts
> +          aresHazards: true,
Good catch -- it is introduced here because I wanted to keep it with `aresExtension`  but is used in am10. I hadn't considered the disconnect, either. https://github.com/bafolts/terraforming-mars/pull/1691