Replace interrupts with deferred actions
bafolts/terraforming-mars pull request #1682
Opened 2020-10-19 15:42 UTC by Lynesth

Removed PlayerInterrupt completely.
Created a new DeferredAction interface that does pretty much the same thing, albeit a bit differently.
Renamed previous interrupts to better describe what the action they are doing is.
Refactored some parts of cards into new deferred actions.

Tested with @nwai90 to make sure things work.
Next commit will be to update the tests.

Note:
- SelectResourceDecrease interrupt was only used for plants and was renamed accordingly.
- More cards and actions could be using existing deferred actions instead of rolling their own, will update them in futur PRs.
- This PR takes care of a lot of double quotes and indentation issues, don't be afraid of the changes :)

2020-10-20 06:27 UTC, kberg commented
Looks like there are still quite a few build errors.

2020-10-20 06:29 UTC, Lynesth commented
@kberg The commit that fixes tests is coming soon (less than an hour). I just wanted to already let you have a look at it meanwhile.

2020-10-20 06:29 UTC, kberg commented on src/cards/Fish.ts
> +import { IActionCard, IResourceCard } from "./ICard";
How much work would it be to undo most of this reforrmatting in the midst of such a significant functional change?

2020-10-20 06:42 UTC, kberg reviewed
72 out of 139 marked as viewed -- granted they were the low effort ones.

So far very good! I love the new API. Expressive, clear, simple. But now it's time to stop for the night.

2020-10-20 15:13 UTC, Lynesth commented
@bafolts @kberg There's still 1 test failing but I don't know how to fix it, I hope one of you can help.
Here's what I managed to understand about it:
- The function failing is `getProjectCardByName` in `Dealer.ts`. [Link to the function](https://github.com/bafolts/terraforming-mars/blob/276873a4f45245f38766ea4242b55906899fa053/src/Dealer.ts#L34-L47)
- It fails because `COMMUNITY_CARD_MANIFEST` is undefined in `decks` array.
- `COMMUNITY_CARD_MANIFEST` is undefined at runtime, but not after that (if I move the `decks` declaration inside the `getProjectCardByName` function, everything works fine).
- It could be that `COMMUNITY_CARD_MANIFEST` is undefined at runtime because of some circular dependency.

No idea what change messed that up :/

2020-10-20 16:17 UTC, Lynesth commented
After checking this out with the help of @nwai90 I removed the Dealer dependency from Playwrights. This fixes the last issue.

2020-10-21 15:03 UTC, Lynesth commented
@kberg I made a custom SimpleDeferredAction for Bioengineering Enclosure when I resolved merge conflicts.
I'll give it some more thoughts when I'll recheck all cards after this PR is merged.
So I hope you don't mind.

2020-10-22 03:45 UTC, kberg requested changes
I've reviewed everything except colonies (and Pharmacy Union, I think?) and also all the tests.

Next time a change this large comes along, please do not reformat.

2020-10-22 03:45 UTC, kberg commented on src/cards/ares/BioengineeringEnclosure.ts
> +        game.defer(new SimpleDeferredAction(
Why so much un-shared code?

2020-10-22 03:45 UTC, kberg commented on src/deferredActions/AddResourcesToCard.ts
> -    public generatePlayerInput() {
Can you please restore this behavior? The amount of copy/paste makes this not useful. Or make this subclassable if you don't want my feature to impact yours.

2020-10-22 03:45 UTC, kberg commented on src/deferredActions/CorrosiveRainDeferredAction.ts
> +        public title: string = "Remove 2 floaters from a card or lose up to 10 MC"
Why is title parameterized when nothing else is parameterized?

2020-10-22 03:45 UTC, kberg commented on src/deferredActions/PlaceCityTile.ts
> +    public execute() {
If it were me I'd add a return type for execute, but perhaps Typescript is inferring that SelectSpace is a valid type.

2020-10-22 03:45 UTC, kberg commented on src/deferredActions/RemoveAnyPlants.ts
> +        if (candidates.length === 1) {
How is this functionally different from the code below where candidates.length > 1?

2020-10-22 03:45 UTC, kberg commented on src/deferredActions/StealResources.ts
> +export class StealResources implements DeferredAction {
What can I read to compare this to?

2020-10-22 03:51 UTC, Lynesth commented on src/Game.ts
> +        return this.deferredActions[0];
No it returns `undefined`.

2020-10-22 04:06 UTC, Lynesth commented on src/Game.ts
> +    private resolveTurmoilDeferredActions() {
I think it was named as such because of the order things happen.
- **A**. Draft, Research, etc, won't detail.
- **B**. Repeat for each player that haven't passed
  - **1**. Player takes 1st action (if pass, goto **4**)
  - **2**. Resolve deferred actions
  - **3**. Player takes 2nd action
  - **4**. Resolve latest action's deferred actions
  - **5**. If all players have passed, goto **C**
- **C**. Production phase
- **D**. Check if game is over
- **E**. WGT stuff (nothing deferred here)
- **F**. Move colonies track
- **G**. Does Turmoil end-of-generation stuff
- **H**. `game.resolveTurmoilDeferredActions()` (if some card asked players to remove an ocean, or discard cards, etc)
- **I**. goto **A**.

2020-10-22 04:10 UTC, Lynesth commented on src/deferredActions/PlaceCityTile.ts
> +    public execute() {
DeferredAction interface states that execute can return `PlayerInput | undefined` and SelectSpace is a PlayerInput and I think Typescript simply know.

2020-10-22 04:13 UTC, Lynesth commented on src/colonies/Pluto.ts
> +        game.defer(new DrawCards(player, game, 1));
Previously the "discard cards" interrupt had an extra parameter that made it draw a card before prompting to discard.
It was only used for Pluto.
Since I see some places where we will want to defer card draws in the futur, I simply made that a deferred action and removed the extra parameter from DiscardCards.

2020-10-22 04:14 UTC, Lynesth commented on src/deferredActions/AddResourcesToCard.ts
> -    public generatePlayerInput() {
I sure don't mind looking into it.
Which part of your code does that bring issues to ?

2020-10-22 04:17 UTC, Lynesth commented on src/deferredActions/CorrosiveRainDeferredAction.ts
> +        public title: string = "Remove 2 floaters from a card or lose up to 10 MC"
That's how it was before.
It was an interrupt only used to defer the action of the Corrosive Rain global event, so its title is pretty much set in stone.

It's to make it clear that it is its only used case that I renamed it to CorrosiveRainDeferredAction.

2020-10-22 04:19 UTC, Lynesth commented on src/deferredActions/RemoveAnyPlants.ts
> +        if (candidates.length === 1) {
You are correct, it isn't. Thanks.

2020-10-22 04:21 UTC, Lynesth commented on src/deferredActions/StealResources.ts
> +export class StealResources implements DeferredAction {
It is a new deferred action but you can compare it to **Hired Raiders** and the `RemoveAnyPlants` deferred action I suppose.

2020-10-22 07:23 UTC, Lynesth commented on src/Player.ts
> +            game.defer(new SimpleDeferredAction(
We could already just drop it and do

```ts
game.defer({
    player: this,
    execute: () => whatever
});
```

I know I just like properly defined things so when a function expects a class that implements a certain interface I prefer passing it a named object than an anonymous one.

If you mean "bulky" as in "visually/typing", would it be acceptable if it went from `SimpleDeferredAction` to `DeferredAction` ?

I'm not one to be anal about it though, so if you guys prefer to remove it, or if that's one of the defined practice of this project, then so be it ! :)

2020-10-22 07:26 UTC, Lynesth commented on src/cards/ares/BioengineeringEnclosure.ts
> +        game.defer(new SimpleDeferredAction(
As stated [here](https://github.com/bafolts/terraforming-mars/pull/1682#issuecomment-713642937), that wasn't part of my initial PR but was one of the conflicts I had to resolve.
So for now, it works and fixes the little issue you had I think (see your TODO comment I removed in the code). Will think about how to improve it when I do a pass on all cards.
So if it's okay for now, I'd prefer to leave it like this.

2020-10-22 07:27 UTC, Lynesth commented on src/cards/colonies/TitanFloatingLaunchPad.ts
>  import { SelectOption } from "../../inputs/SelectOption";
Sure, no worries. I'm sure someone else can take a look at the colonies ! :)

2020-10-22 08:26 UTC, Lynesth commented on src/colonies/Colony.ts
> +        if (steps === undefined) {
The main reason was to be able to decide if you want to increase it 1 or 2 steps in case you are in ability to do so (it matters for only one colony at the moment I think).

Also it allows being able to bail out early if there's no need to increase it (already at max) and prevent having this being logged: "🕑You increased Callisto colony track 0 step(s)".

2020-10-22 08:39 UTC, Lynesth commented
> Next time a change this large comes along, please do not reformat.

Yeah, when I started reformatting here and there I didn't expect to end up with that much, sorry about that.
As I said I can submit small quotes/indentation PRs which can be merged easily and it would then make this PR more readable of that's needed.

If the current state is really blocking some people from reviewing it, I can even scratch this one and submit another with only functional changes. You guys let me know.

2020-10-22 15:00 UTC, Lynesth commented on src/deferredActions/RemoveAnyPlants.ts
> +        if (candidates.length === 1) {
Commited locally, will wait before pushing.

2020-10-23 05:18 UTC, kberg reviewed
I'm done with all the files I plan to review (minor modulos.)

2020-10-23 05:18 UTC, kberg commented on src/cards/promo/PharmacyUnion.ts
> +            const scienceTags = card.tags.filter((tag) => tag === Tags.SCIENCE).length;
This is really pedantic: can you please move this to a function like it was before and stick it in the code order like it was before? This is a big PR and having to analyze this line-by-line is a bit much.

2020-10-23 05:18 UTC, kberg commented on tests/cards/AsteroidMiningConsortium.spec.ts
> +        expect(input).to.eq(undefined);
expect(input).is.undefined

2020-10-23 05:18 UTC, kberg commented on tests/cards/AsteroidMiningConsortium.spec.ts
> +        expect(input).to.eq(undefined);
Well, in the future.

2020-10-23 05:18 UTC, kberg commented on tests/cards/BigAsteroid.spec.ts
> +        orOptions.options[0].cb(); // remove plants
THANK YOU

2020-10-23 05:18 UTC, kberg commented on tests/cards/colonies/TitanFloatingLaunchPad.spec.ts
> +    it("Should play with single targets", function() {
Did not review.

2020-10-23 05:45 UTC, Lynesth commented on tests/cards/AsteroidMiningConsortium.spec.ts
> +        expect(input).to.eq(undefined);
Yeah ok. Most tests do it that way so I just went with the flow :)

2020-10-23 05:45 UTC, Lynesth commented on tests/cards/BigAsteroid.spec.ts
> +        orOptions.options[0].cb(); // remove plants
Haha

2020-10-23 06:04 UTC, kberg commented on src/Player.ts
> +            game.defer(new SimpleDeferredAction(
Another day.

2020-10-23 06:05 UTC, kberg commented on src/deferredActions/AddResourcesToCard.ts
> -    public generatePlayerInput() {
It's coming soon.

2020-10-23 06:07 UTC, kberg commented on src/deferredActions/StealResources.ts
> +        const stealOptions = candidates.map((candidate) => {
candidates could be length 0. return undefined?

2020-10-23 06:08 UTC, kberg approved these changes
I think this is good. I missed a few no question. If I knew colonies better I'd dig into those.

2020-10-23 06:08 UTC, kberg commented
Great work.

2020-10-23 06:20 UTC, Lynesth commented on src/deferredActions/StealResources.ts
> +        const stealOptions = candidates.map((candidate) => {
You are correct. Thank you.

2020-10-23 10:14 UTC, nwai90 commented
> I think this is good. I missed a few no question. If I knew colonies better I'd dig into those.

@kberg These have been reviewed and tested in-game on @Lynesth's server:

- Pharmacy Union
- Titan Floating Launchpad
- Aerospace Mission
- Trade Advance
- Hygiea
- Leavitt
- Mercury

2020-10-23 10:33 UTC, Lynesth commented on src/cards/community/AerospaceMission.ts
> -        const openColonies = game.colonies.filter((colony) => colony.isActive);
Will close those as @nwai90 reviewed them.

2020-10-23 22:56 UTC, kberg commented
Ah, nope, now merge conflicts.

2020-10-23 22:57 UTC, kberg commented
Oh wait, no I was wrong.

2020-10-23 22:57 UTC, merged

2020-10-23 22:57 UTC, kberg commented
Good work!