Seedable rng 1733
bafolts/terraforming-mars pull request #1785
Opened 2020-10-27 21:27 UTC by SliceOfBread

The shuffling of corporate, prelude and project decks use the game.id as the seed for the random number generator (rng).
Also the when using the random board selection (1 of the 3 main boards), this is done using the game.id.

2020-10-28 05:42 UTC, kberg requested changes
Looks like there are some broken tests below?

2020-10-28 05:42 UTC, kberg commented on server.ts
> +                gameReq.board = boards[Math.floor(parseInt(gameId, 16) / Math.pow(16, 12) * boards.length)];
Why does this use the game id rather than the a seeded rng?

2020-10-28 05:42 UTC, kberg commented on src/Dealer.ts
> +            this.preludeDeck = this.shuffleCards(preludeDeck, new Random(shuffleSeed));
Looking  at a copy of your repo, there are now three different places that create a new instance of Random. Dealer is created by Game -- how about supplying an instance of Random here?

2020-10-28 14:06 UTC, SliceOfBread commented on server.ts
> +                gameReq.board = boards[Math.floor(parseInt(gameId, 16) / Math.pow(16, 12) * boards.length)];
gameId is already generated randomly.

2020-10-28 14:12 UTC, SliceOfBread commented on src/Dealer.ts
> +            this.preludeDeck = this.shuffleCards(preludeDeck, new Random(shuffleSeed));
Not sure I understand the question.
I used separate instances of Random so it would not matter what order the decks got shuffled in the future. The instance for the project cards is kept around for the case where the discards need to be reshuffled.

2020-10-28 14:28 UTC, kberg commented on src/Dealer.ts
> +            this.preludeDeck = this.shuffleCards(preludeDeck, new Random(shuffleSeed));
What's the end goal of this change? It's possible that whatever is built would work in the short term, but puts a reliability burden on ongoing maintenance and change. For example, someone reading this project later on could read this code and say "Oh! Why are there three RNGs? It doesn't make sense." And then consolidate them into one. And then someone else comes along and reorders shuffling (just like I did with tile behavior, and even with the way decks are structured.)

Is this something that this project should continue to support ongoing? If so, then there should be enough comments to describe the feature it is supporting and tests to validate the use cases and support it when we organizationally refactor.

2020-10-29 14:46 UTC, SliceOfBread commented
cancelling this and the associated issue #1733

2020-10-29 14:46 UTC, closed without merging