Cards metadata - requirements [part of #1605]
bafolts/terraforming-mars pull request #1806
Opened 2020-10-30 16:36 UTC by chosta

A chunk (hopefully good one) from the infamous #1605 that should be mergeworthy
+ CardRequirements remastered with builder pattern
+ VP, Description and Content Vue components
+ Some cards using the new new metadata requirements
+ sadly a bit of formatting leftover
+ new unit tests

Thanks Mr K9 for upping my TS game!

2020-10-30 16:39 UTC, chosta commented
Consider reviewing only after 
52ae7ca

2020-10-31 02:49 UTC, kberg requested changes
One typo.

2020-10-31 02:49 UTC, kberg commented on src/cards/IProjectCard.ts
> +    bonusMc?: number | undefined;
This looks like a no-op change. But OK.

2020-10-31 02:49 UTC, kberg commented on src/cards/venusNext/LuxuryFoods.ts
> +        description: "Requires that you have a Varth tag, an Earth tag and a Jovian tag.",
Varth Tag?

2020-10-31 02:51 UTC, kberg approved these changes
Fixed the typo.

2020-10-31 02:56 UTC, merged

2020-10-31 02:57 UTC, kberg commented
Much, much easier. Thank you.l