Refactor global parameter increase methods
bafolts/terraforming-mars pull request #1919
Opened 2020-11-19 05:03 UTC by Lynesth

Each method is refatored in its own commit.

2020-11-19 05:14 UTC, nwai90 approved these changes

2020-11-19 07:22 UTC, kberg requested changes

2020-11-19 07:22 UTC, kberg commented on src/Game.ts
> +    public increaseOxygenLevel(player: Player, _steps: 1 | 2): undefined {
Changing `steps` to `_steps` is probably a bad idea: as far as I can tell it's a standard that function parameters that start with `_` imply they are unused, which is not the case here.

2020-11-19 23:16 UTC, Lynesth commented on src/Game.ts
> +    public increaseOxygenLevel(player: Player, _steps: 1 | 2): undefined {
I changed it.

2020-11-20 05:00 UTC, kberg approved these changes

2020-11-20 05:01 UTC, merged