Move BiofertilizerFacility to CardRender. Create CardRenderTileComponent, which I'm sure isn't right yet.
bafolts/terraforming-mars pull request #1932
Opened 2020-11-21 18:41 UTC by kberg

No question this isn't lining up right, yet. I'm sure the use of the special-tile background isn't going to work, and the sizing is also off. Of course at some point these tiles deserve a refresh.

2020-11-22 10:23 UTC, chosta requested changes
It's a good step forward. I might expand on this PR after merging to handle all tiles. Will probably have an enum instead of direct selector.
Check my _existingItem comment though

2020-11-22 10:23 UTC, chosta commented on src/cards/render/CardRenderer.ts
> +      row.push(symbol);
well spotted

2020-11-22 10:23 UTC, chosta commented on src/cards/render/CardRenderer.ts
> +    this._checkExistingItem();
I think we can drop `this._checkExistingItem()` here. The purpose of this function is to verify existence of a item that the current function needs to modify in some way. E.g. `plants(-1).any`. In the case of `tile()` we will have an issue with a card like mining area, where the first element of the array should be a tile.

2020-11-22 10:23 UTC, chosta commented on src/components/card/CardRenderTileComponent.ts
> +    <div :class="getClasses()></div>
I prefer the shorthand `<div :class="getClasses()" />`
Also this one is probably broken as there is a missing second "

2020-11-22 10:23 UTC, chosta commented on src/cards/ares/BiofertilizerFacility.ts
> +        b.tile('board-space-tile--biofertilizer_facility');
This could be improved to not use a direct selector but I can do it myself as I wanted to implement the `tile()` in my next PR.

2020-11-23 15:48 UTC, kberg commented on src/components/card/CardRenderTileComponent.ts
> +    <div :class="getClasses()></div>
![image](https://user-images.githubusercontent.com/413481/99982983-4bbe7d80-2d79-11eb-809c-1f07e72911f3.png)

I knew that comment looked familiar! :D

2020-11-23 15:49 UTC, kberg commented on src/cards/ares/BiofertilizerFacility.ts
> +        b.tile('board-space-tile--biofertilizer_facility');
I was thinking about this. While separating client from server is always good, does that add anything meaningful to this project?

2020-11-23 15:55 UTC, chosta commented on src/components/card/CardRenderTileComponent.ts
> +    <div :class="getClasses()></div>
well, it turns out I was wrong all along...as @bafolts pointed out his code review HTML5 is not on friendly terms with this shorthand.
https://stackoverflow.com/questions/3558119/are-non-void-self-closing-tags-valid-in-html5

So yeah, `<div></div>` should be preferred and I need to fight the habit of doing the <div/>

2020-11-23 15:55 UTC, chosta commented on src/cards/ares/BiofertilizerFacility.ts
> +        b.tile('board-space-tile--biofertilizer_facility');
Yes. If we change the class-name in the .less file, this would fail. Also, tests.

2020-11-23 16:15 UTC, chosta commented on src/cards/ares/BiofertilizerFacility.ts
> +        b.tile('board-space-tile--biofertilizer_facility');
You got me thinking about this.To be fair, we ALSO need to set the className inside the Vue component if we didn't in the backend. So changing the `.less` class name would have to be followed by changing it in the Vue component too. It just a frontend pattern (in React, Vue, Angular) to deal with classNames in the component logic. The value is that devs would most likely expect it there.

2020-11-23 16:46 UTC, kberg commented on src/cards/render/CardRenderer.ts
> +      row.push(symbol);
:+1:

2020-11-23 16:46 UTC, kberg commented on src/cards/render/CardRenderer.ts
> +    this._checkExistingItem();
Done.

2020-11-23 16:47 UTC, kberg commented on src/components/card/CardRenderTileComponent.ts
> +    <div :class="getClasses()></div>
ack.

2020-11-23 16:48 UTC, kberg commented on src/cards/ares/BiofertilizerFacility.ts
> +        b.tile('board-space-tile--biofertilizer_facility');
Whatever you prefer!

2020-11-23 17:01 UTC, kberg commented
We're gonna need some tests for these things, too. :/

2020-11-23 17:59 UTC, chosta approved these changes

2020-11-23 18:00 UTC, merged