Refactor Player's runInput method
bafolts/terraforming-mars pull request #1964
Opened 2020-11-27 05:20 UTC by Lynesth

Removed unnecessary variables.
Removed duplicated code by adding a `checkInputLength` method.
Removed unnecessary checks from `SelectHowToPayForCard` since those are performed in the callback.
Text for errors that should not happen (like incorrect input length) was kept "simple".
Didn't touch Ares inputs @kberg, but you can probably just add `this.checkInputLength(input, 1, 1);` for both of them.

2020-11-27 16:55 UTC, bafolts commented on src/Player.ts
> -      const foundCards = cards.filter((card) => card.name === cardName);
This is a good change. As the terraforming-mars.herokuapp.com server is getting more traffic every little bit will help.

2020-11-27 17:29 UTC, bafolts commented on src/Player.ts
> +      if (firstOptionLength !== undefined && input[0].length !== firstOptionLength) {
This needs to check that `input.length > 0`. If `input.length` were `0` this would throw a runtime error that `length` is not a property of `undefined`.

2020-11-27 17:39 UTC, bafolts commented on src/Player.ts
> +        const selectedOptionInput = input.slice(1);
This _should_ be fine to only call `slice` on the top level array. The name `selectedOptionInput` is clearer than `remainingInput`. Prior to this change we would have had a copy of the input arrays as well. I don't think we ever mutate the input so this shouldn't matter. While here lets change the type of `input` to `ReadyonlyArray<ReadyonlyArray<string>>`. This will ensure that nothing is modifying these arrays.

2020-11-27 17:59 UTC, bafolts requested changes

2020-11-27 17:59 UTC, bafolts commented on src/Player.ts
> -        if (!this.canUseHeatAsMegaCredits) payMethod.heat = 0;
Lets make a private function for `parseHowToPay(string: json): HowToPay` that can be used in both places this is used. This should further remove code duplication as the `const payMethod: HowToPay = {` wont be declared in both places.

There shouldn't be any need to use `Object.assign`. Should be able to use:

```typescript
private parseHowToPay(string: json): HowToPay {
  try {
    const howToPay: HowToPay = JSON.parse(string);
    // do run-time type checking to verify
    return howToPay;
  } catch (err) {
    // unable to parse input, log warning to be helpful with debugging
  }
}
```

Typescript will take our word for it so that runtime type checking you have verifying the properties makes sense. This is removing the checks that heat can be used as well as steel and titanium but I do think we should be verifying these each place they are used so this seems fine to me to remove. Putting in one function will be helpful.

2020-11-28 00:55 UTC, Lynesth commented on src/Player.ts
> +      if (firstOptionLength !== undefined && input[0].length !== firstOptionLength) {
It is expected that the `length` argument to that function is greater than or equal to 1, so with the check 3 lines above I it should be fine, wouldn't it ?

2020-11-28 01:28 UTC, Lynesth commented on src/Player.ts
> -        if (!this.canUseHeatAsMegaCredits) payMethod.heat = 0;
Done it.
Had to keep the exhaustive "default" HowToPay variable to check against since interfaces are not available at runtime and simply using an array of keys would prevent any futur changes to the HowToPay interface to be caught here.

2020-11-28 01:50 UTC, Lynesth commented on src/Player.ts
> -        if (!this.canUseHeatAsMegaCredits) payMethod.heat = 0;
Also if we want to be thorough, we could change the properties check to:
```ts
        if (Object.keys(howToPay).every((key) =>
          key in defaults &&
          typeof (howToPay as any)[key] === typeof (defaults as any)[key],
        ) === false) {
```
Let me know how you feel about it.

2020-11-28 16:07 UTC, bafolts approved these changes

2020-11-28 16:07 UTC, bafolts commented on src/Player.ts
> -        if (!this.canUseHeatAsMegaCredits) payMethod.heat = 0;
As long was we are checking that a player isn't cheating that should be of more value than this runtime type checking. When we send this data from client we are using `HowToPay` so assuming the user isn't malicious we are only verifying here the `JSON.stringify` worked on the client. The check in place right now should be a better than nothing sanity check that the client and server haven't gotten out of sync.

2020-11-28 16:11 UTC, merged