Top bar
bafolts/terraforming-mars pull request #1989
Opened 2020-12-01 07:03 UTC by alrusdi

Optional sticky top bar. I don't like visuals, but it is probably ok as a start...
![sticky](https://user-images.githubusercontent.com/394311/100707820-1941ff80-33cd-11eb-9e79-c6c4ff909abc.png)

Demo: http://37.230.117.156:9000/

2020-12-01 07:10 UTC, kberg commented
I'll look tomorrow evening. It's a great start.

2020-12-01 07:11 UTC, kberg reviewed
Basically LG, but someone else should opine about CSS and such.

2020-12-01 07:11 UTC, kberg commented on src/components/Preferences.ts
> +                    <div class="preferences_panel_item">
Instead, I'd make it dismissable and redisplayable right on the bar. You've seen this type of thing, of course. And that toggle can be stored as the preference.

2020-12-01 07:11 UTC, kberg commented on src/components/Preferences.ts
> +                    <div class="preferences_panel_item">
... or both, now that I think about it.

2020-12-01 09:10 UTC, chosta reviewed
Thanks for making that optional!
I have no issues with vue and logic. Lets see how the visuals will turn out to be and let me know if you need help.

2020-12-01 09:14 UTC, alrusdi commented
> Thanks for making that optional!
> I have no issues with vue and logic. Lets see how the visuals will turn out to be and let me know if you need help.

If we will make decision to make top bar removable in place (as @kberg suggested above) then i need some visual solution for it. Just "close button" on the right side of the bar looks odd

2020-12-01 09:21 UTC, chosta commented
How about an indicator that slides the bar left / right? Example - Evernote web interface:

![sidebar-1](https://user-images.githubusercontent.com/836179/100720860-44295500-33c7-11eb-8b34-af225de8ef3a.png)

2020-12-01 18:20 UTC, alrusdi commented on src/components/Preferences.ts
> +                    <div class="preferences_panel_item">
> ... or both, now that I think about it.

I've implemented both

2020-12-02 01:54 UTC, bafolts requested changes
I would avoid using `$forceUpdate` and use data properties to let vue handle updating the component naturally without forcing it.

2020-12-02 01:54 UTC, bafolts commented on src/components/TopBar.ts
> +      this.$forceUpdate();
You can avoid using `$forceUpdate` if a data property is created for `hideTopBar`. When that property were to change the template would update without needing to call to force the update. The `hideTopBar` would default to `PreferencesManager.loadValue('hide_top_bar')`.

2020-12-02 05:23 UTC, alrusdi commented on src/components/TopBar.ts
> +      this.$forceUpdate();
Your review lead me to read this article https://michaelnthiessen.com/force-re-render/
Author's point seems to be reasonable, so I've used his technique to force the component update.

2020-12-03 00:54 UTC, bafolts approved these changes

2020-12-03 00:54 UTC, bafolts commented on src/components/TopBar.ts
> +      this.componentKey += 1;
This is at least not using $forceUpdate but still seems to be working against vue. With vue we shouldn't have to be concerned with when the renderer is going to update and it should more or less happen naturally as the data is updated.  If this used:

```
data: function() {
  return {
    hideTopBar: PreferencesManager.preferencesValue.loadValue('hide_top_bar') !== '1'
  }
},
methods: {
   toggleBar(): {
     this.componentKey = this.componentKey === '1' ? '' : '1'
     PreferencesManager.saveValue('hide_top_bar', this.componentKey);
  }
}
```
The template will be updated as we are naturally updating `hideTopBar`. Anyone updating `hideTopBar` then doesn't need to call to `forceRenderer`. As this is at least not using $forceUpdate though it is good enough.

2020-12-03 05:20 UTC, merged