Added timers
bafolts/terraforming-mars pull request #2007
Opened 2020-12-04 17:11 UTC by sienmich

Hi, I'm working on timers.

Right now it looks like this (they are in real time :smile: ) :
![Screenshot from 2020-12-04 17-54-56](https://user-images.githubusercontent.com/19472604/101191970-ae0d5d00-365a-11eb-882f-81999d43307b.png)

I'm wondering about two things:

1. How and where to display them? Right now they are below the corp name, but this is temporary place, they make whole player-info bar too fat. They can replace the `active` status (active player is the one whose timer is rising), but they do not replace the `passed` status.

2. Currently they count time only during your main turn (while making actions), not during draft and card buying. Would you like to count time spend on drafting? More like only when everybody else is waiting or just always when somebody is waiting or even always when you can perform some action?

Cheers!

2020-12-05 01:25 UTC, nwai90 commented
@sienmich Nice work! IMO it suffices to count time only during the active player's turn (Action phase). Placing the timer below corporation name looks like a reasonable trade off.

A couple of points to consider:
1. Could add an option in Preferences to hide the timer for those who don't use it
2. Perhaps make the timers count down instead of up?

2020-12-05 02:44 UTC, ltdstudio commented
good desin, maybe we can make a time award for game.
![time awards](https://user-images.githubusercontent.com/39257428/101231519-c3c86400-36e6-11eb-8dcd-30475f7716c8.png)

2020-12-05 06:59 UTC, kberg commented
I do not recommend using the timer as a VP source.

>

2020-12-05 07:17 UTC, alrusdi commented
>     Would you like to count time spend on drafting

In our "real life" playgroup it was most time consuming part of the game. So i believe we must take into count draft time.

2020-12-05 09:26 UTC, chosta commented
This makes the UI box too long. Let me think about where to put the timesrs and don't break the design. Otherwise it's a great improvement, as many experienced players enjoy faster play.

2020-12-05 23:56 UTC, kevinb9n commented
Having the timer count downward would imply some kind of consequence for when it reaches zero.  But applying any consequences to this timer will be *extremely* difficult to do fairly without warping incentives. Decisions-per-generation vary widely in number and complexity depending on play style and what cards I manage to get.

I don't see it working. I think counting upward, just so that people have some *awareness* of where the time is going, will make a big difference I think. But the player whose timer is the highest is not necessarily the slowest.

2020-12-06 00:05 UTC, kevinb9n commented
(Ideally, it should be ticking when and only when the game is awaiting any kind of decision from me, which I am currently able to give, irrespective of whose turn it is, or whether it is also waiting on other players too.)

2020-12-06 14:10 UTC, sienmich commented
Ok, now timers are counting always when you can perform some action (so in at the beginning of the research phase all timers are rising).
The first action is skipped (choosing corporation or first card in initial drafting), so it's not counting time before you open the game.

2020-12-06 14:11 UTC, sienmich commented
@chosta, any ideas where to put them? I think they should also be visible in initial drafting phase.

2020-12-06 14:20 UTC, sienmich commented
I'm not a big fan of time award or timers counting down, I agree with @kevinb9n. I want the timers to just count the time, that was the best solution in my board terraforming experience.

I'm planning to:
1. Add option to hide them
2. Include them in game results screen
3. Improve UI, put them somewhere else
4. Fix drafting timers (Right now a player who is choosing a draft card does not know if other players are done or are still choosing. So theirs timers are rising, but later when server synchronizes they drop back).

Any more ideas? :smile:

2020-12-06 14:27 UTC, kberg commented
For what it's worth, I *do* strongly want countdown timers, but that can be dealt with in another PR.

2020-12-07 08:28 UTC, chosta commented
Good work so far!
A couple of comments
> 1. Add option to hide them

IMO, timers should be hidden by default. We have to reduce clutter and as a new feature it would need time to settle. Also, not everyone would be comfortable with the pressure the timer gives.

> 3. Improve UI, put them somewhere else
Let me try and figure it out this week. It's a very tight space in the playerInfo component at the moment but I'll figure it out.

Timers in js are a bit tricky so this would need to be thoroughly tested. I'd suggest we go to a separate branch at some point and put it on a beta server. Please check how timers behave in multiple open tabs too.

2020-12-07 17:06 UTC, kberg commented
Is this feature compatible with undo? If I wait 5 minutes and undo an action, what will my timer show?

2020-12-07 17:06 UTC, kberg commented
I suspect to make this work well, it might be time to introduce a new table.

2020-12-07 17:14 UTC, sienmich commented
Good point, it does not work with undo. I'll think about it.

2020-12-08 10:40 UTC, vsrisuknimit commented
> Is this feature compatible with undo? If I wait 5 minutes and undo an action, what will my timer show?

It should count all the time until undo as well.

2020-12-09 19:19 UTC, kberg commented
> > Is this feature compatible with undo? If I wait 5 minutes and undo an action, what will my timer show?
> 
> It should count all the time until undo as well.

Agreed. Having stared at the database code for the last couple of days, I have a suggestion for addressing this.

My advice, is to not worry about it for this PR. This will be a great addition.

2020-12-09 19:40 UTC, sienmich commented
Yeah. I think simple cloning timer before the undo action and restoring it after could work. Since the undo action is being changed right now I'll leave it for next PR.

2020-12-09 20:18 UTC, sienmich commented
Ok, I've done all I wanted in this PR. Ready for review and testing!

2020-12-09 20:21 UTC, sienmich commented
2 things that should have been done in near future, but I don't know how:
 - Fixing timer with undo
 - Improving drafting timers (Right now a player who is choosing a draft card does not know if other players are done or are still choosing. So theirs timers are rising, but later when server synchronizes they drop back)

2020-12-09 21:03 UTC, kberg commented
> Yeah. I think simple cloning timer before the undo action and restoring it after could work. Since the undo action is being changed right now I'll leave it for next PR.

I was thinking just creating a separate table for the timer. No undo there! :D

2020-12-12 12:08 UTC, sienmich commented
So what's next? Somebody wanna review?

2020-12-12 18:00 UTC, vsrisuknimit commented
@sienmich conflicts.

tagging @bafolts @kberg for review.

2020-12-12 18:25 UTC, kberg commented
I was just going to ask. Ha! Since there's a merge conflict, can you resolve that, and THEN I'll take a first look?

2020-12-12 18:58 UTC, kberg reviewed
Looks like you have another conflict to resolve. Which gives me time to go watch Mandalorian with Wifeberg. @sienmich if you are on the discord channel, drop me a DM so I can ask a couple of questions if I have them. sry. thanks. I appreciate it.

2020-12-12 19:04 UTC, sienmich commented
Ya, that merge didn't go as planned. I will look at it tomorrow. Thanks!

2020-12-12 20:09 UTC, kberg requested changes
Take a look at the build issue with `ServerModel`.

I like where this is going, but I have some questions about what it's doing. Before making any significant changes, perhaps help me understand `Timer`, and the `running` count.

Also, I'm sorry if this has already been asked and answered: How does this work during a draft phase? Do all players timers count?

2020-12-12 20:09 UTC, kberg commented on src/Timer.ts
> +  public stop() {
Not sure I understand everything this method is doing -- part of that is of course that I'm not following what's going on with running, or why a player woul dhave mutliple runnings?

2020-12-12 20:09 UTC, kberg commented on src/components/overview/PlayerTimer.ts
> +export const PlayerTimer = Vue.component('player-timer', {
I can't tell by reading, but how does this timer stop counting when it is not the player's turn?

2020-12-13 02:29 UTC, kyshantry commented
So I'd say that it should definitely count during drafting/buying. 

One idea for a count down is that you get a certain amount of time for each turn plus a stored bank

2020-12-13 13:37 UTC, sienmich commented
@kberg, so my main idea of this implementation was to make timers work like this (added just those two lines):
```.ts
class Player {
...
    public setWaitingFor(input: PlayerInput, cb: () => void): void {
      this.timer.start();
      this.waitingFor = input;
      this.waitingForCb = () => {
        this.timer.stop();
        cb();
      };
    }
```
This automatically starts a timer whenever there is an action to perform and stops it when the action is finished. Works with draft, buying cards, choosing prelude or standard projects.
However sometimes after the player finishes action there is a new `timer.start()` called just before (like 0.001 s) the last `timer.stop()`.
For example (chronological order):

1. `timer.start()` called
2. `timer.stop()` called
3. `timer.start()` called
4. `timer.start()` called
5. `timer.stop()` called
6. `timer.stop()` called

To resolve this the Timer has `running` attribute which tells how many more `start()`s there were than `stop()`s. Does it make sense? :)

Should I paste this into the code as documentation?

2020-12-13 14:12 UTC, sienmich commented on src/components/overview/PlayerTimer.ts
> +export const PlayerTimer = Vue.component('player-timer', {
The PlayerTimer (Vue) does not stop, it just refreshes every second. Every second it displays the `Timer.toString()` which changes or not based on the `running` attribute which depends on `start()` and `stop()` calls.

2020-12-13 14:15 UTC, Lynesth commented on src/Timer.ts
> +    if (!this.afterFirstAction) {
Why don't we count the time elapsed for the first action ?
Did you mean the time we spend picking corporation/preludes/project cards ?
If so, what's the reason behind this and how does it work out with the initial draft option ?

2020-12-13 14:15 UTC, Lynesth commented on src/Timer.ts
> +    return res.map((s) => String(s).padStart(2, '0')).join(':');
This can simply be:
```ts
    const elapsedSeconds = this.sumElapsed + (this.running ? Date.now() - this.startedAt : 0);
    return new Date(elapsedSeconds * 1000).toISOString().substr(11, 8);
```

2020-12-13 15:13 UTC, kberg commented
> @kberg, so my main idea of this implementation was to make timers work like this (added just those two lines):
> 
> ```ts
> class Player {
> ...
>     public setWaitingFor(input: PlayerInput, cb: () => void): void {
>       this.timer.start();
>       this.waitingFor = input;
>       this.waitingForCb = () => {
>         this.timer.stop();
>         cb();
>       };
>     }
> ```
> 
> This automatically starts a timer whenever there is an action to perform and stops it when the action is finished. Works with draft, buying cards, choosing prelude or standard projects.
> However sometimes after the player finishes action there is a new `timer.start()` called just before (like 0.001 s) the last `timer.stop()`.
> For example (chronological order):
> 
> 1. `timer.start()` called
> 2. `timer.stop()` called
> 3. `timer.start()` called
> 4. `timer.start()` called
> 5. `timer.stop()` called
> 6. `timer.stop()` called
> 
> To resolve this the Timer has `running` attribute which tells how many more `start()`s there were than `stop()`s. Does it make sense? :)
> 
> Should I paste this into the code as documentation?

Doesn't have to be this detailed. Don't worry about it for now -- now that I understand that I can look at this more closely.

2020-12-13 15:22 UTC, sienmich commented on src/Timer.ts
> +    if (!this.afterFirstAction) {
Using the `setWaitingFor` method described above the first `timer.start()` is called with game creation, before players even get their links to play. Best thing I came up with is not counting the first action. Without the initial drafting it does not count choosing initial cards, with initial drafting it does not count drafting first card.
Or should I just ignore that, because at game creation all players' timers are running anyway?

2020-12-13 15:34 UTC, sienmich commented on src/Timer.ts
> +    return res.map((s) => String(s).padStart(2, '0')).join(':');
Nice, thanks, fixed

2020-12-13 15:35 UTC, Lynesth commented on src/components/overview/PlayerTimer.ts
> +      this.timerText = Timer.fromJSON(this.timer).toString();
Creating a new Timer object every second to get elapsed time doesn't seem like a very efficient way to do it.
You could maybe make that `toString` method static and call it with the timer as argument to make it a bit lighter:
```ts
this.timerText = Timer.toString(this.timer);
```

Also this is somehow called twice each time for the active player. Noticed it by adding a `console.log()` after the assignment. Didn't dig to find out why.

![firefox_2020-12-14_02-34-26](https://user-images.githubusercontent.com/5318258/102016415-fa703f80-3db4-11eb-8a03-9fe69cef0583.png)

2020-12-13 15:42 UTC, Lynesth commented on src/Timer.ts
> +    if (!this.afterFirstAction) {
You can probably ignore it since it's equivalent for all players and it makes the code a bit "complicated" as a side effect. You can get rid of `afterFirstAction` that way. But feel free to gather others opinion on this matter.

2020-12-13 15:42 UTC, Lynesth commented
If the server restarts after the corporation cards have been played but before the first player finished his turn, then all timers are active. It's a pretty specific case but can you look into that as well ?

2020-12-13 16:15 UTC, sienmich commented on src/components/overview/PlayerTimer.ts
> +      this.timerText = Timer.fromJSON(this.timer).toString();
Ok, will change `toString`.

Interesting, the `mounted()` hook is called twice, so there are two parallel refreshers going.
Adding
```.ts
  mounted() {
    console.log('mounted PlayerStatus');
  },
```
to PlayerStatus.ts displays two `mounted PlayerStatus` logs, which means the problem is somewhere higher.
Any idea why? It's my first time in Vue.

2020-12-13 16:19 UTC, sienmich commented on src/components/overview/PlayerTimer.ts
> +      this.timerText = Timer.fromJSON(this.timer).toString();
Ok, there is this new Top bar feature with second timer, which is hidden

2020-12-13 16:37 UTC, sienmich commented on src/Game.ts
> +        player.timer.visible = gameOptions.showTimers;
`visible` does not change per player. I agree, it should belong to some `GameOptions` object rather than `Player`.
However right now every similar feature works that way. The `PlayerModel` class has attributes:

- `coloniesExtension`
- `boardName`
- `showOtherPlayersVP`
- `initialDraft`

and many more. They are all constructed with `getPlayerModel()` from `ServerModel.ts`. So making it the other way with Timers would be inconsistent.

Maybe lets create new issue with this?

2020-12-13 16:45 UTC, sienmich commented on src/Game.ts
> +        player.timer.visible = gameOptions.showTimers;
@Lynesth sugested (https://github.com/bafolts/terraforming-mars/pull/2007/#issuecomment-744025822) to move `visible` to `PlayerModel`. I think it's the right choice.

2020-12-13 17:07 UTC, kevinb9n commented
Those of you who want to continue from this to a sudden-death countdown timer, I'm *asking* you to please read #2108, but it's so long that I can't blame you if you don't.

2020-12-13 17:24 UTC, sienmich commented on src/Timer.ts
> +    if (!this.afterFirstAction) {
Well, I agree now. @kberg, what you think?

2020-12-14 00:44 UTC, sienmich commented on src/Timer.ts
> +  constructor(
Ok, I just serialized it. Is this the way it should be now?

2020-12-14 01:06 UTC, sienmich commented on src/components/overview/PlayerTimer.ts
> +      this.timerText = Timer.fromJSON(this.timer).toString();
Ok, fixed that `toString`. I think I will not change the top bar, 1 ping every second is not that much. If not then let's create new issue about the top bar?

2020-12-14 11:40 UTC, sienmich commented on src/Game.ts
> +        player.timer.visible = gameOptions.showTimers;
And I moved it.

2020-12-14 14:30 UTC, sienmich commented
> If the server restarts after the corporation cards have been played but before the first player finished his turn, then all timers are active. It's a pretty specific case but can you look into that as well ?

That's was a hard one, 3 hours learning how saving the game works. Fixed! Additionally now `running` is boolean, double win.

2020-12-15 06:18 UTC, Lynesth commented
Thanks for the changes, I'll take a new look at it in a few hours.

2020-12-15 06:21 UTC, kberg requested changes
I'm marking as "Request changes" only because there are a couple. Plus you probably have merge conflicts. But this doesn't look confusing any more, and should go in fairly soon.

2020-12-15 06:21 UTC, kberg commented on src/Player.ts
> +      this.timer.start();
So what this means is now setting that you're waiting for something is code for starting the timer. OK. This seems reasonable.

2020-12-15 06:21 UTC, kberg commented on src/SerializedTimer.ts
> +export interface SerializedTimer {
Oh, huh. So, it's possible I made you do far more work than I expected. If I asked you to write a Serialized instance, I'm very sorry. If I didn't ask you to do it but you _inferred it_ I'm still sorry. A lot has happened in the last few days. But leave this for now. I still will ask you to make a change in Timer.deserialize.

2020-12-15 06:21 UTC, kberg commented on src/Timer.ts
> +    Object.assign(timer, d);
We are actively removing calls to Object.assign during deseriailzation, and instead, assigning each individual value. Could you please add those five assignments here?

2020-12-15 06:21 UTC, kberg commented on src/Timer.ts
> +  // start() is always called when player can perform new input action.
"... when the game is waiting for a player to supply input"?

2020-12-15 06:21 UTC, kberg commented on src/Timer.ts
> +    this.running = true;
This is much simpler! Wow!

2020-12-15 06:21 UTC, kberg commented on src/Timer.ts
> +    const elapsed = d.sumElapsed + (d.running ? Date.now() - d.startedAt : 0);
What's the toString used for? Is it worth adding whether the timer is enabled?

2020-12-15 10:39 UTC, sienmich commented on src/SerializedTimer.ts
> +export interface SerializedTimer {
No problem :)

2020-12-15 11:33 UTC, sienmich commented on src/Timer.ts
> +    Object.assign(timer, d);
Yep, fixed

2020-12-16 00:28 UTC, sienmich commented
Currenly testable at https://terraforming-mars-sienmich.herokuapp.com/

2020-12-16 01:10 UTC, Lynesth requested changes

2020-12-16 01:10 UTC, Lynesth commented on src/components/GameEnd.ts
> +      return Timer.toString(p.timer.serialize());
This should be `p.timer`, it's already serialized.

2020-12-16 01:16 UTC, sienmich commented on src/components/GameEnd.ts
> +      return Timer.toString(p.timer.serialize());
Thanks, fixed

2020-12-16 03:43 UTC, Lynesth approved these changes

2020-12-16 07:34 UTC, chosta commented
Can I take a look before merge. Will do in a couple of hours.

On Wed, Dec 16, 2020, 05:43 Lynesth <notifications@github.com> wrote:

> *@Lynesth* approved this pull request.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bafolts/terraforming-mars/pull/2007#pullrequestreview-553334944>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGMEU6TJFY252JVKC4KZFDSVAUGPANCNFSM4UNWR72Q>
> .
>

2020-12-16 21:51 UTC, kberg commented
I'll look again tonight. I took yesterday off to make some art for a change.

>

2020-12-17 01:24 UTC, bafolts requested changes

2020-12-17 01:24 UTC, bafolts commented on src/Player.ts
> +      player.timer = Timer.deserialize(d.timer);
OK. Chiming in. This all looks great and the only thing that stands out is that this `timer` will be `undefined` for every game currently in the database. When first rolling this out the type of `timer` needs to be `SerializedTimer | undefined`.

2020-12-17 01:27 UTC, bafolts commented on src/Player.ts
> +      player.timer = Timer.deserialize(d.timer);
Which begs the question....for games in the database when this timer shows up we will most likely have to just have those users deal with some timer that starts at default value. Eventually wont be a problem.

2020-12-17 02:14 UTC, Lynesth commented on src/Player.ts
> +      player.timer = Timer.deserialize(d.timer);
I always forget about ongoing games, we should probably just wipe the db in those cases :p

I think that instead of having timer `SerializedTimer | undefined`, shouldn't we simply create a new timer when deserializing if `d.timer` is undefined ?

Also regarding new games, they shouldn't see the timers anyway since the option didn't exist.

2020-12-17 02:19 UTC, bafolts commented on src/Player.ts
> +      player.timer = Timer.deserialize(d.timer);
I would put `SerializedTimer | undefined` on the type for now so that typescript can check that we are covering our tracks every place we use the property. It will most likely end up using a new timer when `d.timer` is `undefined` but we will get typescript working for us for free. Putting :robot: s to work!

2020-12-17 02:20 UTC, bafolts commented on src/Player.ts
> +      player.timer = Timer.deserialize(d.timer);
@kberg has been putting comments above places like this with `// remove by [some date]` so that we know the `| undefined` is supposed to be short lived. Future visitors to the code then know they can safely remove the `| undefined`.

2020-12-17 02:25 UTC, Lynesth commented on src/Player.ts
> +      player.timer = Timer.deserialize(d.timer);
Nevermind me, I thought you wanted the whole `timer` to be `| undefined`, not just the argument to the `Timer.deserialize` method. Read your comment a bit too fast.

2020-12-17 02:39 UTC, sienmich commented on src/Player.ts
> +      player.timer = Timer.deserialize(d.timer);
Ok, same thing for `timer.start()` and `.stop()`. They are called even when times ate off. Or do we care only about end game screens?

2020-12-17 02:42 UTC, bafolts commented on src/Player.ts
> +      player.timer = Timer.deserialize(d.timer);
Calling `timer.start()` and `timer.stop()` should be fine even if the values are not used. If the property is `undefined` every old game would fail to deserialize. Only looking to address that situation here with my requested change.

2020-12-17 03:10 UTC, kberg reviewed
Yeah, serialization. Otherwise this looks pretty good.

2020-12-17 03:10 UTC, kberg commented on src/Player.ts
> +      player.timer = Timer.deserialize(d.timer);
> OK. Chiming in. This all looks great and the only thing that stands out is that this `timer` will be `undefined` for every game currently in the database. When first rolling this out the type of `timer` needs to be `SerializedTimer | undefined`.

How did I miss that.

2020-12-17 03:12 UTC, kberg reviewed
Also please add a test in Player.spec.ts like `backward compatible deserialization for actionsThisGeneration` for the timer, a la Brian's concern.

2020-12-17 13:35 UTC, sienmich commented on src/Player.ts
> +      player.timer = Timer.deserialize(d.timer);
Ok, fixed

2020-12-17 15:33 UTC, kberg commented
I think this is ready to go!

2020-12-17 15:33 UTC, kberg approved these changes

2020-12-18 16:45 UTC, vsrisuknimit commented
We have playtested this many times. It seems to be working great. Glad it will be ready soon.

2020-12-18 17:04 UTC, sienmich commented
Still waiting for @bafolts approve, am I right?

2020-12-18 17:05 UTC, bafolts approved these changes

2020-12-18 17:06 UTC, merged