make shuffle board not truely shuffled
bafolts/terraforming-mars pull request #2089
Opened 2020-12-12 10:51 UTC by Ronnoc

!2048

2020-12-12 10:58 UTC, chosta commented
@kberg @bafolts we have a discussion in discord about making the randomization more sensible (in terms of astrobiology). The idea is to have a function or functions that make oceans more / less denser + areas rich / poor on resources.

@Ronnoc we definitely need comments explaining what the functions do. And an easy way to tweak the numbers.
Example: A parameter not allowing for more than X adjacent oceans, or no more than 2 super rich areas

2020-12-12 10:59 UTC, Ronnoc commented
I thought ocean is ok now, but plant are still not go together

2020-12-12 11:01 UTC, nwai90 commented
This should be introduced as a game option imo, not a complete replacement of the full random board tiles option

2020-12-12 13:09 UTC, Ronnoc commented
add some comment & fix typo
some demo map

|  Board   | Example1  | Example2  | Example3  |
|  ----  | ----  | ----  | ----  |
| origin  | ![origin_1](https://user-images.githubusercontent.com/5140023/101984648-b8180700-3cbd-11eb-9f93-3dd68b0120e1.png) | ![origin_2](https://user-images.githubusercontent.com/5140023/101984652-bb12f780-3cbd-11eb-9a36-b7b6beb3e586.png) | ![origin_3](https://user-images.githubusercontent.com/5140023/101984654-bbab8e00-3cbd-11eb-88bd-223ecf597283.png) |
| Hellas  | ![hellas_1](https://user-images.githubusercontent.com/5140023/101984658-bfd7ab80-3cbd-11eb-92c4-cf3d7881c027.png) | ![hellas_2](https://user-images.githubusercontent.com/5140023/101984660-c23a0580-3cbd-11eb-9096-17c6be4984e6.png) | ![hellas_3](https://user-images.githubusercontent.com/5140023/101984662-c2d29c00-3cbd-11eb-9c9e-1296c3e1cf60.png) |
| Elysium  | ![Ely_1](https://user-images.githubusercontent.com/5140023/101984668-cfef8b00-3cbd-11eb-9262-a3b3248391ce.png) | ![Ely_2](https://user-images.githubusercontent.com/5140023/101984669-d1b94e80-3cbd-11eb-9bd2-951906f8f068.png) | ![Ely_3](https://user-images.githubusercontent.com/5140023/101984670-d251e500-3cbd-11eb-8cd8-1a8f70aa44d7.png) |

2020-12-12 13:54 UTC, Ronnoc commented
Some bug here; only 11 oceans in my shuffled map

2020-12-12 14:25 UTC, Ronnoc commented
> 
> 
> <img width="318" alt="Screenshot 2020-12-12 at 7 04 31 PM" src="https://user-images.githubusercontent.com/2408094/101982156-eb05cf00-3cac-11eb-8ea2-9b1b68e546e4.png">
> 
> 
> 
> 
> 
> This should be introduced as a game option imo, not a complete replacement of the full random board tiles option

Will do it in the future(/w)

2020-12-13 04:04 UTC, kberg commented
I think this is a good time to asseess how this project should move forward in terms of the _breadth_ of options it supports. Specifically, do we really need _both_ limited random and full random? I would like to raise this, not here, but in an issue where the devs on the project can talk about it. But to lay out my vision and priority, focusing on fewer options that are good enough is better than more options.

A better randomization strategy sounds wholly better than fully random board tiles, and I suggest that rather than add more options to the UI, just pick one and go with it. I like the promise that comes with the new one.

2020-12-13 04:05 UTC, kberg commented
ob: 
![image](https://user-images.githubusercontent.com/413481/102002840-80fe2180-3cce-11eb-8b5f-6dd2b2c6d6bf.png)

2020-12-13 04:19 UTC, kberg reviewed
I'll read some more of this later. Think about how unit tests will look for this change.

2020-12-13 04:19 UTC, kberg commented on src/BoardBuilder.ts
> +    private Id2AdjIdsMap: Map<number, Array<number>>=new Map();
BoardBuilder is pretty focused and small, so doubling its size to handle the smart randomization case makes it hard to read, and turns this a bit into a dual-purpose class. Can you move this into another class? Say, `BoardRandomizer.`

2020-12-13 04:19 UTC, kberg commented on src/BoardBuilder.ts
> +    private Id2AdjIdsMap: Map<number, Array<number>>=new Map();
"adjacentSpaceMap"

Also, in general, don't use capital letters to describe something that is not a class, or not a FULL_CAPS constant.

2020-12-13 04:19 UTC, kberg commented on src/BoardBuilder.ts
> +      const tilesPerRow = [5, 6, 7, 8, 9, 8, 7, 6, 5];
This is repeating a value already used somewhere else. Having the same data in two places makes it hard to maintain code in the future.

2020-12-13 04:19 UTC, kberg commented on src/BoardBuilder.ts
> +    createConnectIdMap() {
There's a function in Board called getAdjacentSpaces which seems to do this job pretty well - and is easier to read than what's below. Can you use the same behavior? And can Board.getAdjacentSpaces use your newly-created reference map of adjacent spaces?

2020-12-13 04:19 UTC, kberg commented on src/BoardBuilder.ts
> +    getPlantDegree(i: number): number {
What is a 'degree'? What does i mean? If it's the sapce id, rename it to `spaceId`

2020-12-13 04:19 UTC, kberg commented on src/BoardBuilder.ts
> +    getBestNotPlant(): number {
Tiles aren't specified by numbers, but by string ids. Can you use string ids to represent the tile spaces instead? This means ids like `4` will be `"04"`

2020-12-13 04:19 UTC, kberg commented on src/BoardBuilder.ts
> +    getBestNotPlant(): number {
"Return the tile with the most plant bonuses adjacent, that does not have a plant bonus."
There's got to be a better name than `getBestNotPlant`. When I understand more about things like what a degree means, I'll be able to suggest a better name.

2020-12-13 04:19 UTC, kberg commented on src/BoardBuilder.ts
> +      if (candidates.length === 0) return -1;
Use `undefined` when there is no good candidate.

2020-12-13 05:03 UTC, nwai90 commented
> I think this is a good time to asseess how this project should move forward in terms of the _breadth_ of options it supports. Specifically, do we really need _both_ limited random and full random? I would like to raise this, not here, but in an issue where the devs on the project can talk about it. But to lay out my vision and priority, focusing on fewer options that are good enough is better than more options.
> 
> A better randomization strategy sounds wholly better than fully random board tiles, and I suggest that rather than add more options to the UI, just pick one and go with it. I like the promise that comes with the new one.

I'd advocate for keeping both. This is similar to random milestones and awards - what is "better" is very subjective and introducing artificial constraints would prevent certain tile combinations / layouts from ever occurring.

2020-12-13 05:16 UTC, kberg commented
Yeah. Let's get that settled elsewhere. But I think that's a fair
perspective.

>

2020-12-13 11:08 UTC, vsrisuknimit commented
> > I think this is a good time to asseess how this project should move forward in terms of the _breadth_ of options it supports. Specifically, do we really need _both_ limited random and full random? I would like to raise this, not here, but in an issue where the devs on the project can talk about it. But to lay out my vision and priority, focusing on fewer options that are good enough is better than more options.
> > A better randomization strategy sounds wholly better than fully random board tiles, and I suggest that rather than add more options to the UI, just pick one and go with it. I like the promise that comes with the new one.
> 
> I'd advocate for keeping both. This is similar to random milestones and awards - what is "better" is very subjective and introducing artificial constraints would prevent certain tile combinations / layouts from ever occurring.

Agree with keeping both. And perhaps adding a third option later when you can input a JSON for a handcrafted map.

Here is a small poll @kevinb9n made. TL;DR: some people think it would be an improvement. Some prefer total random. https://discord.com/channels/737945098695999559/737945098695999562/785960906353410068

As long as the function is well written with good parameters. People can change those parameters later in their own repo. No need for a third-party board generator.

2020-12-14 01:39 UTC, Ronnoc commented on src/BoardBuilder.ts
> +    createConnectIdMap() {
Board.getAdjacentSpaces is base on spaces, already know the x,y of a space ，which is not when shuffle before build spaces

2020-12-14 01:40 UTC, Ronnoc commented on src/BoardBuilder.ts
> +    getPlantDegree(i: number): number {
Degree is connected node count in th graph

2020-12-14 03:12 UTC, kberg commented on src/BoardBuilder.ts
> +    createConnectIdMap() {
Since the first two spaces are colony spaces, the hex grid map ids won't change from map to map, so it's more reliable than that.

2020-12-14 03:12 UTC, kberg commented on src/BoardBuilder.ts
> +    getPlantDegree(i: number): number {
Then consider `getNumAdjacentPlantBonusSpaces`

2020-12-14 03:12 UTC, kberg commented on src/BoardBuilder.ts
> +        if (!this.oceans[i]) continue;
Why would this oceans[i] be undefined?

2020-12-14 03:12 UTC, kberg commented on src/BoardBuilder.ts
> +      for (const i of idOrder) {
Can you use ```idOrder.forEach((i) => {

});```

At least avoid `for (var in array)`.

2020-12-14 03:12 UTC, kberg commented on src/BoardBuilder.ts
>      public shuffle(...lands: Array<SpaceName>) {
So, how does this algorithm work? First you get all the indexes of ocean spaces, and then you look to place it someplace, but I'm not entirely clear where. And the same goes for gaining plant bonuses? Yes, I could use a description of how this works. We can work through language issues, but just give me a thorough explanation, and we'll go from there.

2020-12-14 07:27 UTC, chosta commented on src/BoardBuilder.ts
>      public shuffle(...lands: Array<SpaceName>) {
I second this. There needs to be a good explanation on how the algorithms work.

2020-12-14 08:54 UTC, Ronnoc commented on src/BoardBuilder.ts
>      public shuffle(...lands: Array<SpaceName>) {
let me show a example
```
this is a naive random board; consider ocean-1; connect to no other ocean; ? is land connected to 3 ocean
    o x x x x 
   o x x o x x 
  x x x x x x x 
 o ? o x 1 x x x 
x o ? x x x x x x 
 x x o x o x o o 
  x x x x x x x 
   x x x x o x 
    x x x x x 
random select ? and place 1 to it; after that, we consider ocean-2, and ? again
    o x x x x 
   2 x x x x x 
  x x x x x x x 
 o ? o x o x x x 
x o 1 x x x x x x 
 x x o x o x o o 
  x x x x x x x 
   x x x x o x 
    x x x x x 
move ocean-2; consider ocean-3, and ? again
    x x x x x 
   o x x x x x 
  ? ? x x x x x 
 o 2 o x o x x x 
x o o ? x x x x x 
 x ? o x 3 x o o 
  x x x x x x x 
   x x x x o x 
    x x x x x 
move ocean-3; consider ocean-4, and ? again
    x x x x x 
   o x x x x x 
  ? ? x x x x x 
 o o o x 4 x x x 
x o o ? x x x x x 
 x 3 o x x x o o 
  x x x x x x x 
   x x x x o x 
    x x x x x 
move ocean-4; consider ocean-5, and ? again
    x x x x x 
   o x x x x x 
  ? ? x x x x x 
 o o o x x x x x 
x o o 4 x x x x x 
 x o o x x x o o 
  x x x x x x x 
   x x x x 5 x 
    x x x x x 
move ocean-5; consider ocean-6, and ? again
    x x x x x 
   o x x x x x 
  ? 5 x x x x x 
 o o o x x x x x 
x o o o x x x x x 
 x o o x x x o 6 
  x x x x x x x 
   x x x x x x 
    x x x x x 
move ocean-6; consider ocean-7, and ? again
    x x x x x 
   o ? x x x x 
  6 o ? x x x x 
 o o o ? x x x x 
? o o o x x x x x 
 ? o o ? x x 7 x 
  x x x x x x x 
   x x x x x x 
    x x x x x 
move ocean 7; the algorithm done
    x x x x x 
   o x x x x x 
  o o 7 x x x x 
 o o o x x x x x 
x o o o x x x x x 
 x o o x x x x x 
  x x x x x x x 
   x x x x x x 
    x x x x x 

```

2020-12-14 17:07 UTC, kberg commented on src/BoardBuilder.ts
>      public shuffle(...lands: Array<SpaceName>) {
@Ronnoc I have a suggestion: write the algorithm, but not in English. Use the language you're most comfortable with. And let's start with Google Translate, or see if someone else wants to help out with the explanation.

I am sorry I can't give you more. As I have to carefully choose how I spend my time on this project, I would rather spend time helping others get well-written PRs in rather than have to reverse-engineer the algorithm from the code, or even from examples.

2020-12-15 05:29 UTC, Ronnoc commented on src/BoardBuilder.ts
> +    private Id2AdjIdsMap: Map<number, Array<number>>=new Map();
Move the related functions of random to the BoardRandomizer class

2020-12-15 05:30 UTC, Ronnoc commented on src/BoardBuilder.ts
> +    private Id2AdjIdsMap: Map<number, Array<number>>=new Map();
change name to adjacentSpaceMap

2020-12-15 05:30 UTC, Ronnoc commented on src/BoardBuilder.ts
> +      const tilesPerRow = [5, 6, 7, 8, 9, 8, 7, 6, 5];
make `tilesPerRow` as a member of `BoardBuilder`

2020-12-15 05:31 UTC, Ronnoc commented on src/BoardBuilder.ts
> +    getPlantDegree(i: number): number {
change the name to `getNumAdjacentPlantBonusSpaces`

2020-12-15 05:31 UTC, Ronnoc commented on src/BoardBuilder.ts
> +      if (candidates.length === 0) return -1;
change -1 to `undefined`

2020-12-15 05:33 UTC, Ronnoc commented on src/BoardBuilder.ts
> +        if (!this.oceans[i]) continue;
This line is to make sure this space is ocean; oceans Will not become undefined

2020-12-15 05:33 UTC, Ronnoc commented on src/BoardBuilder.ts
> +      for (const i of idOrder) {
fixed that

2020-12-15 06:19 UTC, Ronnoc commented on src/BoardBuilder.ts
>      public shuffle(...lands: Array<SpaceName>) {
Thank you very much for your review.

2020-12-15 06:20 UTC, Ronnoc commented on src/BoardBuilder.ts
>      public shuffle(...lands: Array<SpaceName>) {
For a purely random map, it can be found that the ocean is not clustered together.
There are often 'longly' oceans, or two oceans connected together
'longly' ocean, not adjacent to other oceans
two oceans connected together, only adjacent to 1 other ocean (there are other oceans that meet this condition, and it is acceptable to move them too).
For these two oceans, we can move them to other locations
In order to allow more oceans to be connected after moving, choose the land that is most adjacent to the ocean as the target of exchange
Randomness comes from the following
1 Choose the order of the ocean
2 Probability of moving the current ocean
3 Land as moving target

2020-12-15 06:23 UTC, Ronnoc commented on src/BoardBuilder.ts
> +    getBestNotPlant(): number {
change the name to getLandWithTheMostAdjacentPlantBonus

2020-12-17 03:59 UTC, kberg commented on src/BoardBuilder.ts
>      public shuffle(...lands: Array<SpaceName>) {
That's only part of the algorithm. You omitted the plants.

Like I said, can you please write it in your primary language?

2020-12-17 04:47 UTC, Ronnoc commented on src/BoardBuilder.ts
>      public shuffle(...lands: Array<SpaceName>) {
植物部分将使用相同的逻辑。
The plant part will use the same logic.

2020-12-17 16:25 UTC, bafolts requested changes
OK, sorry if this is a lot of comments but it took me 1.5 hours to follow along with this logic and I left comments and suggestions as I went. I think I uncovered a few bugs too. As this is hidden behind a feature flag of sorts as the user has to select they want to use the new _limited_ option I don't think this will be that bad. I do agree with @kberg that more options is not always a good thing but it seems users want to try this out. Removing this _limited_ if we ever wanted to should be easy enough as it is all limited to mostly one class and a few functions within that class behind a check for _limited_. Let me know if you have any questions. I actually like this approach for calculating adjacent spaces better than the implementation in `Board` today.

2020-12-17 16:25 UTC, bafolts commented on src/BoardRandomizer.ts
> +          if (row + 1 < 9) {
I would use `this.tilesPerRow.length` here again for readability.

2020-12-17 16:25 UTC, bafolts commented on src/BoardRandomizer.ts
> +    createAdjacentSpaceMap() {
With the suggestions below I actually think this is a simpler and easier to read solution than `Board::getAdjacentSpaces`. In a separate PR after this one we should attempt to use this strategy more places. We call `getAdjacentSpaces` often so if this is more efficient it will be worthwhile. Also at the point I am struggling to follow `Board::getAdjacentSpaces`.

2020-12-17 16:25 UTC, bafolts commented on src/BoardRandomizer.ts
> +      this.bonuses = bonuses;
This additional setting of `this.bonuses = bonuses` is unnecessary. The `shuffleArray` function modifies the array in place.

2020-12-17 16:25 UTC, bafolts commented on src/BoardRandomizer.ts
> +        const idOrder = [];
This is generating a range from `0...this.bonuses.length`. I believe you can use:

```
[...Array(this.bonuses.length).keys()];
```

2020-12-17 16:25 UTC, bafolts commented on src/BoardRandomizer.ts
> +      this.oceans = oceans;
This setting is unnecessary. The `shuffleArray` option modifies in place.

2020-12-18 09:53 UTC, Ronnoc commented
In the example picture in the original pull request (https://github.com/bafolts/terraforming-mars/pull/2089#issue-538005690), for the ocean adjacent to only 1 ocean, it will move with a probability of 0.5, and for the ocean that is not adjacent to other oceans, it will move with a probability of 1.0.

In the most recent version `f46c0436aa76406269c4dc738c6012f45527a061` used probabilities of 0.3 (originally 0.5) and 0.9 (originally 1.0).

Here are a few sample pictures, I prefer the current version.

It is difficult for me to quantitatively describe what the probability of movement will affect

|  board   | Exmaple  | Exmaple  | Exmaple  |
|  ----  | ----  | ----  | ----  |
| Origin  | ![org1](https://user-images.githubusercontent.com/5140023/102600354-ab7e2d80-4159-11eb-894b-0d9419316da6.jpg) | ![org_2](https://user-images.githubusercontent.com/5140023/102600359-ac16c400-4159-11eb-9498-9250e3f5b1f6.jpg) | ![org_3](https://user-images.githubusercontent.com/5140023/102600363-acaf5a80-4159-11eb-9408-693d36be76fd.jpg) |
| Hellas  | ![Hel_1](https://user-images.githubusercontent.com/5140023/102600348-aa4d0080-4159-11eb-8afe-b2847da244e6.jpg) | ![hel_2](https://user-images.githubusercontent.com/5140023/102600341-a8833d00-4159-11eb-8f33-3311a7fef261.jpg) | ![hel_3](https://user-images.githubusercontent.com/5140023/102600345-a9b46a00-4159-11eb-8d35-3bba67b96ee2.jpg) |
| Ely  | ![ely_1](https://user-images.githubusercontent.com/5140023/102600318-a4571f80-4159-11eb-95a0-5406aabc0d0c.jpg) |  ![ely_2](https://user-images.githubusercontent.com/5140023/102600326-a6b97980-4159-11eb-855b-789e5f92edad.jpg) | ![ely_3](https://user-images.githubusercontent.com/5140023/102600333-a7eaa680-4159-11eb-93c5-05486b58a3b2.jpg) |

原始pull request中示例图, 对于只与1个海洋相邻的海洋, 会以0.5的概率移动走, 对于不与其他海洋相邻的海洋, 会以1.0的概率移动走.

在最近的版本 `f46c0436aa76406269c4dc738c6012f45527a061` 采用了0.3(原本是0.5) 和 0.9(原本是1.0) 的概率.

这里是几张示例图, 我更倾向于现在的版本.

我比较很难定量地描述挪动的概率会影响什么

2020-12-18 09:56 UTC, Ronnoc commented
> OK, sorry if this is a lot of comments but it took me 1.5 hours to follow along with this logic and I left comments and suggestions as I went. I think I uncovered a few bugs too. As this is hidden behind a feature flag of sorts as the user has to select they want to use the new _limited_ option I don't think this will be that bad. I do agree with @kberg that more options is not always a good thing but it seems users want to try this out. Removing this _limited_ if we ever wanted to should be easy enough as it is all limited to mostly one class and a few functions within that class behind a check for _limited_. Let me know if you have any questions. I actually like this approach for calculating adjacent spaces better than the implementation in `Board` today.

Thank you very much for your review, I may not have time to deal with the comments in this pull request until the weekend.

非常感谢你的review, 我可能要到周末才有时间处理这个pr里面的评论

2020-12-21 13:50 UTC, Ronnoc commented on src/BoardRandomizer.ts
> +      this.oceans = oceans;
solving

2020-12-21 13:54 UTC, kberg commented
I'm reworking the Board classes. My advice is to keep working on this PR
without resolving merges - focus on a clear, tested and readable algorithm,
and I'll help with the last bit later.

>

2020-12-21 13:56 UTC, Ronnoc commented on src/BoardRandomizer.ts
> +        const idOrder = [];
Will be fixed in the next commit.

2020-12-21 13:56 UTC, Ronnoc commented on src/BoardRandomizer.ts
> +      this.bonuses = bonuses;
Will be fixed in the next commit

2020-12-21 13:57 UTC, Ronnoc commented on src/BoardRandomizer.ts
> +          if (row + 1 < 9) {
Will be fixed in the next commit

2020-12-21 13:58 UTC, Ronnoc commented on src/BoardRandomizer.ts
> +      for (let row = 0; row < 9; row++) {
Will be fixed in the next commit

2020-12-21 14:00 UTC, Ronnoc commented on src/BoardRandomizer.ts
> +          if (i > 0) adjIds.push(idx - 1); // left
Well, I think the current logic is okay.
When i=0, `i>0` is false, and it will not be pushed.
When row = 0, i = 1, `i> 0` is true, then it should also be pushed

2020-12-21 14:02 UTC, Ronnoc commented on src/BoardBuilder.ts
> +    private tilesPerRow: Array<number> = [5, 6, 7, 8, 9, 8, 7, 6, 5];
Will be fixed in the next commit

2020-12-21 14:03 UTC, Ronnoc commented on src/RandomBoardOptionType.ts
> +    NONE = 'No randomization',
Will be fixed in the next commit

2020-12-21 14:04 UTC, Ronnoc commented on src/components/CreateGameForm.ts
> +    isRandomBoardEnabled: function(): Boolean {
Will be fixed in the next commit

2020-12-21 14:05 UTC, Ronnoc commented on src/components/CreateGameForm.ts
> +      const component = (this as any) as CreateGameModel;
Will be fixed in the next commit

2020-12-21 14:05 UTC, Ronnoc commented on src/components/CreateGameForm.ts
> +        component.randomBoardOption = RandomBoardOptionType.LIMITED;
Will be fixed in the next commit

2020-12-21 14:06 UTC, Ronnoc commented on src/components/CreateGameForm.ts
> +        this.randomBoardOption = RandomBoardOptionType.NONE;
This option enables or disables random board option instead of choosing limited or unlimited.

2020-12-21 14:08 UTC, Ronnoc commented on src/components/CreateGameForm.ts
> +        return RandomBoardOptionType.LIMITED;
Will be fixed in the next commit

2020-12-21 14:10 UTC, Ronnoc commented on src/OriginalBoard.ts
> +    builder.setMustBeLandSpaces(SpaceName.NOCTIS_CITY, SpaceName.THARSIS_THOLUS, SpaceName.ASCRAEUS_MONS, SpaceName.ARSIA_MONS, SpaceName.PAVONIS_MONS);
card like `LUNA METROPOLIS`, `DAWN CITY` also `Place a City tile on the RESERVED AREA`.
so I think `MustBeLandSpaces` is better than `ReservedSpaces`.

2020-12-21 14:14 UTC, Ronnoc commented on src/BoardRandomizer.ts
> +    // calcualte how many tile adjacent to i is ocean
calculate will be fixed in the next commit.
In https://github.com/bafolts/terraforming-mars/pull/2089#discussion_r541840335, kberg asked me to change -1 to undefined.
The 0 here is also not good, because in the number index view of the board (0-60), 0 is a valid number for the index.

2020-12-21 14:14 UTC, Ronnoc commented on src/BoardRandomizer.ts
> +    // calcualte how many tile adjacent to i has plant
response similar to the ocean comment

2020-12-21 14:18 UTC, Ronnoc commented on src/BoardRandomizer.ts
> +          if (i + 1 < tilesInThisRow) adjIds.push(idx + 1); // right
Well, I think the current logic is okay.
When we are in the last row, the leftmost tile also has its adjacent space on the right.

2020-12-21 14:35 UTC, Ronnoc commented on src/RandomBoardOptionType.ts
> +    NONE = 'No randomization',
I copied the randomMA code before. If you want to change it, it may be better to change synchronously.
I'm not sure what to do on the client side.

2020-12-21 14:53 UTC, Ronnoc commented
> I'm reworking the Board classes. My advice is to keep working on this PR without resolving merges - focus on a clear, tested and readable algorithm, and I'll help with the last bit later.
> […](#)

Sorry, but I have merged main just now....

2020-12-21 14:55 UTC, Ronnoc commented on src/BoardRandomizer.ts
> +            if (i - minOffset < 0) adjIds.push(idx - minOffset); // upright
I will take time to do this in the next few days

2020-12-22 04:04 UTC, Ronnoc commented on src/BoardRandomizer.ts
> +            if (i - maxOffset + this.tilesPerRow[row - 1] >= 0) adjIds.push(idx - maxOffset); // upleft
Fixed in current submission.

2020-12-23 01:51 UTC, bafolts commented
@Ronnoc do you mind if I create a branch in `bafolts` named `update_shuffle` which this pull request can focus? Some of the requested changes I had were minimal but may have been lost in translation. Instead of the continual back and forth I think it would be quicker if I made the small changes in a pull request towards that branch instead of going directly to `main`. Does this work for you?

2020-12-23 03:50 UTC, Ronnoc commented
> @Ronnoc do you mind if I create a branch in `bafolts` named `update_shuffle` which this pull request can focus? Some of the requested changes I had were minimal but may have been lost in translation. Instead of the continual back and forth I think it would be quicker if I made the small changes in a pull request towards that branch instead of going directly to `main`. Does this work for you?

Ofcourse you can

2020-12-23 20:45 UTC, bafolts commented
@Ronnoc I updated the base branch to `bafolts:feature/update_shuffle` can you address the merge conflicts?

2020-12-26 02:28 UTC, Ronnoc commented
@bafolts merged

2020-12-28 01:03 UTC, bafolts approved these changes

2020-12-28 01:04 UTC, merged

2021-04-01 10:16 UTC, vsrisuknimit commented
@Ronnoc @bafolts do you know what became of this option? I think it is a great alternative for people who would like to play with a different map but not totally random.

2021-04-01 16:56 UTC, bafolts commented
The code is in the `feature/update_shuffle` branch. If there is still interest in it would need to rebase the branch to `main` and then put up pull request.

2021-04-01 17:16 UTC, vsrisuknimit commented
@Ronnoc are you interested in bringing this to the main repo? With unlimited option still available?