load games when needed from database
bafolts/terraforming-mars pull request #2092
Opened 2020-12-12 17:18 UTC by bafolts

Whenever the server starts up we currently load every game from the database into javascript memory. With the increasing number of games being played on the demo site we are running out of javascript memory. This change loads only the game id and player ids into javascript memory when the server is starting. Unless a game is requested we then don't bother wasting javascript memory on the game. The storing of game id and player id in memory is used to avoid constantly querying the database for situations which may results in 404 as this cheaper heroku instance doesn't have the greatest postgres database either.

Will add unit tests and then move this to a real PR.

2020-12-12 17:20 UTC, bafolts commented on server.ts
> +          // game was not found!
Need to have this return 404. Looking at this now this current version must not have worked if game wasn't found and would have returned the `gameToRebuild` prior to it being restored.

2020-12-12 18:08 UTC, kberg requested changes
There's a lot I like about this, but I'm putting on my extra-pedantic lenses for this one.

2020-12-12 18:08 UTC, kberg commented on src/database/GameLoader.ts
> +        this.loadGameIntoMemory(gameId, cb);
This is brittle. it assumes that calling loadPlayerIntoMemory occurs when loadGmeIntoMemory hasn't been called. Some of that is a naming issue, some of that is that we could solve a lot of this with Promises -- I think.

In the meantime, this probably works. I say probably because to be certain I have to read about when and how lGIM and lPIM are called, hence, context makes this brittle. A little flexibility here would go a long way. Or at minimum, clear documentation.

2020-12-12 18:08 UTC, kberg commented on src/database/GameLoader.ts
> +        this.loadGameIntoMemory(gameId, (game) => {
If this is happening in `onAllGamesLoaded` then all games are not loaded. Consider renaming this method to `onAllKeysLoaded`.

2020-12-12 18:08 UTC, kberg commented on src/database/GameLoader.ts
> +        this.loadGameIntoMemory(gameId, (game) => {
Also, if this APi is doing what it's doing, how does the entire PR fulfill its promise to only load games when needed?

2020-12-12 18:08 UTC, kberg commented on src/database/IDatabase.ts
> +     * @param cb called with game if exists
"called with game if exists, else err" ?

2020-12-13 02:13 UTC, bafolts commented on src/database/GameLoader.ts
> +        this.loadGameIntoMemory(gameId, cb);
In the updated version I tried to make this more idempotent. This became `loadPlayer` and always loads the player checking every map to see if it needs to. I haven't spotted it yet but it feels like this is another class hiding in here which if pulled out would make this instantly clearer. I added a queue of games and players that need to be loaded that get worked through one at a time. It gives preference to loading games as one game contains multiple players that would become available. I am attempting to avoid the situation where 5 players are waiting to take a turn while the server is restarting. These 5 players would all end up requesting their player id simultaneously and if we don't act on the requests in a queue we could end up re-loading the same game 5 times. Most of this comment I am typing I will put in class documentation as it may not be clear why all of this complexity is here.

2020-12-13 02:16 UTC, bafolts commented on src/database/GameLoader.ts
> +        this.loadGameIntoMemory(gameId, cb);
Once a game is up and running we never call out to the database except for saving state and undo operations. When heroku is restarting, the `server.ts` starts up and any "waiting for" request will query for their player id. When the data isn't available they have to wait until all of the game id and player ids have been loaded from the database. Once those are loaded we have to work through any request that happened to be waiting. Anyone starting a new game during this time shouldn't be impacted and will avoid all of this logic.

2020-12-13 02:19 UTC, bafolts commented on src/database/GameLoader.ts
> +        this.loadGameIntoMemory(gameId, (game) => {
I changed this in my recent push and got rid of `start`. Until any request for player or game is made we never hit the database.

2020-12-13 03:53 UTC, kberg commented
OK, I read your responses and it looks like you're mid-repair. Ping me when you feel like this is ready for another look.

2020-12-14 21:56 UTC, bafolts commented on server.ts
> +          // game was not found!
Ugh, still need to do this. It wasn't here before but makes sense to add.

2020-12-14 22:02 UTC, bafolts commented on server.ts
> -          gameLoader.addGame(gameToRebuild);
Ugh. I don't know if anyone even uses this feature, but my change wont work. At some point later in the UI this game ends up being created and the new version needs to be added to the map at that time. Very frustrating. I will have to add a `GameLoader::delete` to remove a game so that this can then add the game back with this new version.

2020-12-14 22:05 UTC, bafolts commented on server.ts
> -          gameLoader.addGame(gameToRebuild);
I need to address this prior to merging. This needs to update the copy of `Game` we have in the database. Will need a `GameLoader::delete` which removes our local copy in javascript so that on subsequent calls to `getByGameId` we pull the most recent version from the database into javascript memory.

2020-12-15 01:52 UTC, bafolts commented
OK. @kberg I think this is now ready. I added a `GameLoader::remove` so when we "reload" a game we can remove the copy in javascript and get fresh data from database.

2020-12-15 06:37 UTC, kberg reviewed
I'll need another pass to internalize most of the rest of this, but this looks like quite a good improvement.

2020-12-15 06:37 UTC, kberg commented on server.ts
> -import {Color} from './src/Color';
Already a massive improvement.

2020-12-15 06:37 UTC, kberg commented on server.ts
> +const gameLogs = new GameLogs();
Oh my goodness, seriously, this is getting better.

2020-12-15 06:37 UTC, kberg commented on server.ts
> +      GameLoader.getInstance().remove(game_id);
I haven't read the new `GameLoader` yet, but my instinct is that clearing the copy probably belongs as part of `getByGameId`, and possibly doesn't happen if the meat of `getByGameId` fails.

2020-12-15 06:37 UTC, kberg commented on server.ts
> -gameLoader.start(() => {
Huh. I'm very curious now.

2020-12-15 06:37 UTC, kberg commented on server.ts
> -gameLoader.start(() => {
I'm reading this like watching a murder mystery unfold.

No Color import? GameLogs doesn't need a GameLoader? A donut hole with a little donut inside it? With its own little donut hole?

2020-12-15 06:37 UTC, kberg commented on src/database/GameLoader.ts
> +  // player ids which we know exist mapped to game id
oh my gosh this documentation is fantastic.

2020-12-15 06:37 UTC, kberg commented on src/database/GameLoader.ts
> +      GameLoader.instance = new GameLoader();
Add `private constructor() { }` I think?

2020-12-15 06:37 UTC, kberg commented on src/database/GameLoader.ts
> +   * Determines if game is available in javascript
Why the short line length? /minor

2020-12-15 06:37 UTC, kberg commented on src/database/GameLoader.ts
> +        Database.getInstance().getGame(
For readability, how about sticking this in a private `loadGameFromDatabase` method?

2020-12-15 14:46 UTC, bafolts commented on src/database/GameLoader.ts
> +   * Determines if game is available in javascript
I seem to be a steam punk tech luddite. I work on a raspberry pi 4 model b with an old tiny monitor. This was a long line to me!

2020-12-15 14:48 UTC, bafolts commented on server.ts
> -gameLoader.start(() => {
This is similar to an onion, but instead of increasing tears while peeling deeper there is an ever increasing smile and feelings of joy.

2020-12-15 14:51 UTC, bafolts commented on server.ts
> +      GameLoader.getInstance().remove(game_id);
A second argument to `getByGameId` would work here. The argument would be `true` if you wanted to force a new copy from database.

2020-12-17 04:00 UTC, kberg commented on server.ts
> +      GameLoader.getInstance().remove(game_id);
> A second argument to `getByGameId` would work here. The argument would be `true` if you wanted to force a new copy from database.

Agree

2020-12-18 17:51 UTC, alrusdi commented
@kberg do you satisfied with current state of PR? Your change request is blocking it from merge.

2020-12-18 17:56 UTC, bafolts commented
I am working on his changes now.

2020-12-21 00:14 UTC, bafolts commented
@kberg the heroku server is running out of memory while starting up and trying to load games from memory. Is this good enough to approve?

2020-12-21 00:47 UTC, Lynesth commented on src/database/GameLoader.ts
> +  public has(gameId: GameId): boolean {
I'd rename this method to `isLoaded()`. It currently makes it pretty confusing with `this.games.has()`.
And then maybe add a `isPreloaded()` one that simply does `this.games.has()` (see comment below for reference)

2020-12-21 00:47 UTC, Lynesth commented on src/database/GameLoader.ts
> +  private loadAllGames(): void {
Could we rename this as well ?
It's not doing the same thing as `loadGame` at all, so probably something like `preloadAllGames()` would be better ?

2020-12-21 01:10 UTC, kberg commented on src/database/GameLoader.ts
> +  private readonly gameRequests: Array<[GameId, boolean, LoadCallback]> = [];
```
// requests for games that are waiting to load
// [idToLoad, bypassCache, callback]
```

2020-12-21 01:11 UTC, kberg approved these changes
One comment to clarify the boolean. But that's optional. This looks good to go. Good work!

2020-12-21 03:01 UTC, bafolts commented on src/database/GameLoader.ts
> +  public has(gameId: GameId): boolean {
I meant to remove this. Was needed before refactor. Gone now.

2020-12-21 03:06 UTC, merged