Updated SolarFarm.ts
bafolts/terraforming-mars pull request #2136
Opened 2020-12-17 16:06 UTC by sienmich

Option 2. from https://github.com/bafolts/terraforming-mars/issues/2134

2020-12-17 17:44 UTC, chosta commented
please check my comment in #2134

2020-12-18 18:37 UTC, chosta requested changes
Sorry to go back and forth on this but I went out and tried out all the options myself and now feel that the option should be the best in this case. We have an asterix that makes the player read the text and decide what to do.
please, go for 
`pb.energy(1).slash().plants(1)`

2020-12-18 19:09 UTC, sienmich commented
No problem :)
Done

2020-12-19 16:57 UTC, chosta approved these changes

2020-12-19 18:15 UTC, merged