Add warning property to cards
bafolts/terraforming-mars pull request #2170
Opened 2020-12-23 03:06 UTC by Lynesth

_Disclaimer: I don't like Vue. This is working and doesn't seem_ too much _but please @chosta or @alrusdi, take a look and see if there's a better way to take care of the frontend part._

This is the first part of the implementation to improve Reds taxes calculation which will then lead to a full cards rewrite (hopefully).
This PR just adds a new property called `warning` to ICard that can be displayed below the card when selected.

The goal is to assign some meaningful message to that property during a card's `canAct` or `canPlay` to give some info to the user. No card is using it at the moment. It looks like this (don't pay attention to the text itself, it was just to test it):

![firefox_2020-12-23_14-05-45](https://user-images.githubusercontent.com/5318258/102954611-fb793d80-4527-11eb-9aa6-d1e5b3ba784b.png)

It is related to #1642.

2020-12-23 03:57 UTC, kberg commented
As far as I'm concerned this is a net improvement, and so ought to go in. It can most definitely be improved.

2020-12-23 03:58 UTC, kberg commented
That said, there's a discussion about this topic -- and there I raised my concern about a slippery slope. But this is good.

2020-12-23 04:20 UTC, Lynesth commented
> I raised my concern about a slippery slope.

That's why this PR only gives the tool but doesn't use it yet.
It will be up to us to approve the uses we made of it to prevent sliding down that slope ;)

2020-12-23 07:49 UTC, alrusdi requested changes

2020-12-23 07:49 UTC, alrusdi commented on src/cards/ICard.ts
> +    warning?: string;
This warning must implement Message interface to be translatable to other-than-english languages

2020-12-23 07:49 UTC, alrusdi commented on src/components/SelectHowToPayForCard.ts
> +    <div v-if="hasCardWarning()" class="card-warning">{{ cardWarning }}</div>
Please add v-i18n property

2020-12-23 07:50 UTC, alrusdi commented
@Lynesth what exact points against Vue?

2020-12-23 15:12 UTC, Lynesth commented
> @Lynesth what exact points against Vue?

I guess simply the fact that I don't know it and usually spend way too much times doing what sounds like simple things to do.

2020-12-23 15:39 UTC, kberg commented on src/cards/ICard.ts
> +    warning?: string;
Thanks, I was just coming here to make that comment.

2020-12-23 16:12 UTC, bafolts requested changes
I would send the warning through `PlayerInputModel` with the `warning` property and not associate it with one card. It makes sense that there would be a warning regarding input from a player but not a warning regarding one card. The warning only makes sense through the context of player input. The error we throw today "Not enough cards selected" should also use this `PlayerInputModel` warning property.

2020-12-24 03:44 UTC, kevinb9n commented
Two of us in the family play a LOT, and I asked the other today if there was one thing she wished would change the most, and this happened to be the one she brought up.

I think you can hold out against the slippery slope IF you have a clear criterion that you try to converge toward. Something like: "there is at least one instruction on this card that will provably cause NO change to the game state". Not "a state change that might not matter", etc.

2020-12-24 03:50 UTC, Lynesth commented
@bafolts
Since these warnings are card dependent, how exactly do you want this to be done, I don't get it.
They are printed before you validated the input and they don't prevent you from validating the input.

2020-12-24 04:25 UTC, Lynesth commented on src/cards/ICard.ts
> +    warning?: string;
Did it and used `$t` to translate it, like we do for the title.

2020-12-24 07:19 UTC, alrusdi approved these changes
Now it is seems to be correct to me.

2020-12-24 08:23 UTC, chosta commented on src/styles/cards.less
> +    color: #d73a49;
Can you, please, add a variable in variables.less called `@color_error` and use it as a variable in the class .card-warning. I'll probably do a PR soon to add some more such variables and refactor the existing by using variables instead of hardcoded values.

2020-12-25 01:08 UTC, merged