[WIP] Standard projects as cards
bafolts/terraforming-mars pull request #2188
Opened 2020-12-25 19:22 UTC by sienmich

Idea from https://github.com/bafolts/terraforming-mars/issues/2185

Currently it looks like this:
![Screenshot from 2020-12-25 20-19-14](https://user-images.githubusercontent.com/19472604/103141028-d1be4300-46ee-11eb-94cc-9d80fea2fabf.png)

2020-12-25 20:46 UTC, kevinb9n commented
Looking good!
It looks like it's using greenery_no_o2 instead of greenery.png?

Not sure about a banner color, but yellow is sorta associated with corporation cards already. I thought of using gray because it also indicates neutral-ness (like gray delegates, sorta).

2020-12-25 20:52 UTC, kevinb9n commented
Only asking if it happens to be easy:
Can *some* symbol like maybe an asterisk go in the expansion symbol location for Buffer Gas, just as a reminder that it won't always be there? Feel free to ignore.

2020-12-25 22:09 UTC, kberg reviewed
I'll review more later. Good first step.

2020-12-25 22:09 UTC, kberg commented on src/CardFinder.ts
> +    public standardProjectsFromJSON(cards: Array<ICard | CardName>): Array<StandardProjectCard> {
Since standard projects are fully computable by gameOptions, I would not use serialization / deserialziation at all. Just rebuild the standard projects from the game options.

2020-12-25 22:09 UTC, kberg commented on src/CardName.ts
> +    STANDARD_GREENERY = 'Greenery',
Keep the same order that the rest of the cards have, which I believe is mostly by expansion. Unless I'm mistaken.

2020-12-25 22:09 UTC, kberg commented on src/Dealer.ts
> +        standardProjects: this.standardProjects.map((c) => c.name),
I like THIS.

2020-12-25 22:09 UTC, kberg commented on src/SerializedDealer.ts
> +    standardProjects: Array<IProjectCard | CardName>;
Same - this can entirely be removed.

2020-12-25 22:09 UTC, kberg commented on src/SerializedPlayer.ts
> -    powerPlantCost: number;
Why is that?

2020-12-25 22:09 UTC, kberg commented on src/cards/StandardCardManifests.ts
> +import {BufferGas} from './standardProjects/BufferGas';
This belongs in the expansion the standard project comes from.

2020-12-25 22:09 UTC, kberg commented on src/cards/StandardCardManifests.ts
> +import {PowerPlantStandard} from './standardProjects/PowerPlant';
I'm pretty confident these two projects can be conjoined into one.

2020-12-25 23:03 UTC, sienmich commented on src/CardFinder.ts
> +    public standardProjectsFromJSON(cards: Array<ICard | CardName>): Array<StandardProjectCard> {
Agree, fixed

2020-12-26 00:09 UTC, sienmich commented on src/cards/StandardCardManifests.ts
> +import {BufferGas} from './standardProjects/BufferGas';
You mean the BufferGas? Not really. It was introduced in Prelude, but it is meant to be in game no mater if you are using the prelude cards or not (if you don't use them, then solo mode is 14 turns, but still has the Buffer Gas). Right?

2020-12-26 00:12 UTC, sienmich commented on src/cards/StandardCardManifests.ts
> +import {PowerPlantStandard} from './standardProjects/PowerPlant';
You mean the two power plants? I guess you are right, normal cards don't change their costs yet with discounts. I'll delete the second one

2020-12-26 00:28 UTC, sienmich commented on src/cards/StandardCardManifests.ts
> +import {PowerPlantStandard} from './standardProjects/PowerPlant';
Done

2020-12-26 00:33 UTC, sienmich commented on src/SerializedPlayer.ts
> -    powerPlantCost: number;
Right now the condition if a player is thorgate is checked only in `PowerPlant.ts` (with `player.corporationCard?.name === CardName.THORGATE`), so there is no point to keep for every player this `powerPlantCost` variable imo

2020-12-26 00:43 UTC, sienmich commented on src/CardName.ts
> +    STANDARD_GREENERY = 'Greenery',
At the beginning of this file it is sorted by expansion and alphabetically, from the middle it's going more and more random order. I think it's nice to have them together, as they differ from normal cards more than normal cards differ between expansions. I ordered them by the price. Ok?

2020-12-26 01:33 UTC, sienmich commented
Ok, finished :smile:
Reviewers are welcome. Would you like some testing server?

About those colors: I'm far from a graphic. I tried some grays but they were really ugly. For me those goldy yellows are quite interesting. Those Standard Projects seem very powerful now :) I'm very open to some color propositions, best with two color hexes. Maybe even `#dev-topics` pool?

2020-12-26 04:31 UTC, kberg commented
> Ok, finished 
> Reviewers are welcome. Would you like some testing server?
> 
> About those colors: I'm far from a graphic. I tried some grays but they were really ugly. For me those goldy yellows are quite interesting. Those Standard Projects seem very powerful now :) I'm very open to some color propositions, best with two color hexes. Maybe even `#dev-topics` pool?

The colors are two things:
1. Great
2. Good enough. Launch as is.

2020-12-26 04:41 UTC, kberg reviewed
Wondering just how much this round of comments are helpful or not.

I'd like to try to remove the complexity out of Dealer, which I think is possible, and I think really will simplify what you're doing. Perhaps this weekend I can take a crack at it, if you think what I'm suggesting is either unclear or bonkers.

Leave the cards in the Manifests, that's a good thing (I've secretly wanted CardManifest to really be an `ExpansionManifest` which might contain things like Colonies, eg, so whether or not these are cards, I see them as belonging there.

2020-12-26 04:41 UTC, kberg commented on src/Dealer.ts
> +    public standardProjects: Array<StandardProjectCard> = [];
Why exactly would one need to _deal_ from a deck of standard projects? I bet the answer to that question is "it doesn't, actually" and this implementation can be further simplified.

2020-12-26 04:41 UTC, kberg commented on src/Dealer.ts
> +      function addToDecks(manifest: CardManifest, standardProjectsOnly = false) {
Why is a standardProjectsOnly parameter necessary?

2020-12-26 04:41 UTC, kberg commented on src/Player.ts
> +    if (game.getPlayers().length !== 1) {
This probably should be done at game set-up.

2020-12-26 04:41 UTC, kberg commented on src/Player.ts
> +      projects.sort((a, b) => a.cost - b.cost).filter((card) => card.canAct(this, game)),
This sort is probably debateable. I'd rather see a defined order. Since Standard Projects are small and really won't change much, we can define a hard-coded order. That's kind of my preference.

2020-12-26 07:10 UTC, Lynesth commented
Hmm, I'm a bit like @kberg here.
I understand wanting to make them look like cards in the front end, but why are you making them cards in the back end ? That's not what they are and it's really confusing me.

2020-12-26 14:40 UTC, sienmich commented
> why are you making them cards in the back end ?
@Lynesth, my point of view:
For example, there may come a time (maybe soon :smile:) when somebody would like to rewrite how `canPlay()` and  `canAct()` are working to include all "ocean placement bonus vs reds policy" scenarios. Having more common interfaces in our repo makes everything easier to change and adapt, coding becomes simpler. `ICard` fits perfectly for SP,  they have their layout generated from `metadata`, they have their `name`, `play/action` and `canAct/canPlay` methods. I think that having them as cards is much cleaner than 400 lines of `if` instructions in `Player.ts`.
I know that SP are not cards in the board game, but the board version is managed by humans. For us it will be easier in future to have them as cards.
Would you agree? :)

2020-12-26 15:29 UTC, kberg commented
For the record, I like that they look and act like cards. I'm just saying
the similarity ends there.

>

2020-12-27 00:14 UTC, sienmich commented on src/Dealer.ts
> +    public standardProjects: Array<StandardProjectCard> = [];
"it doesn't, actually" :smile:

However I see this that way:
We need some structure / object which loads all SPs and stores them. There are two options:
1. I write new structure for SP only
2. I use the Dealer.
3. Eventually I could split the Dealer into CardLoader and Dealer, then SP could only use the CardLoader.
I think 2. is the simpler one - less redundant code like loading the cards, or choosing which expansion to include.
Would you agree? If not I can change, no problem :)

2020-12-27 00:27 UTC, sienmich commented on src/Player.ts
> +    if (game.getPlayers().length !== 1) {
I agree, fixed

2020-12-27 00:31 UTC, sienmich commented on src/Player.ts
> +      projects.sort((a, b) => a.cost - b.cost).filter((card) => card.canAct(this, game)),
I think sort is not that bad, that's the order in original game. Hard coding sounds like additional unnecessary code for me. However we don't need to sort them every time, moved that to game creation.

2020-12-27 00:33 UTC, sienmich commented on src/Dealer.ts
> +    public standardProjects: Array<StandardProjectCard> = [];
Maybe 3 is not that bad after all, i'm willing to choose 3 if u want :)

2020-12-27 00:38 UTC, sienmich commented on src/Dealer.ts
> +      function addToDecks(manifest: CardManifest, standardProjectsOnly = false) {
Because SPs are not being serialized I need to load them with every game creation from card manifests.
Like so:
```
    public static deserialize(d: SerializedDealer, gameOptions: GameOptions): Dealer {
      const dealer = new Dealer();
   ...
      dealer.discarded = cardFinder.cardsFromJSON(d.discarded);
      dealer.preludeDeck = cardFinder.cardsFromJSON(d.preludeDeck);
      dealer.standardProjects = this.newInstance(gameOptions, true).standardProjects;
      return dealer;
    }
```
To speed things up I'm loading only SPs, not every card in game.
I'm not sure about that one. Is there a better way?

2020-12-27 01:19 UTC, bafolts commented on src/CardFinder.ts
> +    public standardProjectsFromJSON(cards: Array<ICard | CardName>): Array<StandardProjectCard> {
If this is fixed is this function still needed?

2020-12-27 01:23 UTC, bafolts commented on src/Dealer.ts
> +      function addToDecks(manifest: CardManifest, standardProjectsOnly = false) {
I would not wedge standard projects in through `Dealer`. The standard projects most likely make more sense associated with `Board` or `Game` than the `Dealer`.

2020-12-27 01:29 UTC, sienmich commented on src/Dealer.ts
> +      function addToDecks(manifest: CardManifest, standardProjectsOnly = false) {
Ok. I will split the Dealer into Dealer and CardLoader. I will use the CardLoader part but I'll store SPs in Game.

2020-12-27 01:29 UTC, bafolts commented on src/Player.ts
> -  private buildPowerPlant(game: Game): PlayerInput {
Regardless of any other comments I leave on this pull request this change is great. Moving these into another file was a long time coming.

2020-12-27 01:31 UTC, sienmich commented on src/Player.ts
> -  private buildPowerPlant(game: Game): PlayerInput {
Thanks! :D

2020-12-27 01:37 UTC, bafolts commented on src/Dealer.ts
> +      function addToDecks(manifest: CardManifest, standardProjectsOnly = false) {
The `ALL_CARDS_MANIFESTS` should provide access to the standard projects. A `CardLoader` may be overkill but I can never complain if there is less logic in `Game`.

2020-12-27 01:50 UTC, bafolts commented on src/Player.ts
> -  public powerPlantCost: number = 11;
I can't complain with this going away. When first writing all the project cards way back when I often tried to avoid explicitly calling out cards for game logic. With where the project is now I will always be in favor of using less memory in this way when we can calculate the value from another stored value.

2020-12-27 01:57 UTC, bafolts commented on src/Dealer.ts
> +      const manifests = [
You shouldn't need to type cast if you use `const manifests: Array<[boolean, CardManifest>] = []`

2020-12-27 02:03 UTC, sienmich commented on src/Dealer.ts
> +      const manifests = [
Thanks, I was just googling this one :)

2020-12-27 02:14 UTC, bafolts commented on src/cards/standardProjects/BufferGas.ts
> +    let cost = this.cost;
Instead of removing this manually I would just return false here if not a single player game. This should remove complexity in game setup with having to remove this project.

2020-12-27 02:18 UTC, sienmich commented on src/cards/standardProjects/BufferGas.ts
> +    let cost = this.cost;
Cool, done

2020-12-27 02:27 UTC, bafolts commented on src/cards/standardProjects/PowerPlant.ts
> +      player.megaCredits += 3;
Giving 3 mega credits after paying for the project is different than the cost being 3 less. If you only have 8 mega credits the `canAct` will return true and this could very well happen to work where we subtract megacredits to a negative value only to then add 3 here to return a player to 0. Instead of changing in this way I would make the `getPowerPlantCost` a public getter on `Player`.

```
public Player {
   get powerPlantCost(): number {
     return this.corporationCard?.name === CardName.THORGATE ? 8 : 11;
   }
}
```

2020-12-27 02:32 UTC, bafolts commented on src/cards/standardProjects/StandardProjectCard.ts
> +    abstract canAct(player: Player, game: Game): boolean
I am not familiar with the reds ruling party but if using this base class could consider adding the cost there. Is it specific to certain projects or based on a property like `cost` that could be calculated? If it is based on the `name` then it wouldn't make sense to put here.

2020-12-27 02:35 UTC, bafolts commented on src/cards/standardProjects/StandardProjectCard.ts
> +    abstract actionEssence(player: Player, game: Game): void
This can be `protected` as far as I can tell.

2020-12-27 02:36 UTC, bafolts commented on src/components/card/Card.ts
> -      if (this.isCorporationCard()) {
Did something change where the `isCorporationCard` block can now be removed?

2020-12-27 02:39 UTC, bafolts commented on src/styles/cards.less
> -.card-colony {
Did this move somewhere? Surprised to see this being removed.

2020-12-27 02:40 UTC, bafolts commented on src/styles/cards.less
> +    width: calc(100% + 12px);
Did this `width` and `top` need to change? This will impact more than only the standard project cards being added. What did this change visually? With enough changing in this pull request may be better to make this change separately.

2020-12-27 02:47 UTC, bafolts requested changes
I had a few comments and questions about stuff which seemed like they may have been removed by mistake. Similar to @kberg I also think we should move the complexity out of `Dealer` as the list of standard projects is static for the most part. This seems very close. We didn't have unit tests prior to this. With these standard projects moving into their own classes it should be much easier to unit test them. If unit tests not added before merging we should make an issue to write unit tests for these.

2020-12-27 03:02 UTC, Lynesth commented
> Having more common interfaces in our repo makes everything easier to change and adapt, coding becomes simpler.

I won't disagree with that, but the only thing standard projects would have from `ICard` are `name`, `canAct` and `action`.
My point is that a `Bike` is not a `Car` and wouldn't be lumped with them or be made part of a `CarDealer` just because it can be use as a transportation mean and has wheels. An underlying interface/class that both implement/extend from would most likely be made in that case.

Nevertheless, I would keep each of them as their own class, like you did, since this is a good thing to remove them from Player. 👍

2020-12-27 12:33 UTC, sienmich commented on src/styles/cards.less
> -.card-colony {
It was unused for a while.
There was also a conflict. SP Colony automatically is getting `.card-colony` class, so removing it was a fix.

2020-12-27 12:38 UTC, sienmich commented on src/styles/cards.less
> +    width: calc(100% + 12px);
I changed that in a way, that this orange selection tool works both on normal cards and SPs (which are smaller).
Without this change the selection box was always normal size, so was really ugly with SPs.

2020-12-27 12:42 UTC, sienmich commented on src/components/card/Card.ts
> -      if (this.isCorporationCard()) {
This class (`card-corp`) was unused

2020-12-27 12:44 UTC, sienmich commented on src/cards/standardProjects/StandardProjectCard.ts
> +    abstract actionEssence(player: Player, game: Game): void
Agree, I'll change that

2020-12-27 12:49 UTC, sienmich commented on src/cards/standardProjects/StandardProjectCard.ts
> +    abstract canAct(player: Player, game: Game): boolean
You mean to automatize that paying additional 3 MC? I agree so much. However that's how every other card in game is currently coded, it's a thing for another PR.

2020-12-27 14:51 UTC, sienmich commented on src/cards/standardProjects/StandardProjectCard.ts
> +    abstract actionEssence(player: Player, game: Game): void
Done

2020-12-27 14:55 UTC, sienmich commented
Allright, the Dealer has been split into Dealer and CardLoader. Now the Dealer is created from a CardLoader. SPs are stored in Game (just `public standardProjects: Array<StandardProjectCard>;`) and are loaded also using the CardLoader. I agree this is much cleaner than with the Dealer only.
@kberg, @bafolts

2020-12-27 15:18 UTC, sienmich commented on src/cards/standardProjects/PowerPlant.ts
> +      player.megaCredits += 3;
Fixed

2020-12-27 15:23 UTC, sienmich commented on src/CardLoader.ts
> +      this.addToDeck(deck, getter(manifest));
I'm not js native speaker. `getCards` is meant to be called like `getCards(CardLoader.getCorporationCards)`. Is there a better way to do this?

2020-12-27 21:45 UTC, bafolts commented on src/Game.ts
> +    game.standardProjects = cardLoader.getCards(CardLoader.getStandardProjects).sort((a, b) => a.cost - b.cost);
The `standardProjects` property can be set within the constructor. The `gameOptions` is provided as an argument to the `Game` constructor.

2020-12-27 21:46 UTC, bafolts commented on src/Game.ts
> +  public standardProjects: Array<StandardProjectCard> = [];
If this is set from within the constructor you shouldn't need to set it to an empty array. It will be populated once the constructor has finished executing.

2020-12-27 21:52 UTC, bafolts commented on src/CardLoader.ts
> +        deck = deck.filter((card) => ![...this.gameOptions.cardsBlackList].includes(card.name));
`cardsBlackList` is an array and according to it's typedef it will be defined. The check for it being a truthy value is unnecessary. As it is already an array pushing it to another array is also unnecessary. This can be simplified to:

```
deck = deck.filter((card) => this.gameOptions.cardsBlackList.includes(card.name) === false);
```

2020-12-28 01:02 UTC, sienmich commented on src/Game.ts
> +    game.standardProjects = cardLoader.getCards(CardLoader.getStandardProjects).sort((a, b) => a.cost - b.cost);
Right, fixed

2020-12-28 01:02 UTC, sienmich commented on src/Game.ts
> +  public standardProjects: Array<StandardProjectCard> = [];
Agree

2020-12-28 01:03 UTC, sienmich commented on src/CardLoader.ts
> +        deck = deck.filter((card) => ![...this.gameOptions.cardsBlackList].includes(card.name));
True, thanks

2020-12-28 02:52 UTC, bafolts commented
As 45 files have changed here I ran out of steam reviewing today. I will finish looking at this tomorrow. I seem to be only spotting last minute minor changes at this point.

2020-12-28 18:14 UTC, bafolts requested changes
OK. This time I attempted to leave all my comments at once. I am memory obsessed and this change will be adding a property to `Game` so runs the risk of using more memory per game. We sometimes run a thousand games on the terraforming-mars.herokuapp.com per day. On any given day I would say 100 - 1000 games run. We are already using too much memory.

With that in mind I would only change two more things with this PR:

1. Use singletons for the standard project classes. This will ensure we only have one copy of these in memory and we don't intend these to be used in any other way than this. Since `ICardFactory` is assuming that `Factory` always provides a new copy of the card we will need to modify `ICardFactory`. I would add an optional `Instance` that if not undefined returns that instance.

2. Avoid storing `standardProjects` on `Game`. This list can be calculated each time it is needed from `game.gameOptions` using `CardLoader`.

2020-12-28 20:42 UTC, sienmich commented on src/CardLoader.ts
> +      this.addToDeck(deck, getter(manifest));
Thanks!

2020-12-28 21:00 UTC, sienmich commented on src/cards/venusNext/VenusCardManifest.ts
> +    {cardName: CardName.STANDARD_AIR_SCRAPPING, Factory: AirScrapping},
@bafolts 
Ok. From what I understand if you want to have `Factory: AirScrapping.getInstance`, then I need to change  
`Factory: new () => T;` into `Factory: new () => T | () => T;`. Am I right?

2020-12-28 21:04 UTC, sienmich commented on src/cards/venusNext/VenusCardManifest.ts
> +    {cardName: CardName.STANDARD_AIR_SCRAPPING, Factory: AirScrapping},
Putting that `.getInstance()` in every card would create a lot of unnecessary code. I don't see a way to make it once in some `Card` class.
However I came up with this solution:
```ts
export function sharedObject<T>(Obj: new () => T): () => T {
  class sharedObject {
    public constructor() { }

    private static instance?: T = new Obj();

    public static getInstance(): T {
      if (sharedObject.instance === undefined) {
        sharedObject.instance = new Obj();
      }
      return sharedObject.instance;
    }
  }
  return sharedObject.getInstance;
}
```
Does it make sense to you? Then we can do `Factory: sharedObject(AirScrapping)`. Still requires changing Factory type, as above. And that change is big. Maybe I'll open next PR?

2020-12-28 21:15 UTC, bafolts commented on src/cards/venusNext/VenusCardManifest.ts
> +    {cardName: CardName.STANDARD_AIR_SCRAPPING, Factory: AirScrapping},
Doing that in a separate PR should be fine. The memory difference should be equivalent to less than 10 cards added. I could work on that change. First thought of it today while reviewing this PR and it would go a long way into reducing memory usage as most cards don't need to have separate instances created.

2020-12-28 21:23 UTC, bafolts approved these changes

2020-12-28 21:24 UTC, bafolts commented on src/cards/venusNext/VenusCardManifest.ts
> +    {cardName: CardName.STANDARD_AIR_SCRAPPING, Factory: AirScrapping},
As the standard projects are not stored in memory on `Game` this shouldn't be an issue anymore anyway. They will get created and then garbage collected after used.

2020-12-28 21:24 UTC, merged

2020-12-28 21:25 UTC, sienmich commented on src/cards/venusNext/VenusCardManifest.ts
> +    {cardName: CardName.STANDARD_AIR_SCRAPPING, Factory: AirScrapping},
Agree, all green cards for sure.

2020-12-28 21:26 UTC, bafolts commented on src/cards/venusNext/VenusCardManifest.ts
> +    {cardName: CardName.STANDARD_AIR_SCRAPPING, Factory: AirScrapping},
Will need an elegant way to implement it. Most likely some thing on the card manifest or card factory can store it if we see the card doesn't have a resource or some other property that would be tracking state.