Replace saveGameState with saveGame. This moves lastSaveId management into the datbase implementation.
bafolts/terraforming-mars pull request #2213
Opened 2020-12-29 06:46 UTC by kberg

The variations between the two database implementations is minor, but there is starting to look like enough that I might suggest a bridge design pattern to further isolate shared state that exists between the game and the database.

2020-12-29 06:53 UTC, Lynesth requested changes

2020-12-29 06:53 UTC, Lynesth commented on src/database/SQLite.ts
> +    );
Need to increment game.lastSaveId here as well.

2020-12-29 06:53 UTC, Lynesth commented on src/Game.ts
> +     * TODO(kberg): not sure what to do with this comment.
You can remove it from here and make a not in the databases' saveGame methods that the lastSaveId increment must happen after the save so that it is not moved. from there.

2020-12-29 07:04 UTC, kberg commented on src/database/SQLite.ts
> +    );
Good catch.

2020-12-29 07:09 UTC, kberg commented on src/Game.ts
> +     * TODO(kberg): not sure what to do with this comment.
> You can remove it from here and make a note in the databases' `saveGame` methods that the `lastSaveId` increment must happen after the save so that no one inadvertently moves it.

Done, thanks.

2020-12-30 15:17 UTC, Lynesth approved these changes

2020-12-30 15:20 UTC, merged