Added checkMinRequirements and checkMaxRequirements
bafolts/terraforming-mars pull request #2216
Opened 2020-12-29 11:09 UTC by Lynesth

It's pretty easy to forget to add/substract `player.getRequirementsBonus()` when checking for global requirements or to forget that you need to multiply Venus and Temperature by 2.

Anyway, less random comparisons, 2 new methods to take care of that.

All tests pass properly but, when reviewing, please make sure once more that I didn't invert a Min/Max somewhere (should be fine, but who knows).

2020-12-29 18:44 UTC, nwai90 approved these changes

2020-12-30 02:38 UTC, bafolts requested changes

2020-12-30 02:38 UTC, bafolts commented on src/Game.ts
> +    } else { // parameter === GlobalParameter.VENUS
Instead of the comment I would check that `else if (parameter === GlobalParameter.VENUS)`. In the case we were to hit the final `else` this could log a warning and `return false`. Logging that we were provided an unsupported `GlobalParameter`.

2020-12-30 07:21 UTC, Lynesth commented on src/Game.ts
> +    } else { // parameter === GlobalParameter.VENUS
Good call, I'll do that.

2020-12-30 21:27 UTC, kberg approved these changes
A good change.

2020-12-30 21:27 UTC, kberg commented on src/cards/base/CloudSeeding.ts
> +        game.checkMinRequirements(player, GlobalParameter.OCEANS, 3) &&
I suggest `meetsMinRequirements`.

2020-12-31 00:55 UTC, bafolts approved these changes

2020-12-31 04:52 UTC, Lynesth commented on src/cards/base/CloudSeeding.ts
> +        game.checkMinRequirements(player, GlobalParameter.OCEANS, 3) &&
Feel free to sed it everywhere :p
I prefer merging this now before @bafolts forces me to fix hundreds of merge conflicts.

2020-12-31 04:56 UTC, merged