Improved spending heat with StormCraftIncorporated
bafolts/terraforming-mars pull request #2220
Opened 2020-12-29 16:41 UTC by sienmich

2020-12-29 16:43 UTC, sienmich commented on src/Player.ts
> +      (this.isCorporation(CardName.STORMCRAFT_INCORPORATED) && (this.getResourcesOnCorporation() * 2) + this.heat >= 8);
```suggestion
      (this.isCorporation(CardName.STORMCRAFT_INCORPORATED) && (this.getResourcesOnCorporation() * 2) + this.heat >= amount);
```

2020-12-30 21:19 UTC, kberg reviewed
Without looking terribly closely, I think this seems reasonable. Have you done anything to verify its correctness besides the unit tests? (might be enough, I'm just asking.)

2020-12-30 21:19 UTC, kberg commented on src/Player.ts
> +  public canSpendHeat(amount: number) {
What about `availableHeat: number` instead of `canSpendHeat(number): boolean`?

2020-12-30 21:19 UTC, kberg commented on src/Player.ts
> +      return (<StormCraftIncorporated> this.corporationCard).spendHeat(this, amount, cb);
It looks as if spendHeat can be static. /shrug. Whatever we do, I'd love to see Helion's behavior be similar to this one, if possible.

2020-12-30 21:19 UTC, kberg commented on src/Player.ts
> +  public canSpendHeat(amount: number) {
In fact, one of the things I'd like to look at doing is hiding all the raw resource counts behind getters (availableHeat(), availableSteel(), steelProduction(). etc.) /shrug

2020-12-31 00:17 UTC, sienmich commented on src/Player.ts
> +      return (<StormCraftIncorporated> this.corporationCard).spendHeat(this, amount, cb);
I don't understand that one. How this could be static? It subtracts heat (and sometimes floaters) from a player. We have `this.isCorporation`, `this.heat`, and so on.

2020-12-31 00:19 UTC, sienmich commented on src/Player.ts
> +  public canSpendHeat(amount: number) {
Ok, fixed

2020-12-31 00:20 UTC, sienmich commented
> Without looking terribly closely, I think this seems reasonable. Have you done anything to verify its correctness besides the unit tests? (might be enough, I'm just asking.)

I did't, but there are a lot of test checking spending heat already, it should be working good :)

2020-12-31 00:30 UTC, kberg commented on src/Player.ts
> +      return (<StormCraftIncorporated> this.corporationCard).spendHeat(this, amount, cb);
Um, I was referring to `spendHeat` but I think it's a bad idea.

2020-12-31 00:30 UTC, kberg commented on src/Player.ts
> +  public canSpendHeat(amount: number) {
:pray: thanks

2020-12-31 00:31 UTC, kberg commented
I just ate a heavy dinner, so I'm feeling nappish. Wrong time to review a PR. I'll check soon. This is a good change. Thank you!

2021-01-04 23:38 UTC, sienmich commented
> I just ate a heavy dinner, so I'm feeling nappish. Wrong time to review a PR. I'll check soon. This is a good change. Thank you!

Just pinging. Hope your nap was good :smile:

2021-01-05 06:13 UTC, kberg commented
> > I just ate a heavy dinner, so I'm feeling nappish. Wrong time to review a PR. I'll check soon. This is a good change. Thank you!
> 
> Just pinging. Hope your nap was good

What? Huh? Oh, I just woke up.

I mean, um, sorry. Will check tomorrow.

2021-01-05 07:55 UTC, Lynesth requested changes

2021-01-05 07:55 UTC, Lynesth commented on src/cards/colonies/StormCraftIncorporated.ts
> +        player.removeResourceFrom(player.corporationCard as ICard, floaterAmount);
Please also check that the player isn't overspending:
- 3 floaters to pay 5 is ok.
- 3 floaters to pay 6 is ok.
- 3 floaters + 1 heat to pay 5 isn't.
- 3 floaters + 1 heat to pay 6 isn't either.

2021-01-05 20:10 UTC, sienmich commented on src/cards/colonies/StormCraftIncorporated.ts
> +        player.removeResourceFrom(player.corporationCard as ICard, floaterAmount);
Ok, done

2021-01-05 23:10 UTC, Lynesth approved these changes

2021-01-05 23:11 UTC, kberg commented
I defer to @Lynesth, thank you.

2021-01-05 23:11 UTC, merged