(WIP) An untested implentation of Clone
bafolts/terraforming-mars pull request #2223
Opened 2020-12-29 22:56 UTC by kberg

What do people think of this kind of object traversal to clone a game? What do you see as major areas to look out for?

2020-12-30 16:01 UTC, bafolts commented on server.ts
> +            throw new Error(`game ${gameOptions.clonedGamedId} not cloned`); // how to nest errs in the way Java nests exceptions?
This error will end up being thrown on the callstack from where this callback is called within `Cloner`. If it went uncaught there it would end up as an uncaught exception which would stop the node process. Since we are in `server` it may make more sense to return a 404 status code since there wasn't an error but we most likely didn't find the game. As we didn't get an error some 400 level response code would make sense.

2020-12-30 21:04 UTC, bafolts commented on src/database/Cloner.ts
> +        cb(err, undefined);
If we are here `err` will be `undefined`. May be easier to read to pass `cb(undefined, undefined)`. This represents that we had no error pulling the data but were unable to find the game.

2020-12-30 22:20 UTC, bafolts commented on src/database/Cloner.ts
> +    if (obj === undefined || obj === null || typeof obj !== 'object') {
I don't think this needs to check that `typeof obj !== 'object'`. The error from node I read claims that only `undefined` and `null` can't be converted.

```
> Object.entries({})
[]
> Object.entries(undefined)
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
```

2020-12-30 22:23 UTC, bafolts commented on src/database/Cloner.ts
> +        if (typeof val === 'string') {
I think this will work great and it avoids requiring developers to consider how we clone a property when the `PlayerId` is used. I was concerned this wouldn't work with `Array` since an array has number indices and this could attempts to write a string value but it seems to work fine with arrays as well.

```
> Object.entries(["a", "b", "c"])
[ [ '0', 'a' ], [ '1', 'b' ], [ '2', 'c' ] ]
> var a = ["a", "b", "c"]; a["0"] = "z";
'z'
> a
[ 'z', 'b', 'c' ]
```

2020-12-30 22:26 UTC, bafolts commented on src/database/Cloner.ts
> +  private static replacePlayers(obj: any, ids: Array<string>) {
This can be `Array<PlayerId>` to help with self documenting. It is possible to use `object` instead of `any` as the type here if the updated property gets written with `Object.defineProperty(obj, key, { value: ids[idx] })`. If the type were `object` then we would have to protect against `null` since `typeof null` is `object` but we wouldn't have to protect against `undefined`. It would also avoid using `any`.

2020-12-30 22:32 UTC, bafolts commented on src/database/PostgreSQL.ts
> +    // TODO(kberg): why is player size a useful first-class piece of data?
I am pretty sure this is only used by the haphazard garbage collection process to determine number of players.

https://github.com/bafolts/terraforming-mars/blob/main/src/database/PostgreSQL.ts#L146

Ideally we would have a separate table of `game_to_player` which mapped game id to player id. This would allow us to calculate this value and it would also allow the `GameLoader` to pull the player and game ids without needing to deserializing the entire game.

2021-01-03 23:38 UTC, kberg commented on server.ts
> +            throw new Error(`game ${gameOptions.clonedGamedId} not cloned`); // how to nest errs in the way Java nests exceptions?
There's a catch 17 lines down processing the error. Isn't that what you want?

Also, I'm a little surprised there isn't a global catch around `processRequest()` -- wouldn't that prevent that entire class of issues?

2021-01-03 23:39 UTC, kberg commented on server.ts
> +            throw new Error(`game ${gameOptions.clonedGamedId} not cloned`); // how to nest errs in the way Java nests exceptions?
Rather, why doesn't the catch in `requestHandler` address this problem in its entirety?

2021-01-03 23:41 UTC, kberg commented on src/database/Cloner.ts
> +        cb(err, undefined);
It's mostly a lazy way of dealing with proving to the Typescript compiler that serialized is defined.

2021-01-03 23:43 UTC, kberg commented on src/database/Cloner.ts
> +    if (obj === undefined || obj === null || typeof obj !== 'object') {
Nice, but is that slightly too clever? Let me know, happy to defer.

2021-01-03 23:43 UTC, kberg commented on src/database/Cloner.ts
> +        if (typeof val === 'string') {
Good check. :+1:

2021-01-03 23:44 UTC, kberg commented on src/database/Cloner.ts
> +  private static replacePlayers(obj: any, ids: Array<string>) {
... and remove `|| typeof obj !== 'object'` Nice!

2021-01-03 23:54 UTC, kberg commented on src/database/Cloner.ts
> +  private static replacePlayers(obj: any, ids: Array<string>) {
Actually, that doesn't work. By removing 'any' and saying it's an object, the compiler complains with 
```
Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.
```

So in order to perform this extralinguistic behavior, it's got to be an `any`.

2021-01-03 23:55 UTC, kberg commented on src/database/PostgreSQL.ts
> +    // TODO(kberg): why is player size a useful first-class piece of data?
I realize now, it's shown in the CreateGameForm when asking to clone a game.

2021-01-04 17:41 UTC, bafolts requested changes
Spotted once place where error was thrown but `cb` needs to be called. Other comments were minor.

2021-01-04 17:41 UTC, bafolts commented on src/database/Cloner.ts
> +      throw new Error(`Failing to clone from a ${oldPlayerIds.length} game ${sourceGameId} to a ${newPlayerIds.length} game.`);
This needs to call to `cb` with this error. We don't write much asynchronous javascript in the project but in this case the error has to propagate out through `cb`.

2021-01-04 19:48 UTC, kberg commented on src/Game.ts
> +    if (gameOptions.clonedGamedId !== undefined) {
Yep, good idea.

2021-01-04 19:59 UTC, kberg commented on src/database/Cloner.ts
> +      throw new Error(`Failing to clone from a ${oldPlayerIds.length} game ${sourceGameId} to a ${newPlayerIds.length} game.`);
I think the rewrite is much more sensible.

2021-01-04 20:28 UTC, bafolts approved these changes

2021-01-04 21:06 UTC, merged