More cards modified to use less memory.
bafolts/terraforming-mars pull request #2248
Opened 2021-01-01 23:11 UTC by bafolts

This introduces the change to extend `Card` for less memory consumption per instance of a card. This is for base cards starting with letter A through P.

2021-01-01 23:28 UTC, kberg commented
That is A LOT of cards, my friend, with non-trivial differences in the diff. Any tips on how to make the UI do what I need? Or any chance you can break that up?

2021-01-01 23:48 UTC, bafolts commented
Most of the diffs for the cards are only moving properties in to the call to super. Going to have to update hundreds of cards. Would need the UI to be smart enough to spot that the diff only involved moving the data. In lieu of the UI being able to spot that the code only moved how many cards in a batch would be preferred?

2021-01-02 03:26 UTC, kberg commented
Actually hang out I think I have an idea.

2021-01-02 17:42 UTC, kberg reviewed
56 files reviewed, 109 to go.

2021-01-02 17:42 UTC, kberg commented on src/cards/Card.ts
> +    return this.properties.cost === undefined ? 0 : this.properties.cost;
See, this seems like a good place for `this.properties.cost || 0`. What do you think?

2021-01-02 17:44 UTC, bafolts commented on src/cards/Card.ts
> +    return this.properties.cost === undefined ? 0 : this.properties.cost;
Works for me. I am not too caught up on ternary or using `||` here. Six of one half a dozen of the other. Not having to check for `undefined` always better in my book.

2021-01-03 06:30 UTC, kberg reviewed
110 down, 55 to go.

2021-01-03 14:12 UTC, kberg requested changes
That last one!

2021-01-03 14:12 UTC, kberg commented on tests/ares/AresHandler.spec.ts
> +    deck.push(new EnergyTapping());
The comment up top talks about how these cards are chosen for their predetermined costs. That was forced in the earlier version of the test, and now it's happenstance, and not well documented.

Can you please add assertions that those cards have cost 5 and 3? If not, I'd really prefer to restore something hand-crafted.

2021-01-03 15:54 UTC, kberg approved these changes
I can do that last one in another PR. I'd rather unblock you.

2021-01-03 15:56 UTC, merged

2021-01-03 16:14 UTC, bafolts commented
This went out with the deployment today. I usually look at the memory charts every few hours to see if the server is still up. It has been improving over the past few weeks. With this change I expect the slow of the chart to decrease. Yesterday it took 12 hours before the memory climbed enough to get over 60% which seems to be where the heroku dyno crashes and the dyno runs `npm run start` again and we are back and running. If this change stretches that out to a full 24 hours to line up with when I normally deploy we will be in great shape. Besides the log messages I don't know what else would be climbing in memory with each game after this change. From what I saw with the log messages the node javascript should be using string interning so those messages should mostly end up as pointers to objects which shouldn't be more than a few bytes large. Thanks for approving! I will keep the subsequent cards to come to less than 26 at a time.