Add the ability for a card to need to be compatible with more than one other module.
bafolts/terraforming-mars pull request #2256
Opened 2021-01-02 21:28 UTC by kberg

I had hoped not to start putting behavior specific to the moon yet, but this has been overwritten once already (as code moved from Dealer to CardLoader so I thought I'd get it in now.

2021-01-03 17:33 UTC, bafolts commented on src/CardLoader.ts
> +      expansions.forEach((expansion) => {
Instead of using `meets` I think this can make use of `every`. In this situation we need every game option to provide the expansion.

```
expansions.every((expansion) => {
  switch (expansion) {
    case GameModule.Venus:
      return gameOptions.venusNextExtension;
 // you know the rest
 ```

2021-01-03 17:39 UTC, bafolts requested changes
I would leverage `Array.prototype.every`. There are a lot of useful functions on `Array.prototype`.

2021-01-03 23:33 UTC, kberg commented on src/CardLoader.ts
> +      expansions.forEach((expansion) => {
Nice! Done.

2021-01-04 02:02 UTC, bafolts approved these changes

2021-01-04 02:02 UTC, merged

2021-01-04 02:04 UTC, bafolts commented
Your hand-built every was impressive! Thought we would get to use the `&=` operator before I saw it was `every`.