Added Standard Actions
bafolts/terraforming-mars pull request #2288
Opened 2021-01-06 20:13 UTC by sienmich

Closes https://github.com/bafolts/terraforming-mars/issues/2192

For now i created two standard actions:
![Screenshot from 2021-01-06 20-33-30](https://user-images.githubusercontent.com/19472604/103813796-f4424b80-5060-11eb-9ff2-d4a83ef23077.png)

![Screenshot from 2021-01-06 20-34-26](https://user-images.githubusercontent.com/19472604/103813807-f6a4a580-5060-11eb-9f88-9bad738ed260.png)

Converting plants to greenery now requires confirmation (tagging https://github.com/bafolts/terraforming-mars/issues/1240).
I understand that's controversial. I'll be happy to allow placing greenery without confirmation, however I don't know how to implement that. Same goes with current selling patents. I would like to just replace the `Sell Patents` text with sell patents card. For example if `PlayerInput` could have `title` as text or as card would be cool. Any ideas how it should be done? I'm kinda stuck here for now
Also it would be nice to not hide those standard actions even when `Standard Actions` radio button is not selected imo. Same with standard projects. Do you agree? 

Implementation details:
I created StandardAction class. StandardProject is its subclass.

2021-01-06 20:18 UTC, sienmich commented on src/cards/standardActions/ConvertHeat.ts
> +import {SelectOption} from '../../inputs/SelectOption';
```suggestion
```

2021-01-07 00:56 UTC, nwai90 commented
@sienmich Agree that `StandardAction` and `StandardProject` should be differentiated. The main issue I see with this is that every greenery placement and every temperature increase would now require an extra click each, which is not ideal. The idea is great though! 👍

2021-01-07 01:09 UTC, bafolts commented
To avoid the extra clicks we could consider some updated `OrOptions` which used something that looked like a card. Would need a back button though. With that component in place we could then avoid the issue with having to click and confirm.

2021-01-07 01:13 UTC, bafolts commented
Thinking some more. Some `UserActions` player input that supported going back once the top level option were supported should work. Would need to come up with a card for each action such as `Play Project Card` as well. When clicked the UI would go to the card selection screen but now include a back button to go back to the list of all the other actions.

2021-01-07 02:23 UTC, kevinb9n commented
Looking good!

at some point I would like to discuss where this is heading relative to #953 (I put some thoughts at https://github.com/bafolts/terraforming-mars/issues/2192#issuecomment-751511295) but I'm not trying to block you up.

2021-01-07 03:03 UTC, Lynesth commented
> Thinking some more. Some `UserActions` player input that supported going back once the top level option were supported should work. Would need to come up with a card for each action such as `Play Project Card` as well. When clicked the UI would go to the card selection screen but now include a back button to go back to the list of all the other actions.

That would lead to even more clicks then.

2021-01-07 17:56 UTC, sienmich commented
Ok, I don't know how to update those `OrOptions` so they could accept cards. Could sb maybe help with this?
For now I resolved this same as Sell Patents are working - they are looking good in logs, and their whole logic is in separate files. I'd like to merge this for now.

2021-01-09 00:21 UTC, kberg commented
> @sienmich Agree that `StandardAction` and `StandardProject` should be differentiated. The main issue I see with this is that every greenery placement and every temperature increase would now require an extra click each, which is not ideal. The idea is great though!

How many clicks does a player make in the entire game? I find it particularly interesting that greeneries (and in this case, temperature) are a focus. But OK.

2021-01-09 00:32 UTC, sienmich commented
I think less click is better. I will work on displaying cards instead of text in Player Input. Can I merge current version? Any code concerns?

2021-01-09 20:41 UTC, kberg commented
Ah, I didn't realize I was the one giving the OK on this. Any last concerns? 
@nwai90 @bafolts @Lynesth ?

2021-01-09 21:59 UTC, bafolts commented
This change is OK with me. No last concerns.

2021-01-09 22:43 UTC, kberg requested changes
So, what exactly is the point of this PR? What are you actually trying to achieve? I'm trying to dig in and understand it from the code changes alone, but having a little trouble.

2021-01-09 22:43 UTC, kberg commented on src/CardFinder.ts
> +    public getCardByName<T extends ICard>(cardName: string, decksToSearch: (man: CardManifest) => Array<Deck<T>>): T | undefined {
Minor comments, shorten decksToSearch to decksd, and fully spell manifest, which is that way everywhere else.

2021-01-09 22:43 UTC, kberg commented on src/CardFinder.ts
> +    public getProjectOrSAByName(cardName: string): StandardAction | IProjectCard | undefined {
Please don't shorten StandardAction.

2021-01-09 22:43 UTC, kberg commented on src/CardLoader.ts
> +  public getStandardActions() {
Why is this being renamed? They're standard projects, a fairly commonly-understood term.

2021-01-09 22:43 UTC, kberg commented on src/CardName.ts
> +    STANDARD_SELL_PATENTS = 'Sell Patents:SP',
Why is giving this a suffix necessary?

2021-01-09 22:43 UTC, kberg commented on src/Player.ts
> +      action.options.push(convertPlants.action(this, game));
In the cards API, `action` means Do The Thing because it's time to do it. Here, action means something else: return the thing to offer the player. This name is going to be confusing.

2021-01-09 22:43 UTC, kberg commented on src/cards/standardActions/StandardAction.ts
> +    abstract action(_player: Player, _game: Game): PlayerInput | undefined
Why does action have _player, and _game, but canAct has player and game?

2021-01-10 00:10 UTC, sienmich commented on src/CardName.ts
> +    STANDARD_SELL_PATENTS = 'Sell Patents:SP',
There are normal cards called Asteroid and Power Plant. The names must be unique. Earlier it was solved by `asteroid` and `power plant` (no caps). But this way is much better imo

2021-01-10 00:13 UTC, sienmich commented on src/CardLoader.ts
> +  public getStandardActions() {
They are still standard projects - SPs.
SP is a subclass of SA. I didn't want to create separate getters for them, since they are almost the same thing.
So `getStandardActions` returns all SAs, which means SPs and some `Convert Plants`

2021-01-10 00:17 UTC, sienmich commented on src/CardFinder.ts
> +    public getCardByName<T extends ICard>(cardName: string, decksToSearch: (man: CardManifest) => Array<Deck<T>>): T | undefined {
Sure, np. However what does the `d` in `decksd` stands for?

2021-01-10 00:21 UTC, sienmich commented on src/cards/standardActions/StandardAction.ts
> +    abstract action(_player: Player, _game: Game): PlayerInput | undefined
My bad, fixed

2021-01-10 00:33 UTC, sienmich commented on src/Player.ts
> +      action.options.push(convertPlants.action(this, game));
I agree, most of the cards in `.action()` have `game.defer(sth)`. It's not the cleanest. It's made this way because of clicks saving. If `.action()` was in fact placing the greenery, then we would need to confirm it earlier.
I'm planing to change that soon. Once I know how display cards in the middle of some `PlayerInput` objects, I would like to improve that action selecting section.

2021-01-10 00:39 UTC, sienmich commented
> So, what exactly is the point of this PR? What are you actually trying to achieve? I'm trying to dig in and understand it from the code changes alone, but having a little trouble.

I moved those two standard actions from `Player.ts` to separate files to have cleaner code. Also those two actions now display in log, they look nicer than text imo. Additionally this is initial work to some better looking action selection I'm planning to do.

2021-01-10 06:18 UTC, nwai90 commented on src/cards/standardActions/ConvertPlants.ts
> +      b.standardProject('Spend 8 Plants to place a greenery tile and raise oxygen 1 step.', (eb) => {
@sienmich Could the description and iconography in metadata also make use of `player.plantsNeededForGreenery`? e.g. 7 plants for Ecoline instead of 8

2021-01-10 12:21 UTC, sienmich commented on src/cards/standardActions/ConvertPlants.ts
> +      b.standardProject('Spend 8 Plants to place a greenery tile and raise oxygen 1 step.', (eb) => {
It's not that easy, we have one card instance for whole server right now. It's a good idea, once we have changing card prices it should have been done, but not in this PR imo.

2021-01-10 15:38 UTC, kevinb9n commented on src/cards/standardActions/ConvertPlants.ts
> +      b.standardProject('Spend 8 Plants to place a greenery tile and raise oxygen 1 step.', (eb) => {
I do think it's better that the UI not adjust any costs based on player effects until/unless there's at least a plan under way to do it more consistently. The big picture end goal might be something like https://github.com/bafolts/terraforming-mars/issues/2187 (sorry for wall of text)

2021-01-10 16:36 UTC, kberg commented on src/CardName.ts
> +    STANDARD_SELL_PATENTS = 'Sell Patents:SP',
I did not know that! I agree.

2021-01-10 16:36 UTC, kberg commented on src/CardFinder.ts
> +    public getCardByName<T extends ICard>(cardName: string, decksToSearch: (man: CardManifest) => Array<Deck<T>>): T | undefined {
It means I made a typo. I meant `decks`. Sorry!

2021-01-10 16:37 UTC, kberg commented on src/CardLoader.ts
> +  public getStandardActions() {
I don't think Action is a first class object anywhere else in this game, and I think this is the crux of my misunderstanding.

2021-01-10 16:40 UTC, kberg commented on src/Player.ts
> +      action.options.push(convertPlants.action(this, game));
I appreciate clicks saving, but not at the cost of being able to understand the code.

Much of what I've been doing in the last couple of months on this project is taking bits that are hard to understand and make them easier to understand -- I'd rather get that resolved now.

If the whole point of this PR is to remove a click then perhaps it's worth going back and trying something else? I don't want to ruin your hard work, so don't give up yet, because first before doing anything like that, I need to _understand_ this PR.

2021-01-10 16:42 UTC, kberg commented
Aha! I get it now. These really ARE the standard actions from your player board. OK.

2021-01-10 16:43 UTC, kberg commented on src/CardFinder.ts
> +        decksd(man).some((deck) => {
I'm so sorry I made you do this. :-(

2021-01-10 17:11 UTC, kberg requested changes
I kind of don't mind that the game thinks of standard projects and standard actions as 'cards', and fully adopting that idea. After all visually the idea of a 'card' includes drawing a recatangle on a screen. (ref: https://www.nngroup.com/articles/cards-component/#:~:text=Summary%3A%20A%20%E2%80%9Ccard%E2%80%9D%20is,visually%20resembling%20a%20playing%20card.)

2021-01-10 17:11 UTC, kberg commented on src/CardLoader.ts
> +  public getStandardActions() {
I suggest not creating a mental notion of standard project is a standard action. Especially not without good clear of documentation for maintainers.

2021-01-10 17:11 UTC, kberg commented on src/Player.ts
> +  private getNormalActions(game: Game) {
Why is this 'normal' and not 'standard'? I don't understand this yet, but if 'standard' isn't going to work here, then perhaps 'common?

2021-01-10 17:11 UTC, kberg commented on src/cards/standardActions/StandardAction.ts
> +export abstract class StandardAction implements IActionCard, ICard {
Describe with a comment, please.

2021-01-10 17:11 UTC, kberg commented on src/cards/standardActions/ConvertPlants.ts
> +    const hasEnoughPlants = player.plants >= player.plantsNeededForGreenery;
I suggest similar code to ConvertHeat.

2021-01-10 17:11 UTC, kberg commented on src/CardLoader.ts
> +  public getStandardActions() {
I might even suggest that StandardAction be renamed to PlayerBoardAction. Because it's only really representing the two actions on a player board.

2021-01-10 18:45 UTC, sienmich commented on src/CardLoader.ts
> +  public getStandardActions() {
I'd like to convert other actions as well, like colony trading, send a delegate, I just didn't want to make too much changes in 1 PR. They would be nicer with proper graphics insted of text. In this case I think StandardAction is a better than PlayerBoardAction. I'll add some documentation then. Should I separate those SAs from SPs in `CardLoader` then?

2021-01-10 18:47 UTC, sienmich commented on src/Player.ts
> +      action.options.push(convertPlants.action(this, game));
Next time I'll work more on easier understanding me then :)

2021-01-12 05:17 UTC, kberg commented
@sienmich let me know if you want some help with some of this.

2021-01-17 14:17 UTC, sienmich commented on src/Player.ts
> +  private getNormalActions(game: Game) {
Changed to common, added comment

2021-01-17 14:17 UTC, sienmich commented on src/cards/standardActions/StandardAction.ts
> +export abstract class StandardAction implements IActionCard, ICard {
Done

2021-01-18 02:51 UTC, kberg commented on src/CardFinder.ts
> +    public getProjectOrStandardActionByName(cardName: string): StandardActionCard | IProjectCard | undefined {
Note to self to make sure I know why this is necessary.

2021-01-18 02:51 UTC, kberg commented on src/CardFinder.ts
> +      return this.getCardByName(cardName, (man) => [man.corporationCards]);
Please use `manifest`

2021-01-18 02:51 UTC, kberg commented on src/Player.ts
> +    this.setWaitingFor(this.getCommonActions(game), () => {
What does this do? Paging @Lynesth whom I think might understand this best.

2021-01-18 02:51 UTC, kberg commented on tests/cards/moon/MoonColonyStandardProject.spec.ts
> -    card.action(player, player.game);
Changes like this make me think irrelevant changes have leaked into your branch.

2021-01-18 10:44 UTC, sienmich commented on src/CardFinder.ts
> +    public getProjectOrStandardActionByName(cardName: string): StandardActionCard | IProjectCard | undefined {
It's used in LogPanel, when we want to display some card

2021-01-18 10:45 UTC, sienmich commented on src/CardFinder.ts
> +      return this.getCardByName(cardName, (man) => [man.corporationCards]);
Sure, I think it was mentioned somewhere else earlier, sorry :)

2021-01-18 10:48 UTC, sienmich commented on tests/cards/moon/MoonColonyStandardProject.spec.ts
> -    card.action(player, player.game);
I didn't want to add new actions using old (player, game) interface, so I updated a bit too much. Sorry, next time it will be on separate PR

2021-01-18 10:53 UTC, sienmich commented on src/Player.ts
> +    this.setWaitingFor(this.getCommonActions(game), () => {
So the function `Player.takeAction()` was 250 lines and hard to understand. I've extracted half of it (new `getCommonActions()`), which returns normal turn actions as noted in comment next to declaration:
```ts
// Return possible mid-game actions like play a card and fund an award, but no play prelude card.
  private getCommonActions(game: Game) {
```
I think it's a necessary change to improve the code readability.

2021-01-20 01:18 UTC, sienmich commented
Since this PR grew a bit too big and is changing too many things I'll close it and submit those changes in split PRs

2021-01-20 01:18 UTC, closed without merging