Refactored Card Drawing
bafolts/terraforming-mars pull request #2292
Opened 2021-01-07 04:07 UTC by sienmich

2021-01-07 04:13 UTC, sienmich commented on src/deferredActions/DrawCards.ts
> +            false, false, 'Select how to pay for action'));
```suggestion
          this.game.defer(new SelectHowToPayDeferred(
            this.player, selected.length * this.player.cardCost,
            {title: 'Select how to pay for cards'}));
```

2021-01-07 04:42 UTC, Lynesth requested changes

2021-01-07 04:42 UTC, Lynesth commented on src/deferredActions/DrawCards.ts
> +    const total = this.options.from || this.options.amount;
return if `this.options.amount <= 0`

2021-01-07 04:42 UTC, Lynesth commented on src/deferredActions/DrawCards.ts
> +  private selectCardsToDraw(cards: Array<IProjectCard>) {
`selectCardsToKeep` ?

2021-01-07 04:42 UTC, Lynesth commented on src/deferredActions/DrawCards.ts
> +  private selectCardsToBuy(cards: Array<IProjectCard>) {
Where do you check that the player can buy the card(s) ?

2021-01-07 04:42 UTC, Lynesth commented on src/deferredActions/DrawCards.ts
> +  private selected(selected: Array<IProjectCard>, from: Array<IProjectCard>) {
I'm not sure what this function does by reading its name, especially since it's also the name of a variable used quite often in this class.

2021-01-07 04:42 UTC, Lynesth commented on src/deferredActions/DrawCards.ts
> +    return `${amount} card${amount === 1 ? '' : 's'}`;
I think there's a reason we're using `card(s)` instead but someone will probably be able to tell you why, I don't remember (something to do with translation).

2021-01-07 04:42 UTC, Lynesth commented on src/deferredActions/DrawCards.ts
> +    return !!(this.options.include || this.options.tag || this.options.resource || this.options.cardType);
Would you mind using `Boolean(...)` instead of double negation `!!` ?
Or checking each of them against `undefined` ?

2021-01-07 05:03 UTC, Lynesth requested changes
I also notice you sometimes left
```ts
player.drawCard( ... );
return undefined;
```
and sometimes changed it for
```ts
return player.drawCard( ... );
```
Could you standardize this (2nd variant) ?

2021-01-07 05:03 UTC, Lynesth commented on src/deferredActions/DrawCards.ts
> +  private selectCardsToBuy(cards: Array<IProjectCard>) {
Ok so I see it is done before the call to this.
It should probably be moved here, with a different title 'You cannot afford to buy a card' (or whatever) as it was before.

2021-01-07 06:35 UTC, nwai90 commented on src/deferredActions/DrawCards.ts
> +    return `${amount} card${amount === 1 ? '' : 's'}`;
We use it for ease of localisation so that we don't have to worry about plural forms at all. It would be too onerous to have to handle every noun (card, resource, etc.)

2021-01-07 07:11 UTC, kberg reviewed
It's too late at night, so I can't review this reasonably well, but I noticed one thing.

2021-01-07 07:11 UTC, kberg commented on src/cards/base/InventionContest.ts
> +    return player.drawCard(game, {amount: 1, from: 3})!;
! is very, very much dissuaded (except in tests).

2021-01-07 14:12 UTC, sienmich commented on src/deferredActions/DrawCards.ts
> +  private selectCardsToBuy(cards: Array<IProjectCard>) {
Good idea, added that inside

2021-01-07 14:19 UTC, sienmich commented on src/cards/venusNext/SponsoredAcademies.ts
> +        p.drawCard(game);
@Lynesth, I think I'm gonna make sth like this (in `Player.ts`):
```ts
  public drawCard(game: Game, options?: DrawCards.Options) {
    game.defer(new DrawCards(this, game, options));
  }
```
Because in log we want first info which card was played and later how many cards were drawn. Am i right? Does it make sense?

2021-01-07 14:21 UTC, sienmich commented on src/cards/venusNext/SponsoredAcademies.ts
> +        p.drawCard(game);
Or maybe, doesn't really matter. What do u prefer?
```ts
  public drawCard(game: Game, options?: DrawCards.Options) {
    game.defer(new DrawCards(this, game, options));
    return undefined;
  }
```

2021-01-07 14:46 UTC, Lynesth requested changes

2021-01-07 14:46 UTC, Lynesth commented on src/deferredActions/DrawCards.ts
> +        selected = selected.slice(0, this.options.amount);
I'm not sure but, why are we slicing the array here ?

2021-01-07 14:46 UTC, Lynesth commented on src/deferredActions/DrawCards.ts
> +        selected = selected.slice(0, howManyCanAfford);
Same question as above.

2021-01-07 14:46 UTC, Lynesth commented on src/deferredActions/DrawCards.ts
> +      }, this.options.amount, 0,
I think the maximum number of cards should be `howManyCanAfford` here instead of `this.options.amount`.

2021-01-07 14:46 UTC, Lynesth commented on src/deferredActions/DrawCards.ts
> +      `Select at most ${howManyCanAfford}${info} card(s) to buy`,
I know you probably wanted it to be future proof somehow but since all actions that allow you to buy a card only let you buy one, you'd probably better of checking we can afford 1 card and change the message completely if we can't.

If you really want to keep it that way, then please just change the title and the button if we can't buy cards at all. "Select at most 0" with a "Buy" button is strange.

2021-01-07 14:46 UTC, Lynesth commented on src/deferredActions/DrawCards.ts
> +    const cards = this.game.dealer.drawProjectCardsByCondition(this.game, total, this.options.include || include);
Should also probably add a failsafe after this one in case no cards were drawn (Celestic in a non venus game for example) to simply return.

2021-01-07 14:47 UTC, Lynesth commented on src/cards/venusNext/SponsoredAcademies.ts
> +        p.drawCard(game);
It should be fine to do yes. But it's late so I might be missing something.

2021-01-07 15:11 UTC, sienmich commented on src/deferredActions/DrawCards.ts
> +        selected = selected.slice(0, this.options.amount);
If somebody is cheating, he could select more cards than he should (the restriction is on client side, he could just upload custom POST to server or select more cards modifying some code). This slice is server side verification, if there are more cards selected then intended I just slice them.
I'm not sure if this is necessary. Should i remove this?

2021-01-07 15:22 UTC, sienmich commented on src/deferredActions/DrawCards.ts
> +      `Select at most ${howManyCanAfford}${info} card(s) to buy`,
Ok, I'll change that.
I'm thinking of exporting this part and applying it to buying cards after draft (from 4), I'm not sure if those prices are checked there.

2021-01-07 16:16 UTC, sienmich commented on src/deferredActions/DrawCards.ts
> +      }, this.options.amount, 0,
Thanks, fixed

2021-01-07 16:16 UTC, sienmich commented on src/deferredActions/DrawCards.ts
> +      `Select at most ${howManyCanAfford}${info} card(s) to buy`,
Done

2021-01-07 16:18 UTC, sienmich commented on src/cards/venusNext/SponsoredAcademies.ts
> +        p.drawCard(game);
I changed all to `return player.drawCard( ... );`

2021-01-08 02:47 UTC, Lynesth commented on src/deferredActions/DrawCards.ts
> +        selected = selected.slice(0, this.options.amount);
All checks are already performed server side in `Player.runInput()` so you can remove it from here.

2021-01-08 02:49 UTC, sienmich commented on src/deferredActions/DrawCards.ts
> +        selected = selected.slice(0, this.options.amount);
Ok, thanks!

2021-01-08 03:01 UTC, sienmich commented on src/deferredActions/DrawCards.ts
> +        selected = selected.slice(0, this.options.amount);
Done

2021-01-08 03:07 UTC, Lynesth requested changes

2021-01-08 03:07 UTC, Lynesth commented on src/cards/venusNext/SponsoredAcademies.ts
>          p.drawCard(game);
Not sure it really matters but I think active player usually prefers drawing before the others, so probably leave this as a deferred action as well.

2021-01-08 03:07 UTC, Lynesth commented on src/Player.ts
> +    }));
Have you checked that this is actually working ?
What part of the code runs all deferred actions after calling each player's `runResearchPhase` ?

2021-01-08 03:07 UTC, Lynesth commented on src/Player.ts
> +
Moving this here will probably break a lot of things we don't have tests for.
If you just want to put the "Red played this card" log before playing the card, move the log here but leave adding the card to the played cards where it was before.

2021-01-08 03:13 UTC, sienmich commented on src/Player.ts
> +
Ok, right

2021-01-08 03:29 UTC, sienmich commented on src/Player.ts
> +    }));
You are right, it's not working. I was testing it, but changed to `game.defer` instead of `player.setWaitingFor` just before the commit. Good spot, thanks!

2021-01-08 03:54 UTC, sienmich commented on src/Player.ts
> +    }));
I don't know how to get around the fact that my `drawCard` returns `SelectCard<IProjectCard> | undefined`. In this case it's clearly the first one. Could I just cast it (`as SelectCard<IProjectCard>`)?
Or is there a way to tell TypeScript that when `options.isBuying === true` then return type is not undefined?
I could also make `setWaitingFor` accept `undefined`, but that's probably too ugly.

2021-01-08 13:12 UTC, sienmich commented on src/Player.ts
> +    }));
Ok, I added an if, seems the best solution to me

2021-01-08 13:37 UTC, Lynesth requested changes

2021-01-08 13:37 UTC, Lynesth commented on src/Player.ts
> +    game.log('${0} played ${1}', (b) => b.player(this).card(selectedCard));
This should not be logged if the card is of type PROXY.

2021-01-08 13:39 UTC, Lynesth commented on src/Player.ts
> +    }));
Unfortunately, you can't tell TS what you'd like. Because the `cards` you are passing to the function might be an empty array for some reason (since `this.dealCards()` can return an empty array and `this.draftedCards` could be empty as well as far as TS knows), in which case it'll return undefined anyway.

2021-01-08 13:45 UTC, Lynesth commented on src/inputs/SelectAmount.ts
> +        public cb: (amount: number) => undefined | PlayerInput,
What are this change...

2021-01-08 13:45 UTC, Lynesth commented on src/inputs/SelectOption.ts
> +        public cb: () => PlayerInput | undefined) {
... and this one for ?

2021-01-08 14:37 UTC, sienmich commented on src/inputs/SelectOption.ts
> +        public cb: () => PlayerInput | undefined) {
@Lynesth, After changing the
```ts
player.drawCard(game);
return undefined;
```
into
```ts
return player.drawCard(game);
```
a lot of functions no longer are returning undefined (because `drawCard(...): undefined | SelectCard<IProjectCard>`).

I see no harm (yet) in possibility of different PlayerInputs callbacks to return other PlayerInputs. Is there one?

`SelectOption` signature is not a problem, but that `SelectAmount` change would be helpful.

2021-01-10 01:40 UTC, Lynesth approved these changes
This look ok to me now.
I'd still like 1 more pair of eyes to take a look though if possible @bafolts @kberg

2021-01-10 16:29 UTC, kberg requested changes
By and large a good PR, but i have a few thoughts and comments.

2021-01-10 16:29 UTC, kberg commented on src/deferredActions/DrawCards.ts
>  export class DrawCards implements DeferredAction {
OK, so I'm going to give some feedback on this. This is an improvement, but there's a further improvement to consider. Please excuse me if you know about these ideas already.

There's a notion in OO called the [Single Responsibility Principle](https://en.wikipedia.org/wiki/Single-responsibility_principle) which basically says that one class should do one thing well. Now, drawCard isn't a class, it's a method, but there's a similar idea about methods, which is kind of the notion of [coupling](https://en.wikipedia.org/wiki/Coupling_(computer_programming)). This method really does several things:

1. It draws `from` cards from the project deck.
2. It lets a player select up to `amount` cards
3. It makes the player pay for them if configured.

In other words, I expect something called 'drawCards' to do kind of one thing: **Draw Cards.**

I'm not *entirely* there's a better approachin what the right approach is yet, but I want to think about it. In some ways, imagine an API a little different from this (don't go changing things, I'm just thinking.) But the fact that all the options are mixed into one object (rules for drawing, rules for keeping, rules for buying) makes me cautious.

2021-01-10 16:29 UTC, kberg commented on src/deferredActions/DrawCards.ts
> +  export interface Options {
I suggest renaming a few things to disambiguate:

1. change `amount` to `count`. Amount can be mistaken for a MC amount
2. change `from` to `keep`, and invert its responsibility as a parameter: Now, 'keep' is always the lower value, never `count` nee `amount`. "Draw 2 from 4" sounds like drawing 2 cards from a deck of 4 cards, not drawing 4 cards from a deck and keeping 2.
3. `isBuying` can be easier to read as `paying`

Can you please add a comment describing what cards is, as a parameter?

2021-01-10 16:29 UTC, kberg commented on src/deferredActions/DrawCards.ts
> +  private runCb() {
Can be simplified to this.options.cb?() and then you can remove this function?

2021-01-10 16:29 UTC, kberg commented on src/deferredActions/DrawCards.ts
> +    const howManyCanAfford = Math.min(this.options.amount, Math.floor(this.player.spendableMegacredits() / this.player.cardCost));
You can just call this `max`

2021-01-10 16:29 UTC, kberg commented on src/deferredActions/DrawCards.ts
> +    const info = howManyCanAfford !== this.options.amount ? `at most ${howManyCanAfford} (you cannot afford more) `:'';
I suggest keeping this a little simpler:

```
let msg = max === 0 ?
  'You cannot afford any cards' :0
  `Select up to ${max} cards to buy for ${this.player.cardCost} MC each`;

return new SelectCard(
  msg,
  ...
```

Having part of the initial message logic here, and even more down in the `SelectCard` constructor makes it harder to read.

2021-01-10 16:29 UTC, kberg commented on src/deferredActions/DrawCards.ts
> +        if (selected.length > 0) {
Can the statement above be run only after the payment? Can be a TODO.

2021-01-10 16:29 UTC, kberg commented on src/inputs/SelectAmount.ts
> +        public cb: (amount: number) => undefined | PlayerInput,
Can you respond to this question, please?

2021-01-10 16:29 UTC, kberg commented on src/deferredActions/DrawCards.ts
>  export class DrawCards implements DeferredAction {
This is now a pretty critical and meaty bit of code, particularly the varied amount of options for drawing and selectig cards. What do you think would be the right tests to make you confident this worked?

2021-01-10 17:29 UTC, sienmich commented on src/deferredActions/DrawCards.ts
>  export class DrawCards implements DeferredAction {
I mostly agree.
I think some kind of a solution would be to make more smaller classes, like `DrawCards`, `BuyCards`, `SelectCardsToKeep` etc. And make the `DrawCards` use thaose smaller ones and rename it to some kind of `AdvancedDrawCards` or `GetNewCards`.
I'd prefer to leave it as it is and aim to refactor with OO rule our giants like `Player` or `Game`

2021-01-10 17:31 UTC, sienmich commented on src/inputs/SelectAmount.ts
> +        public cb: (amount: number) => undefined | PlayerInput,
Here: https://github.com/bafolts/terraforming-mars/pull/2292#discussion_r553979583

2021-01-10 18:00 UTC, sienmich commented on src/deferredActions/DrawCards.ts
> +  private runCb() {
`this.options.cb?()` is not working. However, `this.options.cb?.();` is. Turns out, that `?.` is the overloaded operator. https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining

2021-01-10 18:30 UTC, sienmich commented on src/deferredActions/DrawCards.ts
>  export class DrawCards implements DeferredAction {
It's tested via all cards test, like `BusinessContacts` and `BusinessNetwork`, so it should be all right. Should I add separate test file?

2021-01-10 19:11 UTC, kberg commented on src/deferredActions/DrawCards.ts
>  export class DrawCards implements DeferredAction {
I think so, given how critical this is.

2021-01-12 05:29 UTC, kberg reviewed
Couple of things. This is looking pretty good.

2021-01-12 05:29 UTC, kberg commented on src/cards/venusNext/MorningStarInc.ts
> +      return player.drawCard(3, {tag: Tags.VENUS});
So there's something funny about this being a return value`drawCards` reads like an immediate action, so what is the return value? If it's not obvious, if you have to go look up a couple of functions in to figure it out, we need something better.

What is the return value of drawCard?

If it's a deferred action, then I suggest calling drawCard "drawCardDeferred" etc.

2021-01-12 05:29 UTC, kberg commented on src/deferredActions/DrawCards.ts
> +    console.log(max, options.keepMax, cards.length);
Remove before flight.

2021-01-12 05:29 UTC, kberg commented on src/deferredActions/DrawCards.ts
> +      console.log(max, player.spendableMegacredits(), player.cardCost);
This too.

2021-01-12 05:29 UTC, kberg commented on tests/defferedActions/DrawCards.spec.ts
> +    expect(player.game.dealer.discarded.length).to.eq(expectedDiscardedCards);
expect(player.game.dealer.discarded).has.length(expectedDiscardedCards)

2021-01-12 05:29 UTC, kberg commented on tests/defferedActions/DrawCards.spec.ts
> +    check(2, 0);
Tell me if you think this is more readable. Up top, have 

`let dealer: Dealer` and initialize to `game.dealer`

And then replace calls to `check` with

```
expect(player.cardsInHand).have.length(2);
expect(dealer.discardedCards).have.length(0);
```

I think people will be able to understand that more than check(2, 0). Sometimes there's better options than terse, but you tell me.

2021-01-12 12:15 UTC, sienmich commented on tests/defferedActions/DrawCards.spec.ts
> +    check(2, 0);
Agree, changed

2021-01-12 12:34 UTC, sienmich commented on src/cards/venusNext/MorningStarInc.ts
> +      return player.drawCard(3, {tag: Tags.VENUS});
I just added the return types as template, now it looks like this:
```ts
  public drawCard(count?: number, options?: DrawCards.DrawOptions): undefined {
    return DrawCards.keepAll(this, count, options).execute();
  }

  public drawCardKeepSome(count?: number, options?: DrawCards.AllOptions): SelectCard<IProjectCard> {
    return DrawCards.keepSome(this, count, options).execute();
  }
```
It makes a lot of sense, because if we just draw cards, then we do not need additional input, and we are buying / choosing, then we need to Select those Cards.

2021-01-12 12:36 UTC, sienmich commented on src/cards/venusNext/MorningStarInc.ts
> +      return player.drawCard(3, {tag: Tags.VENUS});
`return player.drawCard(3, {tag: Tags.VENUS});` is just a shortcut from
```
player.drawCard(3, {tag: Tags.VENUS});
return undefined;
```
, as @Lynesth suggested above

2021-01-12 13:03 UTC, Lynesth commented on src/cards/venusNext/MorningStarInc.ts
> +      return player.drawCard(3, {tag: Tags.VENUS});
I suggested it since it can (maybe that changed now, haven't checked) return either undefined or a SelectCard input. So it makes sense to simply have it like that.

2021-01-12 13:44 UTC, kberg commented on src/cards/venusNext/MorningStarInc.ts
> +      return player.drawCard(3, {tag: Tags.VENUS});
> `return player.drawCard(3, {tag: Tags.VENUS});` is just a shortcut from

I'll ask you to restore the original, because I think it's not clear. *IF* you're going to actually return a SelectInput instead, then I'd ask for a name more appropriate "draw cards" is a statement to draw cards, which this does most of the time.  

@Lynesth a related side question: what's the difference between returning SelectInput and calling game.defer? Is this basically two ways of doing the same thing? If so, is it right to drop one?

2021-01-12 13:45 UTC, kberg reviewed
Modulo my one comment about return values, I think this is good to go.

I would approve the PR now, except that I think if you make a change based on my last comment , it's worth just reading it to catch issues first. Otherwise, we're basically done.

2021-01-12 14:41 UTC, kberg approved these changes

2021-01-12 14:42 UTC, kberg commented
This is really good. It's a net change of -100 lines, and that's WITH tests.

2021-01-12 14:42 UTC, merged

2021-01-12 14:50 UTC, Lynesth commented on src/cards/venusNext/MorningStarInc.ts
> +      return player.drawCard(3, {tag: Tags.VENUS});
@kberg If the returned value of a `play` call (or an `action` one) is not undefined, it will be deferred using `game.defer()`.

So you can return a SelectInput if that's the only thing the `play` method needs to prompt the player.

But if you have to prompt the player for multiple things (place an ocean and draw cards, discard then draw cards, etc) then you have to use game.defer directly inside the method.