buttons to hide green and orange cards
bafolts/terraforming-mars pull request #2334
Opened 2021-01-10 22:30 UTC by vsrisuknimit

This PR can close #2309 .

By default
![image](https://user-images.githubusercontent.com/14239220/104137187-0675ff80-5369-11eb-94a1-59c0c8dc796b.png)

After hiding green cards is clicked
![image](https://user-images.githubusercontent.com/14239220/104137193-0d9d0d80-5369-11eb-812f-e0ffda90f683.png)

After hiding orange cards is clicked
![image](https://user-images.githubusercontent.com/14239220/104137196-142b8500-5369-11eb-81e7-6acecaa88548.png)

Things that I would like to do. In order of importance:
1) Force refresh. Right now you have to refresh the page for this to take effect.
2) Both buttons to be on the same row but above the cards. I tried to nested div but compiler screamed at me for having more than one nested template or something.
3) Fix css. I always mess up css selector. There must be a cleaner way to do this.
4) Show cards number of those particular types on the buttons.

2021-01-10 23:03 UTC, vsrisuknimit commented
The buttons are now on the same row.

![image](https://user-images.githubusercontent.com/14239220/104137888-26f48880-536e-11eb-8751-012cdf873a80.png)

2021-01-10 23:08 UTC, vsrisuknimit commented
I see ForceRender() function is TopBars.ts but I don't under how it works. Why does it force render?

https://github.com/bafolts/terraforming-mars/blob/5f75aec88078be7aa019fe8fbcf729611daac846/src/components/TopBar.ts#L20

2021-01-10 23:28 UTC, bafolts commented
Force rendering should be avoided. Vue will monitor when `data` changes which should require updating the component. Here whenever a card is hidden or shown if you update a property on `data` then vue will naturally update the component.

2021-01-10 23:34 UTC, bafolts commented on src/components/PlayerHome.ts
> +      const val = PreferencesManager.loadValue('hide_automated_cards');
Storing this in `PreferencesManager` is fine but we need to leverage the tools that vue provides for this. I would make `hide_automated_cards` a property on `data`. Then in a `watch` when `hide_automated_cards` changes I would write that change to `PreferencesManager`. What is here is working against vue instead of with it and leading to needing the force update.

```
data: {
   return {
      hide_automated_cards: PreferencesManager.loadValue('hide_automated_cards')
   }
},
watch: {
   hide_automated_cards: function () {
     PreferencesManager.preferencesValues.set('hide_automated_cards', this.hide_automated_cards);
   }
}
```

With this in place as you update `this.hide_automated_cards` the `PreferencesManager` will naturally be kept up to date. We really should work to remove any place we are using force update and refactor it to work with vue.

2021-01-11 14:55 UTC, vsrisuknimit commented on src/components/PlayerHome.ts
> +      const val = PreferencesManager.loadValue('hide_automated_cards');
@bafolts I added data and watch but it still requires a refresh to update the state of the hide/show. I don't understand vue so I am probably doing something wrong here.

2021-01-11 16:41 UTC, vsrisuknimit commented
![image](https://user-images.githubusercontent.com/14239220/104211211-cca50780-5401-11eb-9197-1e5eff5eae19.png)

Example with transparency.

It still requires manual refresh to take effect after clicking the button. I need help here @bafolts , @chosta .

I also would like to show the number for each type. I have not figured out how yet.

2021-01-11 18:12 UTC, vsrisuknimit commented
Perhaps the transparency should be switched. Normally it is somewhat transparency. Then once you hide something, that button becomes more bright, showing you can click to un-hide.

2021-01-11 20:35 UTC, vsrisuknimit commented
Now I have the card type number.

All type shown (buttons are transparent)
![image](https://user-images.githubusercontent.com/14239220/104235113-7dbb9a00-5422-11eb-8ca6-957b4808cfde.png)

Automated and event card are hidden (buttons are light up)
![image](https://user-images.githubusercontent.com/14239220/104235137-86ac6b80-5422-11eb-9cf4-7d1957775942.png)

2021-01-12 01:10 UTC, vsrisuknimit commented
Switch transparency back according to some feedbacks. Lit when showing card but not too bright. Dim when hiding cards but not too dim.

![image](https://user-images.githubusercontent.com/14239220/104256284-f0d80700-5448-11eb-8667-200c14a231de.png)

![image](https://user-images.githubusercontent.com/14239220/104256351-12d18980-5449-11eb-8a64-4e47416087bd.png)

2021-01-12 02:26 UTC, vsrisuknimit commented
@bafolts now that I merged your PR, do I need to do anything else? Sorry I am still very confused by Git.

2021-01-12 02:31 UTC, bafolts commented on src/components/PlayerHome.ts
> +        return this.isActiveCardShown() ? 'hiding-card-button hiding-card-button--active' : 'hiding-card-button hiding-card-button--active-transparent';
There is a lot of duplication here with `hiding-card-button hiding-card-button--`. I would put this in a `const prefix` to store it once. This takes up space in the generated build and it is also code that has to be updated if this prefix were to change. Then this can become.

```
if (hideType === 'ACTIVE') {
    return this.isActiveCardshown() ? prefix + "active" : prefix + "active-transparent";
}
```

2021-01-12 02:32 UTC, bafolts commented on src/components/PlayerHome.ts
> +        return this.isActiveCardShown() ? 'Hide active cards' : 'Show active cards';
Simplify these to reduce duplication to:

`return (this.isActiveCardShown() ? 'Hide' : 'Show') + ' active cards';`

2021-01-12 02:34 UTC, bafolts approved these changes
The usage of vue looks good now. I am glad we have this in place because we should copy this pattern every place we are updating local storage. Minor string updates I would make before merging that aren't critical.

2021-01-12 02:48 UTC, vsrisuknimit commented on src/components/PlayerHome.ts
> +        return this.isActiveCardShown() ? 'Hide active cards' : 'Show active cards';
Simplified this and the css.

2021-01-12 02:49 UTC, vsrisuknimit commented on src/components/PlayerHome.ts
> +        return this.isActiveCardShown() ? 'hiding-card-button hiding-card-button--active' : 'hiding-card-button hiding-card-button--active-transparent';
Simplified this and the css.

2021-01-12 09:19 UTC, alrusdi requested changes

2021-01-12 09:19 UTC, alrusdi commented on src/components/PlayerHome.ts
>      getToggleLabel: function(hideType: string): string {
@vsrisuknimit can you please add translation support for these strings?

2021-01-12 13:57 UTC, vsrisuknimit commented on src/components/PlayerHome.ts
>      getToggleLabel: function(hideType: string): string {
added translation

2021-01-12 14:15 UTC, merged