keyboard shortcut
bafolts/terraforming-mars pull request #2344
Opened 2021-01-12 03:16 UTC by vsrisuknimit

Here is a draft of the keyboard shortcuts.

It does not listen yet or not redirect. I cannot tell which is which. I look into event listener on the browser but I don't see anything when a press a key. 

Tag @bafolts for help.

2021-01-12 05:59 UTC, kberg reviewed
**UM.** How did I manage to push directly to your repo?

Anyway, I managed to get keyboard shortcuts sort of workingg, and somehow they're now in this PR because of it.

2021-01-12 05:59 UTC, kberg commented on src/components/PlayerHome.ts
> +        console.log('f pressed');
remove.

2021-01-12 05:59 UTC, kberg commented on src/KeyboardNavigation.ts
> +export enum KeyboardNavigation {
What a great selection of shortcuts.

2021-01-12 11:00 UTC, vsrisuknimit commented
Thank @kberg and @bafolts  . I changed the getElementByClass to getElementById instead. That is more specific and redirect us to where we want. Changed the behavior of the scrollIntoView to put the element in the middle of the page instead of the very far top which is obscured by the top bar.

Do we need both mounted and v-on? I thought one of the them should do. I tried to remove v-on but it seems we need it.

One major problem is that now there is this little blue border going over the whole element with v-on. Not sure how to remove it.

![image](https://user-images.githubusercontent.com/14239220/104305393-a2ebef00-549a-11eb-8bfa-8533d6a0b9af.png)

2021-01-12 11:17 UTC, vsrisuknimit commented
I was able to remove the blue outline but we hate in-line style so that perhaps should be somewhere else. I am not sure where since :class for that element is doing something weird.

2021-01-12 11:53 UTC, chosta commented
@vsrisuknimit you can use a function for the classes based on conditional logic.
Do a global search for `getClasses` to see how this could be done.

2021-01-12 14:01 UTC, vsrisuknimit commented
@Lynesth raised the issue of non-qwerty keyboards. This mapping does not make a lot of sense there.

I think the best path forward is to have mappable keys. I will need help with that.

Otherwise we can do shift+1, shift+2, but one key is much better.

2021-01-12 17:44 UTC, kberg commented
> @Lynesth raised the issue of non-qwerty keyboards. This mapping does not make a lot of sense there.
> 
> I think the best path forward is to have mappable keys. I will need help with that.
> 
> Otherwise we can do shift+1, shift+2, but one key is much better.

No, but 1,2,3,4,5 are excellent

2021-01-12 17:50 UTC, vsrisuknimit commented
@kberg just plain number will not work well. Some users may type in a number when paying for a cost.

![image](https://user-images.githubusercontent.com/14239220/104352491-bf0c8200-54d4-11eb-9aaa-c2e406c4601d.png)

2021-01-12 18:09 UTC, vsrisuknimit commented
Tested. Typing in the input field will trigger the keyboard shortcut. So we should avoid plain number.

2021-01-13 02:04 UTC, bafolts requested changes
This looks right. I would use `KeyboardEvent` instead of `any`.

2021-01-13 13:29 UTC, vsrisuknimit commented on src/components/PlayerHome.ts
> +    navigatePage: function(event: any) {
@bafolts if I use KeyboardEvent, event.target.nodeName does not work. "Property 'nodeName' does not exist on type 'EventTarget'."

2021-01-13 17:29 UTC, vsrisuknimit commented
Added key mapping graphics in the help page.

![image](https://user-images.githubusercontent.com/14239220/104487323-f34a7600-559a-11eb-8478-6ebc160df2f5.png)

2021-01-13 17:38 UTC, vsrisuknimit commented
These are the poll results from Discord.

![image](https://user-images.githubusercontent.com/14239220/104488279-22adb280-559c-11eb-8df7-17df5850ff4b.png)

![image](https://user-images.githubusercontent.com/14239220/104488298-28a39380-559c-11eb-9187-6ffed9f7b6c3.png)

I also added the ability to change the scrolling speed in preferences setting.

2021-01-13 17:55 UTC, vsrisuknimit commented on src/components/PlayerHome.ts
> +    navigatePage: function(event: any) {
Fixed now. Cast event.target as Element.

2021-01-14 01:51 UTC, bafolts commented on src/KeyboardNavigation.ts
> +  TURMOILBOARD = '',
Many of these are missing. I can't imagine this works with these missing.

2021-01-14 01:53 UTC, bafolts commented on src/components/PlayerHome.ts
> +        <div v-on:keydown="navigatePage" tabindex="0" id="player-home" :class="'shortkey-no-outline'+(player.turmoil ? ' with-turmoil': '')">
I think you can use `v-on:keydown.prevent` instead of manually calling to prevent default ourselves.

2021-01-14 01:53 UTC, vsrisuknimit commented on src/KeyboardNavigation.ts
> +  TURMOILBOARD = '',
4 are what I decided would be useful in the end. I left the rest there as a place holder in the future if we want remappable keys. Should I remove them all?

2021-01-14 02:04 UTC, vsrisuknimit commented on src/components/PlayerHome.ts
> +        <div v-on:keydown="navigatePage" tabindex="0" id="player-home" :class="'shortkey-no-outline'+(player.turmoil ? ' with-turmoil': '')">
keydown.prevent causes an error.

![image](https://user-images.githubusercontent.com/14239220/104534762-e0f42a80-55e2-11eb-8a2a-555d9a1e2bb8.png)

2021-01-14 02:07 UTC, bafolts commented on src/KeyboardNavigation.ts
> +  TURMOILBOARD = '',
Yes. If we decide to add them later we can add them then. I would also remove their corresponding ids from the template.

2021-01-14 02:13 UTC, vsrisuknimit commented on src/KeyboardNavigation.ts
> +  TURMOILBOARD = '',
Removed the unused keys and ids.

2021-01-14 02:16 UTC, bafolts approved these changes

2021-01-14 06:00 UTC, merged