Update RoboticWorkforce with a Units data structure. Also,...
bafolts/terraforming-mars pull request #2361
Opened 2021-01-13 07:06 UTC by kberg

Also, move some of the units to cards that have static properties. Tests still pass, is that good enough?

This will vastly simplify the work involved in enabling cards for Robotic Workforce by just annotating the cards themselves. There are still outliers, like Solar Farm, et cetera, but this will vastly reduce the amount of code in Robotic Workforce.

(Plus the fields, like those in AI Central) will reduce the logic in getAvailableCards, and can also be used in card.canPlay() and card.play().

2021-01-13 09:23 UTC, Lynesth reviewed
Haven't checked that you didn't mess up the conversion from arguments to units in the `updaters` array.

2021-01-13 09:23 UTC, Lynesth commented on src/cards/base/RoboticWorkforce.ts
>        const result:Updater = updaters.filter((u) => u.name === foundCard.name)[0];
Just use `find` here.

2021-01-13 09:23 UTC, Lynesth commented on src/cards/base/RoboticWorkforce.ts
> +        throw new Error('not enough heat production');
This is missing the check for megaCredits as well.
But I noticed you have a `hasProduction` method in Units, why not use that instead ?

2021-01-13 12:52 UTC, sienmich requested changes

2021-01-13 12:52 UTC, sienmich commented on src/cards/base/RoboticWorkforce.ts
> +        new Updater(CardName.NATURAL_PRESERVE_ARES, {energy: 1}),
MC, not energy

2021-01-13 13:28 UTC, kberg commented on src/cards/base/RoboticWorkforce.ts
> +        new Updater(CardName.NATURAL_PRESERVE_ARES, {energy: 1}),
Thanks.

2021-01-13 13:28 UTC, kberg commented on src/cards/base/RoboticWorkforce.ts
> +        throw new Error('not enough heat production');
I didn't know whether the error codes were meaningful.

2021-01-13 13:29 UTC, kberg commented
> Haven't checked that you didn't mess up the conversion from arguments to units in the `updaters` array.

Really, good point. I'm going to verify correctness using a spreadsheet today. You two have already found two errors, and I should have bothered to do this work first. Mea culpa. Sorry about that.

2021-01-13 18:55 UTC, kberg reviewed
> Haven't checked that you didn't mess up the conversion from arguments to units in the `updaters` array.

Here is my verification:

https://docs.google.com/spreadsheets/d/1u1K3tZIdnjJYs97yaSk7JffvDAIjqxANWC06yWpAWOk/edit#gid=0

I eyeballed everything and it's correct. That @sienmich found an error is because the base data was in error. Moving this stuff over to the card itself will eliminate any future risk of error.

2021-01-13 18:55 UTC, kberg commented on src/cards/base/RoboticWorkforce.ts
> +        new Updater(CardName.NATURAL_PRESERVE_ARES, {energy: 1}),
So you know, the linne to the right does list it under energy.

2021-01-13 18:57 UTC, kberg commented on src/cards/base/RoboticWorkforce.ts
> +        new Updater(CardName.NATURAL_PRESERVE_ARES, {energy: 1}),
Fixed.

2021-01-14 02:28 UTC, bafolts commented on src/cards/Card.ts
> +    return this.properties.productionDelta;
Tests still passing is good enough for me. A test written for this change would mostly be verifying that javascript sets a property which seems like overkill. Assuming that `RoboticWorkforce` has a unit test that relies on this value being set that is verifying this change works.

2021-01-15 01:32 UTC, bafolts approved these changes

2021-01-15 03:21 UTC, kberg commented on src/cards/base/RoboticWorkforce.ts
> +        new Updater(CardName.NATURAL_PRESERVE_ARES, {energy: 1}),
@sienmich I am blocked on submitting this until you release the changes request.

2021-01-15 09:24 UTC, sienmich approved these changes

2021-01-15 09:30 UTC, merged