Sorting blue cards in a sensible way
bafolts/terraforming-mars pull request #2365
Opened 2021-01-14 01:22 UTC by vsrisuknimit

Played blue cards and activate-able blue cards are sorted following the list in ActiveCardSortingOrder.ts. 

![image](https://user-images.githubusercontent.com/14239220/104531596-7d66fe80-55dc-11eb-86f5-629c7aa46d26.png)

This PR can close #1606 .

- - -

- I am concerned that we are sorting this every time and not saved anywhere. The amount of total blue cards are small (119), so maybe that is fine?
- I also don't like this line `cardType.length === 1 && cardType[0] === CardType.ACTIVE` If length = 0, cardType[0] would be a problem. Nested if looks ugly, but I don't know how to write it better.

2021-01-15 01:37 UTC, bafolts commented on src/ActiveCardsSortingOrder.ts
> +].reduce((acc: Array<[CardName, number]>, card, index) => {
This is using `reduce` as `map`. I would instead use `map`.

```
.map((card, index) => [card, index]);
```

2021-01-15 01:45 UTC, Lynesth commented on src/ActiveCardsSortingOrder.ts
> +].reduce((acc: Array<[CardName, number]>, card, index) => {
I knew I was being stupid when I wrote that -_-

2021-01-15 02:04 UTC, bafolts requested changes
We allow the user to order cards by dragging them. The order of the cards displayed is handled within `CardOrderStorage`. 

This change will have to go within `CardOrderStorage` so that it can work with it. Within the `StackedCards` component we should then use the order that `CardOrderStorage` mandates.

2021-01-15 02:08 UTC, vsrisuknimit commented on src/Player.ts
> +      return (ActiveCardsSortingOrder.get(cardA.name) || -1) - (ActiveCardsSortingOrder.get(cardB.name) || -1);
@bafolts Currently you cannot sort that you are performing an action. You can only sort cards in hand. This PR only applies to Played Cards.

![image](https://user-images.githubusercontent.com/14239220/104671828-90e19a80-56ac-11eb-9151-cba896356443.png)

2021-01-15 02:09 UTC, vsrisuknimit commented on src/components/PlayerMixin.ts
> +      console.log('sortActiveCards called.');
Sorry. I will remove it.

2021-01-15 02:16 UTC, vsrisuknimit commented on src/Player.ts
> +      return (ActiveCardsSortingOrder.get(cardA.name) || -1) - (ActiveCardsSortingOrder.get(cardB.name) || -1);
The sorting does take effect. While performing an action, you will cash generator in the front, follow with card draw, and so on according to the list.

2021-01-15 02:37 UTC, bafolts commented on src/Player.ts
> +      return (ActiveCardsSortingOrder.get(cardA.name) || -1) - (ActiveCardsSortingOrder.get(cardB.name) || -1);
Any `SelectCard` is applying the order you may have sorted from within your hand. If you ordered the card before playing it I assume it would be displayed in that order here.

https://github.com/bafolts/terraforming-mars/blob/main/src/components/SelectCard.ts#L86

2021-01-15 02:49 UTC, vsrisuknimit commented on src/Player.ts
> +      return (ActiveCardsSortingOrder.get(cardA.name) || -1) - (ActiveCardsSortingOrder.get(cardB.name) || -1);
You are right. That is not good. That mean once a card is played the order of action cannot be rearranged. I think it will be better for these blue cards being activated to be auto arranged accordingly to the list I provided.

2021-01-15 02:51 UTC, bafolts commented on src/Player.ts
> +      return (ActiveCardsSortingOrder.get(cardA.name) || -1) - (ActiveCardsSortingOrder.get(cardB.name) || -1);
I would do both. If as a user you have dragged it that takes precedent. If you have not dragged the card then use the order from the pre-defined list. I could put all this logic in `CardOrderStorage` to let that contain all the card sorting logic.

2021-01-15 02:52 UTC, vsrisuknimit commented on src/Player.ts
> +      return (ActiveCardsSortingOrder.get(cardA.name) || -1) - (ActiveCardsSortingOrder.get(cardB.name) || -1);
Sometimes you drag card in hand because you want to play them first. Activating the cards is a different matter. I don't think it should rely on the order while it was in hand at all.

2021-01-15 03:02 UTC, bafolts commented on src/Player.ts
> +      return (ActiveCardsSortingOrder.get(cardA.name) || -1) - (ActiveCardsSortingOrder.get(cardB.name) || -1);
I agree.

There are complexities being introduced here. We create the `SelectCard` on the server but display it on the client. May need to re-factor when we are sorting the cards and not do it by default inside `SelectCard`. One problem is that the user defined drag order is only available on the client. 

What if we update the logic inside `SelectCard` and when calling to get ordered cards we pass an argument for the cards that are in the players hand. If we see the card is still in your hand then we use the dragged order. If the card is not in your hand then we rely on any defaults that may be defined.

2021-01-15 20:46 UTC, vsrisuknimit commented on src/Player.ts
> +      return (ActiveCardsSortingOrder.get(cardA.name) || -1) - (ActiveCardsSortingOrder.get(cardB.name) || -1);
@bafolts I modified SelectCard to now have isBlueAction value. It should be false by default. playActionCard will assign isBlueAction to true. When that happens, getOrderedCards in SelectCard will return the order according to the ActiveCardsSortingOrder instead of CardOrderStorage.

2021-01-16 01:17 UTC, bafolts commented on src/Player.ts
> +      return (ActiveCardsSortingOrder.get(cardA.name) || -1) - (ActiveCardsSortingOrder.get(cardB.name) || -1);
Is there a problem with the solution I proposed? Using a field for `isBlueAction` doesn't seem like it will scale well. For the next specific `SelectCards` we want to sort will we then do some other `isAnotherAction` flag? Before you spend time coding towards some solution I think we need to agree on what that solution is going to be. 

I am still curious as to your thoughts towards the solution I proposed yesterday.

> What if we update the logic inside SelectCard and when calling to get ordered cards we pass an argument for the cards that are in the players hand. If we see the card is still in your hand then we use the dragged order. If the card is not in your hand then we rely on any defaults that may be defined.

If the card is in your hand using the order you have dragged the cards makes sense to me. When the card is not in your hand using the `ActiveCardsSortingOrder` also makes sense to me. We know which cards are in your hand through `PlayerModel::cardsInHand` so the look-up should be an `Array.prototype.find` on a small number of cards. This solution shouldn't involve any server side changes nor data model changes.

2021-01-16 01:35 UTC, vsrisuknimit commented on src/Player.ts
> +      return (ActiveCardsSortingOrder.get(cardA.name) || -1) - (ActiveCardsSortingOrder.get(cardB.name) || -1);
@bafolts I did not realize we have a way to look up `PlayerModel::cardsInHand`. I was trying to do what you suggested but I went it in a round about way. I only focus if it is blueAction instead so as to disturb the least number of things. I was not sure if anything else should rely on the CardOrderStorage other than cardsInHand.

2021-01-16 01:40 UTC, vsrisuknimit commented on src/Player.ts
> +      return (ActiveCardsSortingOrder.get(cardA.name) || -1) - (ActiveCardsSortingOrder.get(cardB.name) || -1);
So far, the only two things that I think need sorting are just these two: All Played Blue Cards and Blue Cards that you are activating. SelectCards is used in so many things. I don't want it to sort anything else.

2021-01-16 18:54 UTC, vsrisuknimit commented on src/Player.ts
> +      return (ActiveCardsSortingOrder.get(cardA.name) || -1) - (ActiveCardsSortingOrder.get(cardB.name) || -1);
@bafolts let me know how I should proceed.

2021-01-17 02:40 UTC, bafolts requested changes
As long as the sorting is all client side this approach is fine. I have minor suggestions and questions left.

2021-01-17 02:40 UTC, bafolts commented on src/ActiveCardsSortingOrder.ts
> +export const ActiveCardsSortingOrder: Map<CardName, number> = new Map([
This is only used by the front end. Plan is to eventually move front end related code to it's own directory. For the time being I think this makes more sense in `src/components/ActiveCardsSortingOrder` since it is for use with a front end component.

2021-01-17 02:40 UTC, bafolts commented on src/components/PlayerMixin.ts
> +      return inCards.sort(function(cardA, cardB) {
The call to `sort` modifies the array. This could have unintended consequences if the caller doesn't know the array is going to be sorted. I would use `inCards.slice().sort` to sort a copy of the array instead.

2021-01-17 02:40 UTC, bafolts commented on src/components/PlayerMixin.ts
> +        return (ActiveCardsSortingOrder.get(cardA.name as CardName) || 0) - (ActiveCardsSortingOrder.get(cardB.name as CardName) || 0);
Using `0` when the card is not found is going to give it the same precedence as `CardName.EARTH_CATAPULT` which also has a value of `0`. Is this intentional? When a card is not found is it supposed to go to the end or beginning of the resulting list?

2021-01-17 02:40 UTC, bafolts commented on src/components/PlayerMixin.ts
> +      if (cardType.length === 1 && cardType[0] === CardType.ACTIVE) {
Instead of assuming the caller of `getCardsByType` wants this sort order I would instead wrap the call to `getCardsbyType` with `sortActiveCards`.

```
sortCards(getCardsByType(cards, [CardType.ACTIVE]);
```

This will avoid having to guess when we want to use this sorting.

2021-01-17 02:40 UTC, bafolts commented on src/components/SelectCard.ts
> +        return this.playerinput.cards.sort(function(cardA, cardB) {
This is duplicating `sortActiveCards`. I would re-use the same implementation.

2021-01-17 19:12 UTC, vsrisuknimit commented on src/ActiveCardsSortingOrder.ts
> +export const ActiveCardsSortingOrder: Map<CardName, number> = new Map([
Moved to components folder

2021-01-17 20:23 UTC, vsrisuknimit commented on src/components/PlayerMixin.ts
> +      if (cardType.length === 1 && cardType[0] === CardType.ACTIVE) {
wrap it now

2021-01-17 20:23 UTC, vsrisuknimit commented on src/components/SelectCard.ts
> +        return this.playerinput.cards.sort(function(cardA, cardB) {
made a function in ActiveCardsSortingOrder.ts and export it

2021-01-17 20:24 UTC, vsrisuknimit commented on src/components/PlayerMixin.ts
> +        return (ActiveCardsSortingOrder.get(cardA.name as CardName) || 0) - (ActiveCardsSortingOrder.get(cardB.name as CardName) || 0);
It should go toward the end. I changed it to be ActiveCardsSortingOrder.size.

2021-01-17 20:25 UTC, vsrisuknimit commented on src/components/PlayerMixin.ts
> +      return inCards.sort(function(cardA, cardB) {
I added slice at first. @Lynesth thought it was fine not to make a copy. Added slice back..

2021-01-17 23:09 UTC, bafolts approved these changes
Cool! No complaints at this point. :shipit:

2021-01-17 23:10 UTC, merged