Game setup details on
bafolts/terraforming-mars pull request #2372
Opened 2021-01-14 13:45 UTC by vsrisuknimit

This PR can close #1598.

Currently I will focus on the admin page but it would be good to be able to see it during the game as well from the player link.

2021-01-15 02:00 UTC, vsrisuknimit commented
![image](https://user-images.githubusercontent.com/14239220/104671023-f6348c00-56aa-11eb-8ed3-5ce16acd65de.png)

So far this is only in the GameHome page. I am not quite sure what if we need all of these in the main game page. Perhaps just soloTR?

Is it safe to pass GameOption to player? Would that undermine any security and allow the player access to the admin page?

2021-01-15 02:16 UTC, bafolts commented on src/components/GameHome.ts
> +          <div v-html="getSoloDetail(game.gameOptions)"></div>
Using `v-html` is an anti-pattern. It doesn't allow us to take advantage of anything vue offers. Convert all of the functions to vue templates. For example the `getSoloDetail` is:

```
<div>Solo mode: {{gameOptions.soloTR ? "63 TR" : "All parameters"}}</div>
```

2021-01-15 02:19 UTC, bafolts commented on src/models/GameHomeModel.ts
> +    gameOptions: GameOptions;
This will need a `GameOptionsModel`. The types of `GameOptionsModel` need to be JSON ready and tailored for client side.

2021-01-15 02:23 UTC, bafolts requested changes
None of the data in `GameOptions` should pose a security concern. The `clonedGamedId` is the only one that would indirectly expose the game so I wouldn't include that with `GameOptionsModel`.

In other places (notably Turmoil) we make use of `v-html` often. Using `v-html` should be a last resort. We should have no need for `v-html` now that the cards are no longer stored in HTML. The `v-html` attribute should only be used if we had raw HTML data that we needed to display somewhere, we shouldn't use it in places where we are generating HTML client side.

Once `v-html` isn't used and the `GameOptionsModel` is added this looks good to merge.

2021-01-15 03:20 UTC, vsrisuknimit commented on src/models/GameHomeModel.ts
> +    gameOptions: GameOptions;
I am super lost about what to do here.

2021-01-15 03:30 UTC, vsrisuknimit commented on src/components/GameHome.ts
> +          <div v-html="getSoloDetail(game.gameOptions)"></div>
I am converting but I thought v-if does not like enum. Is there a way around it than making one method to check each enum?

2021-01-15 12:50 UTC, vsrisuknimit commented on src/components/GameHome.ts
> +          <div v-html="getSoloDetail(game.gameOptions)"></div>
Removed all v-html. Still have some methods for nested if statement or dealing with enum.

2021-01-15 14:10 UTC, chosta reviewed
Looks good to me. We just need to see what to do with @bafolts's advice.

2021-01-15 14:10 UTC, chosta commented on src/components/GameSetupDetail.ts
> +        <div id="game-setup-detail" class="game-setup-detail-container">
please, add some offset to the right so that stuff is aligned with the container above

2021-01-15 15:28 UTC, kberg commented on src/models/GameHomeModel.ts
> +    gameOptions: GameOptions;
Hope my chat was helpful

2021-01-15 17:48 UTC, vsrisuknimit commented on src/models/GameHomeModel.ts
> +    gameOptions: GameOptions;
@kberg Perhaps to @chosta but it was a bit above my level. Thank you though.

2021-01-16 02:08 UTC, vsrisuknimit commented on src/components/GameSetupDetail.ts
> +    if (this.game !== undefined && this.game.players.length === 1) return 'N/A';
Milestones Awards: for solo game looks weird. Technically no one should see this at all. Solo games skip this page.

2021-01-16 02:09 UTC, vsrisuknimit commented on src/components/GameSetupDetail.ts
> +  getGameConfigs: function(gameOptions: GameOptions): string {
Remove this now.

2021-01-16 02:09 UTC, vsrisuknimit commented on src/components/GameSetupDetail.ts
> +        <div id="game-setup-detail" class="game-setup-detail-container">
Added

2021-01-16 02:25 UTC, vsrisuknimit commented on src/components/GameHome.ts
> +        <br>
added spacing by a different div instead. I may want to call game-setup-detail from a different location without the header whitespace.

2021-01-16 02:33 UTC, vsrisuknimit commented on src/components/GameSetupDetail.ts
> +  getMilestonesAwardsDetail: function(gameOptions: GameOptions): string {
Please do. Thank you.

2021-01-16 02:38 UTC, vsrisuknimit commented
Current design. Still waiting for the fixed GameHomeModel.

![image](https://user-images.githubusercontent.com/14239220/104795122-fcde0480-5779-11eb-93a7-a5e40e3f852d.png)

2021-01-16 21:21 UTC, vsrisuknimit commented
This PR is superseded by #2426 .

2021-01-16 21:21 UTC, closed without merging