Refactored cards requirements.
bafolts/terraforming-mars pull request #2378
Opened 2021-01-14 18:34 UTC by sienmich

Right now every card has it's requirements in 3 places:

1. `metadata.requirements`
2. `metadata.description`
3. canPlay() method

This PR makes 3. (`canPlay()`) automatically from the 1. (`metadata.requirements`).

More specifically:
In the `abstract class Card` I added this method:
```ts
  public canPlay(player: Player, _game?: Game) {
    if (this.properties.metadata.requirements === undefined) {
      return true;
    }
    return this.properties.metadata.requirements.satisfies(player);
  }
```
Now every card with requirements either does not implement it's own `canPlay()` or uses `super()` inside of it.
Checking the requirements is inside the `CardRequirement` class.

2021-01-14 19:00 UTC, sienmich commented
Additionally I'd like soon to generate requirements in `metadata.description` automatically. This could help removing inconsistencies like `Requires +2 C` vs `Requires +2 C°`. It's harder because of translations. Please let me know what u think about it.

2021-01-15 02:30 UTC, Lynesth commented on src/cards/CardRequirement.ts
> +        .map((res) => player.getResource(res)).filter((count) => count > 0).length;
```ts
      const standardResources = [Resources.MEGACREDITS, Resources.STEEL, Resources.TITANIUM, Resources.PLANTS, Resources.ENERGY, Resources.HEAT]
        .filter((res) => player.getResource(res) > 0).length;
```

2021-01-15 02:30 UTC, Lynesth commented on src/cards/CardRequirement.ts
> +      const nonStandardResources = player.getCardsWithResources().map((card) => card.resourceType).filter((v, i, a) => a.indexOf(v) === i).length;
Just a thought:
```ts
      const nonStandardResources = new Set(player.getCardsWithResources().map((card) => card.resourceType)).size;
```

2021-01-15 02:30 UTC, Lynesth commented on src/cards/CardRequirement.ts
> +      return this.satisfiesInequality(greeneries);
Just an idea to prevent looping the whole board each time:
```ts
      let greeneries = 0;
      return player.game.board.spaces.some((space) => {
        if (space.tile?.tileType === TileType.GREENERY && (space.player.id === player.id || this._isAny)) {
          greeneries++;
          return this.satisfiesInequality(greeneries);
        } else {
          return false;
        }
      });
```

But maybe the number of cities/greeneries/oceans could already be saved on the board directly ?

2021-01-15 02:52 UTC, kberg reviewed
What concerns me about this PR is that it starts to conjoin behavior and visualization a little closer than I'm clear, yet, is a good idea. Once we go down this path, it's hard to come back.  But look -- I'm happy to hear other peoples' opinions. I won't be reviewing this tonight, though.

2021-01-15 02:52 UTC, kberg commented on src/cards/CardRequirement.ts
> +      if (player.game.turmoil !== undefined) {
return player.game.turmoil?.chairman === player.id;

2021-01-15 08:52 UTC, sienmich commented on src/cards/CardRequirement.ts
> +      return this.satisfiesInequality(greeneries);
It's not working, because `satisfiesInequality` sometimes checks for <=, sometimes for >=.

2021-01-15 09:18 UTC, sienmich commented
> What concerns me about this PR is that it starts to conjoin behavior and visualization a little closer than I'm clear, yet, is a good idea. Once we go down this path, it's hard to come back. But look -- I'm happy to hear other peoples' opinions. I won't be reviewing this tonight, though.

Well, all I can say is that it is a good idea in my opinion. Card visualization is a representation of its behavior. Having less redundancy between them should lead to less bugs, less inconsistency, more readable code. And much nicer and faster new cards implementation.

2021-01-15 09:23 UTC, chosta commented
I like where this is going. I have one concern for the automatic description though. Printing the description for cards in an automated manner would work well for a card that has nothing else to add as a description but not so well for cards with bigger descriptions. Example:
`Advanced Ecosystems` -> `(Requires a Plant tag, a Microbe tag, and an Animal tag.)`
but
`AI Central` -> `(Requires 3 Science tags to play. Decrease your Energy production 1 step.)`

You probably intend to prepend the automated description but this mean the rest of it should be written as "Decrease your Energy Production 1 step" which would look incomplete when added to the metadata. You would then probably want to automate the second part of the description too, which could be easy for most of the cards but there are some exceptions with more customized descriptions like `Desperate Measures` where you'd need custom text describing the card. I'm just raising awareness of the 80/20 problem that we might have here and whether we should take the path to complete description automation (which I support).

2021-01-15 09:32 UTC, Lynesth commented on src/cards/CardRequirement.ts
> +      return this.satisfiesInequality(greeneries);
Ah yeah, we'd either have to make 2 different loops depending on isMax:
```ts
      const countGreenery = (space: ISpace) => space.tile?.tileType === TileType.GREENERY && (space.player.id === player.id || this._isAny);
      let greeneries = 0;
      if (isMax) {
        return player.game.board.spaces.every((space) => {
          if (countGreenery(space)) {
            greeneries++;
            return this.satisfiesInequality(greeneries);
          } else {
            return true;
          }
        });
      } else {
        return player.game.board.spaces.some((space) => {
          if (countGreenery(space)) {
            greeneries++;
            return this.satisfiesInequality(greeneries);
          } else {
            return false;
          }
        });
      }
```

Or you could do it like this I guess:
```ts
      let greeneries = this.isMax ? this.amount * 2 : 0;
      return player.game.board.spaces.some((space) => {
        if (space.tile?.tileType === TileType.GREENERY && (space.player.id === player.id || this._isAny)) {
          this.isMax ? greeneries-- : greeneries++;
          return this.satisfiesInequality(greeneries);
        } else {
          return false;
        }
      });
```

2021-01-15 09:43 UTC, sienmich commented on src/cards/CardRequirement.ts
> +      return this.satisfiesInequality(greeneries);
Nice, clever cheat :). I think the original looping through all spaces is not that computational consuming (half of the times we have to loop all board spaces anyway), and is simpler. So I'd leave it as it is?

2021-01-15 09:50 UTC, chosta requested changes
Apart from some organizational issues which should be just advice for future PRs, I'm mostly satisfied. What I'd like to see is some good unit test coverage on the `satisfies` functionality though.

2021-01-15 09:50 UTC, chosta commented on src/cards/ares/EcologicalSurvey.ts
> +        requirements: CardRequirements.builder((b) => b.greeneries(3).any()),
Not important but this got me a bit confused as it probably belongs to a different PR or at least a separate commit.

2021-01-15 09:50 UTC, chosta commented on src/cards/ares/GeologicalSurvey.ts
> +        requirements: CardRequirements.builder((b) => b.greeneries(5).any().max()),
Same here

2021-01-15 09:50 UTC, chosta commented on src/cards/colonies/CoronaExtractor.ts
> +  constructor() {
So here you are just moving things in the constructor I guess. Should be a separate PR imo.

2021-01-15 09:50 UTC, chosta commented on src/cards/CardRequirement.ts
> +  protected satisfiesInequality(calculated: number) : boolean {
This needs unit tests :) The whole `satisfies` functionality I mean.

2021-01-15 09:50 UTC, chosta commented on src/cards/CardRequirement.ts
> +    case RequirementType.COLONIES:
Will this work for `Pioneer Settlement` where the requirements has `max()` too. (Maybe it passes the tests, not sure I've covered it properly.

2021-01-15 09:58 UTC, chosta commented
> What concerns me about this PR is that it starts to conjoin behavior and visualization a little closer than I'm clear, yet, is a good idea. Once we go down this path, it's hard to come back. But look -- I'm happy to hear other peoples' opinions. I won't be reviewing this tonight, though.

Opionion:
I'm with you on the `behaviour + viz` part but to be honest but these days I'm more inclined to sacrifice a bit of clean and lean for handy and automated.

2021-01-15 10:22 UTC, sienmich commented on src/cards/ares/EcologicalSurvey.ts
> +        requirements: CardRequirements.builder((b) => b.greeneries(3).any()),
I had to change this, so for EcologicalSurvey the satisfies() is working good. Ok, next time I can separate the commits better :)

2021-01-15 10:26 UTC, sienmich commented on src/cards/CardRequirement.ts
> +    case RequirementType.COLONIES:
It will, the `satisfiesInequality` checks for min / max

2021-01-15 16:10 UTC, chosta approved these changes
Please, check what I did for CardRenderer tests concerning global requirements here #2375

Maybe it's a good idea to make sure requirements are inside bounds too.

2021-01-15 16:30 UTC, merged