Simplified some cards with the new `canPlay()`
bafolts/terraforming-mars pull request #2405
Opened 2021-01-15 17:50 UTC by sienmich

2021-01-15 18:01 UTC, kberg commented on src/cards/base/Capital.ts
> +    return super.canPlay(player) &&
So, this is tricky. I would like to avoid calling super.canPlay() with EVERY call to canPlay. In the same way standard projects have their `essense` methods, the same thing would apply here. However, I don't recommend calling it `essence` because the global parameters are what you might also call _essential._

2021-01-15 18:04 UTC, kberg commented on src/cards/base/Capital.ts
> +    return super.canPlay(player) &&
I'll add: I'm doing something mildly similar with Moon behaviors, but my long-term plan is to keep The Moon outside key code execution paths until it's more easily adopted, and also because Moon cards don't need the same degree of backward compatibility that these cards need. It is why I consider that a slightly separate case.

2021-01-15 19:20 UTC, sienmich commented on src/cards/base/Capital.ts
> +    return super.canPlay(player) &&
Agree. Pushed. I called it `canPlayAdditionalChecks`.

2021-01-18 11:08 UTC, sienmich commented on src/cards/prelude/LavaTubeSettlement.ts
> +  protected canPlayAdditionalChecks(player: Player, game: Game): boolean {
```suggestion
  protected canPlayAdditionalChecks(player: Player): boolean {
```

2021-01-18 15:43 UTC, kberg requested changes

2021-01-18 15:43 UTC, kberg commented on src/cards/Card.ts
> +    if (this.properties.metadata.requirements?.satisfies(player) === false) {
This statement here is why I am concerned about having requierments in metadata. Metadata is DATA. But what this method shows is metadata having BEHAVIOR.

2021-01-18 15:43 UTC, kberg commented on src/cards/Card.ts
> +  public canPlay(player: Player, game?: Game) {
Hmm. We can do better.

As far as I can tell, canPlay is called in five places: `Player`, `ValleyTrust`, `Tactician`, `Playwright` and `CuttingEdgeTechnology`.

The most important one is in `Player.getPlayableCards` which reads like this

```
getPlayableCards() {
  player.cardsInHand.filter((card) => {
    // lots of checks for money and costs.
    if (player.canAfford(cost) && card.canPlay(player, card)) {
      return true;
    };
  }
}
```

That can be simplified by breaking out that whole method into its own. Which I'm going to sneakily call `canPlay` So now there's Player.canPlay(card) and IProjectCard.canPlay(...);

I submit that the right place to make this change is to put it in there. And then the other four classes that use card.canPlay() can adjust accordingly as they need to.

The problem with this is that it changes the way all our tests will need to work. Right now, calling `card.canPlay` is enough, but it won't be. Moving canPlay behavior into Player means cards have to go down that route, which means calling the new `Player.canPlay(card)`. Which includes just one more wrinkle: `Player.canPlay` includes the megacredit cost of a card. That's easy: these tests which are moving from calling card.canPlay to Player.canPlay() also need a set-up step that incldues megacredits.

AND THEN

Once that's done we can start thinking about how to move all the additional cost checks for cards that raise the TR rate. But that's also tricky, and worth discussion at a later point.

Once that settles down, the same change can

2021-01-18 16:54 UTC, kberg commented on src/cards/Card.ts
> +  public canPlay(player: Player, game?: Game) {
Take a look at https://github.com/bafolts/terraforming-mars/pull/2444 as an example of how I'm doing similar things.

2021-01-27 17:10 UTC, sienmich commented
First I'll move the `requirements` to the card from the card metadata, then I'll create new PR similar to this one, in which the `canPlay` will be simplified.

2021-01-27 17:10 UTC, closed without merging