Create CONTRIBUTING.md
bafolts/terraforming-mars pull request #2451
Opened 2021-01-17 17:37 UTC by kberg

@bafolts I added a "questions" section at the bottom.

2021-01-17 18:52 UTC, vsrisuknimit requested changes

2021-01-17 18:52 UTC, vsrisuknimit commented on CONTRIBUTING.md
> +[Post an issue](https://github.com/bafolts/terraforming-mars/issues/new) or [Find us on Discord](https://discord.gg/AUfyx5ba)
This specific Discord invite code that you created is valid for 24 h. Please use https://discord.gg/fWXE53K that is the same one of Readme.MD.

2021-01-17 18:54 UTC, kberg commented on CONTRIBUTING.md
> +[Post an issue](https://github.com/bafolts/terraforming-mars/issues/new) or [Find us on Discord](https://discord.gg/AUfyx5ba)
Thanks!

2021-01-18 16:30 UTC, vsrisuknimit commented
The discord link looks good. It sounds reasonable. But again I am not qualified to review anything haha. Tagging @bafolts to look at it.

2021-01-18 16:31 UTC, vsrisuknimit submitted a review, later dismissed

2021-01-18 16:31 UTC, vsrisuknimit commented
Wait I approved the one specific change or did I approve the whole thing. I am confused. Sorry.

2021-01-18 16:36 UTC, kberg commented
> Wait I approved the one specific change or did I approve the whole thing. I am confused. Sorry.

Well, you did approve the whole thing. But I can wait. You can change your approval state if you don't want me to submit yet.

Or, just  go back to suggesting more changes.

2021-01-18 16:39 UTC, vsrisuknimit commented
Let's wait for @bafolts .

2021-01-18 16:49 UTC, bafolts approved these changes
This looks good. :shipit:

2021-01-18 16:49 UTC, merged