Standardize and rename standard projects, and move them to their respective directories.
bafolts/terraforming-mars pull request #2458
Opened 2021-01-18 03:27 UTC by kberg

2021-01-18 10:40 UTC, sienmich requested changes

2021-01-18 10:40 UTC, sienmich commented on src/cards/turmoil/TurmoilCardManifest.ts
> +    {cardName: CardName.BUFFER_GAS_STANDARD_PROJECT, Factory: BufferGasStandardProject},
Buffer Gas comes from Prelude expansion, not Turmoil

2021-01-18 10:40 UTC, sienmich commented on src/cards/standardProjects/SellPatents.ts
>  import {CardMetadata} from '../CardMetadata';
There are now two Sell Patents copies (same with other SPs). Is it intentional?

2021-01-18 10:40 UTC, sienmich commented on src/cards/base/standardProjects/SellPatentsStandardProject.ts
> +import {Player} from '../../../Player';
There are now two Sell Patents copies (same with other SPs). Is it intentional?

2021-01-18 10:40 UTC, sienmich commented on src/cards/turmoil/TurmoilCardManifest.ts
> +    {cardName: CardName.BUFFER_GAS_STANDARD_PROJECT, Factory: BufferGasStandardProject},
https://boardgamegeek.com/filepage/166087/terraforming-mars-prelude-stronghold-games-english

2021-01-18 17:48 UTC, kberg commented on src/cards/standardProjects/SellPatents.ts
>  import {CardMetadata} from '../CardMetadata';
This turned out to be a little sloppier than I expected. Give me some time to clean it up.

2021-01-19 07:03 UTC, kberg commented on src/cards/base/standardProjects/SellPatentsStandardProject.ts
> +import {Player} from '../../../Player';
My bad, this one should stay, the others should go.

2021-01-19 07:06 UTC, kberg commented on src/cards/turmoil/TurmoilCardManifest.ts
> +    {cardName: CardName.BUFFER_GAS_STANDARD_PROJECT, Factory: BufferGasStandardProject},
Whoops! Fixed.

2021-01-19 10:25 UTC, sienmich approved these changes
Looks good now. Just those two peeky things, feel free to ignore them

2021-01-19 10:25 UTC, sienmich commented on src/CardName.ts
> +    AIR_SCRAPPING_STANDARD_PROJECT = 'Air Scrapping',
You moved Air Scrapping to the Venus part here, but the Buffer Gas and Colony are still at the top

2021-01-19 10:25 UTC, sienmich commented on src/CardName.ts
> +    ASTEROID_STANDARD_PROJECT = 'Asteroid:SP',
I'm not sure if having some of them with ':SP' and some without is good idea.

2021-01-19 14:21 UTC, kberg commented on src/CardName.ts
> +    AIR_SCRAPPING_STANDARD_PROJECT = 'Air Scrapping',
The card names in this enum are all commingled, and then there started to be a separation by type. I'm not sure really what to do here. Perhaps throw caution to the wind and alphabetize the whole thing?

2021-01-19 14:21 UTC, kberg commented on src/CardName.ts
> +    ASTEROID_STANDARD_PROJECT = 'Asteroid:SP',
It should be OK. You only need to :separator when when two cards have the same name.

2021-01-19 14:39 UTC, merged

2021-01-19 14:40 UTC, kberg commented
Thanks!