Fix wordings
bafolts/terraforming-mars pull request #2482
Opened 2021-01-19 23:04 UTC by vsrisuknimit

This PR can close #2357 .

2021-01-19 23:52 UTC, kberg requested changes

2021-01-19 23:52 UTC, kberg commented on src/CardName.ts
> -    CEOS_FAVORITE_PROJECT = 'CEOs Favorite Project',
Cards cannot be renamed. This will break all past games. Unfortunately this file can't be in the PR.

2021-01-19 23:52 UTC, kberg commented on src/CardName.ts
> -    CEOS_FAVORITE_PROJECT = 'CEOs Favorite Project',
This is tied, amusingly, to my comment wishing card numbers were our indexes.

2021-01-20 00:10 UTC, vsrisuknimit commented on src/CardName.ts
> -    CEOS_FAVORITE_PROJECT = 'CEOs Favorite Project',
What is the problem with breaking all past games?

2021-01-20 00:11 UTC, vsrisuknimit commented on src/CardName.ts
> -    CEOS_FAVORITE_PROJECT = 'CEOs Favorite Project',
Old games are deleted anyway. It is a demo server nothing is promised to be kept.

2021-01-20 00:42 UTC, kberg commented on src/CardName.ts
> -    CEOS_FAVORITE_PROJECT = 'CEOs Favorite Project',
It breaks all games in progress.

2021-01-20 01:18 UTC, vsrisuknimit commented on src/CardName.ts
> -    CEOS_FAVORITE_PROJECT = 'CEOs Favorite Project',
So? Updates did that in the past. People make new games.

2021-01-20 03:45 UTC, kberg commented on src/CardName.ts
> -    CEOS_FAVORITE_PROJECT = 'CEOs Favorite Project',
Understood. I just spent a lot of December rewriting serialization in such a way that it maintained full backward compatibility over a period of time, and then removed the archiaic versions. In fact, I've held back on a turmoil backward compatibility serilaization fix because I realized when dismantling the old version after the requisite waiting period that I did it wrong, and that I'm going to need to repeat the process.

I understand that you want to rename these key values. Are you willing to let this file slip out of this PR for the time being, and I'll work on a safe channge like this?

2021-01-20 08:10 UTC, chosta commented on src/CardName.ts
> -    CEOS_FAVORITE_PROJECT = 'CEOs Favorite Project',
We should never make a change that breaks existing games knowingly. That is just bad customer care :) Let's leave the game breaking file out of this PR as @kberg for now.

2021-01-20 10:58 UTC, vsrisuknimit commented
@chosta @kberg  I reverted the specific change on `CardName.ts`. The changes to the names are left on the translation files since `CEO's` is not in use anyway by `CEOs`.

BTW, Rad-chem vs Rad-Suits was why @kevinb9n noticed they appeared out of order in the debug-ui. The capitalization.

2021-01-20 14:27 UTC, kberg commented
> @chosta @kberg I reverted the specific change on `CardName.ts`. The changes to the names are left on the translation files since `CEO's` is not in use anyway by `CEOs`.
> 
> BTW, Rad-chem vs Rad-Suits was why @kevinb9n noticed they appeared out of order in the debug-ui. The capitalization.

I'd love to fix them, just ... with a little more work.

2021-01-20 14:28 UTC, kberg commented on src/cards/prelude/ResearchCoordination.ts
> +        description: 'After being played, when you perform an action, the wild tag counts as any tag of your choice.',
I'm OK with the changes overall, but wonder why this was done. (Not a wording change, but I also assume it wasn't accidental.)

2021-01-20 15:21 UTC, vsrisuknimit commented on src/cards/prelude/ResearchCoordination.ts
> +        description: 'After being played, when you perform an action, the wild tag counts as any tag of your choice.',
@kberg to make it consistent with other cards that describe wild tag. Check with @kevinb9n .

2021-01-20 19:23 UTC, vsrisuknimit commented on src/cards/prelude/ResearchCoordination.ts
> +        description: 'After being played, when you perform an action, the wild tag counts as any tag of your choice.',
Mostly that description is shown in parentheses which is appropriate for the wild tag explanation. This is already in use in Septem Tribus. So I made it the same for these two cards.

2021-01-21 15:11 UTC, kevinb9n commented on src/cards/prelude/ResearchCoordination.ts
> +        description: 'After being played, when you perform an action, the wild tag counts as any tag of your choice.',
Basically the all-caps sans-serif style is used for cases where there is *no* iconographic depiction for the instruction.

2021-01-22 17:14 UTC, kberg approved these changes

2021-01-23 01:52 UTC, bafolts commented
Merge this branch with `main` to pickup the workflow change that runs `build-linux` and `build-windows`.

2021-01-23 02:58 UTC, vsrisuknimit commented
@bafolts I think I did it.

2021-01-23 03:01 UTC, bafolts commented
Success! Sorry for the inconvenience during the transition. With the `build-windows` check we run the `npm run build` on a windows machine. This should help us support windows users and avoid inadvertently breaking their builds.

2021-01-23 03:02 UTC, merged