Follow the rulebook for neutral greenery placement
bafolts/terraforming-mars pull request #2486
Opened 2021-01-20 05:57 UTC by daniel-ziegler

Instead of using RNG, discard cards to determine where neutral greeneries go.

This required updating `Board.getAdjacentSpaces` to return adjacent spaces in clockwise order, starting from the top left. I'll update the unit tests to verify that.

2021-01-20 06:30 UTC, kberg commented on src/boards/Board.ts
> +      const coordsInOrder = [
For the next person reading this, I suggest dropping `coordsInOrder` to `coords` and just add a comment indicating they're in clockwise order.

// Coordinates are in clockwise order. Order only ever matters during solo game set-up when placing
// starting forests. Since that is the only case where ordering matters, it is adopted here.

2021-01-20 06:30 UTC, kberg commented on src/boards/Board.ts
> +      const listsToConcat = coordsInOrder.map(([x, y]) => this.spaces.filter((adj) =>
I don't think what you're writing is bad, though I am lost by how line 73 works. That's OK. Still, let me ask this question: what if this method stayed as is, and ordering occurred in the solo set-up? That way there wouldn't need to be special code here, which is called probably thousands of times a game, just to handle the two calls needed for set-up? If adding a method `Board.getAdjacentSpace(space:, dx, dy): ISpace | undefined` makes it easier, then I'm all for that.

Another alternative: Cache the adjacent space definitions during board construction,

```
private readonly adjacency: Map<SpaceId, Array<number>>

getAdjacentSpaces(...) {
  return adjacency.get(spaceId).map((idx) => this.spaces[idx]));
}
```

Perhaps then we get a double win. I think that's better only because it's a one-time set-up and doesn't have to be considered when reading later on.

2021-01-20 06:31 UTC, kberg commented
If you want to not knock yourself out regarding the tests, just do the ordering test in one or two places.

2021-01-20 06:31 UTC, kberg commented
By the way, thanks for doing this. I was glad just to have the card draw for the cities, and didn't think through the forests, so I'm glad to see this being done.

2021-01-20 06:59 UTC, Lynesth requested changes

2021-01-20 06:59 UTC, Lynesth commented on src/Game.ts
> +  public discardForCost(toPlace: string) {
Could this use TileType ?

2021-01-20 06:59 UTC, Lynesth commented on src/boards/Board.ts
> +      const listsToConcat = coordsInOrder.map(([x, y]) => this.spaces.filter((adj) =>
I agree that the ordering should go into the solo setup functions as we don't care about it here, and it's increasing this function's execution time by a substantial amount.

2021-01-21 01:51 UTC, bafolts commented
Also glad to see this done. The official rule book is always right.

2021-01-21 01:54 UTC, Lynesth commented
> Also glad to see this done. The official rule book is always right.

What about making cards drawn from the top of the deck then ? :)

2021-01-21 05:15 UTC, daniel-ziegler commented
Thanks for the feedback! Putting the ordering in the solo setup would make sense, but it seems fiddly to reorder after the spaces the fact and I also would rather not duplicate the coordinate manipulation code for finding adjacent spaces.

What if I kept the ordering in `getAdjacentSpaces` but set up a map at setup to make it quick to find up spaces by coordinates? That would also speed up the function for other callers.

2021-01-21 05:37 UTC, Lynesth commented
> What if I kept the ordering in `getAdjacentSpaces` but set up a map at setup to make it quick to find spaces by coordinates? That would also speed up the function for other callers.

Sure, that would work. We were actually thinking of doing this in the upcoming days. What kind of map are you thinking about ?
Something like `Map<SpaceId,Space[]>` ?

2021-01-21 05:50 UTC, kberg commented
> > What if I kept the ordering in `getAdjacentSpaces` but set up a map at setup to make it quick to find spaces by coordinates? That would also speed up the function for other callers.
> 
> Sure, that would work. We were actually thinking of doing this in the upcoming days. What kind of map are you thinking about ?
> Something like `Map<SpaceId,Space[]>` ?

Except the flavor of this project is Map<SpaceId, Array<ISpace>>.

If this is the mechanism you use rather than the index into the full array, please be sure the clone this array on every call so as to prevent someone manipulating it.

The rest of the algorithm was much more expensive than an array clone, I think we can settle on this much memory improvement.

2021-01-21 06:51 UTC, daniel-ziegler commented
It seemed to me that going from (x,y) to SpaceID was hard so I was instead going to make a nested `Map<number, Map<number, Space>>` indexed first by `x` and then by `y`. Anything wrong with that plan?

2021-01-21 07:17 UTC, kberg commented
Is it hard, or inefficient? Now that it occurs at setup or deserialization
it's possibly the second one. But you do what you think is best, I'm
confident your change won't be so far from the finished result.

On Thu, Jan 21, 2021, 1:52 AM Daniel Ziegler <notifications@github.com>
wrote:

> It seemed to me that going from (x,y) to SpaceID was hard so I was instead
> going to make a nested Map<number, Map<number, Space>> indexed first by x
> and then by y. Anything wrong with that plan?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/bafolts/terraforming-mars/pull/2486#issuecomment-764424273>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADE6KJDBWOI2GGJNORVG3TS27FI7ANCNFSM4WKEUNPA>
> .
>

2021-01-21 07:24 UTC, Lynesth commented
Oh I meant an adjacentSpaces map, that, given 1 space id would give all the spaces adjacent to it.

2021-01-23 05:08 UTC, daniel-ziegler commented on src/Game.ts
> +  public discardForCost(toPlace: string) {
Done. `getSpaceByOffset` is used in `AresHazards.ts` though so the logging behavior there has changed slightly (and I haven't tested that it looks reasonable)

2021-01-23 05:10 UTC, daniel-ziegler commented on src/Game.ts
> +  public discardForCost(toPlace: string) {
BTW is the Ares hazard placement supposed to avoid tiles next to cities? (I know nothing about Ares)

2021-01-23 05:29 UTC, daniel-ziegler commented
Okay, I switched to the plan where adjacent spaces are precomputed in the constructor and made the test check the clockwise ordering. Let me know what you think!

2021-01-23 05:29 UTC, daniel-ziegler commented on src/boards/Board.ts
> +      const coordsInOrder = [
Done.

2021-01-23 05:29 UTC, daniel-ziegler commented on src/boards/Board.ts
> +      const listsToConcat = coordsInOrder.map(([x, y]) => this.spaces.filter((adj) =>
I went with the plan to cache adjacent space definitions.

2021-01-23 07:14 UTC, Lynesth commented on src/boards/Board.ts
> +      }
I have not tested this piece of code at all, but it should probably be a bit less costly (need to benchmark it I guess):
```ts
/*
 * Returns true inside the loop when it's done searching adjacent spaces
 * Returns false inside the loop to continue to the next iteration
 * /
const spaces: Array<ISpace> = [];
this.spaces.some((adj) => {
  if (adj.spaceType === SpaceType.COLONY) {
    return false;
  }
  if (adj.y > space.y + 2) {
    return true;
  }
  if (adj.y < space.y - 2 || adj.x < space.x - 2 || adj.x > space.x + 2) {
    return false;
  }
  const index = coords.findIndex(([x, y]) => x === adj.x && y === adj.y));
  if (index === -1) {
    return false;
  }
  spaces[index] = adj;
  if (spaces.length === 6) {
    return true;
  }
  return false;
});

return spaces.flat();
```

2021-01-23 07:14 UTC, Lynesth commented on src/boards/Board.ts
> +    this.maxY = Math.max(...spaces.map((s) => s.y));
I don't think this is necessary to keep this.
At the moment, it is hardcoded anyway that a board is of a certain number of rows and and certain number of tiles per row `[5, 6, 7, 8, 9, 8, 7, 6, 5]` so you can safely assume that both `maxX` and `maxY` are `8`.

But let's get @kberg and/or @bafolts opinions.

2021-01-23 07:16 UTC, Lynesth commented
That's the idea, thank you. I left a couple of comments but globally it looks good to me.

2021-01-23 13:17 UTC, kberg requested changes
Fairly minor comments, really.

2021-01-23 13:17 UTC, kberg commented on src/Game.ts
> +  public getSpaceByOffset(direction: -1 | 1, toPlace: TileType) {
Not related to what you did, but once this is done, I'm going to change getSpaceByOffset to take a number instead of being being responsible for dealing a card, and move it into Board where it should have been.

2021-01-23 13:17 UTC, kberg commented on src/Game.ts
> +  public getSpaceByOffset(direction: -1 | 1, toPlace: TileType) {
Don't go doing that, this is a nice simple PR for the moment. :D

2021-01-23 13:17 UTC, kberg commented on src/GameSetup.ts
> +      let idx = game.discardForCost(TileType.GREENERY);
This function is so much less complicated than before, if you feel like it, move it all into placeCityAndForest and remove the separate function.

2021-01-23 13:17 UTC, kberg commented on src/ares/AresHazards.ts
> +    const space = game.getSpaceByOffset(direction, tileType);
Yes, this is fine. Good.

2021-01-23 13:17 UTC, kberg commented on src/boards/Board.ts
> +    this.maxY = Math.max(...spaces.map((s) => s.y));
The Moon's board is 4,5,6,5,4, which is why you can't assume size.

2021-01-23 13:17 UTC, kberg commented on src/boards/Board.ts
> +      }
Probably not nitpicking, but could also wait for a follow-up. Fortunately, the tests for adjacent spaces became a totally complete set, so it's easy to verify any breaks at all. :D

2021-01-23 13:17 UTC, kberg commented on src/boards/Board.ts
> +  private readonly adjacency = new Map<SpaceId, Array<ISpace>>();
`adjacentSpaces`?

2021-01-23 13:17 UTC, kberg commented on src/boards/Board.ts
> +      }
For what it's worth, I think this new algorithm is harder to understand (I don't understand it yet) so how about making it more readable in a follow-up, and owning its correctness?

2021-01-23 13:17 UTC, kberg commented on src/boards/Board.ts
> +  // Returns adjacent spaces in clockwise order starting from the top left.
Put this comment up by the top: `stores adjacent spaces in clockwise order starting from the top left.`?

2021-01-23 13:17 UTC, kberg commented on tests/moon/MoonBoard.spec.ts
>    it('getAdjacentSpaces', () => {
Interesting: the test below doesn't need changing?

2021-01-23 17:18 UTC, daniel-ziegler commented on src/boards/Board.ts
> +      }
A simpler fast plan might be:
1. Build a map from (x,y) to ISpace
2. Look up each of the adjacent coords in that map
Anyway, I won't worry about any of that for this PR

2021-01-23 18:16 UTC, daniel-ziegler commented on tests/moon/MoonBoard.spec.ts
>    it('getAdjacentSpaces', () => {
It wasn't testing order so it still passed (but wasn't strict). I've updated it to test order as well.

2021-01-23 18:16 UTC, daniel-ziegler commented on src/boards/Board.ts
> +  // Returns adjacent spaces in clockwise order starting from the top left.
Done

2021-01-23 18:16 UTC, daniel-ziegler commented on src/boards/Board.ts
> +  private readonly adjacency = new Map<SpaceId, Array<ISpace>>();
Renamed

2021-01-23 18:16 UTC, daniel-ziegler commented on src/GameSetup.ts
> +      let idx = game.discardForCost(TileType.GREENERY);
Done

2021-01-23 18:43 UTC, kberg commented on tests/moon/MoonBoard.spec.ts
>    it('getAdjacentSpaces', () => {
Gah! Thanks.

2021-01-25 00:31 UTC, kberg approved these changes
Thank you! Not only did you resolve a game rule, you made the game faster. I couldn't imagine the millions of times that method is called.

2021-01-25 00:32 UTC, kberg commented
@Lynesth this PR is blocked on your review, so I'll leave it to you to merge when you are satisfied.

2021-01-25 01:31 UTC, Lynesth approved these changes

2021-01-25 02:02 UTC, merged