Update chairman mode for Agendas
bafolts/terraforming-mars pull request #2517
Opened 2021-01-22 02:53 UTC by nwai90

Closes https://github.com/bafolts/terraforming-mars/issues/2423.

Main change:
- If AgendaStyle is CHAIRMAN and a player is the new chairman, either the ruling policy or ruling bonus can be changed, but not both
- If AgendaStyle is CHAIRMAN and a neutral delegate is the new chairman, nothing changes
- If AgendaStyle is STANDARD or RANDOM, get the predefined agenda from staticAgendas (i.e. no change)

<img width="401" alt="Screenshot 2021-01-22 at 9 11 20 AM" src="https://user-images.githubusercontent.com/2408094/105439519-f848ad00-5c9f-11eb-8ec7-93e6f4e34f64.png">

2021-01-22 17:21 UTC, kberg commented
In the visual example above, what actually _is_ the ruling policy?

2021-01-23 01:16 UTC, nwai90 commented
> In the visual example above, what actually _is_ the ruling policy?

@kberg The existing ruling policy and bonus are displayed on the Turmoil board. It re-renders dynamically depending on what was changed by the player

2021-01-23 14:38 UTC, kberg requested changes

2021-01-23 14:38 UTC, kberg commented on src/turmoil/PoliticalAgendas.ts
>    staticAgendas: Map<PartyName, Agenda> | undefined;
If these are no longer static, then rename this. Can be a follow-up since it will meaningfull complicate readability of this PR.

2021-01-23 14:38 UTC, kberg commented on src/turmoil/PoliticalAgendas.ts
> +        agendaStyle: d.agendaStyle,
This here is the problem: all of these changes are going to break current games. Their chairman's choice behavior will change mid-game -- that is --- if the game can be deserialized.

One alternative is to introduce a fourth option, making the thrd option invisible in the New Game UI and eventually removing it. (Though it makes past games not cloneable -- but long-term historically preserving cloning has never been a priority in this project.)

Another option is to think through the serialization problem more carfully, which I leave up to you to consider.

2021-01-24 03:35 UTC, nwai90 commented on src/turmoil/PoliticalAgendas.ts
> +        agendaStyle: d.agendaStyle,
So here's the thing: Current code lets chairman change both ruling bonus and policy. New code updates `ChoosePoliticalAgendas` to allow chairman to change only one of them.

We could in theory add a 4th value to `AgendaStyle` enum e.g. `CHAIRMAN_LIMITED` to reflect the new behaviour, but it's ugly to do that. It also means maintaining two versions of logic for `ChoosePoliticalAgendas` and having to deprecate the old one at some point when doing the migration.

About the concern of breaking existing games due to a new property being added to `deserialize` method, a quick and dirty fix could be to do `agendaStyle: d.agendaStyle === undefined ? AgendaStyle.STANDARD : d.agendaStyle`. Chairman behaviour for ongoing `AgendaStyle.CHAIRMAN` games would change in subsequent generations, which is fine imo.

2021-01-25 03:11 UTC, kberg commented on src/turmoil/PoliticalAgendas.ts
> +        agendaStyle: d.agendaStyle,
> About the concern of breaking existing games due to a new property being added to `deserialize` method, a quick and dirty fix could be to do `agendaStyle: d.agendaStyle === undefined ? AgendaStyle.STANDARD : d.agendaStyle`. Chairman behaviour for ongoing `AgendaStyle.CHAIRMAN` games would change in subsequent generations, which is fine imo.

staticAgendas are serialized differently, too. How do you take that into account?

2021-01-25 03:12 UTC, kberg commented on src/turmoil/PoliticalAgendas.ts
> +        agendaStyle: d.agendaStyle,
And are you saying, then, that active games will have the surprise that the chairman is suddenly half-powered? Which is what happen when this fix gets pushed to production. A fourth option is ugly, but that's the cost of repairing a moving train.

2021-01-29 07:26 UTC, kberg commented on src/turmoil/PoliticalAgendas.ts
> +        agendaStyle: d.agendaStyle,
@nwai90 checking in -- is this stuck? Let me know.

2021-01-31 02:39 UTC, nwai90 commented on src/turmoil/PoliticalAgendas.ts
> +        agendaStyle: d.agendaStyle,
Yup @kberg

2021-01-31 03:05 UTC, kberg approved these changes

2021-01-31 03:05 UTC, kberg commented on src/turmoil/PoliticalAgendas.ts
> +        agendaStyle: d.agendaStyle,
So, you have a choice: either break the prior games or keep them working. You've added a new serialized field `agendaStyle` on line 30. All historical games will not have this value. So, you can't just add it as

`agendaStyle: AgendaStyle;`

but have to make it optional to support loading historical games,

`agendaStyle: AgendaStyle | undefined`

Now you can know that all deserialized games without it are old ones. But you still don't know when reading it which agenda style is in place, particularly as you have reused existing fields.

So consider making this entire change in a couple of steps.

1. Add the agendaStyle field, make it optional.  Do nothing with it other than serialize and deserialize it.
2. Add a new map that is just like staticAgendas, but a new field. let's call it `agendas`. On newInstance, initialize it with the appropriate first agenda/policy for each part. When agenda type is CHAIRMAN, keep the map up to date. But never use it.
2a. `agendas` also must be `|undefined` in its definnition in `SerializedPoliticalAgendas`, because otherwise it breaks historical games. But keep deserializing it, and have some tests.
3. Wait some period of time. 10 days? All historical games will have `agendas` populated. And then you can include the new behavior for the chairman's agenda, and start ignoring `staticAgendas`.
4. At some point in the future (not long, actually, but in a separate PR, perhaps) remove `staticAgendas`.

What do you think?

2021-01-31 05:05 UTC, kberg requested changes
Sorry, I'm trying to set the review to request changes instead of approve.

2021-02-15 18:25 UTC, kberg commented
In chatting with @nwai90 I went to check the database in the demo server to see how many active games use chairman mode. The answer ise 550.

```
psql postgresql://... -c "select game_id, game::json->'gameOptions'->'politicalAgendasExtension' from games where status='running'" > /tmp/result.sql

      1 (163879 rows)
    550  "Chairman"
      1   ?column?  
     27  "Random"
   7788  "Standard"
```

So just overwriting seems a bad idea.

2021-07-10 17:51 UTC, kberg commented
@nwai90 this has been settled in the main repo, yes? Close?

2021-07-11 00:53 UTC, nwai90 commented
> @nwai90 this has been settled in the main repo, yes? Close?

Yes this PR is outdated, will close. The change is already done and merged in a newer PR

2021-07-11 00:53 UTC, closed without merging