Adding disount to tags
bafolts/terraforming-mars pull request #2557
Opened 2021-01-25 14:41 UTC by chosta

Continuing #2150

(1) Discount for Valley trust
![valley](https://user-images.githubusercontent.com/836179/105719205-b2534980-5f2a-11eb-810f-569939467524.png)
(2) Discount for Valley trust + Earth catapult
![valley+ec](https://user-images.githubusercontent.com/836179/105719215-b4b5a380-5f2a-11eb-8597-72e2b1686415.png)

The reason this is labelled `do not merge` is because I was not sure how to expose the player discounts. I've considered several different approaches and would like to have an agreement to what we would like to use before commiting to it. 
1) Current approach.
 Just a map of all known discounts on cards in a map `DISCOUNTS_MAP`. The benefit is that it works immediatelly. Drawbacks - not pretty, not extendable (or extendable to an extent)
2) Adding a `discounts` static property to `Card.ts`.
(I've done it for the sake of review but the changes could fly if we don't choose this approach). If the `discounts` property is used, every card that has a discount would have an object as propery describing the tag and the amount for the discount. This will probably require a `getCardDiscount` to be refactored. Benefits - central control of discounts, pretty and extendable, no backend. Drawback - we need to use cardFinder.getCardByName (looping throuhg the player.playedCards array) in the frontend and potentially add unnecessary computations.
3) Adding a `discounts` property in the playerModel. 
Benefits - no unnecessary computations. Drawback - needs to be coded from scratch :)

2021-01-25 15:03 UTC, kberg commented
I would not include Earth Catapult. Global discounts should be made obvious elsewhere. As, I think should any tag discounts. Making discounts visible on cards does make more sense.

2021-01-25 15:04 UTC, sienmich commented
Maybe we could go for sth similar to metal bonus indicators, like this (I messed up the transparency):
![Screenshot from 2021-01-25 15-58-25](https://user-images.githubusercontent.com/19472604/105722860-62728380-5f26-11eb-9c5c-6a78429162fc.png)
It could save some space (although I'm not sure if it is necessary). What do you think?

2021-01-25 15:06 UTC, sienmich commented
> I would not include Earth Catapult. Global discounts should be made obvious elsewhere. As, I think should any tag discounts. Making discounts visible on cards does make more sense.

We could consider placing global discounts next to the wild tag, but maybe that's not that intuitive

2021-01-25 15:07 UTC, sienmich commented on assets/settings.json
> +{"version":"701d717e Thu, 21 Jan 2021 07:42:36 -0700","waitingForTimeout":5000}
Is this supposed to be here?

2021-01-25 15:26 UTC, chosta commented on assets/settings.json
> +{"version":"701d717e Thu, 21 Jan 2021 07:42:36 -0700","waitingForTimeout":5000}
No, it's just something that was left behind in between commits. Just ignore it for the time being.

2021-01-25 15:28 UTC, chosta commented
> I would not include Earth Catapult. Global discounts should be made obvious elsewhere. As, I think should any tag discounts. Making discounts visible on cards does make more sense.

The reason we show this on the player board is for other players to be able to see what discounts you have. Imagine a 4p game that spans for 4 hours. Sometimes you skip a log entry that might be really important (like EC). This is much needed as well as what you suggest. Discount on cards when you play them should be a separate issue.

2021-01-25 15:31 UTC, chosta commented
> It could save some space (although I'm not sure if it is necessary). What do you think?

Space was supposed to created for discounts and player + corp name. One of the reasons for this rework was not having the space for discounts. I've considered your proposal and to be fair I even like it more that the current solution. I think we can fill the space above with identifiers of cards that are crucial to the game. I was thinking icons of penguins, ants, cutting edge (we can get creative).

2021-01-25 15:38 UTC, chosta commented
I also need to express my opinion on the way we work on issues. I've taken this one because of the great approval rating it got ( 6 rockets!). Now I see suggestions to completely change it. Should we have a better process in terms of deciding what and how to do it? I didn't 100% agree with the design but did it as it was given nevertheless because it got so much <3. As you know frontend work could be very time-consuming and this took me a while to make every pixel perfectly aligned..I'm not complaining, just suggesting to maybe find a way to find an agreemend between devs before we take on a task. Or we just roll with it and take the slack if any :)
This is just food for thought related to the future of this project. I'll focus on this task and will probably present a slightly different design approach, close to what @sienmich suggested because I also think it's simply better. Let me know what you think about the way discounts are exposed in this PR. Thanks.

2021-01-25 16:12 UTC, sienmich commented
Sorry for that, I understand it must be frustrating. At the time you proposed those changes they seemed optimal (rocket worthy!). In the meantime those metal indicators were released and after playing with them I think the small MC icon is very nice and fits here as well. It's just a thought / suggestion tho, feel free to go with current layout.

I think we need those discount counters, a lot of players were asking for them. And I agree, that discounts on cards are not working here, because we want to see other players discounts.
Thanks for all the front!

2021-01-25 16:13 UTC, kevinb9n commented
> I also need to express my opinion on the way we work on issues. I've taken this one because of the great approval rating it got ( 6 rockets!). Now I see suggestions to completely change it. Should we have a better process in terms of deciding what and how to do it?

Yes :-)

I wrote up my thoughts on this design here and in the following comment: https://github.com/bafolts/terraforming-mars/issues/2150#issuecomment-748725660

It doesn't work to show Earth Catapult as applying to every tag, because a per-card discount is different from a per-tag discount (where the discount applying to each tag on the card is added together). I think it works fine to show it above the "# cards in hand" indicator, which is even right nearby.

2021-01-25 16:15 UTC, kevinb9n commented
> Maybe we could go for sth similar to metal bonus indicators, like this (I messed up the transparency):
> ![Screenshot from 2021-01-25 15-58-25](https://user-images.githubusercontent.com/19472604/105722860-62728380-5f26-11eb-9c5c-6a78429162fc.png)
> It could save some space (although I'm not sure if it is necessary). What do you think?

(For whatever it's worth, I still like the original proposal.)

2021-01-25 16:23 UTC, nwai90 commented
@chosta I hear you. I think there is a bloat of issues (177!) such that it becomes hard for people to keep track of everything. This particular issue is one that has not been discussed in great detail. I'm guessing @kberg has the same concern about global discounts - that displaying the same -2 n times for n tags is repetitive UI. It may be possible to come up with something better but this is probably fine too

2021-01-25 16:44 UTC, chosta commented
> @chosta I hear you. I think there is a bloat of issues (177!) such that it becomes hard for people to keep track of everything. This particular issue is one that has not been discussed in great detail. I'm guessing @kberg has the same concern about global discounts - that displaying the same -2 n times for n tags is repetitive UI. It may be possible to come up with something better but this is probably fine too

I think showing the discount to you when playing the card is a separate issue. The player board should show what others have at a glance. We are discussing in discord, making these discounts optional, so I think it's going in the right direction.

This, I think is better as a design. We can add icons for key cards on the top. Just throwing that out there:
![penguins (1)](https://user-images.githubusercontent.com/836179/105736260-44fce400-5f3d-11eb-8132-67b0ae66fb60.jpg)

2021-01-25 16:55 UTC, chosta commented
Actually there was a cool suggestion about the global discounts. Earth Catapult, Sky Docks, Anti-Grav and Research Outpost could be added to the card symbol to the left!

2021-01-25 20:03 UTC, vsrisuknimit commented
@chosta Can I propose an alternative this evening? I don't like the one above all tag icons either.

Should we move this to git discussion or keep talking in this PR?

2021-01-25 20:46 UTC, chosta commented
Here + post in general in discord too

On Mon, Jan 25, 2021, 22:04 Jeep <notifications@github.com> wrote:

> @chosta <https://github.com/chosta> Can I propose an alternative this
> evening? I don't like the one above all tag icons either.
>
> Should we move this to git discussion or keep talking in this PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bafolts/terraforming-mars/pull/2557#issuecomment-767078980>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGMEU52RNFCA2FDEWW2NV3S3XFDTANCNFSM4WR3G3DA>
> .
>

2021-01-26 01:42 UTC, vsrisuknimit commented
![rect872](https://user-images.githubusercontent.com/14239220/105788006-99a85b00-5f4d-11eb-9786-df5eaf2b0700.png)

@chosta the first four are possible for any corp. The last one is possible for three specific corp and not possible to come together. So total of five boxes maximum.

A VP icon on top of jovian tag. 1 for 1x multiplier. 2 for 2x. 3 is the maximum as we don't count Terraforming Ganymede.

2021-01-26 02:09 UTC, vsrisuknimit commented
![image843-2](https://user-images.githubusercontent.com/14239220/105790095-9fa03b00-5f51-11eb-90ee-0215fbd2330d.png)

Remove card for global discount and add cutting edge tech.

2021-01-26 02:15 UTC, sienmich commented
Nice work! I think I still prefer (a bit) small discounts indicators on the tags. It's more minimalistic, less data to process.
The jovian VP is a  cool idea, this could be added with those small indicators too (bottom right corner of the tag, like usual?)
That cutting edge is tempting, since it's hard to show it in previous version.

2021-01-26 02:57 UTC, vsrisuknimit commented
![multiplayer-discount](https://user-images.githubusercontent.com/14239220/105794101-4e477a00-5f58-11eb-994e-451db4b18616.png)

A big picture mockup with other players.

2021-01-26 06:20 UTC, kevinb9n commented
i do think that putting the discount amount right above where the tag already is is much more elegant. And it means you can easily see things like "the player I'm passing to has -2 on space, but damn, the player THEY pass to has -8." – it all lines up vertically.

The Jupiter VP symbol is a nice idea and since there aren't any Jovian discounts it doesn't have to fit below the discount row.

(Nothing to the right of Venus has any discounts either, so I would suggest *not* showing zeroes there, in case you decide you want to use that real estate for something else...)

2021-01-26 10:10 UTC, chosta commented
Just adding @ssimeonoff's suggestion to have them all at one place.
![bar-simon](https://user-images.githubusercontent.com/836179/105831475-70c8aa00-5fcf-11eb-84d4-be07d57d397e.png)

2021-01-26 10:20 UTC, chosta commented
Thanks for all the suggestion and feedback. I've decided to go for a version of the UI that combines many of the excellent suggestions. It will look like this:
![current state](https://user-images.githubusercontent.com/836179/105831659-a8cfed00-5fcf-11eb-8a30-99b571273535.png)
+ global discounts displayed on card
+ any other discount displayed on the corresponding tag
+ jovian multiplier on top of tag with VP icon

I'll probably switch back to the old "boxed" view with the updated design from @ssimeonoff. While, @vsrisuknimit's suggestion is the best way to fill the space on top of the player board, it does feel a bit cluttered and unnecessary.
The main reason we went for the player and corp name going top was to make space for discounts identificators. It turned out that there was no need for them to be that big of a size and therefore we can go back to having a compact view. I'll let this settle for a while before doing it though.

P.S. I still need that code review :)

2021-01-26 12:39 UTC, vsrisuknimit commented
![multiplayer-superscript](https://user-images.githubusercontent.com/14239220/105845444-b9b93800-5fa8-11eb-832f-2851ff45088a.png)

Here is a mockup of the superscript design.

I will summarize the discussion on Discord.
- How would you represent cutting edge tech?
- Hard to do rebate.
- The discount above card can be confused with Terralabs ability / Polyphemos.
- But I guess we have to go with this if we are going back to the box design.
- As a player, I don't care to read vertically. There is no need to know all players' space discount at once. What is more important while playing is horizontal reading. I care about all the discount of one player (leader or the person immediately downstream of my draft, or the person after that). This is especially useful if all the discounts are together next to the player name.
- Whatever design we go with, I would consider putting discount next to name of the person downstream of my draft. Here is an example: 

![draft-discount](https://user-images.githubusercontent.com/14239220/105845857-64c9f180-5fa9-11eb-9557-c637a0a03db3.png)

2021-01-26 12:53 UTC, chosta commented
> * Whatever design we go with, I would consider putting discount next to name of the person downstream of my draft. Here is an example:

I quite like this idea, too. 

Let's roll with `superscript` + `jovians` and see where it takes us. Ultimately, we can have 2 or more UI views depending on the player needs / feedback.

2021-01-26 12:59 UTC, vsrisuknimit commented
Two more points I forgot:
- Try top center instead of superscript (top right). See below.
- Add a toggle to hide/show discount next to concise/full button.

![multiplayer-superscript](https://user-images.githubusercontent.com/14239220/105847896-41547600-5fac-11eb-9982-96b4409dcea6.png)

2021-01-26 13:05 UTC, chosta commented
> * Try top center instead of superscript (top right). See below.
I don't like it. There is no consistancy with the alloy bonus. I can try and move the mc a bit to the left but for me right > center.
> * Add a toggle to hide/show discount next to concise/full button.
Not in this PR. If we have a button like that would it be hiding the alloy bonus too?

2021-01-26 13:14 UTC, vsrisuknimit commented
> I don't like it. There is no consistancy with the alloy bonus. I can try and move the mc a bit to the left but for me right > center.

We can move the alloy bonus toward the center if you would like. Superscript is fine for alloy since there is empty space on the right. Tags are much closer together, superscript looks less good there. I don't think we need consistency here. They mean different things.

> Not in this PR. If we have a button like that would it be hiding the alloy bonus too?

Don't think so. The alloy bonus does not add as much clutter as the tag discount.

2021-01-26 13:31 UTC, chosta commented
Sorry, I just don't agree with you. I'd like for this PR to go through and get feedback from the players. Then we can take action. If this is not widely accepted, I'll implement your suggestion. If it's moderately accepted, then I'll implement your suggestion and add a "compact" mode that will also enable discounts toggle. If people think its trash, I'll accept that too.
Also, I think the screenshot with the "full picture" is a bit deceiving. Currently, there is are NO rebates implemented and even if they were, they wouldn't be placed like that (it was just a thought I suggested on the go). Again, this PR is about discounts. I don't mind throwing work in the bin but I need actual player feedback before doing so.

2021-01-26 14:37 UTC, ssimeonoff commented
I am a bit worried that with all those MC(yellow) icons everywhere, the UI will get as colourful and bright as a xmas tree.

2021-01-26 14:47 UTC, chosta commented
> I am a bit worried that with all those MC(yellow) icons everywhere, the UI will get as colourful and bright as a xmas tree.

You started this :)

But seriously, a fully discounted game only comes in the last generations. I even think it's good on a psychological level.
Building an engine = Having nice stuff
Sir Lancelot's upgrades do look good, right :) ?
![knights](https://user-images.githubusercontent.com/836179/105859912-b8622c80-5ff5-11eb-94d8-62356ee39da3.jpeg)

I can't stress enogh how important is to roll this to players and actually see it in game. We can make a thousand guesses what is good or not but until we have the experience in a real game, no conclusions can be drawn, especially with a controvercial design solutions because they all are.
And to repeat myself, I don't mind rolling back or modifying any design as long as it's the right thing to do. But ... Do, we must.

2021-01-26 15:06 UTC, vsrisuknimit commented on src/components/overview/PlayerTagDiscount.ts
> +    getClasses: function(): string {
Same here, do we need a method for this?

2021-01-26 15:06 UTC, vsrisuknimit commented on src/components/overview/PlayerTags.ts
> +  CardName.TERRAFORMING_GANYMEDE,
TfG is not an ongoing multiplier. Once it is out of the hand, the TR is adjusted. It does not matter anymore if you pass that person more jovian.

2021-01-26 15:06 UTC, vsrisuknimit commented on src/components/overview/PlayerTags.ts
> +      console.log(multipliers, 'multi');
remove console log?

2021-01-26 15:08 UTC, vsrisuknimit commented
> I can't stress enogh how important is to roll this to players and actually see it in game. We can make a thousand guesses what is good or not but until we have the experience in a real game, no conclusions can be drawn, especially with a controversial design solutions.

I made some comments on the code, but I am probably not qualified to review and approve this.

If we want to see player feedback sooner, we could try a beta server.

2021-01-26 15:12 UTC, chosta commented on src/components/overview/PlayerTags.ts
> +      console.log(multipliers, 'multi');
yes

2021-01-26 15:13 UTC, chosta commented on src/components/overview/PlayerTags.ts
> +  CardName.TERRAFORMING_GANYMEDE,
Correct, my bad

2021-01-26 15:14 UTC, chosta commented on src/components/overview/PlayerTagDiscount.ts
> +    getClasses: function(): string {
It used to need it because of something I had to add. Well spotted.

2021-01-26 15:14 UTC, chosta commented on src/components/overview/PlayerTagDiscount.ts
> +    getMegacreditsClasses: function(): string {
Deprecated, not used.

2021-01-26 15:15 UTC, chosta commented on src/components/overview/JovianMultiplier.ts
> +    <div :class="getClasses()">{{ amount }}</div>
Not needed too

2021-01-26 15:23 UTC, chosta commented
Thanks for the comments. Last commit should resolve the issues. No need for beta testing this...It's not a crazy new feature, just a couple of helpful icons. I'm curious to see if people notice the jovian multiplier indicator. This needs to go in production without explanation, so we can have genuine reactions. Trust me.

2021-01-26 15:52 UTC, vsrisuknimit commented on assets/translations.json
> +{"You start with 1 titanium production and 42 MC.":{"cn":"你起始获得42MC和提升钛合金产能1级","de":"Du beginnst mit 1 Titan-Produktion und 42 M€.","fr":"Vous commencez avec une production de titane de 1 et 42 M€.",
Is this file supposed to be part of this PR?

2021-01-26 15:52 UTC, vsrisuknimit commented on compile-vue-templates.js
> +    console.log(result.tips);
no need for console.log?

2021-01-26 15:52 UTC, vsrisuknimit commented on src/components/overview/PlayerTags.ts
> +  if (player.gameOptions.coloniesExtension === false && tag === SpecialTags.CITY_COUNT) {
Is this supposed to be COLONY_COUNT instead of CITY_COUNT?

2021-01-26 16:15 UTC, kevinb9n commented
I'm happy with how all this is going!

2021-01-26 16:18 UTC, chosta commented on assets/translations.json
> +{"You start with 1 titanium production and 42 MC.":{"cn":"你起始获得42MC和提升钛合金产能1级","de":"Du beginnst mit 1 Titan-Produktion und 42 M€.","fr":"Vous commencez avec une production de titane de 1 et 42 M€.",
It's not supposed to be there but it got in between commits. A merge with main fixes it, so don't worry about it.

2021-01-26 16:19 UTC, chosta commented on src/components/overview/PlayerTags.ts
> +  if (player.gameOptions.coloniesExtension === false && tag === SpecialTags.CITY_COUNT) {
Actually it's supposed to be a logical `||`
This check should ignore cities and colonies

2021-01-26 16:20 UTC, chosta commented on compile-vue-templates.js
> +    console.log(result.tips);
no need, true

2021-01-26 16:38 UTC, vsrisuknimit approved these changes
Look good to me but let's see what others say.

2021-01-26 16:59 UTC, sienmich approved these changes

2021-01-26 21:24 UTC, chosta commented
Please, someone add a do not merge, Jeep pointed out a possible issue that
I'll check as soon as I can. Thanks

On Tue, Jan 26, 2021, 18:59 sienmich <notifications@github.com> wrote:

> *@sienmich* approved this pull request.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bafolts/terraforming-mars/pull/2557#pullrequestreview-576560966>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGMEU5L4UPB4VA3MCEZH3LS33YHPANCNFSM4WR3G3DA>
> .
>

2021-01-26 21:40 UTC, vsrisuknimit requested changes

2021-01-26 21:40 UTC, vsrisuknimit commented on src/components/overview/PlayerTags.ts
> +  if (player.gameOptions.moonExpansion && tag === Tags.MOON) {
Should not it be `player.gameOptions.moonExpansion === false && tag === Tags.MOON`?

2021-01-26 21:40 UTC, vsrisuknimit commented on src/components/overview/PlayerTags.ts
> +  if (player.gameOptions.coloniesExtension === false || tag === SpecialTags.CITY_COUNT) {
Something is weird here. If colonies expansion is not in use, this function always return false. For all tags. That can't be right.

2021-01-26 21:48 UTC, chosta commented
Yes, this needs to be changed. Might add a test as well.

On Tue, Jan 26, 2021, 23:41 Jeep <notifications@github.com> wrote:

> *@vsrisuknimit* requested changes on this pull request.
> ------------------------------
>
> In src/components/overview/PlayerTags.ts
> <https://github.com/bafolts/terraforming-mars/pull/2557#discussion_r564852095>
> :
>
> > +  SpecialTags.INFLUENCE,
> +  SpecialTags.CITY_COUNT,
> +  SpecialTags.COLONY_COUNT,
> +];
> +
> +export const checkTagUsed = (tag: InterfaceTagsType, player: PlayerModel) => {
> +  if (player.gameOptions.coloniesExtension === false || tag === SpecialTags.CITY_COUNT) {
> +    return false;
> +  }
> +  if ((player.turmoil !== undefined) === false && tag === SpecialTags.INFLUENCE) {
> +    return false;
> +  }
> +  if (player.gameOptions.venusNextExtension === false && tag === Tags.VENUS) {
> +    return false;
> +  }
> +  if (player.gameOptions.moonExpansion && tag === Tags.MOON) {
>
> Should not it be player.gameOptions.moonExpansion === false && tag ===
> Tags.MOON?
> ------------------------------
>
> In src/components/overview/PlayerTags.ts
> <https://github.com/bafolts/terraforming-mars/pull/2557#discussion_r564852342>
> :
>
> > +  Tags.PLANT,
> +  Tags.MICROBE,
> +  Tags.ANIMAL,
> +  Tags.CITY,
> +  Tags.MOON,
> +  'separator',
> +  Tags.EVENT,
> +  SpecialTags.NONE,
> +  Tags.WILDCARD,
> +  SpecialTags.INFLUENCE,
> +  SpecialTags.CITY_COUNT,
> +  SpecialTags.COLONY_COUNT,
> +];
> +
> +export const checkTagUsed = (tag: InterfaceTagsType, player: PlayerModel) => {
> +  if (player.gameOptions.coloniesExtension === false || tag === SpecialTags.CITY_COUNT) {
>
> Something is weird here. If colonies expansion is not in use, this
> function always return false. For all tags. That can't be right.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bafolts/terraforming-mars/pull/2557#pullrequestreview-576784716>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGMEU6MGB5TYE4DYGJW7ZTS34ZHLANCNFSM4WR3G3DA>
> .
>

2021-01-27 08:06 UTC, chosta commented on src/components/overview/PlayerTags.ts
> +  if (player.gameOptions.moonExpansion && tag === Tags.MOON) {
It's the same as `undefined` is considered falsy in javascript but for the sake of consistency it's better to have the === operator

2021-01-27 08:07 UTC, chosta commented on src/components/overview/PlayerTags.ts
> +  if (player.gameOptions.coloniesExtension === false && tag === SpecialTags.CITY_COUNT) {
You were correct in your first comment here. It was a typo. I've made a mess of this...Next commit should be fine though.

2021-01-27 11:02 UTC, vsrisuknimit commented on src/components/overview/PlayerTags.ts
> +  if (player.gameOptions.moonExpansion && tag === Tags.MOON) {
@chosta it is not the equivalent. If Moon is not in use, player.gameOptions.moonExpansion would be undefined and you would get False for the whole if statement even if tag = Tags.MOON. You want it to be true there.

2021-01-27 11:04 UTC, vsrisuknimit approved these changes

2021-01-27 11:06 UTC, vsrisuknimit commented
Look good to my inexperienced eyes. Not sure if you want real programmers to take a look.

2021-01-27 11:32 UTC, chosta commented on src/components/overview/PlayerTags.ts
> +  if (player.gameOptions.moonExpansion && tag === Tags.MOON) {
That is wanted behavior. The order of `&&` and `||` resolves from left to right. So if the moon is undefined or false it will ignore the statement to the right.

2021-01-27 11:33 UTC, chosta commented
> Look good to my inexperienced eyes. But you may want real programmers to take a look still.

You found out enough :). It was already approved by a dev. It should be fine. Thanks.

2021-01-27 11:33 UTC, merged

2021-01-27 12:52 UTC, vsrisuknimit commented on src/components/overview/PlayerTags.ts
> +  if (player.gameOptions.moonExpansion && tag === Tags.MOON) {
It does not matter since you fixed it. But if the Moon expansion is not in use, don't you want this function to return false? The way it was written before, the if statement would be come false and you skip returning false here.

2021-01-27 12:53 UTC, vsrisuknimit commented on src/styles/players_overview.less
> +            // border-bottom: 2px solid rgba(170, 170, 170, 0.2);
Should this be removed rather than commented out?