Static cards - turmoil
bafolts/terraforming-mars pull request #2576
Opened 2021-01-27 17:40 UTC by sienmich

2021-01-29 01:56 UTC, bafolts commented on src/cards/turmoil/PoliticalAlliance.ts
> +      tags: [Tags.MICROBE, Tags.SCIENCE],
These tags are different. Original had no tags.

2021-01-29 01:59 UTC, bafolts requested changes
The tags on `PoliticalAlliance` changed from `[]` to `[Tags.MICROBE, Tags.SCIENCE]`? Was this expected?

2021-01-29 11:29 UTC, sienmich commented on src/cards/turmoil/PoliticalAlliance.ts
> +      tags: [Tags.MICROBE, Tags.SCIENCE],
It's probable some intelligent microbes spices plan to take control over the world. Thanks!

2021-01-29 11:33 UTC, sienmich commented on src/cards/turmoil/AerialLenses.ts
> +import {Card} from '../Card';
```suggestion
```

2021-01-29 11:36 UTC, sienmich commented
@bafolts, since you merged the same turmoil cards, here is now the rest of them.

I'll do today the colonies.

2021-01-30 01:32 UTC, kberg approved these changes

2021-01-30 01:41 UTC, bafolts approved these changes

2021-01-30 01:42 UTC, merged