Minor improvements to Player.ts
bafolts/terraforming-mars pull request #2590
Opened 2021-01-29 04:25 UTC by nwai90

2021-01-29 07:49 UTC, Lynesth requested changes

2021-01-29 07:49 UTC, Lynesth commented on src/Player.ts
> +      Manutech.resolveCorpEffect(this, resource, amount);
onProductionGain ?

2021-01-29 09:28 UTC, Lynesth approved these changes

2021-01-29 12:31 UTC, sienmich reviewed
I like all those changes, putting constants in constants is good. I was just working on similar thing and we'll have a conflict.

2021-01-29 12:31 UTC, sienmich commented on src/Player.ts
> +  private getTotalSpendableResources(canUseSteel: boolean, canUseTitanium: boolean, canUseFloaters: boolean, canUseMicrobes: boolean, spendableSteel?: number, spendableTitanium?: number): number {
This conflicts with my PR: https://github.com/bafolts/terraforming-mars/pull/2559
Could you maybe leave this part for now? I'm planning to further improve it

2021-01-30 22:22 UTC, kberg reviewed
> I like all those changes, putting constants in constants is good. I was just working on similar thing and we'll have a conflict.

What's the state of this PR? Just seeing if there is something I can do.

2021-01-31 02:54 UTC, sienmich approved these changes

2021-01-31 03:00 UTC, nwai90 commented on src/Player.ts
> +    return 3 - this.colonyTradeDiscount;
Done

2021-01-31 03:07 UTC, kberg commented on src/Player.ts
> +  private getTotalSpendableResources(canUseSteel: boolean, canUseTitanium: boolean, canUseFloaters: boolean, canUseMicrobes: boolean, spendableSteel?: number, spendableTitanium?: number): number {
@sienmich this is OK?

2021-01-31 03:08 UTC, kberg commented on src/Player.ts
> +  private getTotalSpendableResources(canUseSteel: boolean, canUseTitanium: boolean, canUseFloaters: boolean, canUseMicrobes: boolean, spendableSteel?: number, spendableTitanium?: number): number {
Sorry never mind, I'm all caught up.

2021-01-31 03:08 UTC, kberg approved these changes

2021-01-31 03:08 UTC, merged