Resolves #2587 - Adds a configurable number of history lines in game log via .env variable
bafolts/terraforming-mars pull request #2605
Opened 2021-01-30 01:21 UTC by puuj

This commit allows a variable number of lines of history in the game log. The number defaults to 50 to maintain the previous behavior, but can be configured using the new LOG_LENGTH variable noted in the updated README.
I used the same pattern as PostgreSQL.ts (for purge days) to define and parse the number of lines.

2021-01-30 01:34 UTC, kberg commented
I'm good with this, but I am going to defer to @chosta who had a minor concern.

2021-01-30 01:44 UTC, bafolts commented
Looks good to me. I am glad we are finally using this data! This api route has been waiting to send back more data.

2021-01-30 01:49 UTC, Lynesth commented
Wouldn't it make more sense to process it like we do for WAITING_FOR_TIMEOUT, and save the value in settings.json instead of checking the process variable each time the component is mounted ?

2021-01-30 01:56 UTC, bafolts requested changes
I believe @Lynesth is right. This compiles because we have the `node` type in our `tsconfig` but I wouldn't think it works. The `process` wont exist client side. This should throw an error that `process` is `undefined` whenever the `LogPanel` were mounted. This change has to use the strategy @Lynesth suggests.

2021-01-30 02:05 UTC, Lynesth commented
> This should throw an error that process is undefined

I think it just returns an empty `process`, no error, if I recall correctly.

2021-01-30 02:24 UTC, kberg commented
> Wouldn't it make more sense to process it like we do for WAITING_FOR_TIMEOUT, and save the value in settings.json instead of checking the environment variable each time the component is mounted ?
> 
> Edit: check `make_static_json.js` to see what I'm talking about.

@puuj how did you test this?

2021-01-30 21:31 UTC, puuj commented
Sorry. I tested this in a haphazard way and didn't realize the issue. I've updated based on the suggestion to use the static JSON file to capture the log length setting, and tested more thoroughly this time.

> > Wouldn't it make more sense to process it like we do for WAITING_FOR_TIMEOUT, and save the value in settings.json instead of checking the environment variable each time the component is mounted ?
> > Edit: check `make_static_json.js` to see what I'm talking about.
> 
> @puuj how did you test this?

2021-01-30 22:23 UTC, kberg commented
Still looks good. Hanging back on this though.

2021-01-31 01:11 UTC, Lynesth commented
LGTM

2021-02-01 08:09 UTC, chosta approved these changes

2021-02-02 02:47 UTC, puuj commented
@bafolts
Since this is stuck in "Changes requested" here's an update:
I made the updates to use settings.json rather than the node process. 

I also tested more thoroughly by getting a game with a long log, and loading it into a fresh DB and a newly rebuilt instance, counting the lines, building again with a lower log length number and running the test again.

Note that since the API endpoint for the log does a destructive log.splice() and stores the truncated log, changing the length parameter from a smaller number to a larger number will still only show the smaller number of lines until more actions are taken.

2021-02-02 02:50 UTC, bafolts approved these changes

2021-02-02 02:50 UTC, bafolts commented
Sorry. Didn't realize my early request changes was the only thing blocking this. This looks good!

2021-02-02 02:51 UTC, merged