add button to hide tiles
bafolts/terraforming-mars pull request #2626
Opened 2021-01-31 14:26 UTC by vsrisuknimit

Normal ![image](https://user-images.githubusercontent.com/14239220/106386978-98d85480-63a5-11eb-96bc-23a3a3120f6b.png)

Once click 'hide tiles'
![image](https://user-images.githubusercontent.com/14239220/106386989-a68dda00-63a5-11eb-957c-5dac5cc4a9af.png)

It does not persist. As soon as you refresh or other player take an action, the view mode goes back to default. I think this is what we want.

Not sure what the button name should be. 'hide tiles'? 'show bonus'?

Still have to adjust the position so it does show over the card during initial research phase.

This PR can close #2050 .

2021-01-31 14:31 UTC, vsrisuknimit commented
@chosta help. I need the position of the button to be absolute so it does shift the terraforming tracks. But during initial draft, absolute just layover cards. What can I do?

![image](https://user-images.githubusercontent.com/14239220/106387285-19e41b80-63a7-11eb-950c-76fc84e4efc0.png)

2021-01-31 15:17 UTC, kberg reviewed
IMO an excellent bit of work. While there are more elegant solutions, this is one of those cases where the perfect would be the enemy of the good.

How would you envision this applying to The Moon simultaneously? I wouldn't worry about this just yet, though, but I would like your opinion.

2021-01-31 15:17 UTC, kberg commented on src/components/Board.ts
> +        <div class="hide-tile-button" v-on:click.prevent="hideTile()">Hide tiles</div>
"show map"?

2021-01-31 16:08 UTC, chosta commented on src/components/Board.ts
> +        <div class="hide-tile-button" v-on:click.prevent="hideTile()">Hide tiles</div>
"show tiles"?

2021-01-31 16:21 UTC, chosta requested changes
If you want to have something that is positioned absolutely relative to the parent container, just add "position: relative" (to the parent)

2021-01-31 16:21 UTC, chosta commented on src/components/Board.ts
> +    hideTile: function() {
Devs like the word `toggle` in such cases.

2021-01-31 16:21 UTC, chosta commented on src/components/Board.ts
> +      return this.isTileHidden = !this.isTileHidden;
I'd prefer to have this in two lines so we separate the concerns.
1) Assignment
2) return statement

2021-01-31 16:22 UTC, chosta commented
Also, you have to toggle the text too - Hide tiles should become Show tiles and vice versa (upon click)

2021-01-31 16:23 UTC, chosta commented on src/styles/board.less
> +	top: 610px;
Better to offset it from "bottom"

2021-01-31 16:24 UTC, chosta commented on src/styles/board.less
> +	font-size: 12px;
Please, use a variable for the font size from "variables.less"

2021-01-31 16:24 UTC, chosta commented on src/styles/board.less
> +.hide-tile-button {
Please, consider reusing a class that has been used previously. Check out the buttons for "concise" and "full" view in the player board.

2021-01-31 16:39 UTC, vsrisuknimit commented on src/components/Board.ts
> +    hideTile: function() {
@chosta if I use relative, all the global parameters will be pushed aside.

2021-01-31 16:40 UTC, vsrisuknimit commented on src/components/Board.ts
> +      return this.isTileHidden = !this.isTileHidden;
I guess it does not need to return anything. my bad.

2021-01-31 16:41 UTC, vsrisuknimit commented on src/styles/board.less
> +.hide-tile-button {
That class is inside another class. I cannot use it from here.

2021-02-01 00:07 UTC, vsrisuknimit commented
Before
![image](https://user-images.githubusercontent.com/14239220/106402463-8850ca00-63f7-11eb-9c96-6d49aa9b1efe.png)

After
![image](https://user-images.githubusercontent.com/14239220/106402468-91da3200-63f7-11eb-947b-f5e290fa5284.png)

2021-02-01 00:08 UTC, vsrisuknimit commented on src/styles/board.less
> +	font-size: 12px;
use font small now

2021-02-01 00:09 UTC, vsrisuknimit commented on src/styles/board.less
> +	top: 610px;
bottom now. with pseudoelement to be relative.

2021-02-01 00:09 UTC, vsrisuknimit commented on src/components/Board.ts
> +    hideTile: function() {
changed the function name

2021-02-01 00:09 UTC, vsrisuknimit commented on src/components/Board.ts
> +        <div class="hide-tile-button" v-on:click.prevent="hideTile()">Hide tiles</div>
now show tiles and hide tile

2021-02-01 00:14 UTC, vsrisuknimit commented
> How would you envision this applying to The Moon simultaneously? I wouldn't worry about this just yet, though, but I would like your opinion.

@kberg I imagine the same button will hide tiles on the Moon map as well. It should be pretty easy to add.

2021-02-01 00:56 UTC, vsrisuknimit commented
Do we want to hide player cube as well?

![image](https://user-images.githubusercontent.com/14239220/106403823-69096b00-63fe-11eb-87c8-9e520989b4b6.png)

@chosta I would like to apply translucent only to the tile but not the bonuses. Is there anyway to do it?

2021-02-01 08:21 UTC, chosta commented on src/styles/board.less
> +.hide-tile-button {
My point was to use the style of an existing UI element for consistency. Plase, consider:
`    text-transform: uppercase;
    border-radius: 4px;
    color: black;
    background: #ccc;`

2021-02-01 08:23 UTC, chosta approved these changes
I don't think there is a way (not an easy one at least) to have an element without opacity inside another that is opaque. Just leave it as it is, it does the job and it's just fine.
Check my comment about styling the button before merge.

2021-02-01 11:00 UTC, vsrisuknimit commented on src/styles/board.less
> +.hide-tile-button {
I have all those styles here as well except the background color. I don't want this button to be too bright next to the main map.

2021-02-01 12:37 UTC, vsrisuknimit commented
Two changes:
- Add transparency only to tiles, not bonuses
- Remove player cubes when hiding tiles

Before:
![image](https://user-images.githubusercontent.com/14239220/106459652-2bd5c500-6460-11eb-89b8-c4a0dda20fd4.png)

After:
![image](https://user-images.githubusercontent.com/14239220/106459678-3728f080-6460-11eb-9bf2-d234457c98e6.png)

2021-02-01 13:40 UTC, chosta approved these changes
Yeah, if it's inside a container you can stack opacities. Good work.

2021-02-02 02:49 UTC, merged