Show heat resource megacredit value for Helion
bafolts/terraforming-mars pull request #2646
Opened 2021-02-01 21:36 UTC by ainokna

Hi folks!
Thank you so much for creating an amazing open-source implementation of a great game!
This is my first PR to this repo. Please let me know if I missed any guidelines or best practices.

This PR contains a helper icon reminder that shows heat resource megacredit value for Helion.

My Resources View (Before):
<img width="868" alt="Screen Shot 2021-02-01 at 1 23 49 PM" src="https://user-images.githubusercontent.com/634405/106520374-8c312a80-6491-11eb-85ba-8825dc012aae.png">

My Resources View (After):
<img width="862" alt="Screen Shot 2021-02-01 at 1 23 20 PM" src="https://user-images.githubusercontent.com/634405/106520519-c4d10400-6491-11eb-8f52-ffa6cf6d6e80.png">

Other Player's Resources View (After):
<img width="864" alt="Screen Shot 2021-02-01 at 1 35 25 PM" src="https://user-images.githubusercontent.com/634405/106521005-73754480-6492-11eb-8a30-f5b41385c6c0.png">

The PR addresses #2615

2021-02-01 23:21 UTC, sienmich commented on src/components/overview/PlayerResource.ts
> +      } else if (this.type === Resources.HEAT && this.canUseHeatAsMegaCredits) {
Here you check if `this.type === Resources.HEAT`, in the `isResourceUpgraded` you don't, a bit inconsistency. I think adding them to both places would be clearer

2021-02-01 23:22 UTC, sienmich reviewed
The code looks good to me.
The feature also I like, but I haven't seen it discussed yet.
I'd like one more dev to comment, @chosta?

2021-02-01 23:30 UTC, vsrisuknimit commented
> The code looks good to me.
> The feature also I like, but I haven't seen it discussed yet.
> I'd like one more dev to comment, @chosta?

@sienmich It was talked about in #2615. The code looks good to me with the fix you suggested.

2021-02-01 23:36 UTC, ainokna commented on src/components/overview/PlayerResource.ts
> +      } else if (this.type === Resources.HEAT && this.canUseHeatAsMegaCredits) {
Done! Thank you!

2021-02-01 23:37 UTC, ainokna commented
Thanks for the review! I've updated the code.

2021-02-01 23:42 UTC, vsrisuknimit approved these changes

2021-02-02 00:53 UTC, nwai90 approved these changes

2021-02-02 01:38 UTC, kberg commented on src/models/PlayerModel.ts
> +    canUseHeatAsMegaCredits: boolean,
This is unnecessary since corporationCard is already passed down.

2021-02-02 01:46 UTC, vsrisuknimit requested changes
Request change at @kberg mentioned. PlayerModel already has Corporation. So check for Helion as Corporation name instaed.

2021-02-02 02:28 UTC, Lynesth commented on src/models/PlayerModel.ts
> +    canUseHeatAsMegaCredits: boolean,
`CardModel` doesn't have that info directly.
So does that mean checking for `corporationCard.name`. Is that something we would prefer though ?

2021-02-02 03:49 UTC, ainokna commented
@vsrisuknimit , sure, I can't change that! Can you confirm that it's okay considering @Lynesth 's comment?

2021-02-02 04:00 UTC, ainokna commented
Oh, nevermind! I missed the part about the name.

2021-02-02 04:55 UTC, ainokna commented
I've updated the code to the `corporationCard.name`.

2021-02-02 11:05 UTC, vsrisuknimit approved these changes

2021-02-02 12:02 UTC, sienmich approved these changes

2021-02-02 12:02 UTC, merged