fix version text
bafolts/terraforming-mars pull request #2660
Opened 2021-02-02 18:50 UTC by vsrisuknimit

Fix the version text when built on Heroku.

Before
<img width="302" alt="Screen Shot 2021-02-02 at 1 32 58 PM" src="https://user-images.githubusercontent.com/14239220/106647657-3b870380-655d-11eb-8c0a-739c03c90871.png">

After
<img width="459" alt="Screen Shot 2021-02-02 at 1 41 46 PM" src="https://user-images.githubusercontent.com/14239220/106647644-37f37c80-655d-11eb-87e6-4fc519dd5ce7.png">

This problem does not happen when build locally. Not sure how to safely get rid of the `(Coordinated Universal Time)` at the end. Also do we want GMT +0? Probably right.

2021-02-02 18:53 UTC, vsrisuknimit commented
What exactly does this `process.env.SOURCE_VERSION.substring(0, 7)` do? Can't I just replace with 'deployed'?

2021-02-02 19:29 UTC, vsrisuknimit commented
Simplify deploy. Switch to toUTCstring.

![image](https://user-images.githubusercontent.com/14239220/106652164-08e00980-6563-11eb-8ca5-0da495226c09.png)

2021-02-02 19:36 UTC, vsrisuknimit commented
After switching to toUTCstring

![image](https://user-images.githubusercontent.com/14239220/106652816-fd411280-6563-11eb-9592-b77d97cb5a48.png)

2021-02-03 02:01 UTC, bafolts requested changes

2021-02-03 02:01 UTC, bafolts commented on make_static_json.js
> +        return process.env.SOURCE_VERSION.substring(0, 7) + " " + new Date().toUTCString();
Spent a surprising amount of time looking at this and still not entirely sure why the format with the `( )` suffix is seen on heroku. Heroku should be using node 12.x release. 

https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

My node 12.7 (on ubuntu linux and mac) locally does not include this value. According to MDN sometime in 2018 what the `toUTCString` function returned changed. 

> Prior to ECMAScript 2018, the format of the return value varied according to the platform. The most common return value was an RFC-1123 formatted date stamp, which is a slightly updated version of RFC-822 date stamps.

To remove the suffix I would use the following regular expression:

```
"Tue Feb 02 2021 19:00:05 GMT-0700 (Mountain Standard Time)"
new Date().toString().replace(/ \(.+\)/, '')
"Tue Feb 02 2021 19:00:08 GMT-0700"
```

2021-02-03 02:20 UTC, vsrisuknimit commented on make_static_json.js
> +        return process.env.SOURCE_VERSION.substring(0, 7) + " " + new Date().toUTCString();
@bafolts (time zone) is already removed with toUTCString. The picture shown above is with toUTCString from Heroku. Do I still need to change anything?

2021-02-03 02:23 UTC, bafolts commented on make_static_json.js
> +        return process.env.SOURCE_VERSION.substring(0, 7) + " " + new Date().toUTCString();
However heroku is pulling `toUTCString` seems to be platform dependent. The time zone readable string is being included. I would add the regular expression to strip it on platforms which provide it.

2021-02-03 02:23 UTC, bafolts commented on make_static_json.js
> +        return process.env.SOURCE_VERSION.substring(0, 7) + " " + new Date().toUTCString();
I used `toString` in my example as that was the only output which included what heroku is displaying when we use `toUTCString`.

2021-02-03 03:17 UTC, vsrisuknimit commented on make_static_json.js
> +        return process.env.SOURCE_VERSION.substring(0, 7) + " " + new Date().toUTCString();
added reg ex

2021-02-04 01:42 UTC, bafolts approved these changes

2021-02-04 01:42 UTC, merged