Improved ServerModel
bafolts/terraforming-mars pull request #2687
Opened 2021-02-06 11:26 UTC by sienmich

While working on https://github.com/bafolts/terraforming-mars/pull/2679 I noticed, that there are two functions `getCards` and `getCardsAsCardModel` doing the same thing. I want to merge those two functions.
Additioanly I made `CardModel.calculatedCost` optional (earlier `getCardsAsCardModel` return 0 as `calculatedCost`, which is not the best solution).

I'd like to merge this PR before #2679.

2021-02-07 08:32 UTC, kberg requested changes

2021-02-07 08:32 UTC, kberg commented on src/server/ServerModel.ts
> +  if ([CardType.ACTIVE, CardType.AUTOMATED, CardType.EVENT].includes(card.cardType)) {
You can simplify this to `return card.cost === undefined ? undefined : player.getCardCost(card as IProjectCard)` and also rename this to getCost(). There's nothing special about it being 'calculated'.

2021-02-07 08:32 UTC, kberg commented on src/server/ServerModel.ts
> +    enabled?: Array<boolean>, // If provided, then the cards with false in `enabled` are not selectable and grayed out
This can be simplified by naming the array required, and giving it a default value of `Array(cards.length).fill(true)`

2021-02-07 08:32 UTC, kberg commented on src/server/ServerModel.ts
> +      waitingFor: getWaitingFor(player, player.getWaitingFor()),
No need to pass both parameters. Just pass `player`.

2021-02-07 10:57 UTC, sienmich commented on src/server/ServerModel.ts
> +      waitingFor: getWaitingFor(player, player.getWaitingFor()),
Not really, since there is the
```ts
    if (waitingFor.options !== undefined) {
      for (const option of waitingFor.options) {
        const subOption = getWaitingFor(player, option);
        if (subOption !== undefined) {
          playerInputModel.options.push(subOption);
        }
```
So, it is not always `getWaitingFor(player, player.getWaitingFor())`

2021-02-07 10:57 UTC, sienmich commented on src/server/ServerModel.ts
> +  if ([CardType.ACTIVE, CardType.AUTOMATED, CardType.EVENT].includes(card.cardType)) {
Nice, agree, done

2021-02-07 11:12 UTC, sienmich commented on src/components/SelectHowToPayForProjectCard.ts
> +        throw new Error('Unexpected undefined calculatedCost in SelectHowToPayForProjectCard');
This should never happen. I changed that to `this.cost = this.card.calculatedCost!;`, should be simpler.

This comes from the fact, that we have one class `CardModel` to both `IProjectCards` and some `ICorporationCard`, which is not optimal here (ones do have cost, ones do have not).

2021-02-07 11:20 UTC, sienmich commented on src/server/ServerModel.ts
> +    enabled?: Array<boolean>, // If provided, then the cards with false in `enabled` are not selectable and grayed out
I'm not sure, most of the time it is an unused parameter, so one undefined seems more optimal than an array of falses.
Anyway, I'm planning to change the `enabled` from `Array<bool>` to function `(card) => bool`, which should be cleaner.

2021-02-07 21:07 UTC, kberg approved these changes
How do you know this works? This part of the system doesn't have a lot of tests.

2021-02-07 21:07 UTC, kberg commented on src/components/SelectHowToPayForProjectCard.ts
> +      this.cost = this.card.calculatedCost!; // TODO(sienmich): Remove the ! here. It could require splitting the CardModel into ProjectCardModel and CorporationCardModel.
How about `this.card.calculatedCost || 0`?

2021-02-07 21:07 UTC, kberg commented on src/server/ServerModel.ts
> +      waitingFor: getWaitingFor(player, player.getWaitingFor()),
Ugh,yeah.

2021-02-07 21:07 UTC, kberg commented on src/server/ServerModel.ts
> +    enabled?: Array<boolean>, // If provided, then the cards with false in `enabled` are not selectable and grayed out
All fine.

2021-02-07 23:14 UTC, bafolts requested changes

2021-02-07 23:14 UTC, bafolts commented on src/components/SelectHowToPayForProjectCard.ts
> +      this.cost = this.card.calculatedCost!; // TODO(sienmich): Remove the ! here. It could require splitting the CardModel into ProjectCardModel and CorporationCardModel.
Using `0` makes sense as it was the behavior before and it makes sense as technically corporation cards have no calculated cost. Using `!` is always going to lead to side effects.

2021-02-08 12:03 UTC, sienmich commented on src/components/SelectHowToPayForProjectCard.ts
> +      this.cost = this.card.calculatedCost!; // TODO(sienmich): Remove the ! here. It could require splitting the CardModel into ProjectCardModel and CorporationCardModel.
Sure
```suggestion
      this.cost = this.card.calculatedCost || 0;
```

2021-02-08 12:39 UTC, sienmich commented
> How do you know this works? This part of the system doesn't have a lot of tests.

That's true.
I think it's generally not the best part of the system. I think it would be cleaner to have some subclasses for each PlayerInput type than those switches.
I made minimal changes required to reasonably implement showing card discounts and show card owners in the future.
I don't really feel like writing tests to this.
Testing this manually (playing game) looks good.

2021-02-08 16:46 UTC, kberg commented
Why request an additional review? I think this is ready to go.

2021-02-08 17:03 UTC, sienmich commented
@bafolts requested changes, so until he approves the merge is blocked

2021-02-08 18:54 UTC, bafolts approved these changes

2021-02-08 20:33 UTC, merged

2021-02-08 20:40 UTC, kberg commented
Well, that makes sense, thanks.

>