Turning help-iconology into a full help page
bafolts/terraforming-mars pull request #2720
Opened 2021-02-10 02:24 UTC by vsrisuknimit

I am turning the help-iconology page into a full on help page with information you could normally find on player-aid cards.

2021-02-10 03:15 UTC, vsrisuknimit commented
![image](https://user-images.githubusercontent.com/14239220/107459510-5987d180-6b24-11eb-96a8-0eb2c47733b9.png)

2021-02-10 15:56 UTC, vsrisuknimit commented
![image](https://user-images.githubusercontent.com/14239220/107535305-9dafbc00-6b8e-11eb-98ff-dada34b07c78.png)

2021-02-10 15:58 UTC, vsrisuknimit commented
Good for now. We could add more later. At the moment,I could not think of other stuffs to add unless @kevinb9n has more suggestions. I wrote the game phases tab to be more relevant to the web app (skipping setup for example).

2021-02-10 15:59 UTC, vsrisuknimit commented
Not totally happy with the way the tabs and collapsible list look but they serviceable. Tagging @ssimeonoff just in case he has suggestion.

2021-02-10 16:34 UTC, alrusdi commented
> Not totally happy with the way the tabs and collapsible list look but they serviceable. Tagging @ssimeonoff just in case he has suggestion.

Did you consider of tabs implementation build-in in our css framework (spectre)? https://picturepan2.github.io/spectre/components/tabs.html

2021-02-10 16:48 UTC, vsrisuknimit commented
> > Not totally happy with the way the tabs and collapsible list look but they serviceable. Tagging @ssimeonoff just in case he has suggestion.
> 
> Did you consider of tabs implementation build-in in our css framework (spectre)? https://picturepan2.github.io/spectre/components/tabs.html

No idea what that is and how to use it. Is it already in the repo? I thought we don't like a new library.

2021-02-10 16:53 UTC, vsrisuknimit commented
Ah, I see that it is already there. I will look into trying it out.

2021-02-10 17:37 UTC, vsrisuknimit commented
@alrusdi I gave it a try. I like my tabs better. For the collapsible list, spectre only has accordion. That is not good since opening one section collapses all others. Users might want to see more than one section at once.

2021-02-10 18:35 UTC, alrusdi approved these changes

2021-02-11 02:36 UTC, bafolts requested changes

2021-02-11 02:36 UTC, bafolts commented on src/components/help/HelpPhases.ts
> +            <li v-i18n>Draw 4 prelude cards <div class="expansion-icon expansion-icon-prelude"></li>
Reading through this HTML I spot `div` tags like this which seem like they are not closed. Believe there are `span` as well which are not closed. Going to look through this more tomorrow. Adding these new components to `compile-vue-templates.js` may help catch the HTML issues. Could also consider adding a unit test. The vue unit tests also runs another type checker that may catch these warnings as well.

2021-02-11 09:09 UTC, ssimeonoff commented
The tabs are nice - however they look, in the future the action buttons should look the same.

2021-02-11 11:40 UTC, vsrisuknimit commented on src/components/help/HelpPhases.ts
> +            <li v-i18n>Draw 4 prelude cards <div class="expansion-icon expansion-icon-prelude"></li>
@bafolts I looked through it again. That was the only spot with unclosed div or span. It is kinda of hard to see when writing in one chunk of string.

2021-02-11 21:06 UTC, puuj commented
I think putting the keyboard shortcuts here might make sense, and possibly the standard actions (greenery, temperature)?

2021-02-12 00:12 UTC, vsrisuknimit commented
![image](https://user-images.githubusercontent.com/14239220/107715296-ff5e4c00-6c9c-11eb-9060-1b4a8566dfd9.png)

@puuj, I moved hotkeys to the help-page.

2021-02-12 01:05 UTC, kevinb9n commented on src/components/help/HelpPhases.ts
> +                      <span v-i18n>lobby: one is free, 5 mc per delegate after<span>
Their choice of the homonym "Lobby" for this action (when there is already a *place* called the "Lobby") is such a bad move that I would suggest avoiding and saying "send delegate" instead.

It's possible (though rare) that even your first delegate placed will cost 5 mc, so it's more accurate to just say that they're free if from lobby and 5 mc otherwise.

2021-02-12 01:07 UTC, kevinb9n commented on src/components/help/HelpPhases.ts
> +                    <li v-i18n>(If playing solo, Venus track must be completed as well.) </li>
This should reference the "Mandatory Venus Terraforming" option.

In solo, the game end trigger is 12/14 generations, no relation to terraforming. But if the game end is triggered, then victory is judged immediately.

2021-02-12 01:09 UTC, kevinb9n commented on src/components/help/HelpPhases.ts
> +                    <li v-i18n>Each colony marker goes up one step</li>
Following Market Manipulation, I'd suggest something like "Each colony tile track is increased 1 step if possible". Or "Each unmaxed..." to avoid the "if possible" at the end.

2021-02-12 01:12 UTC, kevinb9n commented on src/components/help/HelpPhases.ts
> +            <li v-i18n>In turn order, play the corporation and pay 3 mc for each of the kept project cards.</li>
Recommend "then buy the project cards that weren't discarded", because Polyphemos/Terralabs.

2021-02-12 01:15 UTC, kevinb9n commented on src/components/help/HelpPhases.ts
> +            <li v-i18n>In turn order, play the corporation and pay 3 mc for each of the kept project cards.</li>
At this point, Generation 1 has already begun, so we should be under "each generation" by now.

Officially, the entire setup process is all part of the first generation.

2021-02-12 01:15 UTC, kevinb9n commented on src/components/help/HelpPhases.ts
> +                    <li v-i18n>use active (blue) card action</li>
would remove "blue" (corps too).

2021-02-12 11:24 UTC, vsrisuknimit commented on src/components/help/HelpPhases.ts
> +            <li v-i18n>In turn order, play the corporation and pay 3 mc for each of the kept project cards.</li>
3 mc is fine. People can deal with the exception themselves.

2021-02-12 11:24 UTC, vsrisuknimit commented on src/components/help/HelpPhases.ts
> +                    <li v-i18n>(If playing solo, Venus track must be completed as well.) </li>
No need to do Mandatory Venus Terraforming. Very weird variant anyway.

2021-02-12 11:25 UTC, vsrisuknimit commented on src/components/help/HelpPhases.ts
> +            <li v-i18n>In turn order, play the corporation and pay 3 mc for each of the kept project cards.</li>
This is easier to read than each generation but gen 1 is different.

2021-02-12 13:14 UTC, vsrisuknimit commented on src/components/help/HelpPhases.ts
> +            <li v-i18n>Draw 4 prelude cards <div class="expansion-icon expansion-icon-prelude"></li>
@bafolts this should be good to go.

2021-02-12 15:19 UTC, kevinb9n commented on src/components/help/HelpPhases.ts
> +                    <li v-i18n>(If playing solo, Venus track must be completed as well.) </li>
That's fine too, I just meant that it is what the sentence as written applies to, fine to remove it.

2021-02-12 15:22 UTC, kevinb9n commented on src/components/help/HelpPhases.ts
> +            <li v-i18n>In turn order, play the corporation and pay 3 mc for each of the kept project cards.</li>
Fair enough. Please consider keeping the word "buy" in there, as that is the game keyword that these corps reference.

2021-02-12 15:24 UTC, kberg reviewed
This is a lot of feature work, and thank you, but consider this, what about just adding markdown to the github wiki instead?

2021-02-12 15:29 UTC, kevinb9n commented on src/components/help/HelpPhases.ts
> +            <li v-i18n>In turn order, play the corporation and pay 3 mc for each of the kept project cards.</li>
It is, and ease of reading is an important virtue. But I think it's only a virtue for correct information. In this case, the current text will lead to disappointed Pristar players and confused UNMI players, who will try to report bugs (it already happens).

2021-02-12 15:31 UTC, kevinb9n commented on src/components/help/HelpPhases.ts
> +                    <li v-i18n>(In solo mode, the game also end when temperature, oxygen and oceans are maxed. If Venus Next is in use, the gaVenus track must be completed as well.) </li>
Nope, again, this is not a game end trigger for solo.

2021-02-12 15:35 UTC, kevinb9n commented
> This is a lot of feature work, and thank you, but consider this, what about just adding markdown to the github wiki instead?

One key question here is whether this content should track with the version of the server that user happens to be on, or whether users will usually be best served by always seeing the latest version.

2021-02-12 15:40 UTC, kevinb9n commented on src/components/help/HelpPhases.ts
> +                    <li v-i18n>(In solo mode, the game also end when temperature, oxygen and oceans are maxed. If Venus Next is in use, the gaVenus track must be completed as well.) </li>
source for ya:

<img width=400 src=https://user-images.githubusercontent.com/934551/107788682-8d6e1d00-6d05-11eb-9a37-214df415a912.png>

2021-02-12 15:43 UTC, kevinb9n commented on src/components/help/HelpPhases.ts
> +                    <li v-i18n>(In solo mode, the game also end when temperature, oxygen and oceans are maxed. If Venus Next is in use, the gaVenus track must be completed as well.) </li>
Getting your terraforming done early is a nice stretch goal, as it prevents the WG from stealing a TR. Sorry, done responding here now.

2021-02-12 15:50 UTC, vsrisuknimit commented
> This is a lot of feature work, and thank you, but consider this, what about just adding markdown to the github wiki instead?

Better for it to be self-contained all in one page as a player aid. No need to link to another Github page. Many users might also be afraid of Github.

2021-02-12 15:59 UTC, vsrisuknimit commented on src/components/help/HelpPhases.ts
> +                    <li v-i18n>(In solo mode, the game also end when temperature, oxygen and oceans are maxed. If Venus Next is in use, the gaVenus track must be completed as well.) </li>
updated. was confused by your earlier statement.

2021-02-12 16:43 UTC, kberg commented
> > This is a lot of feature work, and thank you, but consider this, what about just adding markdown to the github wiki instead?
> 
> Many users might also be afraid of Github.

What does that mean?

2021-02-12 16:45 UTC, kberg commented
> > This is a lot of feature work, and thank you, but consider this, what about just adding markdown to the github wiki instead?
> 
> One key question here is whether this content should track with the version of the server that user happens to be on, or whether users will usually be best served by always seeing the latest version.

Someone with the engineering skill to make meaningful changes that reflect on the iconology will be able to change the link to their local repo, too.

2021-02-12 16:58 UTC, vsrisuknimit commented
> > > This is a lot of feature work, and thank you, but consider this, what about just adding markdown to the github wiki instead?
> > 
> > 
> > Many users might also be afraid of Github.
> 
> What does that mean?

@kberg 
This
![image](https://user-images.githubusercontent.com/14239220/107797976-86f19c80-6d29-11eb-8ad2-e995284502be.png)
is not as user-friendly as this

![image](https://user-images.githubusercontent.com/14239220/107798024-97a21280-6d29-11eb-83e7-6fa1df682457.png)

2021-02-12 19:38 UTC, kberg commented
Nope, not getting it. Using words, what are users afraid of?

>

2021-02-12 22:15 UTC, vsrisuknimit commented
> Nope, not getting it. Using words, what are users afraid of?
> […](#)

When users look at the help page, they want to know how the game is played. It works like an IRL player-aid cards. All the information are now together in one placed. If we have a link to Github, they now need to open two tabs. And now they are overloaded with information. They don't care about 'pull request', 'issues', 'discussion', etc.

2021-02-13 15:31 UTC, kberg commented
Gotcha. I don't think afraid is the right term, nor do I agree with the
concern, but I'm glad to understand your perspective.

2021-02-14 03:05 UTC, closed without merging