Replace localized card discount reporting, moving it to the card. Add Moon Tether.
bafolts/terraforming-mars pull request #2771
Opened 2021-02-15 21:09 UTC by kberg

![image](https://user-images.githubusercontent.com/413481/107992682-31c2be80-6fa7-11eb-86ab-c9e83016db5c.png)
![image](https://user-images.githubusercontent.com/413481/107993075-1dcb8c80-6fa8-11eb-98df-f9aa39cc2d43.png)

2021-02-18 02:04 UTC, bafolts commented on src/models/CardModel.ts
> +    discount?: CardDiscount,
This makes sense to me to place on `CardMetadata`. Placing the `discount` on `CardMetadata` will also help with memory per card.

2021-02-18 02:11 UTC, bafolts commented on src/cards/base/AntiGravityTechnology.ts
> +export const ALL = 'all';
I don't think this is used anywhere. Probably leftover from when taking a different approach. Or I am missing something.

2021-02-18 02:13 UTC, bafolts requested changes
Separating the discount mapping from `PlayerTags` is good change. The added `cardDiscount` property will either have to use the static memory pattern or be placed on the `metadata` property. It feels like it is metadata property to me so would make sense to place on `metadata`.

2021-02-18 02:13 UTC, kberg commented on src/cards/base/AntiGravityTechnology.ts
> +export const ALL = 'all';
A, removing

2021-02-18 02:45 UTC, kberg commented on src/models/CardModel.ts
> +    discount?: CardDiscount,
How about making that a follow-up change?

2021-02-18 04:06 UTC, kberg commented
> Separating the discount mapping from `PlayerTags` is good change. The added `cardDiscount` property will either have to use the static memory pattern or be placed on the `metadata` property. It feels like it is metadata property to me so would make sense to place on `metadata`.

I'm ... not so sure. But OK.

2021-02-18 04:13 UTC, kberg commented
> > Separating the discount mapping from `PlayerTags` is good change. The added `cardDiscount` property will either have to use the static memory pattern or be placed on the `metadata` property. It feels like it is metadata property to me so would make sense to place on `metadata`.
> 
> I'm ... not so sure. But OK.

Do you mean CardMetadata? CardMetadata has mostly been used for rendering. I'd like to keep those separate, and prefer to use the static memory pattern (and replace calls to getCardDiscount where reasonable.)

2021-02-19 02:05 UTC, bafolts approved these changes
Using the static memory pattern would also be fine. Doing in a separate pull request is fine.

2021-02-19 02:55 UTC, kberg commented
> Using the static memory pattern would also be fine. Doing in a separate pull request is fine.

Already done.

2021-02-19 02:55 UTC, merged