Improve Turmoil send delegate UI
bafolts/terraforming-mars pull request #2792
Opened 2021-02-18 23:32 UTC by vsrisuknimit

Problem: Sending delegate to party action is not intuitive. Too much text, not enough info.

This PR can close #1689.

Changes:
- Remove orOptions and Option from Turmoil. Added a new class based on SelectColony
- Display each turmoil party as selectable objects similar to how cards and colonies are done

Example:

![image](https://user-images.githubusercontent.com/14239220/108435329-34c3e600-7217-11eb-9082-886bd9cfabdf.png)

![image](https://user-images.githubusercontent.com/14239220/108435334-38f00380-7217-11eb-803e-4ef587ad18c8.png)

2021-02-19 10:30 UTC, chosta reviewed
Wow, you are getting good at this :)
Front-end wise I don't see anything that bothers me but I'd like someone else to check the server logic before approval.
The only thing that really bothers me are the red arrows showing direction. This has to be a different color in my opinion. The direction is there to help and not to ring an alaram.  I'd choose one of the 50 shades of grey for it.

2021-02-19 10:32 UTC, chosta commented on src/components/SelectPartyToSendDelegate.ts
> +    'Button': Button,
This could be just  {Button, Party}

2021-02-19 11:18 UTC, vsrisuknimit commented
![image](https://user-images.githubusercontent.com/14239220/108498025-48ecff00-727a-11eb-80ff-0f504d6c6145.png)

![image](https://user-images.githubusercontent.com/14239220/108498067-530efd80-727a-11eb-8078-97ba07d1868b.png)

@chosta

2021-02-19 11:18 UTC, vsrisuknimit commented on src/components/SelectPartyToSendDelegate.ts
> +    'Button': Button,
done

2021-02-19 11:36 UTC, alrusdi approved these changes
Everything seems to be allright. Let's merge it

2021-02-19 12:47 UTC, vsrisuknimit commented
Since I have no idea what I am doing on the backend, let's wait for @bafolts or @kberg to or @Lynesth to take a look too.

2021-02-20 02:52 UTC, bafolts commented on src/server/ServerModel.ts
> +  game: Game | undefined,
It isn't necessary to pass `game` as an argument. The `player.game` property should be used.

2021-02-20 02:56 UTC, bafolts requested changes
We have moved away from passing `game` argument separately. If the `player` argument is provided we should use `player.game`. We are trying to do this throughout the code. In `ServerModel` can you revert the introduction of `game` argument to the `getWaitingFor` function and use `player.game`?

2021-02-20 02:58 UTC, bafolts commented on src/deferredActions/SendDelegateToArea.ts
> +    parties.forEach((party) => availableParties.push(party.name));
Not a big deal but this is equivalent to `const availableParties = parties.map((party) => party.name);`. Using the `map` should be more efficient as well.

2021-02-20 03:51 UTC, vsrisuknimit commented on src/deferredActions/SendDelegateToArea.ts
> +    parties.forEach((party) => availableParties.push(party.name));
done

2021-02-20 03:51 UTC, vsrisuknimit commented on src/server/ServerModel.ts
> +  game: Game | undefined,
removed game

2021-02-20 19:40 UTC, bafolts approved these changes

2021-02-20 21:33 UTC, merged