keep trying if error while waiting
bafolts/terraforming-mars pull request #2812
Opened 2021-02-20 22:17 UTC by bafolts

If there is an error response code from the server while waiting for a player to take their turn the server is most likely restarting. This has the failure cases retry while logging the error client side. On the server the non 200 response codes will be logged. If the client failed to reach the server they will try the request again after the update period. This should be a better user experience for multi-player games. This will close #2808

2021-02-21 06:46 UTC, alrusdi approved these changes

2021-02-21 06:46 UTC, alrusdi commented on src/components/WaitingFor.ts
> +          console.warn('unable to reach server waiting for');
Shoudn't it continue only if 500 http status is received?

2021-02-22 01:34 UTC, kberg requested changes

2021-02-22 01:34 UTC, kberg commented on src/components/WaitingFor.ts
> +          console.warn('unable to reach server waiting for');
While the alert isn't pretty, this leaves someone with no understanding of what's going on. Someone might think the server is frozen or something.

If the app up some kind of butter bar I'd be more comfortable with this.

2021-02-28 01:26 UTC, bafolts commented
I am going to modify this to use the custom `alert` we use elsewhere for the `WaitingFor` component. I will also make the error message more verbose to explain the situation that the server is most likely re-starting. Using the custom `alert` wont be as intrusive as the native `alert`. Once the alert is clicked we can then start the waiting for loop back checking with the server. When the server is restarting this will prevent requests from coming in. If someone has a tab open in the background the custom alert wont be as intrusive as the native alert. When they get back to the page they will see there was some problem and clicking ok will start their game back. This will be simpler than introducing a new UI component.

2021-02-28 22:01 UTC, bafolts commented
@kberg I took a simpler approach with this. I think it will improve the situation for #2808. Moving away from the native `window.alert` will avoid potentially stealing focus for users that are running a game in the background or a separate tab. I also improved the error message to make it less vague. This also moves the alert component to a place we can use it more often.

![image](https://user-images.githubusercontent.com/2707843/109435087-dd233880-79d5-11eb-9328-9ff426e90af7.png)

2021-03-01 04:44 UTC, kberg commented on src/components/WaitingFor.ts
> +            root.showAlert(`Received unexpected response from server (${xhr.status}). Server is most likely restarting.`, () => vueApp.waitForUpdate());
"This is often due to the server restating." is a little less potentially misleading, fwiw.

2021-03-01 04:44 UTC, kberg approved these changes

2021-03-02 01:26 UTC, merged