Add corporation contest winner Curiosity II
bafolts/terraforming-mars pull request #2828
Opened 2021-02-23 06:59 UTC by nwai90

<img width="347" alt="Screenshot 2021-02-23 at 2 58 16 PM" src="https://user-images.githubusercontent.com/2408094/108811168-bc2ea200-75e7-11eb-9039-e292f369a21a.png">

2021-02-23 07:20 UTC, kberg commented on src/CardName.ts
> +    CURIOSITY_II = 'Curiosity II',
I assume the card names are in a specific order, so why put this one here?

2021-02-23 07:20 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id === activePlayer.id && space.bonus.length > 0 && space.spaceType !== SpaceType.COLONY) {
According to the text as written, this should not trigger when placing the three special oceans. Those spaces are not empty, they have an ocean tile.

The same applies to placing a tile on top of a hazard.

2021-02-23 07:20 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id === activePlayer.id && space.bonus.length > 0 && space.spaceType !== SpaceType.COLONY) {
As written, you will need to know when the space is on The Moon and not Mars. The way I've been distinguishing between them is to check the tile type. Here you would filter out TileType.MOON_COLONY, TileType.MOON_MINE, and TileType.MOON_ROAD. Ideally, onTilePlaced would include a "satellite" parameter, or perhaps ISpace would include one (that just repeats that it's a Mars or Moon space) but this works since those are the only three types of tiles in use on the Moon.

Or, permit this corporation to apply to The Moon. That may not be what Curiosity II was meant for (Mars, I get it, really I do) but consider that it can put the corporation at a disadvantage.

2021-02-23 07:20 UTC, kberg commented on tests/cards/community/CuriosityII.spec.ts
> +    expect(player.cardsInHand).has.lengthOf(0);
I think you can write .is.empty, but your call.

2021-02-23 07:20 UTC, kberg commented on src/CardName.ts
> +    CURIOSITY_II = 'Curiosity II',
This is so obviously a minor point, but you did it consciously, and I'm curious.

2021-02-23 07:21 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id === activePlayer.id && space.bonus.length > 0 && space.spaceType !== SpaceType.COLONY) {
The first is easy to test for because you can filter on the tile type. But the hazards will not, because by the time this function is called, the hazard has disappeared.

2021-02-23 07:22 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id === activePlayer.id && space.bonus.length > 0 && space.spaceType !== SpaceType.COLONY) {
Wait, I'm, just realizing: this is for when you place a tile on a non-empty space? _non-empty?_

2021-02-23 07:25 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id === activePlayer.id && space.bonus.length > 0 && space.spaceType !== SpaceType.COLONY) {
Now I see -- non-empty isn't about tiles or land claim, it's about space bonuses? I'd suggest rewriting the description either way, and help me understand the proper goal. (If it's space bonus, then the overplacement for hazards and oceans probably still applies.)

2021-02-23 07:25 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +              eb.emptyTile('normal', CardRenderItemSize.SMALL).startEffect.megacredits(3).arrow().cards(1);
I think add astersik before startEffect, since there's a special condition not conveyed in the iconography.

2021-02-23 07:34 UTC, nwai90 commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id === activePlayer.id && space.bonus.length > 0 && space.spaceType !== SpaceType.COLONY) {
The description can be changed if there is a better way to word it. This is the original which is not quite catch-all either, maybe @kevinb9n can help with that. The term "resource" is probably not sufficient here since a card is not a resource.

![image](https://user-images.githubusercontent.com/2408094/108813675-71635900-75ec-11eb-8366-dc6ab18d2655.png)

2021-02-23 07:39 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id === activePlayer.id && space.bonus.length > 0 && space.spaceType !== SpaceType.COLONY) {
The rulebook calls it a "placement bonus"

![image](https://user-images.githubusercontent.com/413481/108814098-3f1c1200-7580-11eb-87c2-4fba9b41e821.png)

"When covering a placement bonus with a tile."?

2021-02-23 07:39 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id === activePlayer.id && space.bonus.length > 0 && space.spaceType !== SpaceType.COLONY) {
Which reminds me: what will this corp do during WGT?

2021-02-23 07:43 UTC, nwai90 commented on src/CardName.ts
> +    CURIOSITY_II = 'Curiosity II',
No real reason, will move it up

2021-02-23 08:08 UTC, nwai90 commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id === activePlayer.id && space.bonus.length > 0 && space.spaceType !== SpaceType.COLONY) {
Resolved

2021-02-23 09:10 UTC, alrusdi approved these changes
It seems working. I've tried it in solo mode and didn't found any issues

2021-02-23 12:40 UTC, kberg requested changes

2021-02-23 12:40 UTC, kberg commented on src/cards/base/RoboticWorkforce.ts
> +    CardName.CURIOSITY_II,
Why is this applied here? This card doesn't have behavior Robotic Workforce would use.

2021-02-23 12:40 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +            ce.effect('When you place a tile on an area ON MARS that has a resource placement bonus, you may pay 3 MC to draw a card.', (eb) => {
@kevinb9n for feedback on this one. A "resource placement bonus" is a new term, and might be just fine.

2021-02-23 12:40 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.game.phase !== Phase.ACTION) return;
This  makes prelude an invalid phase. Suggest using === Phase.SOLAR.

2021-02-23 12:40 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
A prior comment was resolved, but isn't. Specifically, about Ares-compatibility. Overplacing oceans and hazards will not reveal the space bonuses and should be filtered.

Oceans won't be hard to manage, but hazards will be tricky.

2021-02-23 12:50 UTC, nwai90 commented on src/cards/base/RoboticWorkforce.ts
> +    CardName.CURIOSITY_II,
It does. Two steel production is copy-able

2021-02-23 12:54 UTC, kberg commented on src/cards/base/RoboticWorkforce.ts
> +    CardName.CURIOSITY_II,
You're right of course. Sorry, I was so focused on the effect, I hadn't looked at the initial behavior.

2021-02-23 13:07 UTC, nwai90 commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
@kberg Does it matter here though? The effect is triggered when a tile is placed on a space that has some resource(s) on it. On a physical board this would be the equivalent of the "printed" resources on the tile.

My interpretation is that it is not necessary for you to actually gain the bonus resources on the tile itself. For example in the case of hazards, you will never gain the bonus resources when placing a tile on top of a hazard to remove it. Preventing the corporation effect from triggering would significantly weaken this corporation in an Ares game.

2021-02-23 16:14 UTC, kevinb9n commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
I have assumed the behavior should be just like Mining Area/Rights, only widened from 2 resource types to all. How do those currently work in this sense?

2021-02-23 16:16 UTC, kevinb9n commented on src/cards/community/CuriosityII.ts
> +            ce.effect('When you place a tile on an area ON MARS that has a resource placement bonus, you may pay 3 MC to draw a card.', (eb) => {
It was my suggestion, based on Mining Area/Rights.

Or maybe "a placement bonus including at least one resource" would be extra extra clear?

2021-02-23 16:43 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
I do think it matters here, because I think it's thematically inconsistent. A player places a tile over a hazard, and activates the corp ability without gaining the benefit, it's a bit awkward.

Consider if this card was used in a physical game. What would it do?

What if the description read "When you gain a _resource placement bonus_?" This would work, and would work slightly different from `EcologicalSurvey` but they would be pretty similar. I don't understand exactly how the new priority queue works, but @Lynesth promises me that it does the right thing. So perhaps you can mimic Ecological Survey to achieve the this goal.

I realize I'm getting into card design, but my priorities in this discussion are a) consistent behavior, b) mildly reasoanble theme c) clear card description.

2021-02-23 16:44 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
Whether this PR contains such a change or not is less important than us agreeing on what the behavior ought to be (or settling on letting it ride for now.)

2021-02-23 18:01 UTC, vsrisuknimit commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
Sid (the card designer) does not play with Ares. He thinks @nwai90's current wording and the current code behavior is fine.

2021-02-23 18:39 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
> Sid (the card designer) does not play with Ares. He thinks @nwai90's current wording and the current code behavior is fine.

I am not surprised given the wording that was the case.

2021-02-23 19:34 UTC, vsrisuknimit commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
It is fine. It is the behavior we want. It is more balanced this way. So let's move on with it. Or do you not like it just because it is not thematic?

2021-02-23 20:31 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
I will wait for @nwai90 to address my questions.

2021-02-23 21:31 UTC, vsrisuknimit commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
I think going forward we need to be clear whether Ares-compatibility is the responsibility of the person trying to add a new card or it is something to be handled later by the maintainer of Ares. Not everyone plays with Ares and should be expected to understand the intricacy of Ares. I am asking this because there are more cards from the competition that have tile placement action/effect.

I also think that we should talk to the designer if we want to change the design. I did ask Sid. 

> I think you could make it work either way. I don't know what would be best. Probably let it still get the card draw bonus, because otherwise it would be too weak in Ares?

2021-02-23 21:49 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
It's the responsibility of both the author and the reviewer to make sure the change is as broadly compatible as can be, Ares or not Ares. This is a prime example of the sort of "discuss before making a PR" that's now in CONTRIBUTING.md. This is the fundamental problem with incomplete contributions; they put an immense burden on maintainers who also like doing cool things like designing cards.

Did this contest include a commitment to provide a PR to the main repo? If so, I hope the entrants realize that it might have to be different from what they envisioned, either because they didn't consider it, or because it's far too structurally difficult to get right. The community server is a fine place for code with a different definition of compatibility.

I'm going to propose a PR update to contributors.md to indicate this. It will help.

2021-02-23 21:54 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
Honestly, I think once nwai90 and I get a chance to talk this won't take long.

2021-02-24 00:56 UTC, nwai90 commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
There is a difference between merely placing a tile on a space that contains a resource bonus and having to actually gain that bonus. Current code triggers the corporation's ability based on the latter.

In Ares, the hazard covers the bonus, so you don't get those resources if you place there and remove the hazard. It does not mean the resources are not there though. They are still present, you just don't gain them. Allowing this corporation to trigger its effect to pay 3 MC to draw a card hardly seems game-breaking in these scenarios, given that its ability is about average.

The issue is purely pedantic - I will suggest to leave it as is and not further nerf this corporation.

2021-02-24 02:45 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
As you know, the upgraded oceans are also not eligible for the bonuses underneath. That's set a precedent for how tile overlay works. And now Ares will have inconsistent behavior with this for. And that's why I think this isn't pedantic? For the person not playing Ares? Of course. For the person playing Ares, it's inconsistent, confusing, and solvable.

2021-02-24 03:46 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
In a discussion with @nwai90 we came to some agreements.

1. @nwai90 expressed some detail about his concern about nerfing the corp with Ares. While I don't think that's so bad, and also imagine if I used this corp on a physical board, the fact that it's covered would change a lot.
2. In early review, suggested he decide whether to include The Moon, and he chose to not include it. I didn't ask why, but I can imagine it was thematic for our beaitful Mars rover. But in further discussion, by omitting this corp from bonuses on The Moon (and bonuses are coming with the new map) that nerfs the corp (I suspect) even worse than the concern for Ares.

We hit upon a compromise.

1. Allow overplacement on Mars.
2. Enable the corp behavior on The Moon
3. Change the text to clarify overplacement is valid. Two options:
a. When you place a tile on a space with a resource placement bonus, or cover a tile on a space with a space bonus, you may ... .
but that's janky.
b.  When you place a tile on a space with a resource placement bonus you may blah blah end of sentence.) <newline> (Placing a tile on top of another one when the space has a resource placement bonus triggers this effect, such as with Ares.)

What's the saying about compromise? In a good compromise everyone walks away a little unhappy?

2021-02-24 03:53 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
Wait! New idea. Something even simpler in terms of text.

"When you place a tile on a space with a RESOURCE placement bonus, or place a tile on top of another tile, you may..."

(I capitalized RESOURCE because I suspect it's going to matter that people unclear won't get it.)

But that's not janky, remains thematic, and gives this corp it's freedom from being nerfed.

To make it work still requires the same code change I'm going to have to make, but it'll be easy to do and I'll follow up with it in the next day or two.

All we need now is agreement that this is the way to go. (already got an OK from @nwai90)

2021-02-24 11:13 UTC, vsrisuknimit commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
@kberg Cards that are not Ares-specific should not have wording on them that are Ares-specific. That will just confuse the general users who will ask 'how do I place a tile on top of another tile?'.

2021-02-24 16:54 UTC, kevinb9n commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
@vsrisuknimit I think that's a good point. It might (?) still be the most acceptable solution anyway, but it's a good point.

2021-02-25 03:00 UTC, kberg approved these changes

2021-02-25 03:01 UTC, kberg commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
I'd prefer it to be cleaner, too. Like I said before, it seems to be an acceptable compromise.

2021-02-25 13:30 UTC, vsrisuknimit commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
![image](https://user-images.githubusercontent.com/14239220/109159816-1132fb00-7743-11eb-99e6-22f8fbf6da46.png)

The first sentence totally contains the second sentence, making the second one redundant.

Perhaps consider make an Ares version of the corp if you need a very specific wording for its interaction with Ares.

2021-02-25 14:49 UTC, vsrisuknimit commented on src/cards/community/CuriosityII.ts
> +    if (cardOwner.id !== activePlayer.id) return;
I also thought the card logic was changed to ignore what is underneath if you place on top of another tile.

Or make it totally clear this is for Ares. 

> When you place a tile on an area* that has a RESOURCE placement bonus, you may pay 3 mc to draw a card.
> (Ares fan-made expansion only: or when you place a tile on top of another tile)

2021-03-27 00:28 UTC, bafolts commented
Is this waiting on something to merge?

2021-03-27 00:36 UTC, nwai90 commented
@bafolts It's ready for merge

2021-03-27 00:39 UTC, merged