pull logs one generation at a time
bafolts/terraforming-mars pull request #2876
Opened 2021-03-01 02:16 UTC by bafolts

This adds back in the ability to see all logs. On the first generation the logs before the first generation are shown. On the final generation the last 50 are shown. Also added tests! Had to expand the api test handler to support loading by player id.

2021-03-01 02:28 UTC, bafolts commented on src/components/LogPanel.ts
> +      this.getLogsForGeneration(generation);
The type checking system with `compile-vue-templates` isn't working with this for some reason. This is why build is failing. Will have to address before I can merge.

2021-03-01 06:43 UTC, kberg requested changes

2021-03-01 06:43 UTC, kberg commented on tests/routes/FakeGameLoader.ts
> +    this.games.forEach((game) => {
this.games.getPlayers().some()

2021-03-01 06:43 UTC, kberg commented on src/routes/GameLogs.ts
> +      res.end(JSON.stringify(logs));
This is uncompressed? I thought you were looking to compress logs.

2021-03-01 06:43 UTC, kberg commented on src/routes/GameLogs.ts
> +    ctx.gameLoader.getByPlayerId(id, (game) => {
<3

2021-03-01 06:43 UTC, kberg commented on src/routes/GameLogs.ts
> +        logs = game.gameLog.slice(-50);
So does this mean if I'm on, say, generation 3, my UI will have all logs for generations 1 and 2, and only the last 50 for generation 3? So the log view will have a gap representing the first part of the third generation.

Of course generation 3 isn';t going to have 50 operations, but later generations will.

2021-03-01 06:43 UTC, kberg commented on tests/routes/FakeGameLoader.ts
> +    this.games.forEach((game) => {
I'm sure this can be simplified.

2021-03-02 01:37 UTC, bafolts commented on src/routes/GameLogs.ts
> +        logs = game.gameLog.slice(-50);
That is what it would mean. As this is confusing I can update this to return only the logs for that generation. The first generation would also return any log messages from before the first generation was logged.

2021-03-02 01:53 UTC, bafolts commented on src/routes/GameLogs.ts
> +      res.end(JSON.stringify(logs));
When it was all the logs I was looking to compress as those results would be large and always growing. With breaking down by generation the size of what we return should be smaller. Both the `gzip` and `br` impacted the CPU and response times significantly. Sometime on Sunday the response times with `br` grew so large that the server unusable, CPU load was over 4 and response time was averaging 10 seconds.

I would like to consider optimizations once the generation change is in. As heroku doesn't log bandwidth usage I am assuming at least breaking up by generation will lead to smaller payloads then sending back every game log. Ideally there would be some algorithm to send only the logs you needed. This would be straight forward without undo. Without undo the list is always growing and determining which logs a client needs it simple. With undo there may also be a simple strategy for determining which logs a client needs to download. This should be more effective than using compression and put less CPU load on the server.

2021-03-02 02:00 UTC, bafolts commented on src/routes/GameLogs.ts
> +      res.end(JSON.stringify(logs));
So at one point I watched a lot of the online MIT CS courses for advanced data structures. One of these was on retroactive data structures. I think we will need some way on the client to know which timeline you have. As long as no undo operation is used your timeline doesn't change. As long as the timeline doesn't change and we know how many logs you have on the client for that generation and timeline we can send the logs you need. If the timeline has changed you would need all logs. We have `game.gameAge` but I think we may also need a `game.timeline`. When the undo operation is used we could increment `game.timeline` as now we are entering a different timeline. A client may still have the old timeline. With this in place we would then update the log route to also provide `timeline` as an argument. This would all be done in a separate PR but I am curious what you think about this timeline approach @kberg

2021-03-02 04:34 UTC, kberg commented on src/routes/GameLogs.ts
> +      res.end(JSON.stringify(logs));
I covered this a little bit in #2598 LMK your thoughts about that.

2021-03-02 05:16 UTC, kberg approved these changes

2021-03-02 05:16 UTC, kberg commented on src/routes/GameLogs.ts
> +      if (message.message === 'Generation ${0}') {
`if (message.type === MessageType.NEW_GENERATION)` ?  Possibly quicker depending on how often this is called. Or, premature optimization.

2021-03-02 05:16 UTC, kberg commented on src/routes/GameLogs.ts
> +        logs = game.gameLog.slice(-50);
Your call.

2021-03-03 02:19 UTC, bafolts commented on src/routes/GameLogs.ts
> +      if (message.message === 'Generation ${0}') {
I didn't realize that `MessageType.NEW_GENERATION` was a thing. This is good change as it doesn't rely on comparing the string that someone could update.

2021-03-03 02:22 UTC, kberg commented
The regex is still necessary, but the searches are faster. Or you can swap
out the regex with counting the number of NEW_GENERATION log messages
received.

>

2021-03-03 02:43 UTC, merged

2021-03-03 02:45 UTC, bafolts commented
Counting the number of NEW_GENERATION messages would work. We had the bug where we were only storing the last 50 messages. On some servers we may not have the entire log available. Using the check for the value is slower but should prevent against these backwards compatible situations where we may not have all the old logs.