Move ServeAsset and ServeApp to handlers
bafolts/terraforming-mars pull request #2888
Opened 2021-03-05 03:34 UTC by kberg

NOTE: `ServeAsset` isn't really a handler yet. I'm just refactoring to I can start to make some sense out of the intertwined components separately.

2021-03-06 02:38 UTC, bafolts commented on src/server.ts
> +    ['/game', ServeApp.INSTANCE],
There is already an entry for `/game`

https://github.com/bafolts/terraforming-mars/blob/main/src/server.ts#L72

Will need to merge with `CreateGame` in some way.

2021-03-06 02:43 UTC, bafolts requested changes
Will need to consider the duplicate `/game` entries in the `handlers` Map. Can implement the `get` of `CreateGame` and then also remove the work around.

https://github.com/bafolts/terraforming-mars/blob/0e0e31a90a2af98e828d0b339a29b89adb53e628/src/server.ts#L72

2021-03-06 03:26 UTC, kberg commented
> Will need to consider the duplicate `/game` entries in the `handlers` Map. Can implement the `get` of `CreateGame` and then also remove the work around.
> 
> https://github.com/bafolts/terraforming-mars/blob/0e0e31a90a2af98e828d0b339a29b89adb53e628/src/server.ts#L72

This is all easy to fix because Handler multiplexes based on the request method.

2021-03-06 03:26 UTC, kberg commented on src/server.ts
> +    ['/game', ServeApp.INSTANCE],
Done.

2021-03-07 02:43 UTC, bafolts approved these changes

2021-03-07 02:44 UTC, merged