Add a (disabled) prototype for a sound when the log changes
bafolts/terraforming-mars pull request #2952
Opened 2021-03-13 14:36 UTC by kberg

There's a lot that's not good about this, yet. I could spend more time working on the web audio API, but at least this will a) help make it easier for other developers to start thinking about how sounds should change, and b) it is hidden -- it won't make sound unless you have an `experimental=1` parameter in your browser.

Really what I want is a quarter second buzz. I've done sounds before, but not with the web API, so it'll be a while. Plus, it has to be basically battle-tested before considering enabling it.

2021-03-13 14:38 UTC, kberg commented
I thought about adding the `node-web-audio` package so I could write a command-line tool to test sounds but eh, one thing at a time. But I wish there were a faster development cycle.

2021-03-14 14:58 UTC, bafolts commented on src/components/LogPanel.ts
> +          if (PreferencesManager.loadValue('enable_sounds') === '1' && window.location.search.includes('experimental=1') ) {
There is a new `loadBooleanValue` which can be used here to avoid having to check for `=== '1'`.

2021-03-14 15:12 UTC, bafolts commented on src/components/SoundManager.ts
> +    const audioCtx = window.AudioContext || (window as any).webkitAudioContext ? new AudioContext() : undefined;
You most likely only moved this code but the check for `(window as any).webkitAudioContext)` can be removed as it isn't being used. This code is checking that the `AudioContext` constructor or the older `webkitAudioContext` constructor exists but then only makes use of the `AudioContext` constructor. If the `webkitAudioContext` exists but `window.AudioContext` does not exist this line is going to throw a runtime error that `AudioContext` is not a function.

2021-03-14 15:15 UTC, bafolts commented on src/components/SoundManager.ts
> +  function playInContext(cb: (audioCtx: any) => void) {
This doesn't have to use `any`. This can use `AudioContext` as the type of the `audioCtx` argument.

2021-03-14 15:22 UTC, bafolts commented on src/components/SoundManager.ts
> +    audioCtx.resume().then(() => {
The server side has avoided promises thus far. In this situation the audio context is requiring the use of promises. I would use `await` and `async` versus calling `then`. Calling `then` can be harder to read and this also isn't calling to `catch` for errors.

```
async function playInContext(cb: (audioCtx: AudioContext) => void) {
  const audioCtx = createAudioContext();
  if (audioCtx === undefined) return;
  await audioCtx.resume();
  cb(audioCtx);
}
```

2021-03-14 15:26 UTC, bafolts requested changes
Minor tweaks suggested. Moving `SoundManager` into `components` is good move.

2021-03-14 15:30 UTC, bafolts commented
Using and playing wav files may be larger code but should be simpler to develop. Storing them as assets would be simple enough. Could be far less time consuming to develop.

2021-03-14 16:02 UTC, kberg commented
> Using and playing wav files may be larger code but should be simpler to develop. Storing them as assets would be simple enough. Could be far less time consuming to develop.

I sure agree. /shrug

2021-03-14 16:12 UTC, kberg commented on src/components/LogPanel.ts
> +          if (PreferencesManager.loadValue('enable_sounds') === '1' && window.location.search.includes('experimental=1') ) {
Thanks, done.

2021-03-14 16:12 UTC, kberg commented on src/components/SoundManager.ts
> +  function playInContext(cb: (audioCtx: any) => void) {
Thank you.

2021-03-14 16:12 UTC, kberg commented on src/components/SoundManager.ts
> +    audioCtx.resume().then(() => {
Do you mind if I make this change in another PR?

2021-03-14 16:12 UTC, kberg commented on src/components/SoundManager.ts
> +    const audioCtx = window.AudioContext || (window as any).webkitAudioContext ? new AudioContext() : undefined;
OK. Please double-check that I got this right

2021-03-14 16:12 UTC, kberg commented on src/components/SoundManager.ts
> +    const audioCtx = window.AudioContext || (window as any).webkitAudioContext ? new AudioContext() : undefined;
Because _this_ doesn't make sense,either.

```
    const audioCtx = window.AudioContext || new AudioContext();

    if (audioCtx === undefined) console.log('This web browser doesn\'t support Web Audio API');
    return audioCtx;
  }
```

2021-03-14 16:12 UTC, kberg commented on src/components/SoundManager.ts
> +    const audioCtx = window.AudioContext || (window as any).webkitAudioContext ? new AudioContext() : undefined;
Ah, the problem is that if I remove this, then typescript gets fussy. I'm undoing the changes I made based on your suggestion. If you want to dig in, please do! Or teach more, please.

2021-03-14 18:29 UTC, bafolts commented on src/components/SoundManager.ts
> +    const audioCtx = window.AudioContext || (window as any).webkitAudioContext ? new AudioContext() : undefined;
With our stated browser support I would assume that `AudioContext` exists.

https://caniuse.com/?search=AudioContext

Otherwise this would become:

```
const audioCtx = window.AudioContext ? new AudioContext() : undefined;
```

2021-03-14 18:33 UTC, bafolts commented on src/components/SoundManager.ts
> +    const audioCtx = window.AudioContext || (window as any).webkitAudioContext ? new AudioContext() : undefined;
The `window.AudioContext` and `AudioContext` are pointing to the same function. On the browser any variable declared globally will be a property of `window`.

2021-03-14 18:40 UTC, bafolts approved these changes

2021-03-14 23:09 UTC, kberg commented on src/components/SoundManager.ts
> +    const audioCtx = window.AudioContext || (window as any).webkitAudioContext ? new AudioContext() : undefined;
OK, done.

2021-03-15 00:12 UTC, merged