Hidable animated side bar
bafolts/terraforming-mars pull request #3050
Opened 2021-03-28 23:51 UTC by vsrisuknimit

This PR improves on #2969 .

![image](https://user-images.githubusercontent.com/14239220/112772446-dc92b780-8ffe-11eb-9832-86edab1cb4fa.png)

It makes the color brighter but with gradient toward the bottom so the text on the top are not impossible to see. It also rotates the player cube slowly as movement should get attention of users.

It is possible to hide this animation from the Preferences panel.

Example

https://user-images.githubusercontent.com/14239220/112772426-b79e4480-8ffe-11eb-892c-cf326012b8e8.mov

2021-03-29 01:11 UTC, vsrisuknimit commented
@puuj

2021-03-29 23:24 UTC, bafolts requested changes
The rotating of the cube seems great to me. Having a preference only for this animation seems like we are getting far too fine tuned. Every setting we add is another setting a user has to read through to find the setting they may want. Lets include the animation without the setting.

2021-03-29 23:33 UTC, vsrisuknimit commented
@bafolts The rotating cube and color gradient on the side bar will be on by default. The preference panel option is for hiding it. A few users prefer an option to have less distraction including @nwai90 .

2021-03-30 01:19 UTC, vsrisuknimit commented
I agree that we have too many options. We should remove many of the preference panel options (no one should want to hide the game log or player overview table for example). I will do that in another PR.

This is a bit more polarizing and is fine to have option to hide while being on by default.

2021-03-30 18:04 UTC, puuj commented
Sorry, didn't see this. I'm all for a brighter color or gradient. In my personal version I use the original, Mars-red color suggested. I find this very helpful when I'm playing a game while watching TV -- it's super-obvious when it's my turn.

2021-03-31 00:32 UTC, bafolts approved these changes
Approving with trade to remove some other preference in another PR.

2021-03-31 00:37 UTC, merged