Fix promo card on end game page
bafolts/terraforming-mars pull request #3077
Opened 2021-03-30 17:58 UTC by vsrisuknimit

This PR closes #3027 .

<img width="564" alt="Screen Shot 2021-03-30 at 1 49 31 PM" src="https://user-images.githubusercontent.com/14239220/113034035-a882d800-915f-11eb-8e7e-17d244c66b2e.png">

<img width="532" alt="Screen Shot 2021-03-30 at 1 43 34 PM" src="https://user-images.githubusercontent.com/14239220/113034048-ab7dc880-915f-11eb-878f-a1dad3aaff49.png">

![image](https://user-images.githubusercontent.com/14239220/113034011-a3be2400-915f-11eb-98aa-7bb0d1b0b580.png)

It would be better if we rename the promo cards to `Great Dam (promo)` instead of `Great Dam:  promo`, but that will breaks existing games.

2021-03-31 01:13 UTC, bafolts requested changes
I think it is time to move past using type `string` for `detailsCards`.

https://github.com/bafolts/terraforming-mars/blob/main/src/VictoryPointsBreakdown.ts#L14

If we change this type to `Array<[CardName, number]>` we can then avoid needing to further add complexity with parsing data from the string.

Can you change the type of `detailsCards` to `Array<[CardName, number]>` (or some defined interface) and use that instead of trying to work with this string? At that point we can still parse out the colon and the number will be handled by it's type.

2021-03-31 01:30 UTC, vsrisuknimit commented
@bafolts, updated.

![image](https://user-images.githubusercontent.com/14239220/113077393-113d7500-919f-11eb-84e8-0e8ddd550991.png)

2021-04-01 00:33 UTC, bafolts approved these changes

2021-04-01 00:34 UTC, merged

2021-04-01 00:36 UTC, bafolts commented
If a player is playing a game without refreshing the page while this is rolled out they may run into a runtime exception thrown on the game end screen. Refreshing the page will solve this problem for them. I don't think it is worth putting in a fix for this. Be on lookout for this error soon if some unfortunate player playing a game as a server updates runs into this.