Fix typo & show how many cards being bought.
bafolts/terraforming-mars pull request #3079
Opened 2021-03-31 03:26 UTC by kberg

![image](https://user-images.githubusercontent.com/413481/113085770-777dc400-91ae-11eb-8472-f6a967d91556.png)

![image](https://user-images.githubusercontent.com/413481/113085778-7ba9e180-91ae-11eb-8d7f-2911a4aa1e9d.png)

Shows how many cards are being bought or selected. This is particular useful for Business Network:

![image](https://user-images.githubusercontent.com/413481/113086249-4b167780-91af-11eb-9c62-ec1867648ed0.png)
![image](https://user-images.githubusercontent.com/413481/113086274-579ad000-91af-11eb-9308-457f3dcb80a3.png)

2021-03-31 10:18 UTC, vsrisuknimit commented
For Business Network and Inventor Guild, I believe it is better to have two buttons: 'Buy' and 'Discard'. It would be ideal if the color for 'Discard' button is red-shade. Same for 'Skip this action'. But we can do that in another PR.

2021-03-31 11:38 UTC, vsrisuknimit commented on src/deferredActions/DrawCards.ts
> +    const button = max === 0 ? 'Ok' : (options.paying ? 'Buy' : 'Select');
'Oh' might be accurate, ... if you cannot afford any card.

2021-03-31 13:49 UTC, kberg commented on src/deferredActions/DrawCards.ts
> +    const button = max === 0 ? 'Ok' : (options.paying ? 'Buy' : 'Select');
I just don't think that's the case because there's nothing that makes sense. In fact one of my friends saw that and thought "Uh, 'Oh'?"

2021-03-31 13:53 UTC, vsrisuknimit commented on src/deferredActions/DrawCards.ts
> +    const button = max === 0 ? 'Ok' : (options.paying ? 'Buy' : 'Select');
Perhaps change it to 'Skip this action' then.

2021-03-31 16:43 UTC, kberg commented on src/deferredActions/DrawCards.ts
> +    const button = max === 0 ? 'Ok' : (options.paying ? 'Buy' : 'Select');
I'm actually pretty confident this was a mistaken "OK." and I think it's an appropriate bit of text. Do you feel strongly?

2021-03-31 17:40 UTC, vsrisuknimit commented on src/deferredActions/DrawCards.ts
> +    const button = max === 0 ? 'Ok' : (options.paying ? 'Buy' : 'Select');
Not at all. I think you are right.

2021-04-01 00:51 UTC, bafolts requested changes

2021-04-01 00:51 UTC, bafolts commented on src/components/SelectCard.ts
> +      return this.playerinput.buttonLabel + ' ' + this.$data.cards.length;
This should use the `cardsSelected` function instead of `this.$data.cards.length`. I think when vue-js uses the radio button that `this.$data.cards` will be the name of the card and not an array. This may be compiling because `string | Array` would have a `length` property. When `playerinput.minCardsToSelect === 1 && playerinput.maxCardsToSelect === 1` it probably isn't even worthwhile to display the number of cards selected as it will always be one. I think we should use `cardsSelected` here and not display when one card has to be selected.

2021-04-01 03:01 UTC, kberg commented on src/components/SelectCard.ts
> +      return this.playerinput.buttonLabel + ' ' + this.$data.cards.length;
> This should use the `cardsSelected` function instead of `this.$data.cards.length`. I think when vue-js uses the radio button that `this.$data.cards` will be the name of the card and not an array. This may be compiling because `string | Array` would have a `length` property.

That may be, but then why is it actually functioning correctly? Look at the screenshots.

> When `playerinput.minCardsToSelect === 1 && playerinput.maxCardsToSelect === 1` it probably isn't even worthwhile to display the number of cards selected as it will always be one. I think we should use `cardsSelected` here and not display the count when one card has to be selected.

It is. My friend lost a game yesterday because they didn't realize they hadn't selected the one Business Network card.

2021-04-02 00:57 UTC, bafolts commented on src/components/SelectCard.ts
> +      return this.playerinput.buttonLabel + ' ' + this.$data.cards.length;
The only example I can find is `Invention Contest` where `minCardsToSelect === 1` and `maxCardsToSelect === 1`. In this situation with `this.$data.cards.length` we end up displaying:

![image](https://user-images.githubusercontent.com/2707843/113368446-0825e280-931c-11eb-8952-0d1cffa9e1e8.png)

Using `this.cardsSelected()` resolves the issue.

2021-04-02 02:35 UTC, kberg commented on src/components/SelectCard.ts
> +      return this.playerinput.buttonLabel + ' ' + this.$data.cards.length;
Thanks. I fixed this, and tested it locally with the same card.

2021-04-02 21:44 UTC, bafolts approved these changes

2021-04-02 21:44 UTC, merged