calculate award properly
bafolts/terraforming-mars pull request #3101
Opened 2021-04-05 13:04 UTC by vsrisuknimit

This PR can close #3100.

The award that counts resources should getScore that accounts for the final production as if the game is to end now.

![image](https://user-images.githubusercontent.com/14239220/113576563-c92eb000-95ed-11eb-8aa1-1d7db23490de.png)

2021-04-05 13:55 UTC, kberg commented
This feature seems useful for experienced players, but not for beginners. It also demonstrates a behavior that makes awards different from each other without a visual cue. If this showed both values, or gave very clear visual cue that these are special and different, I would approve such a change.

2021-04-05 14:27 UTC, vsrisuknimit commented
@kberg All awards are different from each other. Some count tags, some count tiles. These three awards are the only that count resources. As long as all three behave the same way that should be no problem.

- Showing two numbers are confusing and not compact.
- The current implementation on the other hand should confuse beginner players greatly. "The app says I am winning Thermalist. Why in the world did I lose it at the end of the game? Oh the app did not take final production into account." The current number are next to useless (for these three awards) and make the awards swing and live-vp calculation swing greatly for no reason.
- We can make it different colors, but there is no reason to do that. As I mentioned, all awards are different.

2021-04-05 23:42 UTC, bafolts commented
I think the number may be beneficial to beginners as well as experienced players. As a beginner it may help to show that production matters. A beginner who doesn't know that production is going to be added once mars is terraformed could come to learn they did not end up with the award.

2021-04-06 00:54 UTC, bafolts requested changes

2021-04-06 00:54 UTC, bafolts commented on src/awards/Industrialist.ts
> +        return player.steel + player.energy;
There is code duplication among these three awards. Lets create a function in `src/awards/Awards.ts` for this logic. Can you add an `Awards.pastLastProductionPhase`?

```
function pastLastProductionPhase(game: Game) {
  return game.gameIsOver() && (game.phase === Phase.END || game.phase === Phase.PRODUCTION);
}
```

2021-04-06 01:02 UTC, kberg commented
> I think the number may be beneficial to beginners as well as experienced players. As a beginner it may help to show that production matters. A beginner who doesn't know that production is going to be added once mars is terraformed could come to learn they did not end up with the award.

It _could_ be if it was clear what the number meant. But someone has to unwind it from first principles by identifying the three sources (in the worst case.) If this included an easy way to clarify what the value comes from, I'd be more comfortable with the change.

2021-04-06 01:26 UTC, vsrisuknimit commented on src/awards/Industrialist.ts
> +        return player.steel + player.energy;
Done. I moved it to Game instead.

2021-04-07 00:15 UTC, bafolts commented on src/awards/Industrialist.ts
> +      if (player.game.phase === Phase.END || player.game.isDoneWithFinalProduction()) {
Sorry if my previous comment was confusing but I would include `player.game.phase === Phase.END` in the `isDoneWithFinalProduction` function. Whenever `player.game.phase === Phase.END` was are also done with the final production. This will make the function correct and cut down on the remaining duplication.

2021-04-07 00:17 UTC, bafolts commented
> > I think the number may be beneficial to beginners as well as experienced players. As a beginner it may help to show that production matters. A beginner who doesn't know that production is going to be added once mars is terraformed could come to learn they did not end up with the award.
> 
> It _could_ be if it was clear what the number meant. But someone has to unwind it from first principles by identifying the three sources (in the worst case.) If this included an easy way to clarify what the value comes from, I'd be more comfortable with the change.

Including how these values are calculated should help even with what we are doing today. Even today I don't think we show how these values are calculated.

2021-04-07 00:57 UTC, vsrisuknimit commented on src/awards/Industrialist.ts
> +      if (player.game.phase === Phase.END || player.game.isDoneWithFinalProduction()) {
Done

2021-04-07 01:01 UTC, bafolts approved these changes

2021-04-07 01:02 UTC, vsrisuknimit commented
> It _could_ be if it was clear what the number meant. But someone has to unwind it from first principles by identifying the three sources (in the worst case.) If this included an easy way to clarify what the value comes from, I'd be more comfortable with the change.

Added `(after final production round)` in the award explanation.

2021-04-08 00:23 UTC, merged