Correct amount decreased
bafolts/terraforming-mars pull request #3106
Opened 2021-04-06 19:05 UTC by sauloachkar

Some cards remove more resources than players have in board. Log was showing the full number, instead of the correct number removed.

2021-04-07 00:51 UTC, bafolts commented on src/deferredActions/CorrosiveRainDeferredAction.ts
> +    const amountLost = Math.min(10, this.player.megaCredits);
This `setResource` function _should_ be protecting against this.

https://github.com/bafolts/terraforming-mars/blob/main/src/Player.ts#L310

2021-04-07 00:53 UTC, vsrisuknimit commented on src/deferredActions/CorrosiveRainDeferredAction.ts
> +    const amountLost = Math.min(10, this.player.megaCredits);
@bafolts he is talking accurate logging.

2021-04-07 00:55 UTC, bafolts commented
Can you fix this from within the `Player.setResource` function? This will avoid having to fix it every place we call `setResource`.

https://github.com/bafolts/terraforming-mars/blob/main/src/Player.ts#L329

2021-04-07 02:08 UTC, sauloachkar commented
> Can you fix this from within the `Player.setResource` function? This will avoid having to fix it every place we call `setResource`.
> 
> https://github.com/bafolts/terraforming-mars/blob/main/src/Player.ts#L329

I guess that would be a better fix indeed.

2021-04-08 23:06 UTC, sauloachkar commented
Not quite happy with the code, but it works.
Unexpectedly found a bug LawSuit since it would allow it to be played even if no resources were removed.

2021-04-09 01:09 UTC, vsrisuknimit commented
```ts
let availableAmountToRemove = 0;
    switch(resource) {
      case Resources.MEGACREDITS:
        availableAmountToRemove = this.megaCredits;
        this.megaCredits = Math.max(0, this.megaCredits + amount);
        break;
      case Resources.STEEL:
        availableAmountToRemove = this.steel;
        this.steel = Math.max(0, this.steel + amount);
        break;
      case Resources.TITANIUM:
        availableAmountToRemove = this.titanium;
        this.steel = Math.max(0, this.steel + amount);
        break;
//... continued for other three
    }
```

`.number(amount >= 0 ? amount : Math.min(availableAmountToRemove, amount))`

Would this be cleaner? No need to change any other number for each and every function.

2021-04-09 01:10 UTC, vsrisuknimit commented
What is the bug about Law Suits? The test allows it to go negative. I don't see a bug on the card.

2021-04-09 01:34 UTC, bafolts commented
> ```ts
> let availableAmountToRemove = 0;
>     switch(resource) {
>       case Resources.MEGACREDITS:
>         availableAmountToRemove = this.megaCredits;
>         this.megaCredits = Math.max(0, this.megaCredits + amount);
>         break;
>       case Resources.STEEL:
>         availableAmountToRemove = this.steel;
>         this.steel = Math.max(0, this.steel + amount);
>         break;
>       case Resources.TITANIUM:
>         availableAmountToRemove = this.titanium;
>         this.steel = Math.max(0, this.steel + amount);
>         break;
> //... continued for other three
>     }
> ```
> 
> ```ts
> .number(amount >= 0 ? amount : Math.min(availableAmountToRemove, amount))
> ```
> 
> Would this be cleaner? No need to change any other number for each and every function.

I think this approach would be cleaner. I was trying to follow through the current approach before seeing this comment. Was about to suggest this as well.

2021-04-09 01:45 UTC, sauloachkar commented
> What is the bug about Law Suits? The test allows it to go negative. I don't see a bug on the card.

```
    if (game !== undefined && fromPlayer !== undefined && **amount** < 0) {
    if (game !== undefined && fromPlayer !== undefined && **variation** < 0) {
      if (fromPlayer !== this && this.removingPlayers.includes(fromPlayer.id) === false) {
        this.removingPlayers.push(fromPlayer.id);
      }
```
This is where LawSuit could fail. Sometimes amount could be negative, but variation wasn't. The test was failing because player1 had no megacredit. I setted to 1, so it'd pass.

2021-04-10 11:55 UTC, vsrisuknimit commented
> > What is the bug about Law Suits? The test allows it to go negative. I don't see a bug on the card.
> 
> ```
>     if (game !== undefined && fromPlayer !== undefined && **amount** < 0) {
>     if (game !== undefined && fromPlayer !== undefined && **variation** < 0) {
>       if (fromPlayer !== this && this.removingPlayers.includes(fromPlayer.id) === false) {
>         this.removingPlayers.push(fromPlayer.id);
>       }
> ```
> 
> This is where LawSuit could fail. Sometimes amount could be negative, but variation wasn't. The test was failing because player1 had no megacredit. I setted to 1, so it'd pass.

Law Suits does not fail. It is the new code utilizing variation that might cause an error. This should not happen if we go with the method I suggested above.

2021-04-24 23:55 UTC, kberg commented
@sauloachkar what's your plan for this PR?

2021-04-26 20:14 UTC, sauloachkar commented
> @sauloachkar what's your plan for this PR?

Sorry about the delay. I hope it's alright now.

2021-04-28 00:13 UTC, bafolts commented on src/Player.ts
> +            .number(amount >= 0 ? amount : Math.min(availableAmountToRemove, amount))
If a player has 5 megacredits and `amount` were -10 this would log that the amount was decreased by `-10`. When `amount` is less than `0` I believe this should be `Math.min(availableAmountToRemove, Math.abs(amount))`. Then this would log that megacredits were decreased by `5` and not `-10`.

2021-04-28 00:13 UTC, bafolts requested changes
This is still not quite right. When `amount` is negative need to reconsider what is logged.

2021-04-28 00:28 UTC, kberg commented
> This is still not quite right. When `amount` is negative need to reconsider what is logged.

I could swear I wrote a response that suggested a version of this that was shorter and I think worked out. It also had a spiel about adding tests for good measure.

2021-04-28 00:33 UTC, kberg commented
> > This is still not quite right. When `amount` is negative need to reconsider what is logged.
> 
> I could swear I wrote a response that suggested a version of this that was shorter and I think worked out. It also had a spiel about adding tests for good measure.

Here, I suggested something close to this:

```
  public addResource(resource: Resources, amount: number, options? : { log: boolean, from? : Player | GlobalEventName}) {
    const delta = Math.max(0, this.getResource(resource) + amount);

    if (resource === Resources.MEGACREDITS) this.megaCredits = += delta;
    if (resource === Resources.STEEL) this.steel = += delta;

    if (resource === Resources.TITANIUM) this.titanium = += delta;
    if (resource === Resources.PLANTS) this.plants = += delta;
    if (resource === Resources.ENERGY) this.energy = += delta;
    if (resource === Resources.HEAT) this.heat = += delta;

    if (options?.log === true) {
      const modifier = delta > 0 ? 'increased' : 'decreased';

      if (options?.from !== undefined && options.from instanceof Player && delta < 0) {
        const from: Player = options.from;
        if (from !== this && this.removingPlayers.includes(from.id) === false) {
          this.removingPlayers.push(from.id);
        }

        // Crash site cleanup hook
        if (from !== this && resource === Resources.PLANTS && delta < 0) {
          this.game.someoneHasRemovedOtherPlayersPlants = true;
        }

        this.game.log('${0}\'s ${1} amount ${2} by ${3} by ${4}', (b) =>
          b.player(this)
            .string(resource)
            .string(modifier)
            .number(Math.abs(delta))
            .player(from));
      }

      // Global event logging
      if (options?.from !== undefined && ! (options.from instanceof Player) && amount !== 0) {
        this.game.log('${0}\'s ${1} amount ${2} by ${3} by Global Event', (b) =>
          b.player(this)
            .string(resource)
            .string(modifier)
            .number(Math.abs(delta);
      }

      // Mons Insurance hook
      if (amount < 0 && options?.from !== undefined && options.from !== this) {
        this.resolveMonsInsurance();
      }
    }
  }
```

2021-04-28 04:53 UTC, kberg commented on src/Player.ts
> +    const delta = Math.max(0, this.getResource(resource) + amount) - this.getResource(resource);
I will be really surprised if the - this.getResource(resource) works.

2021-04-28 05:07 UTC, sauloachkar commented on src/Player.ts
> +            .number(amount >= 0 ? amount : Math.min(availableAmountToRemove, amount))
you're right. changed the whole thing again.

2021-04-28 05:08 UTC, sauloachkar commented on src/Player.ts
> +    const delta = Math.max(0, this.getResource(resource) + amount) - this.getResource(resource);
hehe. that was kind of actually my original idea, but getResource() could really made the changes easiear and cleaner

2021-04-28 05:13 UTC, sauloachkar commented
made some tests with actual gaming using Hired Raiders, it seems to be working fine now.

2021-04-29 00:53 UTC, bafolts commented on src/Player.ts
> +    const delta = Math.max(0, this.getResource(resource) + amount) - this.getResource(resource);
This looks right to me now. Without unit tests can someone double check this?

When amount is 0 this will end up with `delta` as 0.
When amount is positive this will end up with `delta` as the positive value.
When amount is negative and sum is greater than 0 this will end up with `delta` as the negative amount.
When amount is negative and sum is less than 0 this will end up with `delta` as the amount we were able to remove.

@sauloachkar could you add a unit test for these 4 situations?

Can you add this unit test in `tests/Player.spec.ts`?

```
it('adds resources', () => {
  const player = TestPlayers.BLUE.newPlayer();
  player.megaCredits = 10;
  // adds any positive amount
  player.addResource(Resources.MEGACREDITS, 12);
  expect(player.megaCredits).eq(22);
  // removes more than we have
  player.addResource(Resources.MEGACREDITS, -23);
  expect(player.megaCredits).eq(0);
  // adds any positive amount
  player.addResource(Resources.MEGACREDITS, 5);
  expect(player.megaCredits).eq(5);
  // removes less than we have
  player.addResource(Resources.MEGACREDITS, -4);
  expect(player.megaCredits).eq(1);
  // makes no change
  player.addResource(Resources.MEGACREDITS, 0);
  expect(player.megaCredits).eq(1);
});
```

2021-04-29 03:57 UTC, sauloachkar commented on src/Player.ts
> +    const delta = Math.max(0, this.getResource(resource) + amount) - this.getResource(resource);
done

2021-04-29 05:13 UTC, kberg commented on src/Player.ts
> +    const delta = Math.max(0, this.getResource(resource) + amount) - this.getResource(resource);
> hehe. that was kind of actually my original idea, but getResource() could really made the changes easiear and cleaner

You know, when I looked at your code and thought "this could be simpler" I hadn't thought of getResource at first, and then it clicked. So, no surprise really. Anyway, we're reaching a good end, at least.

2021-04-29 05:37 UTC, kberg commented on src/Player.ts
> +    const delta = Math.max(0, this.getResource(resource) + amount) - this.getResource(resource);
I see now that the expression above _is_ correct. Sorry about that. But it's also a little confusing on first glance. If you agree, consider replacing it with this:

`const delta = (amount >= 0) ? amount : Math.max(amount, -this.getResource(...)`

I just confirmed that Math.max of two negative values does what I expect:

```
Math.max(-1, -4)
-1
```
so it's possibly correct. Or don't bother, and I'll do it later.

Either way, this looks good.

2021-04-29 16:39 UTC, sauloachkar commented on src/Player.ts
> +    const delta = Math.max(0, this.getResource(resource) + amount) - this.getResource(resource);
that's more elegant, i agree. it's done.

2021-04-29 23:03 UTC, kberg commented
![image](https://user-images.githubusercontent.com/413481/116628581-6b0b9900-a91d-11eb-8a70-b84230898aa0.png)
I think you're good to go once you resolve this.

2021-05-01 21:00 UTC, kberg approved these changes

2021-05-01 21:01 UTC, kberg commented
Thank you, @sauloachkar ! That was a lot of commits and back and forth, but thank  you. Just waiting on @bafolts to approve.

2021-05-01 23:06 UTC, sauloachkar commented
> Thank you, @sauloachkar ! That was a lot of commits and back and forth, but thank you. Just waiting on @bafolts to approve.

Thank you guys for the patience, this is my first PR. Glad to help, as I love the game and have been playing this version a lot latelly.

2021-05-05 00:17 UTC, bafolts approved these changes
Sorry for the delay! Thanks for adding the unit test.

2021-05-05 00:18 UTC, merged