Fix recruitment
bafolts/terraforming-mars pull request #3115
Opened 2021-04-09 00:33 UTC by vsrisuknimit

This PR can close #3114 .

Switching Mars First
<img width="567" alt="Screen Shot 2021-04-08 at 8 27 12 PM" src="https://user-images.githubusercontent.com/14239220/114112040-7d0f9400-98a9-11eb-80f4-8c2c4f5882d9.png">

Mars First still dominant
<img width="559" alt="Screen Shot 2021-04-08 at 8 27 22 PM" src="https://user-images.githubusercontent.com/14239220/114112048-813bb180-98a9-11eb-9afa-500f2069ffc1.png">

Test with Banned Delegate

<img width="621" alt="Screen Shot 2021-04-08 at 8 31 10 PM" src="https://user-images.githubusercontent.com/14239220/114112077-93b5eb00-98a9-11eb-85ba-f380785ddc4c.png">
<img width="419" alt="Screen Shot 2021-04-08 at 8 31 03 PM" src="https://user-images.githubusercontent.com/14239220/114112083-96184500-98a9-11eb-8fea-420a8cd6dec5.png">
<img width="618" alt="Screen Shot 2021-04-08 at 8 31 21 PM" src="https://user-images.githubusercontent.com/14239220/114112090-987a9f00-98a9-11eb-848f-0a3c6d2319bb.png">

In this case, dominance check happens properly.

2021-04-09 01:29 UTC, bafolts requested changes

2021-04-09 01:29 UTC, bafolts commented on src/turmoil/Turmoil.ts
> +    public removeDelegateFromParty(playerId: PlayerId | NeutralPlayer, partyName: PartyName, game: Game, dominanceCheck: boolean = true): void {
Instead of adding the `dominanceCheck` argument can you call to `checkDominantParty` after calling `removeDelegateFromParty` when the argument would be `true`? The `checkDominantParty` function will have to be updated to work with `partyName`. I think this will help us in the long run.

2021-04-09 01:36 UTC, vsrisuknimit commented on src/turmoil/Turmoil.ts
> +    public removeDelegateFromParty(playerId: PlayerId | NeutralPlayer, partyName: PartyName, game: Game, dominanceCheck: boolean = true): void {
@bafolts I don't follow your suggestion. Dominance check is still needed for Banned Delegate where dominant needed to be check immediately. We should not remove it from there.

Currently removeDelegateFromParty is only called by two places, Banned Delegate and Recruitment (under SendDelegateToArea).

2021-04-09 01:38 UTC, vsrisuknimit commented on src/turmoil/Turmoil.ts
> +    public removeDelegateFromParty(playerId: PlayerId | NeutralPlayer, partyName: PartyName, game: Game, dominanceCheck: boolean = true): void {
Mainly, I find it weird that sendDelegateToParty auto-adjust dominance but not removeDelegateFromParty.

2021-04-09 01:55 UTC, bafolts commented on src/turmoil/Turmoil.ts
> +    public removeDelegateFromParty(playerId: PlayerId | NeutralPlayer, partyName: PartyName, game: Game, dominanceCheck: boolean = true): void {
The call to `checkDominantParty` would be removed from the `removeDelegateFromParty` function. In `Banned Delegate` we would then call to:

```
removeDelegateFromParty(playerId, partyName, game);
checkDominantParty(partyName);
```

This will avoid having to introduce the boolean argument only to control what the function calls internally. Usually a function doing more than one thing eventually will lead to difficult to change functions. By using the boolean argument we know the function is doing more than one thing and are trying to have the function only do one thing under certain circumstances.

These links may better explain what I am thinking:
https://www.informit.com/articles/article.aspx?p=1392524
https://martinfowler.com/bliki/FlagArgument.html
https://medium.com/@amlcurran/clean-code-the-curse-of-a-boolean-parameter-c237a830b7a3

2021-04-09 02:01 UTC, vsrisuknimit commented on src/turmoil/Turmoil.ts
> +    public removeDelegateFromParty(playerId: PlayerId | NeutralPlayer, partyName: PartyName, game: Game, dominanceCheck: boolean = true): void {
@bafolts I understand but then I should also separate checkDominantParty from sendDelegateToParty() function as well, since the two functions are parallel. They should behave the same way. 

`sendDelegateToParty()` is called in many more places. If you insist, I will change but then I will have to add `checkDominantParty()` to all these calls below as well.

![image](https://user-images.githubusercontent.com/14239220/114118008-ebf2ea00-98b5-11eb-9b91-2baf94fe9048.png)

2021-04-11 01:44 UTC, vsrisuknimit commented on src/turmoil/Turmoil.ts
> +    public removeDelegateFromParty(playerId: PlayerId | NeutralPlayer, partyName: PartyName, game: Game, dominanceCheck: boolean = true): void {
An alternative is to write a new function specifically to replace delegate. It will copy most of the code from removeDelegateFromParty() though. Not sure about code duplication.

But this way send/removeDelegate still work as we should expect it to: that is to check dominance immediately afterward ... if you really don't want a flag argument.

```ts
    // Use to replace a delegate from a specific party with another delegate with NO DOMINANCE CHANGE
    public replaceDelegateFromParty(
      outgoingPlayerId: PlayerId | NeutralPlayer,
      incomingPlayerId: PlayerId | NeutralPlayer,
      source: 'lobby' | 'reserve' = 'lobby',
      partyName: PartyName,
      game: Game): void {
      const party = this.getPartyByName(partyName);
      if (party) {
        this.delegateReserve.push(outgoingPlayerId);
        party.removeDelegate(outgoingPlayerId, game);
        this.sendDelegateToParty(incomingPlayerId, partyName, game, source);
      } else {
        throw 'Party not found';
      }
    }
```

2021-04-12 10:19 UTC, vsrisuknimit commented
@bafolts I created a function just for replacement.

2021-04-12 14:51 UTC, bafolts approved these changes

2021-04-12 23:33 UTC, merged