Move the "Mars is Terraformed!" announcement to PlayerHome, and get the result from the server, not the client.
bafolts/terraforming-mars pull request #3239
Opened 2021-05-01 16:56 UTC by kberg

2021-05-01 16:56 UTC, kberg commented
I tested this manually.

2021-05-01 17:44 UTC, kberg commented
Fixes #3199

2021-05-04 00:58 UTC, bafolts commented on src/components/PlayerHome.ts
> +    if (this.player.game.isTerraformed && TerraformedAlertDialog.shouldAlert && PreferencesManager.load('show_alerts') === '1') {
When this model change rolls out clients will have the client side code checking model properties which exist. This will allow older clients to catch up.

:+1:

2021-05-04 01:01 UTC, bafolts commented on src/components/Board.ts
> -    shouldNotify: {
This should also remove the `shouldNotify` attribute from the `GameEnd` component.

https://github.com/bafolts/terraforming-mars/blob/main/src/components/GameEnd.ts#L191

2021-05-04 01:16 UTC, bafolts requested changes
I can't be certain but with the `shouldNotify` property being removed from `Board` we may end up showing the `alert` twice with this change. We were providing `shouldNotify` with `false` from the `GameEnd` component.

The only requested change I have is to remove the `shouldNotify` attribute being set on `Board` from the `GameEnd` component. Since the property was removed we should remove it from every place it was used.

2021-05-04 04:01 UTC, kberg commented on src/components/Board.ts
> -    shouldNotify: {
Good catch. Why didn't the compiler catch this?

2021-05-04 04:05 UTC, kberg commented
> I can't be certain but with the `shouldNotify` property being removed from `Board` we may end up showing the `alert` twice with this change. We were providing `shouldNotify` with `false` from the `GameEnd` component.
> 
> The only requested change I have is to remove the `shouldNotify` attribute being set on `Board` from the `GameEnd` component. Since the property was removed we should remove it from every place it was used.

I think it might happen if a player refreshes the page, now that you mention it. But then again, the same thing would have happened with the old code, wouldn't it?

2021-05-04 14:24 UTC, bafolts commented
With the old code if you were on the `GameEnd` screen where we provide the `shouldNotify` property a value of `false` I don't think the alert would have been seen. We used to show the alert and then transition to the `GameEnd` screen.

2021-05-04 20:27 UTC, kberg commented
The alert isn't something shown just _before_ the game end screen, since Mars can be terraformed long before the generation ends.

Unless i'm missing something.

Perhaps restate plainly: what do you want me to change or what do you want me to confirm before approving this change?

2021-05-04 23:25 UTC, bafolts commented
The only requested change I have is to remove the shouldNotify attribute being set on Board from the GameEnd component. Since the property was removed we should remove it from every place it was used.

2021-05-04 23:34 UTC, bafolts commented on src/components/Board.ts
> -    shouldNotify: {
This is one of my least favorite answers but I don't know. The vue template compiler must not consider properties being provided to an element that aren't defined as an error.

2021-05-06 02:52 UTC, kberg commented
> The only requested change I have is to remove the shouldNotify attribute being set on Board from the GameEnd component. Since the property was removed we should remove it from every place it was used.

Oh, of course. That makes sense now. Thanks.

2021-05-07 00:29 UTC, bafolts approved these changes

2021-05-07 15:13 UTC, merged