Brazilian portuguese translations
bafolts/terraforming-mars pull request #3253
Opened 2021-05-04 16:52 UTC by sauloachkar

Some more fixes and new lines

2021-05-05 00:05 UTC, bafolts commented on src/locales/br/base_cards.json
> +    "Action: Spend 1 plant or 1 steel to gain 7M€.": "Ação: gaste 1 planta ou 1 de aço para ganhar 7 M€.",
The english key has a space between `7 M€`. That has to be included here for this translation to be mapped.

2021-05-05 00:08 UTC, bafolts commented on src/locales/br/colonies_corp.json
> +   "You start with 50M€. Increase your M€ production 5 steps. Gain 5 titanium.": "Você começa com 50 M€. Aumente sua produção de M€ em 5 níveis. Ganhe 5 de titânio.",
This space between `50` and `M€` needs to remain in place for this translation to be mapped.

2021-05-05 00:09 UTC, bafolts commented on src/locales/br/log_messages.json
> +    "Spend 1 plant to gain 7 mega credit": "Gastar 1 planta para ganhar 7 megacréditos",
This key needs to remain `Spend 1 plant to gain 7 M€`. There was a recent merge to the `main` branch which made this key change.

2021-05-05 00:10 UTC, bafolts commented on src/locales/br/log_messages.json
> +    "Spend 1 steel to gain 7 mega credit": "Gastar 1 aço para ganhar 7 megacréditos",
This key needs to remain `Spend 1 steel to gain 7 M€`. There was a recent merge to the `main` branch which made this key change.

2021-05-05 00:12 UTC, bafolts requested changes
This changes some of the english keys which came in through recent commits to the `main` branch. I would rebase this branch to the `main` branch. The english keys can't be modified or the translation will not map.

2021-05-05 17:58 UTC, sauloachkar commented
> This changes some of the english keys which came in through recent commits to the `main` branch. I would rebase this branch to the `main` branch. The english keys can't be modified or the translation will not map.

Sorry about that. Did a find and replace on all the [number+M€] and added a space between on all the brazilian portuguese files.

2021-05-06 00:11 UTC, bafolts approved these changes

2021-05-06 00:11 UTC, merged