SFC
bafolts/terraforming-mars pull request #3351
Opened 2021-06-08 21:18 UTC by Argeento

Rewrite vue `.ts` components to [Single File Components](https://vuejs.org/v2/guide/single-file-components.html)

2021-06-08 21:40 UTC, Argeento commented
In every file I run this steps:
 1. Determine if the file is vue component (by searching `Vue.component` string), if so:
 2. Find component name by searching export line `/export const (.*?) = Vue./`
 3. Change `export` to `default export Vue.extends`
 4. Add `name` key to component settings
 5. Search for template string, and if found, move it to the `<template> tag to the top of the document
 6. Move rest of the code to the `<script>` tag
 7. Add empty `<style>` tag to the bottom
 
Moreover, SFC is requiring to have only one default export, so the script also fixed all the imports in all components. You don't have to check them. If project runs, then everything with import/exports is OK.

Every change in templates I will comment in this PR

2021-06-08 21:52 UTC, Argeento commented on src/components/OtherPlayer.vue
> +const hidePlayerData = (root: typeof mainAppSettings.methods, playerIndex: number) => {
Here is the manual change. This function was imported from another component. SFC can only have one export, so I added it here

2021-06-08 21:52 UTC, Argeento commented on src/components/SelectCard.vue
> +interface OwnerModel {
Next manual change. I had to implement this interface once again for this component

2021-06-08 21:52 UTC, Argeento commented on src/components/WaitingFor.vue
> +    console.log('render function in WaitingFor is fired!');
Oh wait.. I left some debug code...

2021-06-08 21:57 UTC, Argeento commented
My recommendation: Please DO NOT CHECK THIS BY HAND. It is waste of time. Run the tests, play some games

2021-06-08 22:06 UTC, Argeento commented on src/components/App.ts
> +            // @ts-ignore
In App.ts are some types error. For now I only ignore them, but the code itself didn't change

2021-06-08 22:36 UTC, Argeento commented
Here is [the script](https://gist.github.com/Argeento/1f54e856d91c0f56023ca93bcae6d0e6) that rewrites components

2021-06-09 00:05 UTC, bafolts commented
> My recommendation: Please DO NOT CHECK THIS BY HAND. It is waste of time. Run the tests, play some games

I am going to write my own script to check the moving of all the templates. Prior to merging will run the script.

2021-06-09 00:05 UTC, kberg requested changes
As I had feared, this includes moving a lot of contents around, making it hard to verify if any accidental changes made it in. This is why I asked to start with one component.

2021-06-09 00:12 UTC, kberg commented
> My recommendation: Please DO NOT CHECK THIS BY HAND. It is waste of time. Run the tests, play some games

Thanks for your recommendation, but I think I laid ou t my reasons for manual verification on Discord. Add to that that we do not have enough tests to not manually verify.

2021-06-09 00:13 UTC, bafolts commented
> As I had feared, this includes moving a lot of contents around, making it hard to verify if any accidental changes made it in. This is why I asked to start with one component.

I had mentioned this in #3343 as well. I agree that starting with one component will help with this transition and spot any issues early before every component is converted.

2021-06-09 00:34 UTC, bafolts commented on package.json
> +    "test": "rm -rf build/tests/components/ && mocha --file build/tests/utils/Vue.js --recursive build/tests",
This separation of tests make sense. I vaguely remember some issue with the `exclude` option with `mocha`. Did the `exclude` option not work? Most of our unit tests are for the back end game server classes and not the front end components.

2021-06-09 00:37 UTC, bafolts commented on src/components/App.ts
> +            // @ts-ignore
I am curious what these type errors are. Ignoring these errors could mean in the future we end up ignoring a real error. Or we are ignoring a real error now.

2021-06-09 00:48 UTC, bafolts commented on package.json
> +    "check-templates": "vtc --workspace . --srcDir ./src/components/ --onlyTemplate"
This `check-templates` command is great. We should turn this on and then can introduce one template at a time. This would allow us to address the issues as we went. Looking quickly at the list most of the issues seem like things we forgot to remove during migrations.

One example:

```
Error in file:///home/algorithm99/Projects/terraforming-mars/src/components/GameSetupDetail.vue
62:37 Property 'undoOption' does not exist on type 'GameOptionsModel'.
  60 |               <div v-if="gameOptions.showTimers" class="game-config timer" v-i18n>timer</div>
  61 |               <div v-if="gameOptions.showOtherPlayersVP" class="game-config realtime-vp" v-i18n>real-time vp</div>
> 62 |               <div v-if="gameOptions.undoOption" class="game-config undo" v-i18n>undo</div>
     |                                      ^^^^^^^^^^
  63 |             </li>
```

2021-06-09 01:07 UTC, bafolts commented on src/components/App.ts
> +import PlayerModel from '../models/PlayerModel.vue';
The reason for the `ts-ignore` and the compile errors are due to importing `PlayerMode.vue`. This should be imported as:

```
import {PlayerModel} from '../models/PlayerModel';
```

This will avoid the need for `ts-ignore`.

2021-06-09 09:11 UTC, Argeento commented on src/components/App.ts
> +import PlayerModel from '../models/PlayerModel.vue';
Fixed

2021-06-10 01:49 UTC, bafolts commented
I am trying to put together a solution that will allow us to pull in a handful of these templates at a time. I don't think this is straight forward since once we use the `.vue` extension we need webpack compiling some of our files and not `tsconfig`.

2021-06-10 15:52 UTC, bafolts commented on tests/LogHelper.spec.ts
> -import {Algae} from '../../src/cards/base/Algae';
This change can go in separate. This seems to pull in a reference to the database which prevents the front end tests from running.

2021-06-11 01:51 UTC, bafolts commented on package.json
> +    "vue-type-check": "^1.1.0",
The `vue-type-check` has a peer dependency of typescript 3. When I try to install without the package-lock file I get an error.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: terraforming-mars@1.0.0
npm ERR! Found: typescript@4.3.2
npm ERR! node_modules/typescript
npm ERR!   typescript@"^4.1.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"^3.9.6" from vue-type-check@1.1.0
npm ERR! node_modules/vue-type-check
npm ERR!   dev vue-type-check@"^1.1.0" from the root project
```

How did you avoid this error?

2021-07-10 17:38 UTC, kberg commented
This can be closed, right? Is there anything else in this which we need?

2021-07-14 23:54 UTC, bafolts commented
This work is slowly getting done a few components at a time. A lot of the major concepts have already been merged.

2021-07-14 23:54 UTC, closed without merging