single file component: Button
bafolts/terraforming-mars pull request #3393
Opened 2021-06-30 01:44 UTC by bafolts

This change involved finding places where `<Button` was being used in templates. I grepped for `<Button` and found a few components where I added `Button` to their `components`. The `vti` tool is also starting to spot issues with our templates. I had to make `title` and `align` optional for the `Button` props.

2021-06-30 02:33 UTC, Argeento requested changes

2021-06-30 02:33 UTC, Argeento commented on src/components/common/Button.vue
> +      required: false,
Optional props must have a default value.
Current [eslint config](https://github.com/bafolts/terraforming-mars/blob/main/.eslintrc.js#L8) should [throw the error here](https://eslint.vuejs.org/rules/require-default-prop.html).

2021-06-30 02:33 UTC, Argeento commented on src/components/common/Button.vue
> +      required: false,
Another optional props without a default value

2021-06-30 15:00 UTC, bafolts commented on src/components/common/Button.vue
> +      required: false,
We are using `plugin:vue/essential` and not `plugin:vue/recommended`. When I put in `plugin:vue/recommended` I see 2000+ warnings including this. I will put a default here and we will need to enable `plugin:vue/recommended` as it seems to be catching countless warnings similar to this.

2021-06-30 15:19 UTC, Argeento commented on src/components/common/Button.vue
> +      required: false,
Oh. Yea, You are right, sorry

2021-06-30 15:19 UTC, Argeento approved these changes

2021-07-01 04:30 UTC, kberg approved these changes
Modulo @Argeento's comment.

2021-07-01 14:36 UTC, bafolts commented on src/components/common/Button.vue
> +      required: false,
With the 2000+ warnings that showed up once I changed to _recommended_ from _essential_ let me try turning on one rule at a time and fixing those warnings. I wish we had used _recommended_ from the start. Pretty sure we only have _essential_ because that must be what was in some vue setup I copy and pasted when first setting up vue. Thank you for filling in as linter for time being!

2021-07-01 14:37 UTC, merged