remove any from PaymentWidgetMixin
bafolts/terraforming-mars pull request #3423
Opened 2021-07-08 01:07 UTC by bafolts

This change removes the usage of `any` from `PaymentWidgetMixin`. It is still not as good as having everything typed and relies on casting to `unknown` but should help avoid issues like we saw with #3419. The mixins with typescript are difficult to type so we need to migrate away from using mixins. The vetur tool also doesn't work with mixins.

In places where without `any` we would have typescript compilation errors I threw a runtime exception.

2021-07-08 02:18 UTC, kberg requested changes
This looks like a good start. Clicking Request Changes viz our discussion earlier. Since I just wrote a test for shtp, it will guide you through this rocky period. Consider adopting my change first and merging it in to here, making your code less risky?

2021-07-08 02:18 UTC, kberg commented on src/components/PaymentWidgetMixin.ts
> +    microbes: number;
Something I just discovered is that microbes and floaters are not used in SHTP at all, and I bet you can remove it from here, and the code itself.

2021-07-08 02:18 UTC, kberg commented on src/components/PaymentWidgetMixin.ts
> +    microbes: number;
The only reason they were in the model was because they had to accommodate this mixin with its anyness.

2021-07-08 02:18 UTC, kberg commented on src/components/PaymentWidgetMixin.ts
> +    microbes: number;
... so move them from this model to the parent model.

2021-07-08 02:18 UTC, kberg commented on src/components/PaymentWidgetMixin.ts
> +      return Math.min((this as unknown as PaymentWidgetModel).player.megaCredits, (this as unknown as PaymentWidgetModel).$data.cost);
Some well-placed newlines will make this easy to read.

```
return Math.min(
    (this as unknown as PaymentWidgetModel).player.megaCredits,
    (this as unknown as PaymentWidgetModel).$data.cost));
```

or 

```
const model = this as unknown as PaymentWidgetModel;
return Math.min(model.player.megaCredits, model.$data.cost)
```

2021-07-08 02:18 UTC, kberg commented on src/components/PaymentWidgetMixin.ts
> +    getResourceRate: function(resourceName: 'steel' | 'titanium' | 'heat' | 'microbes' | 'floaters' | 'science'): number {
How funny I did the exact same thing, but I made this a `type` definition. See https://github.com/bafolts/terraforming-mars/pull/3424/files#diff-87064214149a74384a7f6395bbaf9d63841eb2a633fd98d8d0d0f0b3021b9604R6 and see if you can use any of it.

2021-07-08 02:18 UTC, kberg commented on src/components/PaymentWidgetMixin.ts
> +        throw new Error(`can not reduceValue for ${target} on this`);
:+1:

2021-07-08 02:18 UTC, kberg commented on src/components/PaymentWidgetMixin.ts
> +      if (target === 'microbes') amountHave = (this as unknown as PaymentWidgetModel).playerinput.microbes;
You wrote "this as unknown as PaymentWidgetModel" so much, just add 

asModel: function(): PaymentWidgetModel {
  return this as unknown as PaymentWidgetModel;
}

Then all of this will read better:

amountHave = this.asModel().playerinput.microbes;

2021-07-08 02:18 UTC, kberg commented
This change is terrific.

2021-07-08 23:19 UTC, bafolts commented on src/components/PaymentWidgetMixin.ts
> +    getResourceRate: function(resourceName: 'steel' | 'titanium' | 'heat' | 'microbes' | 'floaters' | 'science'): number {
Yes. I will merge yours first and then update mine accordingly.

2021-07-10 03:54 UTC, kberg requested changes

2021-07-10 03:54 UTC, kberg commented on src/components/PaymentWidgetMixin.ts
> +interface PaymentWidgetModel extends SelectHowToPayModel {
Interesting. Why is this interface necessary and why does it both extend SHTPM and why is it one of its attributes?

2021-07-10 03:54 UTC, kberg commented on src/components/PaymentWidgetMixin.ts
> +      let maxValue: number | undefined = max;
There's a switch in there.

```
let maxValue: number | undefined = max;

if (maxValue === undefined && target !== 'microbes' && target !== 'floaters' && target !== 'science') {
  maxValue = this.asModel().player[target];
}

switch(target) {
case 'megaCredits':
  maxValue = this.getMegaCreditsMax();
  break;
case 'microbes':
  maxValue = this.asModel().playerinput.microbes;
  break;
case 'floaters':
  maxValue = this.asModel().playerinput.floaters;
  if (maxValue !== undefined && this.isStratosphericBirdsEdgeCase()) maxValue--;
  break;
case 'sceince':
  maxValue = this.asModel().playerinput.science;
  break;
}

 if (currentValue === maxValue) return;

if (maxValue === undefined) {
  throw new Error(`unable to determine maxValue for ${target}`);
}
```

2021-07-10 03:54 UTC, kberg commented on src/components/PaymentWidgetMixin.ts
> +      if (target === 'microbes') amountHave = this.asModel().playerinput.microbes;
This looks pretty similar to addValue. Is there some reuse? Can be later.

2021-07-11 01:10 UTC, bafolts commented on src/components/PaymentWidgetMixin.ts
> +interface PaymentWidgetModel extends SelectHowToPayModel {
The interface is capturing what is used on `this`. The `this` has all the properties of `SelectHowToPayModel`.

2021-07-11 01:11 UTC, bafolts commented on src/components/PaymentWidgetMixin.ts
> +      if (target === 'microbes') amountHave = this.asModel().playerinput.microbes;
Trying to minimize what logic changes with this change. Definitely re-use throughout this object.

2021-07-11 03:04 UTC, kberg commented on src/components/PaymentWidgetMixin.ts
> +interface PaymentWidgetModel extends SelectHowToPayModel {
> The interface is capturing what is used on `this`. The `this` has all the properties of `SelectHowToPayModel`.

Huh, OK then. Thanks!

2021-07-11 03:05 UTC, kberg approved these changes
Thanks for the persistence.

2021-07-12 01:15 UTC, merged