fix interplanetary trade
bafolts/terraforming-mars pull request #3476
Opened 2021-07-24 12:13 UTC by vsrisuknimit

Planetary Trade (card) should not count Venus tag or Moon tag by default.

2021-07-24 12:26 UTC, kberg commented on src/constants.ts
> +export const DEFAULT_TAG_COUNT = 10;
This only applies to the one card and it's ready. Seems like it should go there and not be a global constant. Are there other uses for this? If not, please hang it off the card.

2021-07-24 15:16 UTC, nwai90 commented on src/cards/promo/InterplanetaryTrade.ts
> +    if (player.game.gameOptions.venusNextExtension) existingTags++;
While the code works, it is currently placed in the wrong scope, and would be better moved into the `getDistinctTagCount` function in `Player.ts` to handle any existing or future scenarios that require similar logic. Ideally `player.getDistinctTagCount(true, Tags.SPACE)` should return the correct result by considering which expansions are in play, i.e.

<img width="536" alt="Screenshot 2021-07-24 at 11 05 01 PM" src="https://user-images.githubusercontent.com/2408094/126872676-6e8a96ba-3e45-470c-af14-c5853fa11b25.png">

2021-07-24 16:29 UTC, kberg commented on src/cards/promo/InterplanetaryTrade.ts
> +    if (player.game.gameOptions.venusNextExtension) existingTags++;
Good catch. That makes senes.

2021-07-24 17:23 UTC, kberg commented on src/Player.ts
> +      let maxTagCount = constants.DEFAULT_TAG_COUNT;
This is the right place for this logic, but please, still remove the constant unless you expect it to be used elsewhere.

2021-07-24 20:39 UTC, bafolts commented on src/constants.ts
> +export const DEFAULT_TAG_COUNT = 10;
If we ever find another use case for this number we could create a constant at that time.

2021-07-25 20:27 UTC, bafolts requested changes
Can you change the `DEFAULT_TAG_COUNT` from a constant to a local variable?

2021-07-26 13:09 UTC, nwai90 approved these changes

2021-07-26 14:30 UTC, bafolts approved these changes

2021-07-26 14:31 UTC, merged