Refactor award component
bafolts/terraforming-mars pull request #3558
Opened 2021-09-01 22:47 UTC by Argeento

2021-09-02 17:39 UTC, kberg requested changes
I really like the restructuring, but the reformatting and other changes makes it hard to review these. Breaking changes like this into several small commits or a series of small PRs would go a long way toward faster reviews. Please consider that ongoing.

2021-09-02 17:39 UTC, kberg commented on src/components/Award.vue
> +  <div @click="toggleDescription" class="ma-block" title="Press to show or hide the description">
I don't know if removing the capital P breaks internationalization, but can you make sure all the text you've included retains the original case, or, map accordingly?

Note that there's two uses of that phrase, and one translation:

![image](https://user-images.githubusercontent.com/413481/131889814-088f122b-acae-4998-9b0f-afc02ebc3716.png)

(This is a bit why smaller changes are better. I only happened to see this. Are there other text changes?)

2021-09-02 17:39 UTC, kberg commented on src/components/Award.vue
> +      <i :title="award.player_name" class="board-cube" :class="`board-cube--${award.player_color}`" />
Rewriting the components to use `` instead of string concatenation is nice, but it means I have extra review work to do. Please try to constrain these ongoing. I know you like reformatting, and I'm not trying to argue that the existing format is easier to read, but it makes changes harder to review.

2021-09-02 17:39 UTC, kberg commented on src/components/Award.vue
> +      <div class="ma-scores player_home_block--milestones-and-awards-scores">
What happened to show_scores?

2021-09-02 17:39 UTC, kberg commented on src/components/Award.vue
> +    sortedScores(): FundedAwardModel['scores'] {
I can't parse what type `FundedAwardModel['scores']` is. Can you help, please?

2021-09-02 17:39 UTC, kberg commented on src/components/Award.vue
> +      return [...this.award.scores].sort((s1, s2) => s2.playerScore - s1.playerScore);
I'm pretty sure you need the array and spread operators.

2021-09-02 17:39 UTC, kberg commented on src/components/Award.vue
> +          v-text="score.playerScore"
Why have you chosen this instead of what we do elsewhere, to embed this as text inside the <p>?

2021-09-02 19:28 UTC, kberg commented on src/components/Award.vue
> +      return [...this.award.scores].sort((s1, s2) => s2.playerScore - s1.playerScore);
> I'm pretty sure you need the array and spread operators.
I mean "don't need"

2021-09-03 01:01 UTC, Argeento commented on src/components/Award.vue
> +      <div class="ma-scores player_home_block--milestones-and-awards-scores">
Deleted - templet didn't use this variable

2021-09-03 01:08 UTC, Argeento commented on src/components/Award.vue
> +      return [...this.award.scores].sort((s1, s2) => s2.playerScore - s1.playerScore);
`sort` is stupid method that breaks basic principle of FP - do not mutate.
Without additional array wrap - sort method is sorting original array.
Props should not be modified in a child component.
So yes. This array and spread operators are needed.

2021-09-03 01:08 UTC, Argeento commented on src/components/Award.vue
> +          v-text="score.playerScore"
Shorter code / better looking code in column of attributes like this

2021-09-03 01:10 UTC, Argeento commented on src/components/Award.vue
> +    sortedScores(): FundedAwardModel['scores'] {
You can't? or your IDE can't? Its an array of PlayerScore. I can import this interface explicitly if you wan.

2021-09-03 01:13 UTC, Argeento commented on src/components/Award.vue
> +  <div @click="toggleDescription" class="ma-block" title="Press to show or hide the description">
I restored original letter. I will not change any text again - sorry.

2021-09-03 01:28 UTC, Argeento commented on src/components/Award.vue
> +      <i :title="award.player_name" class="board-cube" :class="`board-cube--${award.player_color}`" />
No way :P I will always replace old concatenations to templates string while refactoring. If you want I can crate PR that changes all concatenations in all components at once ([similar to this one](https://github.com/bafolts/terraforming-mars/pull/3550/files))

2021-09-03 03:16 UTC, kberg commented on src/components/Award.vue
> +  <div @click="toggleDescription" class="ma-block" title="Press to show or hide the description">
Don't get me wrong, it's fine to do in context. I've made that mistake with text plenty of times. :D

2021-09-03 03:18 UTC, kberg commented on src/components/Award.vue
> +      <i :title="award.player_name" class="board-cube" :class="`board-cube--${award.player_color}`" />
I hear you. The time I would spend reviewing that change does not make it worthwhile, sorry.

2021-09-03 03:20 UTC, kberg commented on src/components/Award.vue
> +      <div class="ma-scores player_home_block--milestones-and-awards-scores">
I see it referenced externally here

![image](https://user-images.githubusercontent.com/413481/131945672-1f39c428-cbbd-4683-be89-77c31b51f19c.png)

and used inside the template here

![image](https://user-images.githubusercontent.com/413481/131945712-625c48ba-d27b-40f7-983e-f3ae2b10abce.png)

So what am I missing?

2021-09-03 03:23 UTC, kberg commented on src/components/Award.vue
> +      <div class="ma-scores player_home_block--milestones-and-awards-scores">
Huh, yeah, I wonder if something changed beforehand that changed the default values, or something. I'm not sure that's right. It is this kind of multi-purpose change that I find particularly tricky. When submitting a PR, making clear that you're removing features like this in advance would make things easier so I don't have to map intently at both sets of code.

2021-09-03 03:24 UTC, kberg commented on src/components/Award.vue
> +    sortedScores(): FundedAwardModel['scores'] {
I cannot tell. I haven't seen a value used as a type before.

2021-09-03 03:26 UTC, kberg commented on src/components/Award.vue
> +      return [...this.award.scores].sort((s1, s2) => s2.playerScore - s1.playerScore);
I understand. But nothing was broken. Keep it for now, though.

2021-09-03 03:28 UTC, kberg commented on src/components/Award.vue
> +          v-text="score.playerScore"
I think it's OK, I like the simplicity. If v-text was a string, would it respond correctly to the i18n attributes we use to internationalize? If not, it just means that sometimes we do one thing and sometimes another. I assume it will support i18n, though.

2021-09-03 06:03 UTC, Argeento commented on src/components/Award.vue
> +    sortedScores(): FundedAwardModel['scores'] {
It's not a value used as a type. Look at [indexed access type](https://www.typescriptlang.org/docs/handbook/2/indexed-access-types.html)

2021-09-03 06:07 UTC, Argeento commented on src/components/Award.vue
> +  <div @click="toggleDescription" class="ma-block" title="Press to show or hide the description">
Text changes are irrelevant to these code refactors. I should avoid it. Moreover I've checked i18n directive and you are right. Translations are case sensitive.

The `p` letter was restored

2021-09-03 13:35 UTC, kberg commented on src/components/Award.vue
> +      return [...this.award.scores].sort((s1, s2) => s2.playerScore - s1.playerScore);
Rereading my last comment I want to make sure I was clear: don't change it back. :D

2021-09-03 13:36 UTC, kberg commented on src/components/Award.vue
> +    sortedScores(): FundedAwardModel['scores'] {
#til that's neat.

2021-09-03 16:11 UTC, kberg approved these changes

2021-09-03 16:11 UTC, kberg commented on src/components/Award.vue
> +      return [...this.award.scores].sort((s1, s2) => s2.playerScore - s1.playerScore);
OK, so it wasn't clear: I was OK with the indexed type, I thought it was a reasonable use. But thank you.

2021-09-03 16:12 UTC, kberg commented
I think there were one or two more comments, but let's get this in - it's a massive improvement. Thank you!

2021-09-03 16:12 UTC, merged