Add the Moon standard project variant.
bafolts/terraforming-mars pull request #3576
Opened 2021-09-06 16:39 UTC by kberg

Fixes #2951

2021-09-10 01:47 UTC, bafolts commented on src/cards/moon/MoonColonyStandardProject.ts
> +  private static PROPERTIES = {
Was this change made for ease of reading? Making this a static property this code will run while the server or client is starting versus only when the constructor is called. It will also remain in memory. If the change was made for ease of reading I would have use a function `getProperties`.

2021-09-10 01:51 UTC, bafolts requested changes
I would revert the change of using the static properties. Static properties will execute when the javascript is first executed versus only when the constructor is called. They will also remain in memory even if the constructors are never called.

2021-09-10 15:03 UTC, kberg commented on src/cards/moon/MoonColonyStandardProject.ts
> +  private static PROPERTIES = {
Unfortuantely it was not for reading, it was to make it work. I'll add a TODO for this request, though.

2021-09-10 15:11 UTC, kberg commented
> I would revert the change of using the static properties. Static properties will execute when the javascript is first executed versus only when the constructor is called. They will also remain in memory even if the constructors are never called.

I wish I could. Since this is only two cards, I'm going to merge first, and then I'll see if I can come up with something better this afternoon. I realize the "since this is only two cards" argument is a slippery slope once we apply it to all the cards. :D

2021-09-11 00:45 UTC, bafolts approved these changes

2021-09-11 00:53 UTC, kberg commented
Thanks! I'll merge this and get right to it.

2021-09-11 00:53 UTC, merged