Make ApiWaitingFor spectator-friendly.
bafolts/terraforming-mars pull request #3585
Opened 2021-09-10 00:18 UTC by kberg

This triggered a couple of changes: the expectation that players start
with 'p' and spectators start with 's' means that TestPlayer has to
generate its players correctly, which had a follow-on effect to some
other tests. Nothing so major that it deserved its own PR.

2021-09-15 23:22 UTC, bafolts requested changes
I would make a separate function for spectators instead of having a value of `undefined` for the `player` argument represent a spectator. I think this can be broken up as follows.

```
private getWaitingForModel(game: Game, gameAge: number, undoCount: number): WaitingForModel {
  if (game.gameAge > gameAge || game.undoCount > undoCount) {
    return {result: 'REFRESH'};
  }
  return {result: 'WAIT'};
}

private getWaitingForModelPlayer(player: Player, gameAge: number, undoCount: number): WaitingForModel {
  if (this.timeToGo(player)) {
    return {result: 'GO'};
  }
  return this.getWaitingForModel(game, gameAge, undoCount);
}
```

This will avoid the situation where something calling to the function ends up with player being `undefined` by mistake and getting the spectator result.

2021-09-15 23:34 UTC, kberg commented
> I would make a separate function for spectators instead of having a value of `undefined` for the `player` argument represent a spectator. I think this can be broken up as follows.
> 
> ```
> private getWaitingForModel(game: Game, gameAge: number, undoCount: number): WaitingForModel {
>   if (game.gameAge > gameAge || game.undoCount > undoCount) {
>     return {result: 'REFRESH'};
>   }
>   return {result: 'WAIT'};
> }
> 
> private getWaitingForModelPlayer(player: Player, gameAge: number, undoCount: number): WaitingForModel {
>   if (this.timeToGo(player)) {
>     return {result: 'GO'};
>   }
>   return this.getWaitingForModel(player.game, gameAge, undoCount);
> }
> ```
> 
> This will avoid the situation where something calling to the function ends up with player being `undefined` by mistake and getting the spectator result.

Since it's a private method, this felt pretty safe. But, this makes sense.

2021-09-16 00:04 UTC, bafolts commented on src/routes/ApiWaitingFor.ts
> +  // When player is undefined, caller is a spectator.
This comment is no longer relevant.

2021-09-16 00:04 UTC, bafolts approved these changes

2021-09-16 00:38 UTC, merged